### ISSUE TITLE
knife4j-aggregation-spring-boot-starter 发个新版本呗

### ISSUE THREAD

**Issue by jacktao007** [xiaoymin/knife4j#1]
knife4j-aggregation-spring-boot-starter 发个新版本呗  2.0.9有bug
![image](https://user-images.githubusercontent.com/1073365/203468682-b0f7394e-4864-4a81-967c-a1b1710a27b8.png)

**Comment by xiaoymin** [comment]
先快照体验吧

https://gitee.com/xiaoym/knife4j/issues/I5LIQZ
