### ISSUE TITLE
希望对list<enum>能显示出枚举值

### ISSUE THREAD

**Issue by Griffin23** [xiaoymin/knife4j#100]
## 版本
1.9.2

## 前端显示
![image](https://user-images.githubusercontent.com/5829649/58537298-2f459180-8225-11e9-92a7-27ccf63bfc53.png)

## 代码
```
@Data
public class TestListEnum {
    @ApiModelProperty("这个字段是listEnum")
    private List<ColorEnum> listEnum;
    @ApiModelProperty("这个字段是singleEnum")
    private ColorEnum singleEnum;

    public enum ColorEnum {
        RED,
        BLUE
    }
}
```

## 期望
为`List<ColorEnum>`也显示出可用值

**Comment by xiaoymin** [comment]
1.9.4版本已实现

https://www.oschina.net/news/107336/swagger-bootstrap-ui-1-9-4-released
