### ISSUE TITLE
希望ApiInfo的description支持markdown语法

### ISSUE THREAD

**Issue by MrBlite** [xiaoymin/knife4j#103]
希望ApiInfo的description支持（即项目简介）markdown语法，原生的页面description是放在class=markdown的标签里。接口描述也是这个问题。
感谢您！

**Comment by MrBlite** [comment]
之前使用官方的ui时，我们是在description里简单注明每次api的变动情况。鉴于description在其页面的顶部位置，使用markdown语法在此记录这些信息比较直观明了。
swagger-bootstrap-ui 是将AppInfo放在了一个表格里，这种做法似乎不再合适，或者希望是否有好的解决方案可以提供，以解决这种记录Api变动情况的需求。目前每次都有new的标签提示，感觉这个已经很棒了。

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/swagger-bootstrap-ui/issues/IVVRX

和这个issue一样，不过我还是不推荐这种做法~~

**Comment by xiaoymin** [comment]
自定义文档 目前的缺陷就是样式还没有补全,可能会暂时比较难看

https://doc.xiaominfo.com/guide/self-doc.html

不过在下个版本会把这块的相关样式补上 ，优化一下

**Comment by MrBlite** [comment]
太强了，我试试这个功能，感谢！

**Comment by xiaoymin** [comment]
1.9.4版本添加了对markdown语法的支持

https://www.oschina.net/news/107336/swagger-bootstrap-ui-1-9-4-released

**Comment by MrBlite** [comment]
NB!
