### ISSUE TITLE
example值带单引号时页面解析json出错

### ISSUE THREAD

**Issue by zhairuihao** [xiaoymin/knife4j#105]
![image](https://user-images.githubusercontent.com/18378213/59325395-72b7f980-8d15-11e9-8c9b-a6f9c0ccb6fd.png)
![image](https://user-images.githubusercontent.com/18378213/59325412-82cfd900-8d15-11e9-9d0f-1a8321b9a834.png)

**Comment by xiaoymin** [comment]
既然给T了就不要给example了，交给反射吧

**Comment by zhairuihao** [comment]
嗯 正常的dto写example 带单引号也会出现解析出错哦

**Comment by xiaoymin** [comment]
没必要写example了，dto和泛型 通过反射都可以把属性给解析出来，多写无益

**Comment by zhairuihao** [comment]
example 我需要写一些示例值，在value 中写描述时带单引号也出现解析错误了~

**Comment by xiaoymin** [comment]
针对泛型和dto引用类型 为什么还要写example？

dto引用类型每个字段上用`@ApiModelProperty`注解就已经能识别出来了

没必要再dto上面在搞个example

如这样：
```java
@ApiModelProperty(example="{'id':'name'}")
private DTOClass dto;
```

完全没必要像上面的代码一样啊。。

**Comment by zhairuihao** [comment]
好的，谢谢回复； 我要弃用example了
