### ISSUE TITLE
能否加上请求全局参数header,然后api调试页面加上header参数设置

### ISSUE THREAD

**Issue by zebmaster** [xiaoymin/knife4j#110]

**Comment by xiaoymin** [comment]
页面上的全局参数是临时的，如果你要在api上显示,在后端代码可以使用globalparamter

页面上使用全局参数，虽然在api中调试时没有显示，但100%会在发送的时候发送给后端

**Comment by zebmaster** [comment]
前端统一拦截处理比较方便修改，包括部分接口有可能会设置header才能正常响应

**Comment by ashuai5061** [comment]
> 页面上的全局参数是临时的，如果你要在api上显示,在后端代码可以使用globalparamter
> 
> 页面上使用全局参数，虽然在api中调试时没有显示，但100%会在发送的时候发送给后端

大哥,请问我现在引用的4.5.0,没找到这个类globalparam
