### ISSUE TITLE
Can I use swagger-bootstrap-ui for English version?

### ISSUE THREAD

**Issue by vaibhavn** [xiaoymin/knife4j#111]
Can I use swagger-bootstrap-ui for English version?

**Comment by xiaoymin** [comment]
> Can I use swagger-bootstrap-ui for English version?

Yes,Last version has supported English

**Comment by xiaoymin** [comment]
http://swagger-bootstrap-ui.xiaominfo.com/doc.html?showMenuApi=1&plus=1&cache=1&lang=en

**Comment by vaibhavn** [comment]
Highly appreciate your quick response, will check shared link.

**Comment by sowrov** [comment]
There are still some Chinise text in english version. And is it possible to make the english as default without using redirect?

**Comment by xiaoymin** [comment]
> There are still some Chinise text in english version. And is it possible to make the english as default without using redirect?

you can access `http://host:port/doc.html#/home/en-US` using english by default

example: [http://knife4j.xiaominfo.com/doc.html#/home/en-US](http://knife4j.xiaominfo.com/doc.html#/home/en-US)
