### ISSUE TITLE
How to use swagger-bootstrap-ui for multiple modules?

### ISSUE THREAD

**Issue by vaibhavn** [xiaoymin/knife4j#112]
Thanks for creating such nice user friendly custom Swagger UI portal.

I have multiple solutions in my product. Each solution has it's own <solution_name>_swagger.json.
Total solutions/modules count is ~120. All swagger JSON files size is ~40 MB.

How can I use swagger-bootstrap-ui effectively?
Shall I show all solution names in left menu?
Is it possible to load APIs( solution swagger JSON file) when user clicks on solution name in left menu?
I think UI should load swagger JSON when user clicks on solution else 40 MB json files data loading on first page load would be nightmare.

Can you please suggest? I might be wrong on my above assumptions.

**Comment by xiaoymin** [comment]
If you have multiple modules (swagger.json)

You can deploy a front-end version of swagger-bootstrap-ui to customize the API documents that assemble each service

download:https://github.com/xiaoymin/swagger-bootstrap-ui/tree/master/swagger-bootstrap-ui-front

`swagger-bootstrap-ui-front` is a pure front-end version. You can use nginx to proxy the back-end service interface and configure the list of services through static files (swagger.json).

before i have write some document,but it is chinese

links:https://doc.xiaominfo.com/en/ui-front-nginx.html

Later, I found the front version unfriendly. I wrote the chrome application extension of swagger-bootstrap-ui.

You can search for swagger-bootstrap-ui in chrome's App Store

**Comment by xiaoymin** [comment]
![](https://doc.xiaominfo.com/img/solution/sbue.gif)

**Comment by xiaoymin** [comment]
Writing some English documents may help you understand swagger-bootstrap-ui better

https://doc.xiaominfo.com/en/

Any suggestions and questions are welcome for discussion.

**Comment by vaibhavn** [comment]
I have already checked 'https://doc.xiaominfo.com/en/', trying to understand same. I do not know Chinese so little bit difficult to understand everything. :)

As per my understanding, I have to create 120 groups for solutions(as I have 120 solutions and each contains separate swagger JSON that means 120 swagger JSON files) and changing on group, particular group JSON should load. JSON location might be 'swagger-bootstrap-ui-front/json/'.
Correct me if I am wrong.

One more query: Is this UI supports Open API 3.0 too?

**Comment by xiaoymin** [comment]
Just create One group.json file

```json
[
  {
    "name": "swagger",
    "url": "/json/swagger.json",
    "swaggerVersion": "2.0",
    "location": "/json/swagger1.json"
  },
  {
    "name": "swagger1",
    "url": "/json/swagger2.json",
    "swaggerVersion": "2.0",
    "location": "/json/swagger2.json"
  }
//more...
]

```

it include your 120 swagger JSON files url

last，now  it based on Open API 2.0

**Comment by vaibhavn** [comment]
Yes, I can see same in 'swagger-bootstrap-ui-front/json/group.json'. I will try this option.

Any plan to upgrade to support Open API 3.0?

**Comment by xiaoymin** [comment]
At present, we are still focusing on adding more personalized options.

If Springfox-swagger upgrade supports Open API 3.0, I will upgrade it.

**Comment by vaibhavn** [comment]
Yes.. Springfox is still under development to support Open API 3.0.

About Group names :
I was bit concerned about showing 120 solution names in group drop down box at left upper corner.

Instead Is it possible to show solution name as left menu:
![image](https://user-images.githubusercontent.com/3889855/59906780-2b252200-9427-11e9-94e9-ba51cab0a279.png)

When user clicks on solution for example 'Solution 001', system will load solution001_swagger.json from server and displays APIs under 'Solution 001' label.
Showing many solution in single group dropdown list would be less user friendly.
What is your suggestion?

**Comment by xiaoymin** [comment]
SolutionName > tag > Api

like this?

What if there are more than 100 Apis under the current solution? I don't think it's very friendly either.

**Comment by xiaoymin** [comment]
If you have a lot of solutions, I think you should try to categorize them.

For example, orders, users

And these solutions can be presented by different interface addresses, so that the interfaces under a single document will not show much, but will be clearer.

**Comment by vaibhavn** [comment]
I was thinking of like http://sleepy-harbor-80783.herokuapp.com/#!/Installation/get_installations

![image](https://user-images.githubusercontent.com/3889855/59908258-9b817280-942a-11e9-8aea-7f94165079a7.png)

Installation, Device, Device agent are like solutions for my case.
Docker uses the same. For reference : https://docs.docker.com/engine/api/v1.25/#operation/TaskList

I will consider your suggestion to give more thoughts on same, Thanks !

**Comment by xiaoymin** [comment]
In the drop-down list, a drop-down box represents a grouping. Perhaps the following is a list of all current interface groupings, similar to your solution.

In that case, I think you should merge 120 solutions into a JSON file and give it to the UI for automatic rendering.

This and your reference http://sleepy-harbor-80783.herokuapp.com/#!/Installation/put_installations_installationId

The display is the same.

This example of yours also has only one swagger. JSON file

I don't know what I understand, right?

**Comment by xiaoymin** [comment]
```json
"tags": [
    {
      "name": "Solutaion1",
      "description": "Solutaion1"
    },
  {
      "name": "Solutaion2",
      "description": "Solutaion2"
    },
  {
      "name": "Solutaion3",
      "description": "Solutaion3"
    },

//more solutions

```

**Comment by xiaoymin** [comment]
use：http://sleepy-harbor-80783.herokuapp.com/swagger.json

swagger-bootstrap-ui rendering effect

![image](https://user-images.githubusercontent.com/7894406/59909529-74cf3600-9442-11e9-84cd-d26a1752b99e.png)

**Comment by vaibhavn** [comment]
Yes..shared example link uses single JSON file, I do not want to go with this approach( Loading single page with 40 MB JSON data is not feasible ). Personally I did not like right panel of shared UI.
I wanted to show just the left menu UI snap. 
As I mentioned earlier, system should load single JSON and show APIs for the clicked option on left menu.
I thought of adding tags as Solutions but it expects single large JSON to be loaded on first request.

**Comment by vaibhavn** [comment]
> 
> 
> use：http://sleepy-harbor-80783.herokuapp.com/swagger.json
> 
> swagger-bootstrap-ui rendering effect
> 
> ![image](https://user-images.githubusercontent.com/7894406/59909529-74cf3600-9442-11e9-84cd-d26a1752b99e.png)

I will try to achieve same by minimizing my JSON file size.

**Comment by xiaoymin** [comment]
A single loading of 40MB documents is really not friendly enough, and it may cause the browser to fake death.

However, I think you should categorize every document. There won't be so many documents after categorization (120)  :)

**Comment by vaibhavn** [comment]
I was trying to escape from that efforts, I have to fix it now :)
Update:
After re-working on some of solutions and minify JSON files, all JSON files size is **~7 MB** now.

Approaches after our disucssion: 
1. Show solutions as tags in single JSON. OR
2. Show solutions in group drop down and load particular solution swagger JSON on change event.

What do you suggest? Loading 7-8 MB JSON also should not be an big deal, right?

**Comment by xiaoymin** [comment]
How could there be such a large document?

I just tried to create a 7 MB swagger. JSON file, which requires about 12,000 interfaces.

**Comment by vaibhavn** [comment]
There are ~2200 APIs listed and description is quite large text for some API.
Also Model definitions and common swagger JSON info repeated as I have created separate JSON files.
This should bring down to lesser size if I create single JSON for all solution, I am already trying same, will update it.

**Comment by vaibhavn** [comment]
> 
> 
> > use：http://sleepy-harbor-80783.herokuapp.com/swagger.json
> > swagger-bootstrap-ui rendering effect
> > ![image](https://user-images.githubusercontent.com/7894406/59909529-74cf3600-9442-11e9-84cd-d26a1752b99e.png)
> 
> I will try to achieve same by minimizing my JSON file size.

First of all apologies being silent on this issue, was working on other tasks.
I have minified my json to 5.94 MB now, how can I try same swagger JSON with your UI?
could you please provide some steps to try?  Like you did for 'http://sleepy-harbor-80783.herokuapp.com/swagger.json' sample.

**Comment by xiaoymin** [comment]
I have provided an extension of chrome that can be rendered quickly through swagger. json or restful api

You can search for swagger-bootstrap-ui in chrome's App Store

**Comment by xiaoymin** [comment]
Can you send me a copy of swagger.json you currently use to my email address?

Because swagger-bootstrap-ui uses some caching operations in rendering, there may be some problems

Help me improve swagger-bootstrap-ui

email:xiaoymin@foxmail.com

**Comment by vaibhavn** [comment]
Is there any way to deploy locally and try?
can I use `swagger-bootstrap-ui-front` ?


> 
> 
> I have provided an extension of chrome that can be rendered quickly through swagger. json or restful api
> 
> You can search for swagger-bootstrap-ui in chrome's App Store

**Comment by xiaoymin** [comment]
> Is there any way to deploy locally and try?
> can I use `swagger-bootstrap-ui-front` ?
> 
> > I have provided an extension of chrome that can be rendered quickly through swagger. json or restful api
> > You can search for swagger-bootstrap-ui in chrome's App Store

Yes

**Comment by vaibhavn** [comment]
> 
> 
> Can you send me a copy of swagger.json you currently use to my email address?
> 
> Because swagger-bootstrap-ui uses some caching operations in rendering, there may be some problems
> 
> Help me improve swagger-bootstrap-ui
> 
> email:[xiaoymin@foxmail.com](mailto:xiaoymin@foxmail.com)

Sorry @xiaoymin , these APIs are restricted to use in organization and company partners only.
Otherwise I would be happy to share with you.

**Comment by vaibhavn** [comment]
> 
> 
> > Is there any way to deploy locally and try?
> > can I use `swagger-bootstrap-ui-front` ?
> > > I have provided an extension of chrome that can be rendered quickly through swagger. json or restful api
> > > You can search for swagger-bootstrap-ui in chrome's App Store
> 
> Yes

I could not find any steps as how to start/use an swagger-bootstrap-ui-front? Also what are changes required to use local swagger json etc.
I would appreciate if you can point me some links and share some information.

**Comment by xiaoymin** [comment]
Wait a minute for me to find you

**Comment by vaibhavn** [comment]
Thank You !

**Comment by xiaoymin** [comment]
@vaibhavn 

https://doc.xiaominfo.com/en/ui-front-static.html

https://doc.xiaominfo.com/en/ui-front-nginx.html

**Comment by vaibhavn** [comment]
I will check it out.
Chrome extension JSON loads fail with following error:

> Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'SwaggerBootstrapUiExtensionJsonTxt' exceeded the quota.
>     at Object.set (chrome-extension://dhkcgihkeepociepfdeeppmdgbdooahh/module/store.js:12:25)
>     at HTMLButtonElement.<anonymous> (chrome-extension://dhkcgihkeepociepfdeeppmdgbdooahh/module/json.js:55:23)
>     at HTMLButtonElement.dispatch (chrome-extension://dhkcgihkeepociepfdeeppmdgbdooahh/js/jquery-1.12.4.min.js:3:12444)
>     at HTMLButtonElement.r.handle (chrome-extension://dhkcgihkeepociepfdeeppmdgbdooahh/js/jquery-1.12.4.min.js:3:9173)

**Comment by xiaoymin** [comment]
I used the browser's localStorage object to cache the current JSON object. I haven't encountered such a large swagger.json file before. Your situation is beyond the default maximum storage value of the localStorage object.

**Comment by vaibhavn** [comment]
Yeah..I got it. Checking on google for any workaround for same.
I think default local storage is 5MB so it is giving an error( My swagger json is slightly larger in size).

**Comment by xiaoymin** [comment]
This bug needs to be changed later. Maybe there are some other ways to use the caching strategy.

**Comment by vaibhavn** [comment]
> 
> 
> @vaibhavn
> 
> https://doc.xiaominfo.com/en/ui-front-static.html
> 
> https://doc.xiaominfo.com/en/ui-front-nginx.html

I am able to run an application locally using IIS. Great !  
System loaded all the APIs and search also works fine( bit slow, but it is fine).
Though some issues:
1. There are many labels in Chinese language, need to display in English. 
2. In 'Debug' tab, "body" field does not show Input request JSON, instead shows parameter's description.
![image](https://user-images.githubusercontent.com/3889855/60585125-98806d80-9dac-11e9-9c2e-74d618d1f0e3.png)


3. In 'Debug' tab, when I click on 'Send' system does not read "host" provided in swagger.json, instead it try to execute request on localhost.
For example: http://localhost/hello/v1/api/getVariants
But host is provided something different(` "host": "146.167.345.123:9090/hello/v1/api"`).

**Comment by xiaoymin** [comment]
1  Settings for english ,https://doc.xiaominfo.com/en/i18n.html

**Comment by xiaoymin** [comment]
If you use IIS, you should add the reverse proxy configuration so that you can debug it, just like the reverse proxy interface in Nginx conf.

**Comment by vaibhavn** [comment]
> 
> 
> 1 Settings for english ,https://doc.xiaominfo.com/en/i18n.html

Tried using `http://localhost/doc.html?plus=1&cache=1&lang=en`
I am getting following error now:
`Make sure the swagger resource interface is correct.`

Later it does not load APIs because system tries to load JSON from wrong URL.
`http://localhost/v2/api-docs-ext?group=swagger`
instead of
`http://localhost/json/swagger.json`

**Comment by xiaoymin** [comment]
Remove parameter plus 

use:http://localhost/doc.html?cache=1&lang=en

**Comment by xiaoymin** [comment]
last option `Enabling enhancements provided by Swagger BootstrapUi` can't checked

It's an enhancement that works with springfox-swagger, because you're a static swagger.json file, so don't check this option

**Comment by vaibhavn** [comment]
Okay..Thanks for information.
It is working in English locale now. Done !
Also I need to check on 'Debug' tab issues, example JSON does not show.

**Comment by xiaoymin** [comment]
i see, check your params

example:http://swagger-bootstrap-ui.xiaominfo.com/doc.html#/%E5%88%86%E7%BB%84%E6%8E%A5%E5%8F%A3/1.9.4%E7%89%88%E6%9C%AC-20190518/createOrdetrUsingPOST

Normally

![image](https://user-images.githubusercontent.com/7894406/60644404-97ad1180-9e68-11e9-95f9-dbb0cb7c4e60.png)

**Comment by vaibhavn** [comment]
My Sample JSON snipper, anything wrong?
```
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "<i>planList : </i>A list of Prg0AbsPlan objects.<br/>",
            "required": false,
            "schema": {
              "type": "object",
              "properties": {
                "planList": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Prg0AbsPlan"
                  }
                }
              }
            }
          }
      ],
```

**Comment by xiaoymin** [comment]
I just looked at the specification of the OPEN API V2.0.

For the attributes of the schema object, only the implementation of the items attribute is currently implemented in ui.

Because swagger.json generated in springfox-swagger is the most, the other types include properties, allOf should not be resolved at present.

Very sorry

**Comment by vaibhavn** [comment]
I was expecting something like below:

![image](https://user-images.githubusercontent.com/3889855/60656275-cd53f980-9e6c-11e9-8dc6-5506cb961b11.png)

**Comment by vaibhavn** [comment]
Above JSON works fine with default swagger-ui .

But yes, I have modified my generated JSON from springfox using my custom Java utility.
It was my need, I cannot change my server side implementation so did small change in JSON.
Every parameters should be a part of body so I did achieve through my custom utility.
Below are github issues created by me for your reference :
#https://github.com/swagger-api/swagger-editor/issues/1992
#https://github.com/springfox/springfox/issues/3011
