### ISSUE TITLE
关于调试界面的建议

### ISSUE THREAD

**Issue by LuomingXu** [xiaoymin/knife4j#113]
现在的调试界面是这样的
![image](https://user-images.githubusercontent.com/24503603/59963179-1aa5a200-9522-11e9-85ac-c001de6c3e17.png)
要填写的时候还要删去, 有点麻烦

希望可以改成类似这样的
![image](https://user-images.githubusercontent.com/24503603/59963186-2ee99f00-9522-11e9-93fc-18acc1e56e10.png)

除非有了默认值才会有填充(#109)

**Comment by xiaoymin** [comment]
为啥还要删？这个是参数名称 又不是参数值

**Comment by LuomingXu** [comment]
擦, 对不起, ...
眼花了...
那请问这个参数名称可修改是干嘛的?会永久存储吗?

**Comment by xiaoymin** [comment]
为后面动态参数调试保留的缺口

只是目前还没实现

你们使用调试 这个值根本不需要考虑啊，自动就给解析上了

**Comment by LuomingXu** [comment]
ok. 
我要去看看那个ui-front如何配置, 那个更加的需要.

**Comment by xiaoymin** [comment]
> ok.
> 我要去看看那个ui-front如何配置, 那个更加的需要.

front版本如果不好用的话  可以用chrome的扩展程序

https://doc.xiaominfo.com/solution/extension.html

**Comment by LuomingXu** [comment]
Okay

**Comment by LuomingXu** [comment]
en....
![image](https://user-images.githubusercontent.com/24503603/59963654-b9cd9800-9528-11e9-8753-99af36f3d90f.png)
希望这个标签页可以像浏览器的标签一样, 可以用鼠标中键关闭
