### ISSUE TITLE
swagger-bootstrap-ui-front 有计划单独接口通过 hash 地址访问吗

### ISSUE THREAD

**Issue by zxy198717** [xiaoymin/knife4j#114]
如题

**Comment by xiaoymin** [comment]
好的，等我有空 把front版本更新一下

**Comment by xiateapu** [comment]
请问下这个issue现在合入了吗

**Comment by zxz221** [comment]
> 好的，等我有空 把front版本更新一下

front版本在哪下载

**Comment by xiaoymin** [comment]
拖了这么就，终于可以close掉了

各位，front版本的使用方法在官网的文档已经更新，地址：https://doc.xiaominfo.com/knife4j/knife4j-front.html

最新代码在[https://gitee.com/xiaoym/knife4j](https://gitee.com/xiaoym/knife4j)下的`knife4j-front`文件夹中

@zxy198717

@zxz221

@xiateapu
