### ISSUE TITLE
自定义文档 classpath:markdown/* 不支持多目录

### ISSUE THREAD

**Issue by ljguo** [xiaoymin/knife4j#115]
如果多个模块都有自定义文档  合并之后只能显示一个模块的自定义文档
 希望能显示多个模块的自定义文档

**Comment by xiaoymin** [comment]
你指的每个分组的自己的自定义文档吗

**Comment by ljguo** [comment]
是的

**Comment by xiaoymin** [comment]
2.0.6 支持了该功能

更新日志：https://www.oschina.net/news/119457/knife4j-2-0-6-released

自定义文档分组请参考：https://doc.xiaominfo.com/knife4j/enhance.html
