### ISSUE TITLE
返回状态码较多时，界面显示异常

### ISSUE THREAD

**Issue by loong10k** [xiaoymin/knife4j#117]
返回状态码较多时，界面显示异常：
![图片](https://user-images.githubusercontent.com/20489781/60314898-e2291c80-9996-11e9-9ffe-47d4148eb978.png)
建议修改样式！

**Comment by loong10k** [comment]
状态码tab页签，不能滚动，显示不全，应默认显示200

**Comment by xiaoymin** [comment]
。。。。。。

**Comment by loong10k** [comment]
？自定义状态码较多，

**Comment by xiaoymin** [comment]
每个状态码 返回的都不一样？

**Comment by loong10k** [comment]
是的，全局异常处理会定义一批状态码，为了方便前端工程师根据不同状态码处理数据，这里会定义的比较详细，基本上改下样式即可，只是我们自己改，后期更新新版本还是需要更改，看您这边是否在新版本中更新掉这个问题

**Comment by xiaoymin** [comment]
如果每个状态码 都不一样 那是要改的

可以贴一下后端代码

**Comment by loong10k** [comment]
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@ApiResponses({ 
	@ApiResponse(code = 0, message = "认证成功", response = ApiRestResponse.class),
	@ApiResponse(code = HttpStatus.SC_CREATED, message = "已创建", response = ApiRestResponse.class),
	@ApiResponse(code = HttpStatus.SC_UNAUTHORIZED, message = "请求要求身份验证", response = ApiRestResponse.class),
	@ApiResponse(code = HttpStatus.SC_FORBIDDEN, message = "权限不足", response = ApiRestResponse.class),
	@ApiResponse(code = HttpStatus.SC_NOT_FOUND, message = "请求资源不存在", response = ApiRestResponse.class),
	@ApiResponse(code = HttpStatus.SC_INTERNAL_SERVER_ERROR, message = "服务器内部异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10001, message = "认证失败", response = ApiRestResponse.class),
	@ApiResponse(code = 10002, message = "认证请求方法不支持.", response = ApiRestResponse.class),
	@ApiResponse(code = 10003, message = "登录失败次数操作最大限制，请输入验证码", response = ApiRestResponse.class),
	@ApiResponse(code = 10004, message = "验证码发送失败", response = ApiRestResponse.class),
	@ApiResponse(code = 10005, message = "请输入验证码", response = ApiRestResponse.class),
	@ApiResponse(code = 10006, message = "验证码已过期", response = ApiRestResponse.class),
	@ApiResponse(code = 10007, message = "验证码不可用", response = ApiRestResponse.class),
	@ApiResponse(code = 10008, message = "验证码错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10009, message = "用户凭证已过期", response = ApiRestResponse.class),
	@ApiResponse(code = 10010, message = "用户名或密码错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10011, message = "用户未注册", response = ApiRestResponse.class),
	@ApiResponse(code = 10012, message = "用户已注册", response = ApiRestResponse.class),
	@ApiResponse(code = 10013, message = "用户帐号不存在", response = ApiRestResponse.class),
	@ApiResponse(code = 10014, message = "用户帐号未启用", response = ApiRestResponse.class),
	@ApiResponse(code = 10015, message = "用户帐号已过期", response = ApiRestResponse.class),
	@ApiResponse(code = 10016, message = "用户帐号已被锁定", response = ApiRestResponse.class),
	@ApiResponse(code = 10017, message = "没有为用户指定角色", response = ApiRestResponse.class),
	@ApiResponse(code = 10021, message = "认证失败", response = ApiRestResponse.class),
	@ApiResponse(code = 10022, message = "Token缺失", response = ApiRestResponse.class),
	@ApiResponse(code = 10023, message = "Token已过期", response = ApiRestResponse.class),
	@ApiResponse(code = 10024, message = "Token已失效", response = ApiRestResponse.class),
	@ApiResponse(code = 10025, message = "Token错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10026, message = "临时授权码过期", response = ApiRestResponse.class),
	@ApiResponse(code = 10027, message = "第三方授权服务端异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10028, message = "临时授权码错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10110, message = "不允许访问（功能未授权）", response = ApiRestResponse.class),
	@ApiResponse(code = 10111, message = "请求失败", response = ApiRestResponse.class),
	@ApiResponse(code = 10112, message = "数据为空", response = ApiRestResponse.class),
	@ApiResponse(code = 10113, message = "参数类型不匹配", response = ApiRestResponse.class),
	@ApiResponse(code = 10114, message = "缺少矩阵变量", response = ApiRestResponse.class),
	@ApiResponse(code = 10115, message = "缺少URI模板变量", response = ApiRestResponse.class),
	@ApiResponse(code = 10116, message = "缺少Cookie变量", response = ApiRestResponse.class),
	@ApiResponse(code = 10117, message = "缺少请求头", response = ApiRestResponse.class),
	@ApiResponse(code = 10118, message = "缺少参数", response = ApiRestResponse.class),
	@ApiResponse(code = 10119, message = "缺少请求对象", response = ApiRestResponse.class),
	@ApiResponse(code = 10120, message = "参数规则不满足", response = ApiRestResponse.class),
	@ApiResponse(code = 10121, message = "参数绑定错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10122, message = "参数解析错误", response = ApiRestResponse.class),
	@ApiResponse(code = 10123, message = "参数验证失败", response = ApiRestResponse.class),
	@ApiResponse(code = 10201, message = "服务器：运行时异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10202, message = "服务器：空值异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10203, message = "服务器：数据类型转换异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10204, message = "服务器：IO异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10205, message = "服务器：未知方法异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10206, message = "服务器：非法参数异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10207, message = "服务器：数组越界异常", response = ApiRestResponse.class),
	@ApiResponse(code = 10208, message = "服务器：网络异常", response = ApiRestResponse.class)
})

**Comment by loong10k** [comment]
或者在增强功能增加全局异常码页面也可以的

**Comment by xiaoymin** [comment]
你这个response完全是一样的啊。。我以为是不一样的，写这么多不嫌累么。。每个接口都还要写

自定义文档功能你可以试试 https://doc.xiaominfo.com/guide/self-doc.html

**Comment by loong10k** [comment]
父类接口统一定义即可，目的是方便前端理解状态码，之前还没看到你这个自定义文档，谢谢提醒

**Comment by loong10k** [comment]
按文档说明，做了些配置可以在独立的系统看到文档，目前系统是微服务，需要把数据汇聚到网关统一查看文档；在网关那边还是没法看到这个自定义的文档信息：

独立服务：
![图片](https://user-images.githubusercontent.com/20489781/60326229-d0a63b80-99bb-11e9-92a3-64afb56598a5.png)
网关界面：
![图片](https://user-images.githubusercontent.com/20489781/60326287-f03d6400-99bb-11e9-85c7-3fc62cb6531e.png)

**Comment by loong10k** [comment]
关于网关整合swagger和swagger-bootstrap-ui进行文档汇总可参考：
https://github.com/vindell/spring-cloud-gateway-swagger2

**Comment by xiaoymin** [comment]
我晚上看看

**Comment by xiaoymin** [comment]
微服务聚合文档地址你用的是默认的地址/v2/api-docs，这个是springfox-swagger提供的，

我提供的增强接口是新写了一个地址,接口地址是/v2/api-docs-ext，需要换成这个
