### ISSUE TITLE
resteasy如何集成swagger-bootstrap-ui

### ISSUE THREAD

**Issue by leyou240** [xiaoymin/knife4j#120]
我们的服务是用resteasy实现的，经研究现在已经能生成json文件了。
请问怎么集成swagger-bootstrap-ui

**Comment by xiaoymin** [comment]
三种方式吧

第一种：https://doc.xiaominfo.com/solution/ui-front-static.html

第二种：https://doc.xiaominfo.com/solution/ui-front-nginx.html

第三种：https://doc.xiaominfo.com/solution/extension.html

**Comment by xiaoymin** [comment]
第四种 就是  把静态文件拷贝到你的项目中

不过可能需要小改动,

java里面集成默认是有两个接口/swagger-resources和/v2/api-docs

分别对应的是分组和实例

resteasy 有这2个接口也可以方便集成
