### ISSUE TITLE
当返回类型是application/json但是返回的是基础类型例如boolean或者int显示会出错

### ISSUE THREAD

**Issue by qiao-wei** [xiaoymin/knife4j#121]
后台 RestController 
` @ApiOperation(value = "创建用户")
    @ApiResponses({
            @ApiResponse(code = HttpStatus.SC_OK,message = "",response = Long.class),
            @ApiResponse(code = HttpStatus.SC_BAD_REQUEST,message = "Bad Request",response = ErrorMessage.class),
    })
    @RequestMapping(value = {"users"}, method = RequestMethod.POST)
    Object create(@RequestBody AuthUserBO userBO) {

        String username = userBO.getUsername();
        if (StringUtils.isEmpty(username)) {
            return ErrorMessage.build(ResponseCode.USER_USERNAME_EMPTY);
        }
        try {
            userService.insert(userBO);
            return userBO.getId();
        } catch (RecordExistedException ex) {
            LOGGER.debug(ex.getMessage(), ex);
            return ErrorMessage.build(ResponseCode.USER_RECORD_EXISTED);
        }
    }
`

因为200时返回的是基础类型 boolean 
所以前端显示 200 状态时 当成 json 解析  
会出错 。

**Comment by xiaoymin** [comment]
不是很明白，是哪里出错？

**Comment by xiaoymin** [comment]
ui是什么版本？

**Comment by qiao-wei** [comment]
@ApiOperation(value = "...")
    @ApiResponses({
            @ApiResponse(code = HttpStatus.SC_OK,message = "",response = Boolean.class),
            @ApiResponse(code = HttpStatus.SC_BAD_REQUEST,message = "Bad Request",response = ErrorMessage.class),
    })
    @RequestMapping(value = {"i"}, method = RequestMethod.PATCH)
    Object updateI() {
        try {
            // 当前用户可以修改自己的密码
            return  true;
        } catch (RecordExistedException ex) {
            LOGGER.debug(ex.getMessage(), ex);
            return ErrorMessage.build(new ErrorMessage());
        }
    }

这种情况就会出问题 。

**Comment by xiaoymin** [comment]
是出什么问题？能贴ui图吗

**Comment by WilliamShoww** [comment]
对啊，具体哪里有问题啊？表示没看懂
