### ISSUE TITLE
返回类型如果是泛型，参数如何定义

### ISSUE THREAD

**Issue by myitsite** [xiaoymin/knife4j#123]
返回类型如果是泛型，参数如何定义

**Comment by xiaoymin** [comment]
返回类型是泛型 和参数 没什么关系吧？

**Comment by myitsite** [comment]
sorry，表达失误了，应该是返回类型是JSONobject 或者Map等对象的备注说明

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/guide/dynamicResponse.html
