### ISSUE TITLE
调试  字段属性说明不显示问题

### ISSUE THREAD

**Issue by azhon** [xiaoymin/knife4j#124]
https://doc.xiaominfo.com/guide/swagger-des-not-found.html
使用泛型T还是不显示
![QQ截图20190709154238](https://user-images.githubusercontent.com/20559556/60868800-5352b480-a260-11e9-9c5a-8b66bccadc24.png)
![QQ截图20190709154253](https://user-images.githubusercontent.com/20559556/60868803-53eb4b00-a260-11e9-8e61-9d965a68653b.png)
![QQ截图20190709154303](https://user-images.githubusercontent.com/20559556/60868804-5483e180-a260-11e9-8df6-52309dedadfe.png)

**Comment by xiaoymin** [comment]
界面什么效果 

什么版本

**Comment by azhon** [comment]
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
            <version>1.9.0</version>
        </dependency>

![QQ截图20190709160222](https://user-images.githubusercontent.com/20559556/60870225-03c1b800-a263-11e9-98f5-7fc631c65f46.png)

**Comment by azhon** [comment]
就是右边啥也没有

**Comment by xiaoymin** [comment]
Userbean 贴看看

**Comment by azhon** [comment]
get、set方法也生成了
![image](https://user-images.githubusercontent.com/20559556/60870474-877ba480-a263-11e9-97b0-64e4d8abc8c0.png)

**Comment by xiaoymin** [comment]
这也不是同一个啊，你接口那边写的是UserBean

你贴出来的是UserInfoBean

**Comment by azhon** [comment]
![QQ截图20190709160910](https://user-images.githubusercontent.com/20559556/60870769-0bce2780-a264-11e9-803c-1c65f8c03d50.png)
![QQ截图20190709160921](https://user-images.githubusercontent.com/20559556/60870770-0c66be00-a264-11e9-9ed0-798cc486725a.png)
![QQ截图20190709160933](https://user-images.githubusercontent.com/20559556/60870771-0cff5480-a264-11e9-8062-66c9bff35b6a.png)
![image](https://user-images.githubusercontent.com/20559556/60870474-877ba480-a263-11e9-97b0-64e4d8abc8c0.png)
![QQ截图20190709160222](https://user-images.githubusercontent.com/20559556/60870793-1be60700-a264-11e9-8634-2734d8ca950b.png)

**Comment by azhon** [comment]
现在是一整套了，你看下

**Comment by xiaoymin** [comment]
文档  tab页有说明吗 字段的说明

**Comment by azhon** [comment]
有的
![image](https://user-images.githubusercontent.com/20559556/60871247-f1e11480-a264-11e9-9b9f-2e1bb5549587.png)

**Comment by xiaoymin** [comment]
升级版本 试试

**Comment by xiaoymin** [comment]
1.9.1 应该就可以了

http://swagger-bootstrap-ui.xiaominfo.com/doc.html#/%E5%88%86%E7%BB%84%E6%8E%A5%E5%8F%A3/1.9.1%E7%89%88%E6%9C%AC-20190305/findAll1UsingPOST

https://gitee.com/-/ide/project/xiaoym/swagger-bootstrap-ui-demo/edit/master/-/swagger-bootstrap-ui-demo/src/main/java/com/swagger/bootstrap/ui/demo/group/Api191Controller.java

**Comment by azhon** [comment]
1.9.1版本可以了

**Comment by JakeWoki** [comment]
返回字段较多，需要滚动的时候，滚动后说明消失
2.0.8版本还是有问题@xiaoymin
