### ISSUE TITLE
导出xlsx文件时，页面没有反应，空白

### ISSUE THREAD

**Issue by yzx5507** [xiaoymin/knife4j#125]
![image](https://user-images.githubusercontent.com/22589584/60957071-9c753800-a336-11e9-97e4-15f40b243535.png)

但是swagger-ui支持：
![image](https://user-images.githubusercontent.com/22589584/60957194-d0e8f400-a336-11e9-9145-957b476ff14f.png)

**Comment by xiaoymin** [comment]
springfox-swagger和ui都是什么版本

https://doc.xiaominfo.com/guide/downloadAndPreview.html

**Comment by yzx5507** [comment]
2.9.2版本

**Comment by yzx5507** [comment]
添加了produces = "application/octet-stream"，出现了下载文件链接，但是下载的内容不对，文件名是SwaggerBootstrapUiDownload.txt，但是实际上我下载的是xlsx

**Comment by xiaoymin** [comment]
ui升版本

**Comment by yzx5507** [comment]
> ui升版本

1.9.4版本吗，也不行

**Comment by xiaoymin** [comment]
试试1.9.5
