### ISSUE TITLE
异常信息用Springboot的BasicErrorController统一处理后，不能格式化显示

### ISSUE THREAD

**Issue by wuxingye** [xiaoymin/knife4j#126]
![image](https://user-images.githubusercontent.com/9107702/61178366-506c1100-a61e-11e9-9108-b19bc9fee12f.png)

**Comment by wuxingye** [comment]
![image](https://user-images.githubusercontent.com/9107702/61179574-aef1b900-a637-11e9-8ca1-bb2eb1ad0867.png)

swagger可以格式化

**Comment by xiaoymin** [comment]
试试1.9.5

**Comment by wuxingye** [comment]
![image](https://user-images.githubusercontent.com/9107702/62258735-3adc5100-b43e-11e9-83e5-8316e0681d2c.png)

已修复，谢谢
