### ISSUE TITLE
动态字段注释 不支持get请求

### ISSUE THREAD

**Issue by MorningGlow** [xiaoymin/knife4j#128]
![OD%INPT`LWKDVR{P_JG{3_7](https://user-images.githubusercontent.com/10829744/61192570-def89500-a6e7-11e9-80a6-7690202129ef.png)
![@)Q{QD90%NUR~BP39 %J4`3](https://user-images.githubusercontent.com/10829744/61192575-e5870c80-a6e7-11e9-9a24-51dbafcff38e.png)
![1U8R`QZK8(V0Y)WVH B3%~U](https://user-images.githubusercontent.com/10829744/61192581-f2a3fb80-a6e7-11e9-8e17-48ebc726625c.png)
![MVJ7`)`4E9X2JNL)Z4)75XJ](https://user-images.githubusercontent.com/10829744/61192585-f768af80-a6e7-11e9-9d21-ba8bdf7556e4.png)

**Comment by xiaoymin** [comment]
ui依赖的发送组件jQuery,axios均不支持get请求发送body,况且该类请求在各个规范里面也不尽相同,有些会过滤掉GET请求body内容,因此暂不支持此功能,请使用POST或者PUT
