### ISSUE TITLE
接口返回boolean时，不能在文档中显示返回值类型及示例

### ISSUE THREAD

**Issue by yupaits** [xiaoymin/knife4j#13]
接口返回值类型为boolean时，接口文档中返回值类型和示例的部分内容为空，猜想非引用类型可能都会出现这种情况。而官方的swagger-ui 2.x版本能显示返回值为 boolean 类型。
版本：
swagger: 2.8.0
swagger-bootstrap-ui: 1.7.9

**Comment by xiaoymin** [comment]
能否贴下后台的相关代码，返回的，前端界面显示的界面截图更好

**Comment by yupaits** [comment]
后台代码：

```java
@ApiOperation("添加店铺商品")
@PostMapping("")
public boolean addShopGoods(@RequestBody ShopGoodsCreate shopGoodsCreate) {
     return shopGoodsService.addShopGoods(shopGoodsCreate);
}
```
现截的图，从公司gitlab拉代码跑的：
![swagger-bootstrap-ui](https://user-images.githubusercontent.com/12194490/43906924-fcab7558-9c26-11e8-8027-560926762f24.png)

换成swagger-ui code为200时这里是能显示返回值为 boolean 类型：
![swagger-ui](https://user-images.githubusercontent.com/12194490/43907155-72a7b3fc-9c27-11e8-809c-b940e7d880b8.png)
![swagger-ui](https://user-images.githubusercontent.com/12194490/43907211-89ec8326-9c27-11e8-8d95-d861031ec3f6.png)

**Comment by xiaoymin** [comment]
1.8.1 已经返回处理
