### ISSUE TITLE
非200的情况下不能正常展示json格式化效果

### ISSUE THREAD

**Issue by gyk001** [xiaoymin/knife4j#130]

**Comment by gyk001** [comment]
![image](https://user-images.githubusercontent.com/918796/61786088-95265200-ae3f-11e9-97f3-d87d3d045b57.png)
正常返回200是可以格式化显示json和字段注释

**Comment by gyk001** [comment]
![image](https://user-images.githubusercontent.com/918796/61786174-b8510180-ae3f-11e9-8da7-dc95d0b35c6d.png)
返回非200时结果无法正常格式显示

**Comment by xiaoymin** [comment]
1.9.5已解决
