### ISSUE TITLE
接口返回的数据类型为对象集合，如List<CategoryScreenVO>，但是界面显示时却没有识别出集合中对象

### ISSUE THREAD

**Issue by chenpengliang0909** [xiaoymin/knife4j#133]
接口返回的数据类型为对象集合，如List<CategoryScreenVO>，但是在原生swagger能识别出集合中对象，在咱们这却没有识别出来呢；
![image](https://user-images.githubusercontent.com/42886170/61857339-8e0e4b00-aef6-11e9-94ba-876819975ea6.png)

![image](https://user-images.githubusercontent.com/42886170/61857423-b8600880-aef6-11e9-8be4-60777721268d.png)

**Comment by xiaoymin** [comment]
ui的版本是多少

**Comment by chenpengliang0909** [comment]
版本：<version>1.9.3</version>
