### ISSUE TITLE
响应体中的长整型显示错误

### ISSUE THREAD

**Issue by WilliamShoww** [xiaoymin/knife4j#135]
一下是页面上显示的内容
```json
{
  "state": "SUCCESS",
  "data": [
    {
      "id": 1153475471162216400,
      "name": "***********",
      "postNum": 2,
      "readNum": 0
    }
  ]
}
```
浏览器f12 看到的内容，也是服务端给的内容
```json
{"state":"SUCCESS","data":[{"id":1153475471162216445,"name":"***********","postNum":2,"readNum":0}]}
```
id 是长整型 最后两位显示错误了

**Comment by WilliamShoww** [comment]
版本1.9.1 和最新的1.9.5 都有一样的问题，并且是必现

**Comment by xiaoymin** [comment]
这个问题是存在的，在前端使用JSON.parse方法的时候 精度丢失的问题。。

**Comment by WilliamShoww** [comment]
> 这个问题是存在的，在前端使用JSON.parse方法的时候 精度丢失的问题。。

有什么办法可以解决吗？

**Comment by WilliamShoww** [comment]
> > 这个问题是存在的，在前端使用JSON.parse方法的时候 精度丢失的问题。。
> 
> 有什么办法可以解决吗？

因为这个问题，很影响有关联关系的接口直接调试

**Comment by xiaoymin** [comment]
暂时还没找到解决方案。。
原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作

**Comment by WilliamShoww** [comment]
> 暂时还没找到解决方案。。
> 原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作

后来百度了一下，明白问题所在了，还好前端还没开始，前端开始了，我在想他们应该怎么办？

**Comment by Jnoee** [comment]
我是把长整型处理成字符串传给前端。

**Comment by blueye4ky** [comment]
> 暂时还没找到解决方案。。
> 原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作

chrome使用JSON-handle插件可以显示一致的，是否可以做参考。

**Comment by xiaoymin** [comment]
> > 暂时还没找到解决方案。。
> > 原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作
> 
> chrome使用JSON-handle插件可以显示一致的，是否可以做参考。

谢谢，我参考一下

**Comment by WilliamShoww** [comment]
> > 暂时还没找到解决方案。。
> > 原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作
> 
> chrome使用JSON-handle插件可以显示一致的，是否可以做参考。

问一下 JSON-handle可以引入包吗？在任何地方都支持长整型精度？百度没找到，只有插件

**Comment by xiaoymin** [comment]
> > > 暂时还没找到解决方案。。
> > > 原来想的是是使用正则的方式替换.但是这种方式需要对每一个返回的接口的json进行遍历,如果返回的层次比较深的话 每次都遍历太耗时，何况并不是所有的都需要这种操作
> > 
> > 
> > chrome使用JSON-handle插件可以显示一致的，是否可以做参考。
> 
> 问一下 JSON-handle可以引入包吗？在任何地方都支持长整型精度？百度没找到，只有插件

磁盘上可以看到JSON-handle的用到的js

里面有一个json5.js ，我试了一下 是可以的 ，不会丢失精度

**Comment by xiaoymin** [comment]
![image](https://user-images.githubusercontent.com/7894406/63570354-71296e00-c5af-11e9-8335-57a633f509d3.png)
![image](https://user-images.githubusercontent.com/7894406/63570372-7e465d00-c5af-11e9-99e3-4e1746097786.png)

**Comment by xiaoymin** [comment]
1.9.6 解决了这个问题 
https://www.oschina.net/news/109441/swagger-bootstrap-ui-1-9-6-released
新发布的swagger-bootstrap-ui的最后一个版本1.9.6

项目也更名为knife4j了,ui和java代码分离了

后续会以此来继续更新

https://doc.xiaominfo.com/knife4j/
