### ISSUE TITLE
访问api-docs-ext?group=default出现404

### ISSUE THREAD

**Issue by Jnoee** [xiaoymin/knife4j#137]
我用的spring boot 2.1.6，doc.html页面打开了，但是请求 http://localhost:8080/v2/api-docs-ext?group=default 这个地址出错 404，不知是何原因？

**Comment by xiaoymin** [comment]
api-docs-ext是我提供的，后端要使用`@EnableSwaggerBootstrapUI`增强注解

**Comment by Jnoee** [comment]
加了注解好了，谢谢。
