### ISSUE TITLE
以thymeleaf作为视图，访问doc.html返回的却不是接口文档界面，而是其它视图

### ISSUE THREAD

**Issue by developers-youcong** [xiaoymin/knife4j#139]
我这边个人项目采用的主要技术栈是SpringBoot，以thymeleaf作为视图模板。
之前没有采取thymeleaf作为视图模板时，可以正常通过http://localhost:port/project_name/doc.html
访问到正常接口文档界面。
但是当我配置thymeleaf后，就不能访问了，直接返回的是其它视图，请问是什么原因呢？
我的application.yml关键配置如图:
![image](https://user-images.githubusercontent.com/45055576/62629268-6cce4580-b95f-11e9-8be6-8ea42e36a9d6.png)

相关版本:
SpringBoot版本为1.5.9
swagger-bootstrap-ui版本为1.9.3
我觉得与版本是没有关系的，不过列出来看看会有什么帮助。

**Comment by xiaoymin** [comment]
指定静态资源应该就可以了，doc.html不走后端视图解析

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/faq/springboot-404.html 应该和404处理差不多的方式
