### ISSUE TITLE
oauth2 header token空格被URL编码导致后端获取不到token

### ISSUE THREAD

**Issue by JiaRG** [xiaoymin/knife4j#140]
全局参数设置：
![image](https://user-images.githubusercontent.com/31472350/62693916-f1739f00-ba05-11e9-8ba4-99cdf6cff98b.png)
请求参数列表：
![image](https://user-images.githubusercontent.com/31472350/62694009-1f58e380-ba06-11e9-90ad-bb797d16fb4c.png)
实际请求及响应：
![image](https://user-images.githubusercontent.com/31472350/62694198-765eb880-ba06-11e9-8b67-b390efd73a63.png)

**Comment by xiaoymin** [comment]
1.9.6 解决了这个问题 
https://www.oschina.net/news/109441/swagger-bootstrap-ui-1-9-6-released
新发布的swagger-bootstrap-ui的最后一个版本1.9.6

项目也更名为knife4j了,ui和java代码分离了

后续会以此来继续更新

https://doc.xiaominfo.com/knife4j/
