### ISSUE TITLE
调试时候的使用的 host 并不是 swagger 文档中定义的 host

### ISSUE THREAD

**Issue by zxy198717** [xiaoymin/knife4j#142]
如题，调试的时候没有使用 swagger 定义的 host 及 scheme。而是使用的 doc 页面的。

另外 host 能否支持自定义？

一般情况下，开发环境会有多套，部署一套文档。调试的时候支持自定义 host，会比较高效。

**Comment by xiaoymin** [comment]
如果不走doc页面中的地址，在网页端会出现跨域的情况(服务端未处理cors的情况下)

**Comment by zxy198717** [comment]
默认走 doc 页面中的地址也可以，最好能支持前端自定义 host，这样的话，多套环境就可以使用一份文档了。

**Comment by ymybxx** [comment]
> 如果不走doc页面中的地址，在网页端会出现跨域的情况(服务端未处理cors的情况下)

跨域问题是服务端需要解决的，但是前端最好还是能自定义

**Comment by xiaoymin** [comment]
用用knife4j-admin 吧，不用在代码层网关聚合文档，独立中间件，任意聚合Swagger文档

https://www.oschina.net/news/115814/knife4j-admin-1-0-released

**Comment by zxy198717** [comment]
@xiaoymin 试了一下，knife4j-admin 在调试的时候用的也不是 swagger 文档内定义的 host，其实最好能支持配置 host，跨域问题后端会解决的，不复杂。
