### ISSUE TITLE
Path型的参数无法传递

### ISSUE THREAD

**Issue by ExhaustiveMethod** [xiaoymin/knife4j#143]
![11](https://user-images.githubusercontent.com/41338498/63409553-fd0e8f00-c423-11e9-8f73-c34aefeac90c.PNG)
![2](https://user-images.githubusercontent.com/41338498/63409609-14e61300-c424-11e9-9772-8eb3918421b0.PNG)
![3](https://user-images.githubusercontent.com/41338498/63409615-17486d00-c424-11e9-9bb1-8dbebe3bf608.PNG)
当使用path型参数时，后台无法接受到，应该是没有拼接到URL上？
使用的版本是1.9.5

**Comment by rends** [comment]
同错误

**Comment by xiaoymin** [comment]
195 确实存在这个问题  194 没有的
有个pr改了 测试疏漏

**Comment by ExhaustiveMethod** [comment]
> 195 确实存在这个问题 194 没有的
> 有个pr改了 测试疏漏

194可以使用。谢谢
