### ISSUE TITLE
PathVariable

### ISSUE THREAD

**Issue by dlarmor** [xiaoymin/knife4j#144]
![image](https://user-images.githubusercontent.com/24198244/63483582-79aa7780-c4cf-11e9-9228-d544f9d5109a.png)
![image](https://user-images.githubusercontent.com/24198244/63483592-83cc7600-c4cf-11e9-8075-25bac6b4c732.png)

PathVariable 详情下 会请求失败

**Comment by blueye4ky** [comment]
Duplicate of #同样的问题，调试页面不会将url参数{schoolId}带入，这应该是一个BUG吧

**Comment by xiaoymin** [comment]
1.9.5有这个bug，用1.9.4可以的

**Comment by hellokaton** [comment]
期待 `1.9.6` 发布 🥰

**Comment by xiaoymin** [comment]
1.9.6 解决了这个问题 
https://www.oschina.net/news/109441/swagger-bootstrap-ui-1-9-6-released
新发布的swagger-bootstrap-ui的最后一个版本1.9.6

项目也更名为knife4j了,ui和java代码分离了

后续会以此来继续更新

https://doc.xiaominfo.com/knife4j/
