### ISSUE TITLE
PathVariable参数在调用后,关闭接口标签会替换成传入的参数,下次打开接口标签时输入参数无效

### ISSUE THREAD

**Issue by aprcheng** [xiaoymin/knife4j#145]
![image](https://user-images.githubusercontent.com/31011644/63575599-067f2f00-c5bd-11e9-923a-f0393c1cb113.png)
![image](https://user-images.githubusercontent.com/31011644/63575858-a2109f80-c5bd-11e9-994f-1a765df44ff6.png)
![image](https://user-images.githubusercontent.com/31011644/63576014-f3209380-c5bd-11e9-9beb-5fbd736d1b29.png)

**Comment by aprcheng** [comment]
1.9.4 版本

**Comment by xiaoymin** [comment]
这个是在键入参数值的时候，自动把显示的url中替换成值吗
然后第二次进来就是上一次替换过后的？

**Comment by aprcheng** [comment]
对的

**Comment by xiaoymin** [comment]
1.9.6版本解决了这个bug，在线效果
http://swagger-bootstrap-ui.xiaominfo.com/doc.html#/1.9.X%E7%89%88%E6%9C%AC%E6%8E%A5%E5%8F%A3/1.9.6%E7%89%88%E6%9C%AC-20190827/pathUserUsingPOST


新发布的swagger-bootstrap-ui的最后一个版本1.9.6

项目也更名为knife4j了,ui和java代码分离了

后续会以此来继续更新

https://doc.xiaominfo.com/knife4j/

**Comment by aprcheng** [comment]
这个bug在我的项目没有得到解决
![image](https://user-images.githubusercontent.com/31011644/63906611-0793de80-ca4b-11e9-84c9-67822b0bacdd.png)

**Comment by xiaoymin** [comment]
升级后清理缓存

**Comment by aprcheng** [comment]
可以了  谢谢
