### ISSUE TITLE
nodejs能用吗，能否支持下?

### ISSUE THREAD

**Issue by yeongjet** [xiaoymin/knife4j#146]

**Comment by xiaoymin** [comment]
nodejs有解析框架么。

**Comment by henryzp** [comment]
@xiaoymin ，eggjs有一个swagger的插件，你可以看看的。。。感觉应该是有的

**Comment by xiaoymin** [comment]
直接上front版本吧，把swagger的json作为离线版本来使用，文档：https://doc.xiaominfo.com/knife4j/knife4j-front-source-modified.html
