### ISSUE TITLE
能否支持将接口文档统一到一个服务中展示

### ISSUE THREAD

**Issue by blueye4ky** [xiaoymin/knife4j#147]
目前我这边结合spring-cloud-gateway将接口文档统一到一个服务中展示，但是gateway与spring-web不兼容，所以@EnableSwaggerBootstrapUi这个注解也不能用，不知道作者有没有这方面的建议，谢谢。

**Comment by xiaoymin** [comment]
是什么冲突？注解不能用 是报什么错吗？

demo地址：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo

模块：knife4j-spring-cloud-gateway  或许你可以参考下

**Comment by blueye4ky** [comment]
好的，我看一下
