### ISSUE TITLE
请问一下，github上面demo是正常运行的，但是接到自己新建的项目alibaba spirngcloud就出问题

### ISSUE THREAD

**Issue by tdcqkris** [xiaoymin/knife4j#148]
![image](https://user-images.githubusercontent.com/24537617/64098927-a0ec2900-cd9a-11e9-8da5-26da51b66fbc.png)

**Comment by xiaoymin** [comment]
什么错误？

**Comment by xiaoymin** [comment]
这种情况可以看看接口请求,如果请求里面的数据是错的，那ui就渲染不出来了，

**Comment by tdcqkris** [comment]
knife4j-spring-cloud-gateway我接的是这个demo,  demo再本地运行都是正常的，

**Comment by xiaoymin** [comment]
关于Spring Cloud alibaba的demo  可以提交一个PR上来么，我可以看一下

正好也整合进demo 方便别人参考

**Comment by tdcqkris** [comment]
![image](https://user-images.githubusercontent.com/24537617/64099176-37b8e580-cd9b-11e9-885b-cf3b81d2ef03.png)

**Comment by tdcqkris** [comment]
springcloud alibaba,最近一直再调研，就差这个接口的整合方面demo

**Comment by tdcqkris** [comment]
我想问一下，我刚刚发的图中的那个小数点或者那个路径是在哪里该的吗，找了好久没找到

**Comment by xiaoymin** [comment]
应该没有逗号的。。。很神奇

**Comment by xiaoymin** [comment]
微服务版本可以试试knife4j-admin

https://doc.xiaominfo.com/solution/admin.html
