### ISSUE TITLE
在线调试，能够自定义headers的内容吗？

### ISSUE THREAD

**Issue by tanqimin** [xiaoymin/knife4j#15]
有些特殊的情况，如需要在Headers加入Token，需要自定义Headers的内容，希望可以加入此功能。

**Comment by xiaoymin** [comment]
这个功能本身就包含的，目前最新版本是1.8.1

我的demo里面也有，你可以参考一下

demo地址：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo

demo的在线地址：http://swagger-bootstrap-ui.xiaominfo.com/doc.html

**Comment by tanqimin** [comment]
看到了，不好意思，没看清楚DEMO
