### ISSUE TITLE
返回数据类型复杂，JSON转换异常，doc页面无响应

### ISSUE THREAD

**Issue by xinyaw** [xiaoymin/knife4j#150]
1.doc页面渲染 调用swagger /v2/api-docs出现以下异常
![image](https://user-images.githubusercontent.com/43558556/64139425-671b3100-ce33-11e9-8e12-d4e3300946da.png)
2.页面出现空白
![image](https://user-images.githubusercontent.com/43558556/64139552-de50c500-ce33-11e9-872b-edf1b503d010.png)

**Comment by xiaoymin** [comment]
参考这个
https://doc.xiaominfo.com/faq/swaggerResourceInvalid.html

**Comment by xinyaw** [comment]
多谢多谢，按照文档已解决该问题
