### ISSUE TITLE
发送请求数据异常的问题

### ISSUE THREAD

**Issue by MHYJ** [xiaoymin/knife4j#154]
在执行接口调用时，以form表单形式提交，但是表单数据并没有按键值对形式传递，如图所示：
![image](https://user-images.githubusercontent.com/8298959/64674549-a8e74f80-d4a3-11e9-9e68-e4647b4b8c93.png)

**Comment by xiaoymin** [comment]
这种其实并非是ui的问题，springfox-swagger框架识别出来的问题

将form表单类型的参数识别成了body类型

你可以在你的接口代码中，参数前面加上`@RequestParam`参数进行约束，ui就会显示成单行文本框（body类型一般是针对@RequestBody注解标注的参数使用的多行）

**Comment by MHYJ** [comment]
哇，回复的好快。确实是必须指定这个注解才行，可能之前用过类似的工具(不用指定这个注解也可以)，习惯性的忽略这个注解了
