### ISSUE TITLE
想把这套 UI 修改为 php 的扩展包，请问作者可以使用吗？

### ISSUE THREAD

**Issue by damaainan** [xiaoymin/knife4j#155]
想把这套 UI 修改为 php 的扩展包，请问作者可以使用吗？

**Comment by xiaoymin** [comment]
可以，欢迎发扬光大

**Comment by damaainan** [comment]
感谢！！！

**Comment by xiaoymin** [comment]
不知道php是否也是类似Java这样，直接发布到中央仓库的方式，外网可以直接引用，类似于模块引用

如果也是这样的话，可以挂个宣传链接，方便php的朋友直接引用

**Comment by damaainan** [comment]
可以发布成公共的包。感觉很好，也是给自己找个事做

**Comment by xiaoymin** [comment]
期待你的公共包 和一篇博客介绍啊 我可以挂到 https://doc.xiaominfo.com/

这个说明文档上去
