### ISSUE TITLE
返回的JSON键中有点（.）、中括号时（[]）或为数字时，会自动变成两个引号

### ISSUE THREAD

**Issue by xqdd** [xiaoymin/knife4j#156]
![image](https://user-images.githubusercontent.com/20871761/65133815-e4e75b00-da35-11e9-83a6-d8dfee2a6b1d.png)

**Comment by xqdd** [comment]
![image](https://user-images.githubusercontent.com/20871761/65135613-d189bf00-da38-11e9-9913-23bc2e3dc419.png)

**Comment by BLF2** [comment]
我也遇到你这个问题了，请问你解决了吗

**Comment by xqdd** [comment]
没有，问题不大，和前端说一下就行了

**Comment by BLF2** [comment]
哈哈 这个办法可以 我没去看源码 感觉是在json格式化的时候出现的问题  在raw里面就是正常的

**Comment by xiaoymin** [comment]
2.0 解决了 试试新版本吧

https://www.oschina.net/news/112095/knife4j-2-0-released

**Comment by BLF2** [comment]
感谢大佬
