### ISSUE TITLE
header传参自动多了一个XMLHttpRequest

### ISSUE THREAD

**Issue by yuanhan1993** [xiaoymin/knife4j#158]
使用的是1.9.6版本，在全局参数里加上header后，传到后台显示的header多了一个XMLHttpRequest。
例如：
在全局参数增加一个header: x-requested-with:**{"token":"123"}**
后端HttpServletRequest 获取header时，获取到的x-requested-with值为：
**{"token":"123"}, XMLHttpRequest**

**Comment by xiaoymin** [comment]
截图 看看

**Comment by yuanhan1993** [comment]
> 截图 看看

![image](https://user-images.githubusercontent.com/20400416/65493236-0ab4aa00-dee5-11e9-8552-e6e16310c066.png)
![image](https://user-images.githubusercontent.com/20400416/65493359-48b1ce00-dee5-11e9-8b05-a8f58f164f6c.png)
![image](https://user-images.githubusercontent.com/20400416/65493462-7434b880-dee5-11e9-8068-567dbac357df.png)

**Comment by xiaoymin** [comment]
你这个名字最好换一个，x-requested-with是前端ajax发送的标志请求头，混在一起可能会有问题，这个应该和ui框架是没关系的
