### ISSUE TITLE
DELETE请求无法正确处理请求头

### ISSUE THREAD

**Issue by captainjack0x7C8** [xiaoymin/knife4j#16]
delete请求会将请求头放在url参数中

**Comment by xiaoymin** [comment]
能详细说明一下吗

**Comment by captainjack0x7C8** [comment]
我在delete请求中使用@RequestHeader，参数是说明也确实显示该参数位于header中，但try it out时，参数实际是以url param形式发送的，切换到/swagger-ui.html后没有这个问题

**Comment by xiaoymin** [comment]
好的，感谢反馈， 我看下

**Comment by captainjack0x7C8** [comment]
人人为我，我为人人

**Comment by xiaoymin** [comment]
1.8.2 已解决，欢迎升级反馈

**Comment by xiaoymin** [comment]
新版已更新，感谢使用反馈~~

http://www.xiaominfo.com/2018/08/26/swagger-bootstrap-ui-1.8.2-issue/
