### ISSUE TITLE
类上使用ApiModel注解,在value中有点[.], 会导致ui接口无法显示内容

### ISSUE THREAD

**Issue by Nitsuya** [xiaoymin/knife4j#160]
举例:
@ApiModel(value="com.xxx.xxx.xxx.xx.entity")
@Data
public class User implements Serializable {
  private String data;
}
controller:
@ApiOperation(position = 2, value = "测试2")
@PostMapping(value = "/test")
public User test(@RequestBody User user){ return null; }
--------
说明:
@ApiModel(value="com.xxx.xxx.xxx.xx.entity")
如果value带了点[.] 会导致UI上无法显示字段内容.. 但是如果参数是parameter没问题, body就会出现问题..
补充:
测试官方UI也有这个问题~

**Comment by ya-dao** [comment]
感谢老哥提的这个issue，各种尝试搞3个多小时，看到这儿帮了我大忙了。

**Comment by xiaoymin** [comment]
那就别带了吧

**Comment by lvlonghu-dadi01** [comment]
也不能加 “/”
