### ISSUE TITLE
@PathVariable Long类型显示异常

### ISSUE THREAD

**Issue by king-luffy** [xiaoymin/knife4j#161]
@PathVariable Long类型显示异常，Long类型会被显示成Integer类型，类型int64没有正常显示
`    @RequestMapping(value="/citys/{city_id}/apartments",method= RequestMethod.GET,headers = {"Api-Version=1"})
    @AuthPointCut(permitUserTypes = {UserType.Operator})
    @ApiOperation(value = "查询城市门店列表", notes = "查询城市门店列表")
    public SearchListApartmentResponse searchListApartment(@ApiIgnore RequestHeader header, @PathVariable Long city_id){
        return  new SearchListApartmentResponse();
    }`
    
![image](https://user-images.githubusercontent.com/12569278/67101450-3bda7e80-f1f4-11e9-801d-a69580876cf9.png)

**Comment by xiaoymin** [comment]
2.0 解决了  试试吧

https://www.oschina.net/news/112095/knife4j-2-0-released
