### ISSUE TITLE
出现了URL：bootstrap.min.css.map 404的错误。

### ISSUE THREAD

**Issue by zz99132242** [xiaoymin/knife4j#162]
需要删除引用的bootstrap.css最后一行
/*# sourceMappingURL=bootstrap.css.map */

**Comment by xiaoymin** [comment]
感谢反馈，下个版本修正

**Comment by xiaoymin** [comment]
2.0版本全新改版，应该没这个问题了 ，试试吧

https://www.oschina.net/news/112095/knife4j-2-0-released
