### ISSUE TITLE
controller返回Map,页面中的key是两个双引号""name""

### ISSUE THREAD

**Issue by ruoook** [xiaoymin/knife4j#163]
controller返回Map,页面中的key是两个双引号""name"",使用原生的swagger-ui可以正常显示的
![Snipaste_2019-10-15_16-48-02](https://user-images.githubusercontent.com/17269181/67296325-e1eef700-f51a-11e9-8e94-670cc37f80e6.png)

**Comment by taoes** [comment]
+ JSON 数据格式如下:
![image](https://user-images.githubusercontent.com/22141049/68267127-546be500-008c-11ea-8639-18434768f0f3.png)

+ 渲染出来的结果

![image](https://user-images.githubusercontent.com/22141049/68267157-69e10f00-008c-11ea-9d2d-c877776fddb7.png)

**Comment by xiaoymin** [comment]
代码能贴一下？

是什么版本

**Comment by taoes** [comment]
版本 1.9.6  返回数据结构如下：
![image](https://user-images.githubusercontent.com/22141049/68286182-9c563080-00bb-11ea-93bb-ff151f63a397.png)

其中的data传Map的话，就会出现双引号的问题，返回的JSON 正常，格式化就会出现这样的问题

**Comment by xiaoymin** [comment]
1.9.6 版本确实存在这个bug，感谢反馈

**Comment by xqdd** [comment]
相关https://github.com/xiaoymin/swagger-bootstrap-ui/issues/156

**Comment by xiaoymin** [comment]
2.0 解决了 这个问题，试试吧

https://www.oschina.net/news/112095/knife4j-2-0-released
