### ISSUE TITLE
现在响应类型为JSONObject,该怎么添加字段注释呢

### ISSUE THREAD

**Issue by yangbo1987** [xiaoymin/knife4j#164]

**Comment by xiaoymin** [comment]
文档地址：https://doc.xiaominfo.com/guide/dynamicResponse.html
可以参考一下

众多Demo：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo

**Comment by maxid** [comment]
https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot-demo/src/main/java/com/swagger/bootstrap/ui/demo/group/Api195Controller.java
