### ISSUE TITLE
希望新的版本能支持spring data rest 直接集成到starter里面

### ISSUE THREAD

**Issue by sunshixiong789** [xiaoymin/knife4j#168]
发现好像不能够使用 spring data rest,希望能够适用于spring data rest和spring mvc

**Comment by xiaoymin** [comment]
spring mvc 和spring boot 没什么区别

**Comment by sunshixiong789** [comment]
现在项目基本都是spring boot的，我是说支持能够生成spring data rest这个api文档

**Comment by xiaoymin** [comment]
rest这个比较麻烦，相当于要写一个类似于springfox的解析，生成一份OpenApi格式结构

**Comment by sunshixiong789** [comment]
现在我用的<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-data-rest</artifactId>
        </dependency>这个组件，使用的你的ui还是能够展示，只不过在你改版后的不能用

**Comment by xiaoymin** [comment]
什么问题，报什么错

**Comment by sunshixiong789** [comment]
增强功能也不能用






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoymin"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午2:18
收件人: "xiaoymin/swagger-bootstrap-ui"<swagger-bootstrap-ui@noreply.github.com&gt;; 
抄送: "孙士雄"<1285913468@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xiaoymin/swagger-bootstrap-ui] 希望新的版本能支持spring data rest 直接集成到starter里面 (#168)




rest这个比较麻烦，相当于要写一个类似于springfox的解析，生成一份OpenApi格式结构
 
&mdash;

**Comment by sunshixiong789** [comment]
没有，只不过支持spring boot2.0的要swagger 3.0 SNAPSHOT版本的才能用，所以我使用的这三个依赖集成方式
![image](https://user-images.githubusercontent.com/31101988/68738586-a5964e80-0621-11ea-8ce5-8b2b7ad2ef29.png)

**Comment by xiaoymin** [comment]
3.0 SNAPSHOT的是目前还没有支持的，最高依赖springfox的版本是2.9.2

**Comment by sunshixiong789** [comment]
嗯嗯，好的，感谢，我想表达的就是最好支持spring data rest就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xiaoymin"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午2:32
收件人: "xiaoymin/swagger-bootstrap-ui"<swagger-bootstrap-ui@noreply.github.com&gt;; 
抄送: "孙士雄"<1285913468@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xiaoymin/swagger-bootstrap-ui] 希望新的版本能支持spring data rest 直接集成到starter里面 (#168)




3.0 SNAPSHOT的是目前还没有支持的，最高依赖springfox的版本是2.9.2
 
&mdash;

**Comment by xiaoymin** [comment]
面包会有的，牛奶也会有的：）
