### ISSUE TITLE
接口调试时后端会执行两次

### ISSUE THREAD

**Issue by Gahon1995** [xiaoymin/knife4j#169]
比较明显的表现就是数据库会查询两次

**Comment by xiaoymin** [comment]
这个你可以看network请求的，如果请求发了两次，那是ui的问题，反之则是你自己代码的问题

**Comment by Gahon1995** [comment]
请求是发了一次，但是后端会执行两次查询，而且只有通过swagger的这个执行才会执行两次，使用postman就只会执行一次

**Comment by xiaoymin** [comment]
请求只发1次和ui没啥关系了吧

**Comment by Gahon1995** [comment]
不清楚，莫名其妙的问题

**Comment by xiaoymin** [comment]
可以debug调试的

**Comment by Gahon1995** [comment]
目前没看出来啥问题，等其他地方出现了这个问题再说吧
