### ISSUE TITLE
返回接口带泛型参数是，解析出错

### ISSUE THREAD

**Issue by wulife** [xiaoymin/knife4j#17]
如果返回值时带泛型的参数时，响应状态码显示处解析实体类的字段属性少了引号，js的json.parse会解析出错。

![got5l 3s4ukht94rw wi fc](https://user-images.githubusercontent.com/26455549/44406194-98f58880-a58d-11e8-9ccc-02b2d80dfd7f.png)

![zja 81lawq s kicj 20 i](https://user-images.githubusercontent.com/26455549/44405625-4798c980-a58c-11e8-9c74-05ea7714685f.png)

![p pj o 41v2i2ku sn](https://user-images.githubusercontent.com/26455549/44405986-2b495c80-a58d-11e8-8f79-0c60dfc3bf8e.png)

![Uploading 0OMAFQ]B@XDDN@N%%_1QG@B.png…]()

**Comment by wulife** [comment]
补上漏了的ResultUtil
![kts z0q og yyb1y6e7b](https://user-images.githubusercontent.com/26455549/44408004-06a3b380-a592-11e8-9bff-55459c7dbe81.png)

**Comment by wulife** [comment]
另外，提一个小建议，个人觉得这个表头的说明要么同意用英文，要么都用中文，两个都用，个人感觉挺奇怪的
![7 s i5ivrth3vawsk0gpkp](https://user-images.githubusercontent.com/26455549/44408267-a3665100-a592-11e8-837b-8b3411f48490.png)

**Comment by xiaoymin** [comment]
@wulife  使用的版本号是多少呢、?

**Comment by xiaoymin** [comment]
针对泛型的返回，你在ctl的代码层最好需要标注出来
```java
publict ResultUtil<User> userInfo(@RequestBody User user)
```

还有使用@ApiModel注解，value一般填写类名，最好和类名一直，description填写说明

**Comment by wulife** [comment]
@xiaoymin 版本是最新的
publict ResultUtil<User> userInfo(@RequestBody User user)
这个返回类型的我之前有写，后面改来改去就改没了，
@apimodel的value值我晚上回去试下

**Comment by xiaoymin** [comment]
@wulife 好的，那我也看下这个问题，感谢反馈

**Comment by wulife** [comment]
好的，谢谢！

**Comment by wulife** [comment]
@xiaoymin 我的代码https://github.com/wulife/-swagger-bootstrap-ui

**Comment by wulife** [comment]
@xiaoymin 我知道哪里错了
![6e1b5y4 ydw8 4 l gg_a](https://user-images.githubusercontent.com/26455549/44469468-21d9f600-a65a-11e8-9a77-2f60449cfe61.png)
这里的example的key,value少了引号

另外，这边的响应体的参数类型显示和schema不对应
![sl 8vj giepm0 u 9y e e](https://user-images.githubusercontent.com/26455549/44470627-cd844580-a65c-11e8-9fb8-442e339caecc.png)

**Comment by xiaoymin** [comment]
新版已更新，感谢使用反馈~~

http://www.xiaominfo.com/2018/08/26/swagger-bootstrap-ui-1.8.2-issue/
