### ISSUE TITLE
对于多种code 有返回响应类的情况 收集不到Swagger Models侧边栏里面不能显示实体

### ISSUE THREAD

**Issue by ruanzhi** [xiaoymin/knife4j#170]
下面是/v2/api-docs返回的json例子：
{"swagger":"2.0","info":{"description":"简单优雅的restful风格","version":"1.0","title":"springboot利用swagger构建api文档"},"host":"localhost:8080","basePath":"/","tags":[{"name":"样例管理接口","description":"样例controller，构建各种测试路径"}],"paths":{"/demo/hello":{"post":{"tags":["样例管理接口"],"summary":"首页","description":"这个项目入口地址","operationId":"homeUsingPOST","consumes":["application/json"],"produces":["*/*"],"parameters":[{"name":"商品id","in":"query","description":"shopId","required":false,"type":"integer","format":"int32","x-example":3748}],"responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/ResultVO«UserVO»"}},"400":{"description":"参数不合法","schema":{"$ref":"#/definitions/ResultVO"}},"500":{"description":"服务端错误","schema":{"$ref":"#/definitions/ResultVO"}}},"deprecated":false}}},"definitions":{"ResultVO":{"type":"object","properties":{"code":{"type":"integer","format":"int32","example":3748,"description":"code码"},"data":{"type":"object","description":"对应的数据"},"msg":{"type":"string","example":"成功","description":"对应msg"}},"title":"ResultVO","description":"统一返回对象实体"},"ResultVO«UserVO»":{"type":"object","properties":{"code":{"type":"integer","format":"int32","example":3748,"description":"code码"},"data":{"description":"对应的数据","$ref":"#/definitions/UserVO"},"msg":{"type":"string","example":"成功","description":"对应msg"}},"title":"ResultVO«UserVO»","description":"统一返回对象实体"},"UserVO":{"type":"object","properties":{"userId":{"type":"integer","format":"int32","example":3748,"description":"用户id"}},"title":"UserVO","description":"用户页面VO实例"}}}

**Comment by xiaoymin** [comment]
试试2.0版本

https://www.oschina.net/news/112095/knife4j-2-0-released
