### ISSUE TITLE
springcloud gateway添加改ui有问题，SecurityConfiguration与原本spring内部冲突

### ISSUE THREAD

**Issue by xincan** [xiaoymin/knife4j#171]

**Comment by xiaoymin** [comment]
你总得把cloud的以及ui的相关版本贴一下吧

冲突错误是啥

不然我也找不到问题所在啊

**Comment by xincan** [comment]
不好意思，我点快了sorry

**Comment by xincan** [comment]
![image](https://user-images.githubusercontent.com/38775862/69029086-ebcb2380-0a0e-11ea-8852-a3e51d748f9c.png)
![image](https://user-images.githubusercontent.com/38775862/69029154-1cab5880-0a0f-11ea-9b02-60da0724d012.png)
![image](https://user-images.githubusercontent.com/38775862/69029177-292fb100-0a0f-11ea-95f2-d253bfdcb86c.png)
![image](https://user-images.githubusercontent.com/38775862/69029244-5c724000-0a0f-11ea-8f20-d67388d01784.png)


SecurityConfiguration和您封装的冲突了，swagger的版本是2.9.2，swagger-bootstrap-ui是1.9.6

**Comment by xiaoymin** [comment]
包路径都不一样，怎么冲突了？

报什么错误 没看到

**Comment by xiaoymin** [comment]
用用knife4j-admin 吧，不用在代码层网关聚合文档，独立中间件，任意聚合Swagger文档

https://www.oschina.net/news/115814/knife4j-admin-1-0-released
