### ISSUE TITLE
成功请求后，再次发送api请求出现不携带token头部参数的问题，刷新后解决

### ISSUE THREAD

**Issue by taoes** [xiaoymin/knife4j#177]
+ 版本2.0
+ 升级到2.0.0 之后，配置了Authorization，在成功请求一次之后，再次点击，发送的请求中不携带token了，导致请求报错(自己的业务的设置)

+ 参数的配置
![image](https://user-images.githubusercontent.com/22141049/70881802-b2cfa000-2008-11ea-9c34-94bce4a7658a.png)

![image](https://user-images.githubusercontent.com/22141049/70881814-bbc07180-2008-11ea-9d54-193f3254ca5d.png)

**Comment by taoes** [comment]
+ 1.9.6 版本正常

**Comment by xiaoymin** [comment]
是连续点击两次 发送？

**Comment by taoes** [comment]
不是，是先点击一次，成功请求后，再次点击就会这样
POST请求偶尔出现，GET请求正常，其他的暂时没有尝试

**Comment by xiaoymin** [comment]
那很奇怪额。。http://knife4j.xiaominfo.com/doc.html#/%E5%88%86%E7%BB%84%E6%8E%A5%E5%8F%A3/1.9.6%E7%89%88%E6%9C%AC-20190827/longUserRest1UsingGET

我用这个测 添加好Auth的参数后，参数发送是都带上的

**Comment by taoes** [comment]
我在测试下，看看能不能再次复现，然后在反馈给你吧，谢谢了😀
