### ISSUE TITLE
强依赖 swagger bean

### ISSUE THREAD

**Issue by wenjies** [xiaoymin/knife4j#178]
在线上环境一般都会关闭swagger 我们是通过来“@ConditionalOnProperty(value ={"swagger.enable"})”控制这时就会报以下错误：

Description:
Parameter 0 of constructor in com.github.xiaoymin.swaggerbootstrapui.plugin.DynamicResponseModelReader required a bean of type 'springfox.documentation.schema.TypeNameExtractor' that could not be found.

Action:
Consider defining a bean of type 'springfox.documentation.schema.TypeNameExtractor' in your configuration.

**Comment by xiaoymin** [comment]
Spring各个依赖组件的版本，你的代码写的示例  贴出来

**Comment by wenjies** [comment]
pom：
 `
		<parent>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-parent</artifactId>
			<version>1.5.11.RELEASE</version>
		</parent>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.6.1</version>
		</dependency>

		 <dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.github.xiaoymin</groupId>
			<artifactId>swagger-bootstrap-ui</artifactId>
			<version>1.9.6</version>
		</dependency>

`


code:

`
	@Configuration
	@EnableSwagger2
	@ConditionalOnProperty(value = {"swagger.enable"}, matchIfMissing = true)
	class Swagger2 {
		/**
		 * swagger2 配置
		 */
		@Bean
		public Docket createRestApi() {
			ApiInfoBuilder apiInfoBuilder = new ApiInfoBuilder();
			apiInfoBuilder.title("xxxApi");
			apiInfoBuilder.description("xxxx  API");
			apiInfoBuilder.termsOfServiceUrl("http://www.xxx.gov.cn");
			Contact contact = new Contact("xxx", "", "");
			apiInfoBuilder.contact(contact);
			apiInfoBuilder.version("1.0");
			ApiInfo apiInfo = apiInfoBuilder.build();

			Docket docket = new Docket(DocumentationType.SWAGGER_2);
			docket.apiInfo(apiInfo);
			ApiSelectorBuilder select = docket.select();
			select.apis(RequestHandlerSelectors.basePackage("com.xxx"));
			select.paths(PathSelectors.any());
			select.build();
			return docket;
		}
	}
`

application.yml： 
#swagger 配置上线改为false
swagger.enable: false

在关掉swagger时spring 就不会实例化swagger 相关的bean 
swagger-bootstrap-ui 无法注入swagger依赖所以报错
（使用springfox-swagger-ui不会报错）

**Comment by xiaoymin** [comment]
升升级吧，springfox2.6.1 还是4年前的版本，虽然目前最新版2.9.2 也有一段时间了，但是比2.6.1 还是要早一些的

`swagger-bootstrap-ui `更名为`knife4j`后也发布了3版了，基于springfox-swagger的2.9.2版本

文档：https://doc.xiaominfo.com/knife4j/springboot.html


最后，根据你发的版本号,我复测没有出现，代码示例：[https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/master/knife4j-lower-spring-boot-demo](https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/master/knife4j-lower-spring-boot-demo)

**Comment by 011011100010110101101111** [comment]
奇怪了，我是 springfox-swagger 2.9.2  spring-bootstrap-ui 1.9.5 , 跟他这个一模一样的问题。

**Comment by MaphicalYng** [comment]
我也遇到了这个问题，解决方法是：在配置类加个注解：

```java
import springfox.documentation.swagger2.annotations.EnableSwagger2WebMvc;
@EnableSwagger2WebMvc
```
