### ISSUE TITLE
axios的get请求无法设置Content-Type

### ISSUE THREAD

**Issue by marvinpan8** [xiaoymin/knife4j#179]
请修复此BUG， 参考https://www.cnblogs.com/gxsyj/p/10697593.html

**Comment by xiaoymin** [comment]
你的使用场景是什么，相关代码贴出来

**Comment by xiaoymin** [comment]
2.0.3已改

试试吧
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html
