### ISSUE TITLE
FireFox打开是白板一片

### ISSUE THREAD

**Issue by icafe** [xiaoymin/knife4j#18]
RT~

FireFox 版本：61.0.2 (64 位)
<img width="692" alt="bug" src="https://user-images.githubusercontent.com/1488836/44468598-269daa80-a658-11e8-97f7-495e0798e940.png">

**Comment by xiaoymin** [comment]
firefox确实没考虑兼容，目前都是在chrome上开发的

**Comment by xiaoymin** [comment]
下个版本会解决这个问题

**Comment by xiaoymin** [comment]
1.8.2已解决此问题，欢迎升级反馈，谢谢

**Comment by derekzhan** [comment]
为什么我的chrome打开也是一片空白呢，我查看web控制台也没有任何错误提示。
