### ISSUE TITLE
返回类型对象中如果存在map时的bug

### ISSUE THREAD

**Issue by dingqianwen** [xiaoymin/knife4j#180]
如果返回类型使用map，key：33，value：对象，例如：
```java
class Temp {
   private String name;
   private Map<Long, Object> condition = new HashMap<>();
}
```

则会出现以下情况，key会出现多余的一对""，不是正确的json格式，如下：
```json
"condition": {
          ""33"": {
            "value": 33,
            .....
          }
}
```
这个问题在swagger2中是不存在的，希望修复

**Comment by xiaoymin** [comment]
2.0 已经修复了

变更日志：https://www.oschina.net/news/112095/knife4j-2-0-released

**Comment by dingqianwen** [comment]
> 2.0已经修复了
> 
> 变更日志：[https](https://www.oschina.net/news/112095/knife4j-2-0-released) ://www.oschina.net/news/112095/knife4j-2-0-released[](https://www.oschina.net/news/112095/knife4j-2-0-released)

好的，我们开始升级版本

**Comment by dingqianwen** [comment]
> 2.0 已经修复了
> 
> 变更日志：https://www.oschina.net/news/112095/knife4j-2-0-released

多谢你的建议，我们已经完美解决，但是我们认为2.0以后版本没有之前的更好用

**Comment by xiaoymin** [comment]
> > 2.0 已经修复了
> > 变更日志：https://www.oschina.net/news/112095/knife4j-2-0-released
> 
> 多谢你的建议，我们已经完美解决，但是我们认为2.0以后版本没有之前的更好用

哈哈，其实我倒是很奇怪啊，之前的版本都是没有一个整体风格的，这个是基于后端js和前端antd的风格统一的，如果是界面的话，可能每个人的体验不一样吧

功能上有意见的话欢迎提上来，界面上的话，如果有兴趣也欢迎专业的前端来进行优化(毕竟我是后端，只能做到如此啦~~)

**Comment by DingQianWen** [comment]
已解决
