### ISSUE TITLE
接口在postman中返回数据正常，在swagger中请求后，数据未返回

### ISSUE THREAD

**Issue by HackenPai** [xiaoymin/knife4j#182]
在knife4j 2.0.1 版本下，接口在post返回数据正常，在swagger中请求后，数据未返回，接口结果未渲染显示：
![image](https://user-images.githubusercontent.com/8666099/71444500-abb53a00-274c-11ea-9e7e-b51e38fa034e.png)
![image](https://user-images.githubusercontent.com/8666099/71444576-50d01280-274d-11ea-894a-735dba7afd6a.png)

**Comment by CodingOX** [comment]
我的也是结果没有渲染！

**Comment by panlw** [comment]
GET 也是同样现象，除了下面的JS报错以外，没看到其他错误，在 Chome Console 的 Network Tab 中Response 是有数据的，但是应用没更新UI，似乎是Tab多开几个就会这个问题。

![image](https://user-images.githubusercontent.com/60350/73631549-45e59780-4694-11ea-85a8-258063342458.png)

补充一点：上面的JS错误是一开始就有的，不是 GET 请求时才有，所以觉得应该不是这个问题。

**Comment by xiaoymin** [comment]
这个应该是切换tab导致的

**Comment by xiaoymin** [comment]
试试2.0.2吧
