### ISSUE TITLE
Spring Cloud微服务架构，子服务的配置Docket对象，不能指定groupName

### ISSUE THREAD

**Issue by ghost** [xiaoymin/knife4j#184]
@Bean("StaffApis")
    public Docket staffApis() {
        return new Docket(DocumentationType.SWAGGER_2)
                .groupName("员工模块")
                .select()
                .apis(RequestHandlerSelectors.withClassAnnotation(Api.class))
                .paths(PathSelectors.regex("/staff.*"))
                .build()
                .apiInfo(groupApiInfo())
                .enable(enable);
    }

.groupName("员工模块") 指定后 http://ip:port/v2/api-docs 路径后会带参数

http://ip:port/v2/api-docs?group=%E5%91%98%E5%B7%A5%E6%A8%A1%E5%9D%97

这个能兼容吗？

**Comment by xiaoymin** [comment]
这个不是ui来兼容的吧？
