### ISSUE TITLE
不影响使用，只是弹窗很多这样的提示Generating unique operation named,不舒服，有优化方案嘛

### ISSUE THREAD

**Issue by xuzongmeng** [xiaoymin/knife4j#186]
Generating unique operation named: deleteUsingPOST_10
Generating unique operation named: updateUsingPOST_10
Generating unique operation named: listUsingGET_10
Generating unique operation named: infoUsingGET_10
Generating unique operation named: addUsingPOST_10

**Comment by xiaoymin** [comment]
版本、截图

**Comment by xuzongmeng** [comment]
版本：1.9.6，其它我回退之前的版本也
有这样的提示。![image](https://user-images.githubusercontent.com/16155051/71567423-e24ad600-2af9-11ea-961d-c65f7efa11e0.png)

**Comment by xiaoymin** [comment]
这个是springfox的日志，你自己日志级别 限制一下就ok了啊

**Comment by xuzongmeng** [comment]
好的  谢谢了
