### ISSUE TITLE
建议调试返回结果增加table显示

### ISSUE THREAD

**Issue by viokuma** [xiaoymin/knife4j#188]
指定返回结果中一个对象数组字段，生成table显示，可以很方便的进行调试。
建议加入这个功能。

另外传参字段也可以考虑可视化

**Comment by xiaoymin** [comment]
你们现在的需求是怎样的，一般返回都会有封装的（一些公共字段之类的），这个table很难做

如果返回的接口是纯json数组，做个table显示倒是可以

**Comment by viokuma** [comment]
![image](https://user-images.githubusercontent.com/1708895/71883415-609a1e80-3171-11ea-9128-5e5fd0b75f85.png)

我们返回的是json，并且很多是这样的分页结构，其中有一个items数组对象包装的具体业务记录。
我的建议是增加table显示选项，然后页面有一个参数填入"items"，就把"items"数组显示成table。
我觉得做后台大部分人都是这样的返回结构，就是对象数组名字不一样罢了

**Comment by xiaoymin** [comment]
是在接口已经返回后 新增一个tab？ 在界面输入类似jsonpath的路径显示table 还是 在发送后直接处理 直接界面显示table？

**Comment by viokuma** [comment]
![image](https://user-images.githubusercontent.com/1708895/71884789-efa83600-3173-11ea-92f5-c0dfdcbaeb06.png)
我的建议是在请求前就可以设置table显示的json路径，然后可以用cookies保存设置，下次调用就方便

![image](https://user-images.githubusercontent.com/1708895/71884347-1fa30980-3173-11ea-835d-8618f02c7621.png)
然后返回时也可以切换table、json等
