### ISSUE TITLE
用knife4j-front集成出来的效果不是2.0最新效果

### ISSUE THREAD

**Issue by jianning0925** [xiaoymin/knife4j#189]
直接用maven依赖knife4j出来的跟集成静态swagger方式出来的效果不一样

**Comment by jianning0925** [comment]
用这个好像可以knife4j-spring-ui

**Comment by xiaoymin** [comment]
front版本是原来的 没改，其实前后端分离版本可以用knife4j-vue 那个里面的

下载后 安装依赖npm install

然后可以直接运行的，改一下代理的地址

**Comment by xiaoymin** [comment]
knife4j-spring-ui是java开发者直接jar包引用的 ，配合springfox
