### ISSUE TITLE
`knife4j-spring-boot-starter`中`swagger-annotation`有依赖冲突

### ISSUE THREAD

**Issue by panlw** [xiaoymin/knife4j#191]
![image](https://user-images.githubusercontent.com/60350/73623772-30af3f80-4679-11ea-950f-03b6929ded38.png)

```xml
    <dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-spring-boot-starter</artifactId>
      <version>2.0.1</version>
    </dependency>
```

`swagger-annotation` 的依赖版本有两个，建议把 1.5.20 那个依赖从`springfox-swagger2`中给`exclusion`掉 :-)

**Comment by xiaoymin** [comment]
感谢反馈

**Comment by xiaoymin** [comment]
2.0.2已解决
