### ISSUE TITLE
field名称不能为空,导致非空异常

### ISSUE THREAD

**Issue by jtxf1** [xiaoymin/knife4j#193]
knife4j-spring-boot-starter 版本1.9.6,
项目启动一直报错不影响使用:c.g.x.knife4j.spring.util.ByteUtils - null.
源码提示//field名称不能为空,导致非空异常
                // https://gitee.com/xiaoym/swagger-bootstrap-ui/issues/IYLVC
但是网址已经打不开了

**Comment by xiaoymin** [comment]
这个错我在那个issue回复了吧？
还是说现在还有？

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/IYLVC
