### ISSUE TITLE
api接口 json接受数据类型   属性串起来了在同一个controller不同的接口中

### ISSUE THREAD

**Issue by luoluo001** [xiaoymin/knife4j#194]
![image](https://user-images.githubusercontent.com/24263006/74813231-ffe53080-532f-11ea-9afd-e0f84063afc2.png)
请求接收APi及参数：
![image](https://user-images.githubusercontent.com/24263006/74813302-260ad080-5330-11ea-87ab-acf98b411157.png)

以下是doc.html的示例：
![image](https://user-images.githubusercontent.com/24263006/74813783-d5e03e00-5330-11ea-91f0-56eccd972d74.png)

`
{
	"asks": [
		{
			"clarifyRounds": 0,
			"clarifyWords": "",
			"effectRounds": 0,
			"failReply": "",
			"toReply": "",
			"varId": 0
		}
	],
	"content": "",
	"flowId": 0,
	"groups": [
		{
			"conditions": [
				{
					"condition": "",
					"id": 0,
					"value": "",
					"varId": 0
				}
			],
			"flowId": 0,
			"id": 0,
			"name": "",
			"positionX": 0,
			"positionY": 0,
			"type": ""
		}
	],
	"id": 0,
	"inputVars": [
		{
			"callEmpty": 0,
			"dynamic": 0,
			"value": "",
			"varId": 0
		}
	],
	"name": "",
	"outputVars": [
		{
			"dataType": "",
			"varId": 0
		}
	],
	"positionX": 0,
	"positionY": 0,
	"renderStyle": "",
	"reqHeaders": "",
	"reqMethod": "",
	"reqUrl": "",
	"style": "",
	"styleType": "",
	"type": ""
}
`

ReqAddNode 类结构：
`

@ApiModel("节点基础信息")
public class ReqAddNode implements Serializable{
    
    private static final long serialVersionUID = -4698892999275200399L;

    @ApiModelProperty(value = "流程id", required = false)
    private Long flowId;

    @ApiModelProperty(value = "节点名称", required = true)
    private String name;

    @ApiModelProperty(value = "节点类型", required = true)
    private String type;
    
    @ApiModelProperty(value = "节点横坐标", required = true)
    private Integer positionX;
    
    @ApiModelProperty(value = "节点纵坐标", required = true)
    private Integer positionY;

    public Long getFlowId() {
        return flowId;
    }

    public void setFlowId(Long flowId) {
        this.flowId = flowId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getPositionX() {
        return positionX;
    }

    public void setPositionX(Integer positionX) {
        this.positionX = positionX;
    }

    public Integer getPositionY() {
        return positionY;
    }

    public void setPositionY(Integer positionY) {
        this.positionY = positionY;
    }

    
}

`

ReqAddQueryNode ：类结构
`
    public class ReqAddQueryNode extends ReqAddNode {

    private static final long serialVersionUID = -4781152183644472595L;
    
    /** 请求地址 */
    @ApiModelProperty(value = "请求地址",required = true)
    private String reqUrl ;
    
    /** 请求方式 */
    @ApiModelProperty(value = "请求方式",required = true)
    private String reqMethod ;
    
    /** 请求head */
    @ApiModelProperty(value = "请求head",required = true)
    private String reqHeaders ;
    
    /** 输出样式 */
    @ApiModelProperty(value = "输出样式",required = true)
    private String renderStyle ;
    
    @ApiModelProperty(value = "入参列表",required = true)
    private List<ReqAddQueryInputVar> inputVars;
    
    @ApiModelProperty(value = "出参列表",required = false)
    private List<ReqAddQueryOutputVar> outputVars;
    
    public String getReqUrl() {
        return reqUrl;
    }

    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl;
    }

    public String getReqMethod() {
        return reqMethod;
    }

    public void setReqMethod(String reqMethod) {
        this.reqMethod = reqMethod;
    }

    public String getReqHeaders() {
        return reqHeaders;
    }

    public void setReqHeaders(String reqHeaders) {
        this.reqHeaders = reqHeaders;
    }

    public String getRenderStyle() {
        return renderStyle;
    }

    public void setRenderStyle(String renderStyle) {
        this.renderStyle = renderStyle;
    }

    public List<ReqAddQueryInputVar> getInputVars() {
        return inputVars;
    }

    public void setInputVars(List<ReqAddQueryInputVar> inputVars) {
        this.inputVars = inputVars;
    }

    public List<ReqAddQueryOutputVar> getOutputVars() {
        return outputVars;
    }

    public void setOutputVars(List<ReqAddQueryOutputVar> outputVars) {
        this.outputVars = outputVars;
    }
    
}

`

其中许多字段都是从其他几个子类获取到的属性到示例中了。比如asks（不限于）是ReqAddDialogueNode的属性，在查询的这个接受参数类中压根没有这个属性，这个示例更像是所有属性的集合。  大神有时间看下哈

补充下： 我数据弄成form的示例显示就正常了

![image](https://user-images.githubusercontent.com/24263006/74816038-4c7f3a80-5335-11ea-96f2-288697fcc596.png)

**Comment by luoluo001** [comment]
补充下 maven的swagger相关依赖。

```
<dependency>
		    <groupId>io.springfox</groupId>
		    <artifactId>springfox-swagger2</artifactId>
		    <version>2.9.2</version>
		</dependency>
                <dependency>
		    <groupId>com.github.xiaoymin</groupId>
		    <artifactId>swagger-bootstrap-ui</artifactId>
		    <version>1.8.7</version>
		</dependency>

               <dependency>           
		    <groupId>io.swagger</groupId>            
		    <artifactId>swagger-annotations</artifactId>           
		    <version>1.5.21</version>       
		</dependency>        
		<dependency>            
		    <groupId>io.swagger</groupId>            
		    <artifactId>swagger-models</artifactId>            
		    <version>1.5.21</version>        
		</dependency>
```

**Comment by xiaoymin** [comment]
从你列的这些来看 看不出来问题，`ReqAddDialogueNode`类结构是怎么样的 你没贴

如果出现了不同的属性，可能和你再类上使用`@ApiModel`注解有关系，如下：
```java
@ApiModel("节点基础信息")
public class ReqAddNode implements Serializable{
```

```java
@ApiModel("节点基础信息")
public class ReqAddDialogueNodeimplements Serializable{
```


不同的类给与`@ApiModel`注解的value值是一样的，这样就导致了接口引用了错误的类属性

**Comment by xiaoymin** [comment]
GitHub我看的比较少，以后有问题建议去gitee里面提

地址：https://gitee.com/xiaoym/knife4j

或者加群，直接沟通
