### ISSUE TITLE
多项目聚合，调试请求的地址不能附带host吗

### ISSUE THREAD

**Issue by ymybxx** [xiaoymin/knife4j#195]
不想使用微服务的方式，本来每个服务都是有域名可以访问的
我创建一个服务吧这些swagger文档聚合后，调试界面发送请求host仍然是当前服务，我想附带子服务的host，只能改源码吗？

**Comment by archine** [comment]
同求该问题的答案

**Comment by Xpenf** [comment]
同上！

**Comment by xiaoymin** [comment]
多项目聚合可以单独弄一个服务项目，作为解决这个文档聚合的解决方案

**Comment by xiaoymin** [comment]
用用knife4j-admin 吧，不用在代码层网关聚合文档，独立中间件，任意聚合Swagger文档

https://www.oschina.net/news/115814/knife4j-admin-1-0-released
