### ISSUE TITLE
[2.0.1]当打开多个接口调试时，响应内容 会显示在不对应的接口标签页问题

### ISSUE THREAD

**Issue by loadingspace** [xiaoymin/knife4j#196]
问题描述：
当打开多个接口调试时，响应内容 会显示在不对应的接口标签页问题

复现方式：
1. 打开A接口进入【调试】标签页，点击【发送】按钮，返回结果会显示在A页面的【响应内容】中
2. A接口标签页【不关闭】，打开B接口进入【调试】标签页，点击【发送】按钮，返回结果会显示B页面的【响应内容】中
3.在进入到A接口【调试】标签页，点击【发送】按钮，返回结果会显示在B页面的【响应内容】中

复现概率：
必现

集成环境：springboot 2.2.4.RELEASE
knife4j版本：2.0.1
浏览器：Chrome 80.0.3987.106

 备注：可能和#187问题相同

**Comment by xiaoymin** [comment]
应该是同一个问题导致的

**Comment by xiaoymin** [comment]
2.0.2试试
