### ISSUE TITLE
是否可以支持definitions中各个model的example属性"请求示例"的展示

### ISSUE THREAD

**Issue by morningcx** [xiaoymin/knife4j#197]
目前好像只会对model中存在example属性的properties进行请求示例的展示，对于model的example属性请求示例一直会显示null。springfox-swagger-ui中我试了一下是支持的。

**Comment by xiaoymin** [comment]
贴个图？

**Comment by morningcx** [comment]
![image](https://user-images.githubusercontent.com/35294458/75674930-1345b380-5cc1-11ea-8572-9b1f9108cc64.png)
![image](https://user-images.githubusercontent.com/35294458/75674994-35d7cc80-5cc1-11ea-970c-14c02213070f.png)
这个definitions里面的test-controller-test0是我通过swagger自定义的插件接口添加到上下文里面的，对应的类为springfox.documentation.schema.Model，里面的example属性就对应这个类里面example实例域，springfox-swagger-ui中是支持model对象中example value的展示的：
![image](https://user-images.githubusercontent.com/35294458/75676129-97993600-5cc3-11ea-9cc9-b8f5cc687192.png)

**Comment by xiaoymin** [comment]
JAVA代码能贴一下吗

**Comment by xiaoymin** [comment]
或者可以试试最新版本knife4j-2.0.1的

看看有没有问题

**Comment by morningcx** [comment]
![image](https://user-images.githubusercontent.com/35294458/75677484-86055d80-5cc6-11ea-8307-d2c2e989b02a.png)
主要是针对RequestBody为Map类型的情况下做了一下增强，虽然使用的方法可能有点不太优雅- -，根据接口上面注解的内容生成example里面的内容，然后映射到对应参数的ModelRef中。
parseModels方法相应逻辑也就是为了生成一个新的model加到上下文里面（这里example我写死了）：
![image](https://user-images.githubusercontent.com/35294458/75678071-bef20200-5cc7-11ea-923a-1cb2c922e4db.png)
最新版knife4j-2.0.1示例也是null

**Comment by xiaoymin** [comment]
看看这个 https://doc.xiaominfo.com/guide/dynamic-parameter.html

**Comment by morningcx** [comment]
哈哈，大佬看来都已经想到了，其实我也基于注解也写了一套很垃圾的，但是这种方法如果请求的json层级比较深，结构比较复杂的话也还是要写在DynamicParameter的example里面，所以我的想法就是直接在model的example里面填充json字符串丢给前端。不过在model中给example赋值的情况也少见，好像也只有注册插件的方式注入了。

**Comment by morningcx** [comment]
虽然感觉不那么必要，但还是希望大佬能支持一哈，感谢
