### ISSUE TITLE
@ApiOperationSupport(ignoreParameters = {"billBuyOpertionVO.id","billBuyOpertionVO.billBuyIds","id"}) 无法进行请求参数忽略

### ISSUE THREAD

**Issue by jiangrulei** [xiaoymin/knife4j#199]
<dependency>
				<groupId>com.github.xiaoymin</groupId>
				<artifactId>knife4j-spring-boot-starter</artifactId>
				<version>2.0.1</version>
			</dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger-ui</artifactId>
				<version>2.9.2</version>
			</dependency>
			<dependency>
               <groupId>io.swagger</groupId>
               <artifactId>swagger-annotations</artifactId>
               <version>1.5.22</version>
           </dependency>
           <dependency>
               <groupId>io.swagger</groupId>
               <artifactId>swagger-models</artifactId>
               <version>1.5.22</version>
           </dependency>

你好，这是我的pon 引入文件
@EnableWebMvc
@Configuration
@EnableSwagger2
@EnableKnife4j
@Import(BeanValidatorPluginsConfiguration.class) 
这是我的配置类注解
@ApiOperationSupport(ignoreParameters = {"billBuyOpertionVO.id","billBuyOpertionVO.billBuyIds","id"})
boolean insertBillBuy(@RequestBody @Valid BillBuyOpertionVO billBuyOpertionVO);
这是我的方法注解
这些配置完成以后，在页面参数，没有成功忽略请求参数

**Comment by xiaoymin** [comment]
升级到2.0.2

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/swagger-bootstrap-ui/releases/tag/2.0.2

**Comment by adougebabi** [comment]
我试过用2.0.2 网页上的示例，依然是没办法忽略的

**Comment by xiaoymin** [comment]
> 我试过用2.0.2 网页上的示例，依然是没办法忽略的

那个？

**Comment by adougebabi** [comment]
> > 我试过用2.0.2网页上的示例，依然是没办法忽略的
> 
> 那个？

@ApiOperation(value = "新增Model接口")
@ApiOperationSupport(ignoreParameters = {"uptModel.id","uptModel.name","uptModel.orderDate.id"})
@PostMapping("/insertModel")
public Rest<UptModel> insertModel(@RequestBody UptModel uptModel){
    Rest<UptModel> r =new Rest<>();
    r.setData(uptModel);
    return r;
}
这个

**Comment by xiaoymin** [comment]
这个是最新的https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/master/knife4j-spring-boot-demo，
你列的这个pom.xml是2.0.2？

**Comment by xiaoymin** [comment]
![image](https://user-images.githubusercontent.com/7894406/76697149-3f543200-66ce-11ea-82e0-c86ab8d75b63.png)

线上的demo示例是ok的，版本2.0.2，不知道你测的是那个

接口地址：http://knife4j.xiaominfo.com/doc.html#/%E5%88%86%E7%BB%84%E6%8E%A5%E5%8F%A3/1.9.5%E7%89%88%E6%9C%AC-20190728/insertModelUsingPOST

代码：
```java
@ApiOperation(value = "新增Model接口")
    @ApiOperationSupport(ignoreParameters = {"uptModel.id","uptModel.name","uptModel.orderDate.id"})
    @PostMapping("/insertModel")
    public Rest<UptModel> insertModel(@RequestBody UptModel uptModel){
        Rest<UptModel> r =new Rest<>();
        r.setData(uptModel);
        return r;
    }

```

在文档中id、name、orderDate.id都没有出现

**Comment by xiaoymin** [comment]
@a646911949

**Comment by xiaoymin** [comment]
试试2.0.3吧
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html
