### ISSUE TITLE
关于对象参数层级展示问题

### ISSUE THREAD

**Issue by rbfw** [xiaoymin/knife4j#2]
swagger-ui.html是这样的
{
  "token": "string",
  "userInfo": {
    "email": "string",
    "emailBinding": "string",
    "encryMode": "string",
    "faviconFileId": "string",
    "id": 0,
    "identityFileId": "string",
    "identityNum": "string",
    "identityType": "string",
    "isDeleted": "string",
    "mobile": "string",
    "mobileBinding": "string",
    "nickname": "string",
    "oldId": 0,
    "oldusername": "string",
    "orgCode": "string",
    "orgCodes": "string",
    "orgId": 0,
    "orgIds": "string",
    "orgName": "string",
    "password": "string",
    "salt": "string",
    "sex": "string",
    "sysCode": "string",
    "tel": "string",
    "trueName": "string",
    "trueNameEn": "string",
    "username": "string",
    "verifyStatus": "string"
  }
}
Swagger-Bootstrap-UI是这样的：
{
    "token":"",
    "userInfo":""//这是一个对象，里面的属性就出不来了
}

**Comment by xiaoymin** [comment]
可以提供下完整的json么

**Comment by daijiejay** [comment]
页面效果确实好看了很多，快接近开发人员不需要写接口文档了，但还有一些不足，我也表达一下意见：
1、请求参数中和返回参数中的内部对象属性不能展示，应该就是楼上说的意思；
2、model里的属性没有读取到required是否必须传的注释；
3、model里的枚举属性没有展示出来；
4、文件上传不能在线调试；
5、controller的类名注释description不能展示。
不知道楼主现在还没有在维护，什么时候发布新版本，想知道下一个版本带来什么样的惊喜，非常感谢！

**Comment by xiaoymin** [comment]
font{
        line-height: 1.7;
    }


    
 非常感谢你的建议,后面会考虑进去，近期由于工作任务比较繁重，所以没有这么多精力来优化这个,可能要到中旬、月底才有时间



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }
        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年11月3日 12:21，daijiejay<notifications@github.com> 写道： 


页面效果确实好看了很多，快接近开发人员不需要写接口文档了，但还有一些不足，我也表达一下意见：
1、请求参数中和返回参数中的内部对象属性不能展示，应该就是楼上说的意思；
2、model里的属性没有读取到required是否必须传的注释；
3、model里的枚举属性没有展示出来；
4、文件上传不能在线调试；
5、controller的类名注释description不能展示。
不知道楼主现在还没有在维护，什么时候发布新版本，想知道下一个版本带来什么样的惊喜，非常感谢！
