### ISSUE TITLE
接口文档路径多出了：/v2/api-docs

### ISSUE THREAD

**Issue by chriszh123** [xiaoymin/knife4j#200]
用ip:port形式访问服务器文档地址时，生成的接口文档里接口地址多出了分组的：
访问：http://***.**.**.**:8085//wec-counselor-collector-apps/doc.html
生成的接口路径为：/wec-counselor-collector-apps/v2/api-docs/stu/collector/detailCollector
其中 /v2/api-docs 是多出来的
请问下：这个有可能是哪里配置有问题了呢。
好像是默认加上了分组location的值，
如果访问：http://localhost:8085//wec-counselor-collector-apps/doc.html 
生成的接口路径没有问题，路径为：
/wec-counselor-collector-apps/stu/collector/detailCollector
谢谢

**Comment by xiaoymin** [comment]
版本、图？

**Comment by chriszh123** [comment]
依赖：
<dependency>
			<groupId>com.github.xiaoymin</groupId>
			<artifactId>knife4j-spring-ui</artifactId>
			<version>2.0.0</version>
		</dependency>
![image](https://user-images.githubusercontent.com/27117409/76394773-fb50ec80-63b0-11ea-9290-7b6848717a92.png)
![image](https://user-images.githubusercontent.com/27117409/76394805-073cae80-63b1-11ea-9b3a-fc2c2fd4d434.png)

**Comment by xiaoymin** [comment]
和这个分组Location没什么关系，你的basePath最后里面包含/v2/api-docs

另外，建议升级版本到2.0.2 修复了很多bug

**Comment by chriszh123** [comment]
好的，我升级下。
这个basePath路径是怎么配置的呢？在哪配置的

**Comment by xiaoymin** [comment]
springboot项目里面的application.yml
```yml
server:
 servlet:
    context-path: xxxx
```

如果你什么都没干，这个就是默认的根目录

**Comment by chriszh123** [comment]
我这边环境是本地的Spring mvc，暂时没有用到springboot，本地idea开发环境跑起来的：
http://localhost:8085/wec-counselor-collector-apps/
还需要做什么配置么

**Comment by xiaoymin** [comment]
1、Tomcat是可以设置basePath的
2、创建Docket对象的时候

如果都没有，那就没有其他地方了

**Comment by chriszh123** [comment]
嗯嗯，想问下，用localhost访问用直接用ip访问，在这里有区别么？为什么localhost访问是没问题的呢？

**Comment by xiaoymin** [comment]
没区别
