### ISSUE TITLE
openapi v3 support

### ISSUE THREAD

**Issue by xiaoxiangmoe** [xiaoymin/knife4j#203]
需要 swagger 3 的支持

**Comment by xiaoymin** [comment]
v3的支持，你们现在用的解析框架是springfox还是springdoc-openapi?

**Comment by xiaoxiangmoe** [comment]
我们现在改用 springdoc-openapi 了，因为 springfox 不支持

**Comment by xiaoymin** [comment]
springdoc-openapi我已经开始集成了，需要一些时间

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html
