### ISSUE TITLE
Gateway 配置了Filter 但是没有携带basePath  basePath 空

### ISSUE THREAD

**Issue by JoeCoding-cn** [xiaoymin/knife4j#204]
![image](https://user-images.githubusercontent.com/61448379/77027811-2c917400-69d2-11ea-9abb-e30c023bc2b0.png)
![image](https://user-images.githubusercontent.com/61448379/77027904-5fd40300-69d2-11ea-820d-6bd062f7481d.png)

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/swagger-bootstrap-ui/issues/202

**Comment by xiaoymin** [comment]
用用knife4j-admin 吧，不用在代码层网关聚合文档，独立中间件，任意聚合Swagger文档

https://www.oschina.net/news/115814/knife4j-admin-1-0-released
