### ISSUE TITLE
@ApiOperationSupport接口排序未生效

### ISSUE THREAD

**Issue by TaylorWu** [xiaoymin/knife4j#205]
用spring-boot-single-demo项目中Api196Controller，修改longUserRest的order为2，longUserRest1方法的order为1，但是页面上longUserRest依旧在longUserRest1上面

**Comment by xiaoymin** [comment]
确保使用的最新版本，当前最新版本2.0.2

**Comment by TaylorWu** [comment]
使用最新版本2.0.2，SwaggerConfiguration改为新的注解@EnableKnife4j，排序未生效，还是按字母顺序排序。

**Comment by DerekHQ** [comment]
我使用 2.0.2 / 2.0.3 排序也均未生效

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/knife4j/autoEnableKnife4j.html

**Comment by DerekHQ** [comment]
> https://doc.xiaominfo.com/knife4j/autoEnableKnife4j.html

嗯嗯。刚搜到这个说明！感谢作者！Good Job!

**Comment by Kevintian77585** [comment]
springfox-swagger2使用2.9.2版本，swagger-bootstrap-ui使用最新的1.9.6版本，SpringBoot是2.2.10版本，注解ApiOperationSupport中的order属性还是没有生效，求个统一的解决方案
