### ISSUE TITLE
workbox问题

### ISSUE THREAD

**Issue by skyrunwith** [xiaoymin/knife4j#206]
更新为2.0.2版本后，解决service-work.js 404问题，但又增加了新的问题，问题如下：这三个文件报404，目前不知道用处是什么
![image](https://user-images.githubusercontent.com/16412980/77718022-ced9d900-701c-11ea-8ca1-97b60e98db1d.png)

**Comment by m1ngyuan** [comment]
@skyrunwith me too

**Comment by xiaoymin** [comment]
这个是我Vue打包的问题导致的，目前来说应该是不影响使用的

后面会改进这个 问题

**Comment by m1ngyuan** [comment]
@xiaoymin 会导致页面打开是空白的，无法使用。

**Comment by xiaoymin** [comment]
@m1ngyuan 空白是其他原因导致的吧，

线上的版本就是2.0.2的 http://knife4j.xiaominfo.com/doc.html

没什么问题呢

**Comment by skyrunwith** [comment]
@xiaoymin 是滴，不影响正常使用，但是不懂前端的看到头大

**Comment by xiaoymin** [comment]
> @xiaoymin 是滴，不影响正常使用，但是不懂前端的看到头大

下个版本快了，等一等吧：）

**Comment by m1ngyuan** [comment]
@xiaoymin https://api.inkongjian.com/doc.html#/admin/api/admin-tag-controller/addTagUsingPOST

**Comment by xiaoymin** [comment]
@m1ngyuan 请参考这个：https://gitee.com/xiaoym/knife4j/issues/I19G42

**Comment by m1ngyuan** [comment]
@xiaoymin 谢谢，我们试试

**Comment by xiaoymin** [comment]
试试2.0.3吧
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html

**Comment by m1ngyuan** [comment]
@xiaoymin 好像问题仍然存在。
