### ISSUE TITLE
提一个小建议

### ISSUE THREAD

**Issue by wulife** [xiaoymin/knife4j#21]
这边的这个响应内容复制的时候会把那个折叠的符号一起复制，个人建议可以把那个折叠符号往前移一点，这样就不会和数据一起被复制了
![6e5 r m2a 57 s0p8zj8e1](https://user-images.githubusercontent.com/26455549/45076746-d0cc0680-b11d-11e8-93da-3045420da72f.png)

**Comment by xiaoymin** [comment]
可以的
