### ISSUE TITLE
我要修改前端的一些显示，怎么构建编译您的项目 swagger-bootstrap-ui1.9.6

### ISSUE THREAD

**Issue by heykb** [xiaoymin/knife4j#211]

**Comment by xiaoymin** [comment]
1.x系列是纯JS+HTML 你自己直接改就可以

2.X 看这篇文档https://doc.xiaominfo.com/knife4j/knife4j-front-source-modified.html

![image](https://user-images.githubusercontent.com/7894406/78967609-88fd3480-7b35-11ea-8689-beec5cfb00a5.png)
