### ISSUE TITLE
页面basePath出现多个path

### ISSUE THREAD

**Issue by whuaz** [xiaoymin/knife4j#212]
spring cloud gateway集成knife4j
版本<knife4j.version>2.0.2</knife4j.version>
![Snipaste_2020-04-10_13-02-07](https://user-images.githubusercontent.com/32691494/78963923-84338300-7b2b-11ea-9f07-a2f537880359.png)

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/swagger-bootstrap-ui/issues/202

**Comment by whuaz** [comment]
已解决
