### ISSUE TITLE
默认提交空值为null

### ISSUE THREAD

**Issue by liji2003888** [xiaoymin/knife4j#213]
在UI界面默认选中所有参数，当没有设置值即空值时提交null,，版本使用的2.0.2

**Comment by xiaoymin** [comment]
这个应该是2.0.2版本的GET请求才会出现

感谢反馈，下个版本会修复它

**Comment by liji2003888** [comment]
> 这个应该是2.0.2版本的GET请求才会出现
> 
> 感谢反馈，下个版本会修复它

好的，3Q

**Comment by xiaoymin** [comment]
试试2.0.3吧
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html

**Comment by liji2003888** [comment]
好嘞，万分感谢~~
