### ISSUE TITLE
不该读取public方法的局部变量为参数

### ISSUE THREAD

**Issue by kamjin3086** [xiaoymin/knife4j#214]
请求方式为GET，入参为一个实体类（非json），实体类中有public方法，该方法中的局部变量，理应不被解析的，但也被解析到knife4j的展示页面上了，在方法注解了 @ApiModelProperty(hidden = true)也不行。

**Comment by xiaoymin** [comment]
解析的事情是springfox来做的，要忽略该接口用@ApiIgnore

**Comment by kamjin3086** [comment]
准确来说，请求实体中如果有get开头的public方法，并且get返回是另一个实体类时，此时该实体类的入参会将该getxxx方法返回的实体参数也一并加入进来，，在knife4j的调试及文档页面上展示
看来入参实体中的其他方法除基本getset外，都不能以get/set开头

**Comment by xiaoymin** [comment]
这个问题你可以去springfox里面提提
