### ISSUE TITLE
knife4j-spring-ui-2.0.2.jar!\META-INF\resources\favicon.ico 请问这个图标怎么覆盖？

### ISSUE THREAD

**Issue by geekyouth** [xiaoymin/knife4j#215]
springboot resources 下面放置的 favicon.ico 图标不生效
我的项目需要使用自定义图标。
![image](https://user-images.githubusercontent.com/12899262/79313947-ab2af400-7f33-11ea-9ccc-e9aab05cc554.png)

**Comment by xiaoymin** [comment]
下个版本会剔除该图标，以避免和主项目产生冲突

**Comment by xiaoymin** [comment]
试试2.0.3吧
https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html

**Comment by xiaoymin** [comment]
已经剔除该文件
