### ISSUE TITLE
spring serurity 咋个集成 

### ISSUE THREAD

**Issue by 17623252837** [xiaoymin/knife4j#217]
。。。集成不了

**Comment by xiaoymin** [comment]
![image](https://user-images.githubusercontent.com/7894406/81808540-6efaab80-9552-11ea-86ac-a68e2b9fe9fb.png)
https://doc.xiaominfo.com/guide/accessControl.html#%E5%BC%80%E5%90%AF%E7%94%9F%E4%BA%A7%E7%8E%AF%E5%A2%83-%E5%B1%8F%E8%94%BDswagger%E6%89%80%E6%9C%89%E8%B5%84%E6%BA%90%E6%8E%A5%E5%8F%A3

Security无法是要放开权限接口，供参考
