### ISSUE TITLE
接口访问返回是null的情况下不会刷新响应内容区

### ISSUE THREAD

**Issue by LisDocument** [xiaoymin/knife4j#219]
当前问题情景：我访问了一个接口报错，响应内容区正常打印了错误返回的内容，然后在我修改代码后，同接口返回的是null的情况，响应内容区依旧是之前显示的错误返回的内容，没有刷新，F12查看接口返回的的确是正常的null

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/IZUCU
