### ISSUE TITLE
Knife4j 提ISSUES必看 [置顶]

### ISSUE THREAD

**Issue by xiaoymin** [xiaoymin/knife4j#220]
虽然建立了交流群,但是很多没有加群的朋友会通过ISSUES来反馈问题,提ISSUES本身是一个很好的技术习惯，这有助于Knife4j的发展，同时也能帮助更多的开发者从issue中找到问题所在。

但如何提一个好的issue非常重要，这有助于帮助捉着能很好的定位问题所在,因为作者并不是实时关注,所以经常在处理issues的时候，看到很多朋友提的问题却也无从着手，写下一些建议,希望提issue的朋友能在提的时候都有涉及到：

1、针对如何使用的问题，建议使用`Knife4j`的标签在开源中国社区进行提问以寻求帮助:[https://www.oschina.net/question/ask?tag=swagger-bootstrap-ui
](https://www.oschina.net/question/ask?tag=swagger-bootstrap-ui
)
或者关注Knife4j的微信公众号，加入讨论群寻求帮助
![](https://foruda.gitee.com/images/1661053867569480310/%E6%89%AB%E7%A0%81_%E6%90%9C%E7%B4%A2%E8%81%94%E5%90%88%E4%BC%A0%E6%92%AD%E6%A0%B7%E5%BC%8F-%E6%A0%87%E5%87%86%E8%89%B2%E7%89%88.png)

2、 **Knife4j和springfox-swagger、springdoc-openapi、Spring Boot等版本号** ,这个尤为重要,很多低版本出现的问题有可能我在新发布的版本中已经解决了,每个版本都有更新日志,可以参考这篇文档：[https://doc.xiaominfo.com/knife4j/changelog/](https://doc.xiaominfo.com/knife4j/changelog/)
贴上版本的信息有助于作者更快的定位到问题

3、 **提issue时贴图、贴代码,贴错误异常日志** ,代码不用贴逻辑，只需要贴接口层即可,还有 **相关的实体类** (如果有涉及的话)，有些问题可能是需要一连串的动作，希望能贴整个顺序图，帮助我复现Bug，这些信息有助于我快速定位问题,省去了来回沟通的成本,提高大家的效率

4、在交流群沟通的朋友我也希望能通过提ISSUE来记录下我们沟通的过程,我并非实时处理此问题，这让我集中再处理issues的时候有助于拉回我们彼此沟通时的场景，最终在新版本解决问题

5、一句简单的话不足以概括所有的信息一律当无效关闭处理

 **希望大家提issues的时候多一些信息,也省去大家交流的时间成本，避免浪费大家精力。** 

 **提issues信息不全的(我看不明白,特别是那种我还要问版本号之类的)我会直接关闭处理。请大家理解** 

> 举个很简单的例子，你可能发现了Knife4j的问题，提了issue给作者(这很好)，但是作者可能等了2天(这不是我的主职工作，我也不会全天24小时盯着通知回复问题)才来处理issue，此时，你提的issue中，即没有版本、也没有贴图，就三言两语描述了一下，那作者处理issue时，需要回复询问得到更多的信息来将两人的沟通拉回一个视线上，以确定到底是Knife4j的问题，还是别的什么原因呢，这一来一回的，半个月可能都过去了，这纯浪费大家时间。

**Comment by wuzl807924995** [comment]
在Docket中配置全局参数无效

依赖为最新版
      <dependency>
        <groupId>com.github.xiaoymin</groupId>
        <artifactId>knife4j-spring-boot-starter</artifactId>
        <version>2.0.4</version>
      </dependency>

设置全局依赖代码
           List<Parameter> pars = paramBeans.stream().map(p -> {
                ParameterBuilder tokenPar = new ParameterBuilder();
                return tokenPar.name(p.getName()).description(p.getDescription()).modelRef(new ModelRef(p.getJavaType())).parameterType(p.getParamType()).required(p.isRequired()).build();
            }).collect(Collectors.toList());
            docket.globalOperationParameters(pars);
--------------------------------------------------------------------
                param-beans:
                    - name: token2
                      description: 用户认证
                      java-type: String
                      param-type: header
                      required: false
-----------------------------------------------
@Data
public class ParamBean {

    private String name;

    private String description;

    private String javaType;

    private String paramType;

    private boolean required;
}

**Comment by xiaoymin** [comment]
Gitee提[issue](https://gitee.com/xiaoym/knife4j/issues)

项目地址：[https://gitee.com/xiaoym/knife4j](https://gitee.com/xiaoym/knife4j)

**Comment by Youth99** [comment]
支持不同请求路径显示不同的Docket吗
