### ISSUE TITLE
前端页面报错404

### ISSUE THREAD

**Issue by Lyeluo** [xiaoymin/knife4j#222]
spring boot 版本 2.1.4，spring cloud gateway版本2.1.2，knife4j版本2.0.2 配置完毕后进入页面没有问题，获取数据没有问题，但是F12打开谷歌工具发现报错有静态文件报错404，
同时前端js也有报错：Service worker installation failed. It will be retried automatically during the next navigation
报错如下
![image](https://user-images.githubusercontent.com/34667545/80343716-fa104c00-8898-11ea-9091-f4c28b67eff0.png)
是缺少什么配置吗？

**Comment by xiaoymin** [comment]
这个和knife4j本身的打包有关系，以前的版本有个service-work之类的，这个应该不影响使用，后面的版本会打包的时候把该快内容去除掉

**Comment by Lyeluo** [comment]
@xiaoymin 好的，我知道了，谢谢
