### ISSUE TITLE
实体中的集合类型的时间字段添加了ignoreParameters注解无效问题

### ISSUE THREAD

**Issue by yinhaisong** [xiaoymin/knife4j#226]
入参Vo实体中的时间字段：private List<Timestamp> orderTime;
controller里面接口添加了 @ApiOperationSupport(ignoreParameters = {"OrderVo.orderTime"})
页面入参依然显示createTime[0].date、createTime[0].day... 此类时间参数

**Comment by xiaoymin** [comment]
试试2.0.3吧

https://doc.xiaominfo.com/changelog/2020-05-24-knife4j-2.0.3-issue.html
