### ISSUE TITLE
在线调试的时候，搜索参数会和全局的重复显示

### ISSUE THREAD

**Issue by wulife** [xiaoymin/knife4j#23]
当定义一个全局的header数据的时候，在接口中定义接收时，改参数会重复显示
![header](https://user-images.githubusercontent.com/26455549/45193754-536dd680-b282-11e8-9cc8-7928a21ba95d.png)
![73i2 92hj z 0l0eugi n4p](https://user-images.githubusercontent.com/26455549/45193771-6d0f1e00-b282-11e8-93a3-29766789dec5.png)
![gmt42h sv cbe h30dh2dpk](https://user-images.githubusercontent.com/26455549/45193785-80ba8480-b282-11e8-981e-1e8e17cae316.png)
@xiaoymin

**Comment by xiaoymin** [comment]
全局参数这个功能在当时没有开发支持JWT之前推出的，

像这种情况的话，其实你可以在swagger的config配置文件中配置GlobalParameter功能

**Comment by xiaoymin** [comment]
1.8.4 已经处理了这个重复的参数 试试吧
