### ISSUE TITLE
get请求能否过滤掉空参数

### ISSUE THREAD

**Issue by jianchengwang** [xiaoymin/knife4j#230]
举个例子，如果空参数，我后台用的类型不是字符串就会报400错误，自己手动去掉又很麻烦，参数多的话，要手动一个一个去掉。建议可以跟swagger-ui一样，过滤掉空参数

**Comment by xiaoymin** [comment]
什么版本？

**Comment by xiaoymin** [comment]
2.0.3版本已经解决了GET情况下会传递Null的问题 可以升级一下 

变更日志：https://www.oschina.net/news/115921/knife4j-2-0-3-released

**Comment by jianchengwang** [comment]
> 什么版本？

 <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            
            <version>2.0.2</version>
        </dependency>

**Comment by jianchengwang** [comment]
> 2.0.3版本已经解决了GET情况下会传递Null的问题 可以升级一下
> 
> 变更日志：https://www.oschina.net/news/115921/knife4j-2-0-3-released

试了下可以，另外这样的话，比如参数类型是枚举的话，最好可以清空，看了下ui那边枚举类型是下拉框，只能删掉，另外枚举值一般都有描述等字段，最好能一起展示；还有首页卡半天才有数据生成，是不是可以优化下，从swagger-ui转过来，感觉变卡了好多

**Comment by xiaoymin** [comment]
卡顿的原因还在优化
