### ISSUE TITLE
请求响应内容如果是文件建议直接下载

### ISSUE THREAD

**Issue by jianchengwang** [xiaoymin/knife4j#232]
版本2.0.3
下载文件，响应内容是乱码字符，建议根据请求返回的application/type来判断比较好，如果是文件流的化，直接下载，可以参考swagger-ui的实现

**Comment by xiaoymin** [comment]
指定接口的produces

https://doc.xiaominfo.com/guide/downloadAndPreview.html

**Comment by jianchengwang** [comment]
嗯，指定produces是可以，不过我看postman跟swagger-ui不需要指定就可以了，应该有其他解决思路吧，毕竟返回类型不一定都是octet-stream

**Comment by jianchengwang** [comment]
> 指定接口的produces
> 
> https://doc.xiaominfo.com/guide/downloadAndPreview.html

建议看不指定produces能否实现，因为如果下载文件如果出现错误信息返回一般还是json信息，

**Comment by jianchengwang** [comment]
> > 指定接口的produces
> > https://doc.xiaominfo.com/guide/downloadAndPreview.html
> 
> 建议看不指定produces能否实现，因为如果下载文件如果出现错误信息返回一般还是json信息，

我如果返回错误信息是json,然后强制指定produces为文件流就会产生org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation这个异常

**Comment by xiaoymin** [comment]
目前做不到，用axios组件发送请求的时候，如果是流的请求，发送之前要添加配置responseType:'blob'

否则得到的数据是有问题的

**Comment by zombie-hjb** [comment]
> 嗯，指定produces是可以，不过我看postman跟swagger-ui不需要指定就可以了，应该有其他解决思路吧，毕竟返回类型不一定都是octet-stream

我指定了 produces = { "application/octet-stream" } 后，请求为 consumes = { "multipart/form-data" } ，此时请求参数中有文件类型，会无法上传，直接被丢弃掉，导致后台无法接收文件。改为application/json 后可以上传但是响应内容是乱码字符。


以下为application/octet-stream是的请求头信息
POST /ai/ocrtest HTTP/1.1
Host: 127.0.0.1:8080
Connection: keep-alive
Content-Length: 21
Accept: application/json, text/plain, */*, application/octet-stream
Request-Origion: SwaggerBootstrapUi
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61
Content-Type: multipart/form-data
Origin: http://127.0.0.1:8080
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://127.0.0.1:8080/doc.html
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6

**Comment by jianchengwang** [comment]
> > 嗯，指定produces是可以，不过我看postman跟swagger-ui不需要指定就可以了，应该有其他解决思路吧，毕竟返回类型不一定都是octet-stream
> 
> 我指定了 produces = { "application/octet-stream" } 后，请求为 consumes = { "multipart/form-data" } ，此时请求参数中有文件类型，会无法上传，直接被丢弃掉，导致后台无法接收文件。改为application/json 后可以上传但是响应内容是乱码字符。
> 
> 以下为application/octet-stream是的请求头信息
> POST /ai/ocrtest HTTP/1.1
> Host: 127.0.0.1:8080
> Connection: keep-alive
> Content-Length: 21
> Accept: application/json, text/plain, _/_, application/octet-stream
> Request-Origion: SwaggerBootstrapUi
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.61
> Content-Type: multipart/form-data
> Origin: http://127.0.0.1:8080
> Sec-Fetch-Site: same-origin
> Sec-Fetch-Mode: cors
> Sec-Fetch-Dest: empty
> Referer: http://127.0.0.1:8080/doc.html
> Accept-Encoding: gzip, deflate, br
> Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6

不指定consumes看看呢，没遇到，一般导出都是get请求吧

**Comment by zombie-hjb** [comment]
> > > 嗯，指定produces是可以，不过我看postman跟swagger-ui不需要指定就可以了，应该有其他解决思路吧，毕竟返回类型不一定都是octet-stream
> > 
> > 
> > 我指定了 produces = { "application/octet-stream" } 后，请求为 consumes = { "multipart/form-data" } ，此时请求参数中有文件类型，会无法上传，直接被丢弃掉，导致后台无法接收文件。改为application/json 后可以上传但是响应内容是乱码字符。

> 不指定consumes看看呢，没遇到，一般导出都是get请求吧

依然不行，我这边是要对上传的docx文件进行内容上的修改并且返回出去，我刚刚大概看了一下源码，再swaggerbootstrapui.js?v=1.9.6中。第2890行。reqdata取数据的时候是用params，不是formData。导致的丢失，修改为取formData 就可以处理成功。具体我也没仔细看，对js不是特别了解。不清楚具体为什么要这么处理。
     
https://github.com/xiaoymin/swagger-bootstrap-ui/blob/51527f11d3643c2f92071caab4fa91b70746ad0d/swagger-bootstrap-ui/src/main/resources/webjars/bycdao-ui/cdao/swaggerbootstrapui.js#L2887-L2905



这边判断为octet-stream类型后，请求参数为reqdata，也就是上述赋值的地方。我直接改上述赋值的地方，不清楚会不会对其他情况造成影响。
https://github.com/xiaoymin/swagger-bootstrap-ui/blob/51527f11d3643c2f92071caab4fa91b70746ad0d/swagger-bootstrap-ui/src/main/resources/webjars/bycdao-ui/cdao/swaggerbootstrapui.js#L2969-L2986


@xiaoymin 麻烦作者看下这边是否有问题

**Comment by xiaoymin** [comment]
目前在Knife4j 2.x的版本中，用的是axios，在发送流的请求时,需要指定blob类型，否则从服务端接收到的返回对象不是前端的Blob对象，会导致乱码，无法下载的情况，暂时不知道如何解决。
部分示例代码,https://gitee.com/xiaoym/knife4j上的dev分支：
```js
var requestConfig = {
          baseURL:baseUrl,
          url: url,
          method: methodType,
          headers: headers,
          params: applyReuqest.params,
          timeout: 0,
          //Cookie标志
          withCredentials:this.debugSendHasCookie(headers),
          //此data必传,不然默认是data:undefined,https://github.com/axios/axios/issues/86
          //否则axios会忽略请求头Content-Type
          data:applyReuqest.data
        };
        //console.log(requestConfig);
        //需要判断是否是下载请求
        if (this.debugStreamFlag()) {
          //流请求
          requestConfig = { ...requestConfig, responseType: "blob" };
        }
        const debugInstance = DebugAxios.create();
        //get请求编码问题
        //https://gitee.com/xiaoym/knife4j/issues/I19C8Y
        debugInstance.interceptors.request.use(config => {
          let url = config.url;
          if (config.method === "get" && config.params){
              url += "?";
              let keys = Object.keys(config.params);
              for (let key of keys) {
                if (KUtils.strNotBlank(config.params[key])) {
                  url += `${encodeURIComponent(key)}=${encodeURIComponent(
                    config.params[key]
                  )}&`;
                }
              }
              url = url.substring(0, url.length - 1);
              config.params = {};
          }
          // get参数编码
          config.url = url;
          return config;
        });

```

如果有解决方案，大家可以直接PR过来

**Comment by xiaoymin** [comment]
这个issues就先关闭了
