### ISSUE TITLE
knife4j2.0.2 ApiModelProperty example=json

### ISSUE THREAD

**Issue by kyruntime** [xiaoymin/knife4j#233]
实体类里我有一个字段的`example = "{\"第1名\":1000,\"第2名\":500}"`，通过原生的**swagger-ui.html**访问能正常显示，但是通过原生的**doc.html**访问，显示"[object Object]",我该如何怎么办？
**实体类**
![image](https://user-images.githubusercontent.com/53601447/83832620-b07b1280-a71c-11ea-8ac9-936a4b00d5fb.png)
**swagger-ui.html访问**
![image](https://user-images.githubusercontent.com/53601447/83832628-b5d85d00-a71c-11ea-820b-9074a975b804.png)
**doc.html访问**
![image](https://user-images.githubusercontent.com/53601447/83832676-cc7eb400-a71c-11ea-8a36-06dc8c9a1fe9.png)

**Comment by yoreyuan** [comment]
value 的数据类型改为 Map 就可以了
```java
private Map<String, Object> value;
```

**Comment by xiaoymin** [comment]
2.0.6 已经优化该问题

https://www.oschina.net/news/119457/knife4j-2-0-6-released
