### ISSUE TITLE
springfox-ui包被移除文档未修正和两处名字错误

### ISSUE THREAD

**Issue by winskin** [xiaoymin/knife4j#235]
## 文档名字错误-两处

文档（项目说明）：https://doc.xiaominfo.com/knife4j
`springfox-bean-validators：springfxo验证支持组件`中的`springfxo`应为`springfox`

## `springfox-ui`包被移除文档未修正

文档中说明`knife4j-spring-boot-starter`主要为我们引用的相关jar包`springfox-swagger-ui:springfox提供的ui`

发现版本`2.0.2`和`2.0.3`和master分支并未包含`springfox-swagger-ui`

最近开始使用，如有错误请多多指教。

**Comment by xiaoymin** [comment]
感谢指正
