### ISSUE TITLE
JPA 对象存在一对多多对一关联嵌套时接口文档无法访问

### ISSUE THREAD

**Issue by wangjin** [xiaoymin/knife4j#239]
knife4j starter版本：`2.0.3`
Spring Boot版本：`2.3.0`

JPA 对象存在一对多多对一关联嵌套时接口文档无法访问，页面和后台都没有报错信息。
工程启动时`Successfully started bean 'documentationPluginsBootstrapper' `这步需要30s左右。
有没有什么好的解决办法啊

**Comment by xiaoymin** [comment]
documentationPluginsBootstrapper 是springfox提供的，估计无法优化

**Comment by wangjin** [comment]
好吧
