### ISSUE TITLE
consumes 类型与请求参数的参数类型展示不一致

### ISSUE THREAD

**Issue by Janson-Leung** [xiaoymin/knife4j#24]
1. 参数类型展示：
consumes ["multipart/form-data"]  => 参数类型错误展示为 query
consumes ["application/x-www-form-urlencoded"] => 参数类型错误展示为 formData

2. 在线调试 
参数类型为 formData 的参数，填写了参数值还是提示 参数不能为空

**Comment by xiaoymin** [comment]
试试1.8.3
