### ISSUE TITLE
遇见一个很强迫症的东西

### ISSUE THREAD

**Issue by jtxf1** [xiaoymin/knife4j#240]
当线上关闭swagger功能后会打印这个日志
Mapped URL path [/v2/api-docs] onto method [public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)]
------------------ 5000
------------------ 5000
看了源码完全照不出来这个日志到底是怎么打印的,版本<knife4j.version>2.0.3</knife4j.version>

**Comment by xiaoymin** [comment]
我不会打印诸如5000 之类的这种日志，而且Swagger2Controller这个类是springfox提供的
