### ISSUE TITLE
2.0.3/2.0.4 doc.html页面卡顿问题

### ISSUE THREAD

**Issue by kervin521** [xiaoymin/knife4j#243]
2.0.2页面流畅，而2.0.3/2.0.4页面响应数据过大时出现卡顿现象，并导致整个页面无法点击以及无法滑动，数据量为500KB

最后只能刷新整个页面

**Comment by xiaoymin** [comment]
响应数据500kb？

**Comment by kervin521** [comment]
UI页面显示说明响应码:200耗时:518ms大小:404.42 kb

**Comment by rcfeng** [comment]
老版本没用过，2.0.4确实感觉卡

**Comment by xiaoymin** [comment]
试试2.0.5吧
