### ISSUE TITLE
您好，请问springcloud gateway中有一个小问题，麻烦帮忙看看，谢谢。

### ISSUE THREAD

**Issue by literatureandyou** [xiaoymin/knife4j#246]
您好，请问springcloud gateway 配置
predicates:
          - Path=/edu/api-scripty/**
在文档上调试时是否可以将请求链接的这段URI中的这部分给去除掉？

**Comment by xiaoymin** [comment]
去掉了你如何调试？能保证发送的时候正确转发到你的微服务里面去？

**Comment by literatureandyou** [comment]
由于项目需要，gateway处路由并没有做StripPrefix，所以需要去掉-path，加了一个拦截器改变一下返回值可以解决。对路由到下游服务没有影响。
