### ISSUE TITLE
model有的类不显示说明信息，不知为何

### ISSUE THREAD

**Issue by wangyunzhong123** [xiaoymin/knife4j#254]
![image](https://user-images.githubusercontent.com/9133666/88667442-f5fffe80-d113-11ea-986b-c0fdc167862c.png)

如图，该类有@ApiModel修饰，并且属性有@ApiModelProperty修饰，为何页面的model不显示说明信息？

求助

**Comment by wangyunzhong123** [comment]
2.0.2版本，试了2.0.3版本也不行

**Comment by xiaoymin** [comment]
`@ApiModel`注解修饰的类必须保证全局唯一

另外可以贴贴代码

**Comment by wangyunzhong123** [comment]
`@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel("错题补充信息或笔记")
public class ExtNoteVO {

    @ApiModelProperty("笔记ID")
    private long id;
    @ApiModelProperty("用户账户")
    private long ytkUserId;
    @ApiModelProperty("原始错题ID")
    private long nQId;
    @ApiModelProperty("题干完善信息。在拍照收藏场景使用")
    private List<ExtInfo> content;
    @ApiModelProperty("答案完善信息。在拍照收藏场景使用")
    private List<ExtInfo> answer;
    @ApiModelProperty("笔记。目前在搜题收藏场景使用")
    private List<NoteDetailVO> noteDetails;
    @ApiModelProperty("创建时间")
    private long createdTime;
    @ApiModelProperty("更新时间")
    private long updatedTime;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Accessors(chain = true)
    @ApiModel
    public static class NoteDetail {

        @ApiModelProperty("文字描述")
        private String desc;
        @ApiModelProperty("图片列表")
        private List<String> imageIds;
        @ApiModelProperty("图片url")
        private List<String> imageIdUrls;
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Accessors(chain = true)
    @ApiModel
    public static class ExtInfo {

        @ApiModelProperty("图片列表")
        private List<String> imageIds;
        @ApiModelProperty("图片url")
        private List<String> imageIdUrls;
    }
}`

如上，可以保证这个类是全局唯一的。再次求解

**Comment by xiaoymin** [comment]
没看出来啥问题，是否和lombok组件的注解冲突

**Comment by wangyunzhong123** [comment]
但是另外一个类是ok的，


`
@Data
@NoArgsConstructor
@AllArgsConstructor
@Accessors(chain = true)
@ApiModel("导入错图本操作返回")
public class ImportResultVO {

    @ApiModelProperty("200: 导入完成，可以直接用resultList的结果；201：未完成，需要轮询接口查看结果；202：uuid不存在；203：导入失败，直接显示msg信息")
    private int code;
    @ApiModelProperty("203时提示信息")
    private String msg;
    @ApiModelProperty("操作标识，导入请求会返回；之后轮询用此参数")
    private String uuid;
    @ApiModelProperty(value = "来源", notes = "ImportNotebookSource")
    private ImportNotebookSource source;
    @ApiModelProperty("结果")
    private List<Result> resultList;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Accessors(chain = true)
    @ApiModel("导入错图本结果")
    public static class Result {

        @ApiModelProperty("科目")
        private String course;
        @ApiModelProperty("导入数量")
        private int successCount;
    }
}
`

这个是ok的，

![image](https://user-images.githubusercontent.com/9133666/88783187-10dc7c80-d1c1-11ea-9f56-0208b623cec7.png)

**Comment by xiaoymin** [comment]
@wangyunzhong123 

这种情况，要检查到底是Knife4j的程序是否有问题，很简单

在浏览器请求初始化界面的Swagger接口(`/v2/api-docs`)里面，在返回的JSON中，查看当前类的接口定义，看看接口定义中这个类有没有属性，如果该类有属性，那是Knife4j的程序问题，如果没有属性，那是springfox和lombok组件冲突的问题，可以检查一下

检查JSON中的`definitions`节点中的该类，如下图：
![image](https://user-images.githubusercontent.com/7894406/88870869-11b8f100-d249-11ea-86dd-d2a315ac2568.png)

**Comment by wangyunzhong123** [comment]
嗯，找到问题了。属性的第二个字母是大写的问题...
