### ISSUE TITLE
在Docket中配置全局参数无效

### ISSUE THREAD

**Issue by wuzl807924995** [xiaoymin/knife4j#255]
依赖为最新版

com.github.xiaoymin
knife4j-spring-boot-starter
2.0.4
设置全局依赖代码
List pars = paramBeans.stream().map(p -> {
ParameterBuilder tokenPar = new ParameterBuilder();
return tokenPar.name(p.getName()).description(p.getDescription()).modelRef(new ModelRef(p.getJavaType())).parameterType(p.getParamType()).required(p.isRequired()).build();
}).collect(Collectors.toList());
docket.globalOperationParameters(pars);
            param-beans:
                - name: token2
                  description: 用户认证
                  java-type: String
                  param-type: header
                  required: false

**Comment by xiaoymin** [comment]
springfox提供的全局参数和Knife4j界面提供的全局参数是2个概念

springfox提供的全局参数在项目启动运行初始化Swagger对象的时候,会把Docket对象中的全局参数分配给所有API接口，相当于给每个接口都加个参数，,对于OpenAPI 的规范来说,其实并没有全局参数这个概念，所以不会单独体现

Knife4j提供的全局参数是为了开发在调试的时候方便而单独增加的一个功能,和后台是无关的，在界面中添加一个全局参数同样会给每一个接口打开文档调试的时候，赋予一个全局参数值，但这部分实现是在前端独立来实现的
