### ISSUE TITLE
swagger-bootstrap-ui页面嵌入iframe

### ISSUE THREAD

**Issue by dimples9527** [xiaoymin/knife4j#256]
swagger-bootstrap-ui 页面嵌入iframe 报错 Refused to display in a frame because it set 'X-Frame-Options' to 'deny'。
尝试过设置 X-Frame-Options 请求头，但是不行
请问怎么解决一下

**Comment by rcfeng** [comment]
基于zuul + security

configure(HttpSecurity http)

//解决X-Frame-Options DENY
http.headers().frameOptions().sameOrigin()

**Comment by xiaoymin** [comment]
建议单独打开，嵌入iframe也没打算支持，谢谢
