### ISSUE TITLE
hidden=true的接口并没有隐藏

### ISSUE THREAD

**Issue by imwangjiping** [xiaoymin/knife4j#259]
某个resource下, 所有的mapping都设置@ApiOperation(hidden=true), 这样的情况下,页面上并没有去除掉一级标题, 点击跳转空白页面.
版本: 
io.springfox:springfox-swagger2:2.9.2
com.github.xiaoymin:knife4j-spring-boot-starter:2.0.4

**Comment by xiaoymin** [comment]
隐藏接口用springfox提供的注解`@ApiIgnore`

**Comment by imwangjiping** [comment]
十分感谢.

**Comment by samho2008** [comment]
有用，感谢。`@Api(hidden = true)` 设置了没有用，用 `@ApiIgnore` 就可以了。
