### ISSUE TITLE
泛型数据接口返回list类型时，不能解析

### ISSUE THREAD

**Issue by wulife** [xiaoymin/knife4j#26]
当返回list数据时，响应示例不能解析，
接口代码：
![rpcr 5_ 3teihox7wwj](https://user-images.githubusercontent.com/26455549/45365249-b4910380-b60e-11e8-8062-eedf5a7e7c21.png)
响应示例：
![qcyzqz3qri_z a2e zaaz91](https://user-images.githubusercontent.com/26455549/45365211-975c3500-b60e-11e8-85a7-2baf92b1c270.png)
返回测试数据：
![st3 x ne 3p guum5 s9](https://user-images.githubusercontent.com/26455549/45365297-cd011e00-b60e-11e8-8dfc-e03a204815a2.png)

**Comment by wulife** [comment]
当返回类型是一个实体类对象时可以正常解析
![epk cyqp n2qyk _s o9p 7](https://user-images.githubusercontent.com/26455549/45365609-7cd68b80-b60f-11e8-888e-c516d54536d4.png)

![46 l_u _ wk 1a 7mqh4 4](https://user-images.githubusercontent.com/26455549/45365580-67616180-b60f-11e8-8a28-dcc7971d3569.png)

**Comment by xiaoymin** [comment]
试试1.8.3新版
