### ISSUE TITLE
@Validated @NotBlank 导致doc页面参数不见了，且无法自定义输入（postman测试接口正常）

### ISSUE THREAD

**Issue by en-o** [xiaoymin/knife4j#260]
```java
@RestController
@RequestMapping("user")
@Validated
@Api(tags = "user - user")
public class UserController {
 @ApiOperation("user - 登录")
    @ApiMapping(value = "login",checkToken = false)
    public ResultVO login(@NotBlank String userName) {
        if(!userName.equals("tn")){
            return ResultVO.fail("登录失败");
        }
        String token = JwtUtil.sign(userName, null);
        return ResultVO.success(token);
    }
}
```
![图片](https://user-images.githubusercontent.com/45027672/90036614-d5c86600-dcf5-11ea-9b86-9b335b241900.png)

**Comment by en-o** [comment]
# 换成对象就没事
![图片](https://user-images.githubusercontent.com/45027672/90037642-06f56600-dcf7-11ea-8828-571291540bf8.png)

**Comment by xiaoymin** [comment]
参数没有一般就是springfox解析就没有生成该接口的参数，Ui这层应该不会抛弃参数的，你可以自检一下在界面请求的接口`/v2/api-docs`返回的内容，找到该接口，看看是否有参数

**Comment by en-o** [comment]
![图片](https://user-images.githubusercontent.com/45027672/90118857-6d2bc880-dd8b-11ea-9a39-db1c1ba3273a.png)
api-docs里有

**Comment by en-o** [comment]
![图片](https://user-images.githubusercontent.com/45027672/90119169-d01d5f80-dd8b-11ea-89d2-64f70fd8e292.png)
跑到body里去了
