### ISSUE TITLE
knife4j结合bean-validator

### ISSUE THREAD

**Issue by tangzp** [xiaoymin/knife4j#262]
导出markdown或html的时候，增加一列，专门显示JSR303注解信息

**Comment by linghengqian** [comment]
@xiaoymin 
- I'm a bit confused, shouldn't this issue be closed? After all, SpringDoc V1 and V2 parses JSR-303 normally, specifically for `@NotNull`, `@Min`, `@Max`, and `@Size`. 
- Refer to https://github.com/xiaoymin/swagger-bootstrap-ui/pull/510 and https://springdoc.org/#Introduction .

**Comment by xiaoymin** [comment]
> @xiaoymin
> 
> * I'm a bit confused, shouldn't this issue be closed? After all, SpringDoc V1 and V2 parses JSR-303 normally, specifically for `@NotNull`, `@Min`, `@Max`, and `@Size`.
> * Refer to [Add new module knife4j-openapi3-jakarta-spring-boot-starter #510](https://github.com/xiaoymin/swagger-bootstrap-ui/pull/510) and https://springdoc.org/#Introduction .

@linghengqian Knife4j provides enhanced features to [export offline documents](https://doc.xiaominfo.com/docs/features/exportDocument) (eg:markdown or word)

But the information of jsr303 is not displayed in the offline document, jsr303 is only presented on the web pages
