### ISSUE TITLE
doc.html页面请求计算错误

### ISSUE THREAD

**Issue by hi589dsTq92** [xiaoymin/knife4j#264]
1.doc.html页面的调试功能描述的响应字节数据应为：KB而非kb，使用kb容易引发位/字节歧义；
2.doc.html页面的调试功能计算的耗时时间与实际时间不符，使用chrome浏览器自带开发者工具测得的一条请求/响应时间远低于doc.html所展示的耗时，使用charles代理工具监听的请求/响应时间与chrome开发者工具相同。

**Comment by xiaoymin** [comment]
接口的耗时计算不准，不管是用axios的拦截器 还是response后计算，都会有误差

**Comment by xiaoymin** [comment]
第1条 2.0.5 已改
