### ISSUE TITLE
spring-plugin-core的兼容问题

### ISSUE THREAD

**Issue by kn5886348135** [xiaoymin/knife4j#265]
当前使用spring-boot 2.3.1，knife4j2.0.4，gralde6.4 出现异常，具体异常信息为
An attempt was made to call a method that does not exist. The attempt was made from the following location:    springfox.documentation.spring.web.plugins.DocumentationPluginsManager.createContextBuilder(DocumentationPluginsManager.java:152)
The following method did not exist:
org.springframework.plugin.core.PluginRegistry.getPluginFor(Ljava/lang/Object;Lorg/springframework/plugin/core/Plugin;)Lorg/springframework/plugin/core/Plugin;
大致的意思是尝试调用createContextBuilder这个方法的时候，getPluginFor是不存在的
spring-boot2.3.1依赖的是spring-plugin-core 2.0.0.RELEASE版本，而knife4j依赖的是1.2.0版本，getPluginFor这个方法的参数在新版本中发生了变化

**Comment by xiaoymin** [comment]
knife4j 2.0.6 升级springfox 到2.10.5

spring-plugin也升级了

https://www.oschina.net/news/119457/knife4j-2-0-6-released
