### ISSUE TITLE
swagger-bootstrap-ui与@ComponentScan冲突问题,

### ISSUE THREAD

**Issue by developers-youcong** [xiaoymin/knife4j#266]
swagger-bootstrap-ui版本号为:**1.9.3**

错误提示信息(界面上弹框提示):
请确保swagger资源接口正确

原因如图:
![image](https://user-images.githubusercontent.com/45055576/91925306-4e27b300-ed07-11ea-95dd-10348194a2df.png)

![image](https://user-images.githubusercontent.com/45055576/91925349-61d31980-ed07-11ea-9052-e35781fc9c1a.png)

初步分析结果如下:
是因为SpringBoot主类的@ComponentScan与SwaggerConfiguration配置类中的apis(RequestHandlerSelectors.basePackage("com.eqics.aqa"))冲突导致的。

我搜索了一圈，一直没有找到解决办法，除非注掉主类的@ComponentScan就能正常看到接口。但注掉可能会迫使我改一堆代码。

想请教一下，有什么更好的解决问题方法？

**Comment by xiaoymin** [comment]
怎么算是冲突？没看你贴出错误日志

**Comment by developers-youcong** [comment]
冲突就是项目启动正常后不能正常访问到界面(界面正常会有很大接口，但我这直接提示请确保swagger资源接口正确

**Comment by developers-youcong** [comment]
两个红色标记处，只能保留一个，保留swagger的则访问http://IP:Port/doc.html，直接提示请确保swagger资源接口正确，如图所示:
![image](https://user-images.githubusercontent.com/45055576/91975554-23af1780-ed52-11ea-8448-b257f77689b9.png)

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/faq/swaggerResourceInvalid.html

**Comment by developers-youcong** [comment]
你所提供的网址(包含解决办法)都不能最终解决我的这个问题。我的这个问题就是swagger配置类的和@ComponentScan()冲突导致的，不然也不会出现，只要注释@ComponentScan()就能正常访问。

**Comment by xiaoymin** [comment]
你也没提供异常啊

**Comment by xiaoymin** [comment]
springboot默认自己扫描，为啥还需要加这个scan注解？

**Comment by developers-youcong** [comment]
我之所以需要加@ComponentScan这个注解，是因为我定义一个公共模块处理全局异常和Controller统一信息返回等。
至于对应的异常信息，启动能够正常，就是无法访问界面。去除@ComponentScan该注解就能正常返回了。
有没有什么办法能够确保swagger-bootstrap注解和自定义@CommponentScan注解共存而不冲突。

**Comment by xiaoymin** [comment]
提示的信息 已经贴出来了，你没有给我反馈，swagger资源异常，我给的文档里面有分析原因，是什么导致的 ，这些你都没反馈

有冲突，那么错误异常是什么

这些我都不知道，我咋给你解决？

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/faq/swaggerResourceInvalid.html

这篇文章，对照到你自己的情况去分析，反馈出来 ，不然就好像在讨论AB问题

**Comment by developers-youcong** [comment]
嗯，好的。我在研究研究看看。先关了这个issue。

**Comment by PhaerisWakfu** [comment]
> 至于对应的异常信息，启动能够正常，就是无法访问界面。去除@componentscan该注解就能正常返回了。

@SpringBootApplication不是自带@ComponentScan? 直接basePackage不就完了
