### ISSUE TITLE
接口入参枚举为 List 或者 Array 时，调试模式无法多选

### ISSUE THREAD

**Issue by chenlingmin** [xiaoymin/knife4j#267]
你好，我在定义查询接口，入参为枚举集合时，调试模式没有多选的模式，用的版本是 2.0.4

* controller 代码截图
![image](https://user-images.githubusercontent.com/8233283/91937130-e5026880-ed23-11ea-95b2-beb449e998c2.png)

* api-docs 截图
![image](https://user-images.githubusercontent.com/8233283/91937591-d36d9080-ed24-11ea-9a7b-8ce54df5dca3.png)

* knife4j 截图
![image](https://user-images.githubusercontent.com/8233283/91937662-fac45d80-ed24-11ea-856a-cdd3489ae8fd.png)
![image](https://user-images.githubusercontent.com/8233283/91937634-ea13e780-ed24-11ea-8aec-f83cf455a09b.png)

**Comment by xiaoymin** [comment]
2.0.5 支持了枚举多选
