### ISSUE TITLE
spring boot 2.3.3、springfox 3.0.0与knife4j2.0.4集成报错问题

### ISSUE THREAD

**Issue by leefengzi** [xiaoymin/knife4j#268]
是否暂时未能支持springfox 3.0.0?

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.github.xiaoymin.knife4j.spring.plugin.OperationDynamicResponseModelProvider.apply(OperationDynamicResponseModelProvider.java:45)

The following method did not exist:

    springfox.documentation.spi.service.contexts.RequestMappingContext.findAnnotation(Ljava/lang/Class;)Lcom/google/common/base/Optional;

The method's class, springfox.documentation.spi.service.contexts.RequestMappingContext, is available from the following locations:

    jar:file:/C:/Users/Administrator/.m2/repository/io/springfox/springfox-spi/3.0.0/springfox-spi-3.0.0.jar!/springfox/documentation/spi/service/contexts/RequestMappingContext.class

The class hierarchy was loaded from the following locations:

    springfox.documentation.spi.service.contexts.RequestMappingContext: file:/C:/Users/Administrator/.m2/repository/io/springfox/springfox-spi/3.0.0/springfox-spi-3.0.0.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of springfox.documentation.spi.service.contexts.RequestMappingContext

**Comment by gameldd** [comment]
现在不支持 swagger3.0版本，只做为UI来用的话，还可以。（不要添加 @EnableKnife4j）

**Comment by leefengzi** [comment]
> 现在不支持 swagger3.0版本，只做为UI来用的话，还可以。（不要添加 @EnableKnife4j）

有没有计划去支持3.0?

**Comment by xiaoymin** [comment]
可以用knife4j3.0 

https://www.oschina.net/news/119457/knife4j-2-0-6-released

**Comment by hury88** [comment]
> 现在不支持 swagger3.0版本，只做为UI来用的话，还可以。（不要添加 @EnableKnife4j）

解决了我的问题 去除 @EnableKnife4j
