### ISSUE TITLE
离线文档 markdown格式错误

### ISSUE THREAD

**Issue by SeriousMa** [xiaoymin/knife4j#27]
![image](https://user-images.githubusercontent.com/464213/45421580-0f366800-b6c0-11e8-9e6a-9e3300478dc8.png)

**Comment by xiaoymin** [comment]
这个是使用js模板引擎造成的显示问题，但其实并不影响预览使用

**Comment by SeriousMa** [comment]
@xiaoymin 影响呢...需要人工编辑一下

**Comment by xiaoymin** [comment]
1.8.3 已解决
