### ISSUE TITLE
在实现非rest 风格mvc 时会出现 swagger-ui Models不显示 

### ISSUE THREAD

**Issue by hemingyang** [xiaoymin/knife4j#273]
@RequestBody 在此注解是会显示  ,但是会出现 请求错误

**Comment by xiaoymin** [comment]
代码呢，效果图 都贴出来看看

**Comment by hemingyang** [comment]
![image](https://user-images.githubusercontent.com/28049728/93158064-03159300-f73e-11ea-802b-17d2f80ddd1d.png)

**Comment by xiaoymin** [comment]
在springfox的解析过程中,针对form或者urlform类型，在接口上直接写实体类，springfox会将此类的属性进行拆分解析到OpenAPI规范中的parameter里面去，针对`@RequestBody`注解标注的才会作为OpenAPI中的model引用，出现在OpenAPI规范中的`definitions`节点中

**Comment by hemingyang** [comment]
嗯  有什么其他的解决方案吗 因为我是要渲染页面  但是他会解析成json

**Comment by xiaoymin** [comment]
你这个接口就应该忽略掉，都不算接口

**Comment by hemingyang** [comment]
嗯  但是我想显示Models

**Comment by xiaoymin** [comment]
显示model上面我已经解释过了 ，除了上面的

两位一种方法是在创建Docket对象的时候把Model加进去，这个你具体可以看看构建Docket时的结构

**Comment by hemingyang** [comment]
嗯谢谢
