### ISSUE TITLE
文档对字段为required = true提示不正确（是否必须为false）

### ISSUE THREAD

**Issue by kervin521** [xiaoymin/knife4j#277]

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/94414097-80192180-01ae-11eb-86ee-0937f904c522.png)

**Comment by kervin521** [comment]
![image](https://user-images.githubusercontent.com/9798724/94414197-a0e17700-01ae-11eb-81c3-fe2bb4a31f2a.png)

**Comment by tufeng1992** [comment]
顶！

**Comment by happyyangyuan** [comment]
同样的问题

**Comment by ghostg00** [comment]
同 遇到这问题

**Comment by ghostg00** [comment]
我看了源码  好像是 swagger数据里数组的required 和 生成require  的问题

**Comment by xiaoymin** [comment]
感谢大家的关注，这个bug会在下个版本解决

**Comment by xiaoymin** [comment]
https://www.oschina.net/news/119457/knife4j-2-0-6-released
