### ISSUE TITLE
版本2.8.0，不支持gson的@SerializedName设置字段名称

### ISSUE THREAD

**Issue by xieyuanyou11** [xiaoymin/knife4j#278]
设置u_user展示的是user
uPass字段设置的是u_pass，读出来有两个：uPass、uupass
![image](https://user-images.githubusercontent.com/25951182/94539253-94752100-0277-11eb-84d5-a7b7aa10ab9c.png)
![image](https://user-images.githubusercontent.com/25951182/94539375-ba022a80-0277-11eb-89d5-ada71bd7b9e8.png)

**Comment by xiaoymin** [comment]
是的 本来就不支持，springfox也不支持，另外你这个uPass这种驼峰写法springfox也不支持，不规范

**Comment by xieyuanyou11** [comment]
好的，感谢
