### ISSUE TITLE
引入 knife4j没有扫描到接口

### ISSUE THREAD

**Issue by fortune-bin** [xiaoymin/knife4j#281]
![image](https://user-images.githubusercontent.com/41983216/97657903-08d4f700-1aa6-11eb-8a46-1f8839736180.png)
![image](https://user-images.githubusercontent.com/41983216/97657944-2013e480-1aa6-11eb-95b6-4c31b89ff53f.png)
![image](https://user-images.githubusercontent.com/41983216/97658000-3ae65900-1aa6-11eb-9a73-567bef61e0b2.png)
![image](https://user-images.githubusercontent.com/41983216/97658050-52bddd00-1aa6-11eb-9a25-b00449972d4c.png)
 
不报错接口也没有扫描出来

**Comment by xiaoymin** [comment]
3.x版本底层依赖springfox3,要用`@EnableOpenApi`注解

**Comment by xiaoymin** [comment]
要用springfox2的结构，请用knife4j提供的最新2.x版本

**Comment by fortune-bin** [comment]
引入 2.0.7 版本 出现 
![Uploading image.png…]()

**Comment by fortune-bin** [comment]
@xiaoymin xiao
![Uploading image.png…]()

**Comment by fortune-bin** [comment]
@xiaoymin  引入2.0.7 出现无法注解失效
![image](https://user-images.githubusercontent.com/41983216/97947187-7dba7080-1dc7-11eb-9534-7b1a4ab01aae.png)

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/changelog/

**Comment by xiaoymin** [comment]
https://www.oschina.net/news/119457/knife4j-2-0-6-released
