### ISSUE TITLE
现在如何开启自定义文档

### ISSUE THREAD

**Issue by m01i0ng** [xiaoymin/knife4j#285]
https://doc.xiaominfo.com/guide/self-doc.html#spring-boot%E7%8E%AF%E5%A2%83 安装这个配置方式开启无效，前端个性化设置中也没看到增强功能

**Comment by xiaoymin** [comment]
目前新版本文档变更了，地址：https://xiaoym.gitee.io/knife4j/documentation/selfdocument.html

**Comment by xiaoymin** [comment]
@m01i0ng

**Comment by m01i0ng** [comment]
嗯嗯感谢、看到了、按照配置已开启、现在通过浏览器查看请求有 `x-markdownFiles` 字段、但界面上不展示
![image](https://user-images.githubusercontent.com/19723234/99183605-034f0080-2778-11eb-935c-8b2bba05c6eb.png)

**Comment by xiaoymin** [comment]
@m01i0ng 你这个是什么版本？正常情况下扩展节点外还有一层`x-openapi`

**Comment by m01i0ng** [comment]
目前是 3.0.1 的 starter、我贴下相关配置图
![image](https://user-images.githubusercontent.com/19723234/99183699-b3bd0480-2778-11eb-9dc5-f678e157c603.png)

![image](https://user-images.githubusercontent.com/19723234/99183701-bae41280-2778-11eb-92ec-5053975bba8e.png)

![image](https://user-images.githubusercontent.com/19723234/99183707-c2a3b700-2778-11eb-8dcc-5fde7a27b5a7.png)

**Comment by xiaoymin** [comment]
@m01i0ng 是这样的，如果开发者继续使用OpenAPIv2的规范，就继续使用Knife4j的2.x版本，更新最新即可

如果开发者要用OpenApiV3的规范，即你在创建Docket对象的时候，指定的版本是OAS3,那么这个时候用Knife4j的3.x版本

Knife4j3.x是针对springfox3的封装，开发者两者不要混用，虽然springfox3向下兼容，但是目前也存在诸多问题，作者也是以2.x稳定版本继续迭代，具体的版本变化请参考文档：[https://xiaoym.gitee.io/knife4j/documentation/changelog.html](https://xiaoym.gitee.io/knife4j/documentation/changelog.html)

**Comment by m01i0ng** [comment]
@xiaoymin 了解、换用 2.0.7 版本后可以了、感谢、
