### ISSUE TITLE
找不到”Select a definition“中其他服务的接口

### ISSUE THREAD

**Issue by wsrf16** [xiaoymin/knife4j#287]
![image](https://user-images.githubusercontent.com/11867768/100062922-59543000-2e6b-11eb-8c2d-686bdff6311f.png)
但在原生swagger-ui中没有这个问题，猜测这里使用的basePath不是从json中解析出来的
![image](https://user-images.githubusercontent.com/11867768/100063239-dd0e1c80-2e6b-11eb-9062-d4c0499d812d.png)

**Comment by xiaoymin** [comment]
你这标题和内容 我都没看懂，你内容里面basePath就只有一个“/” ,你这怀疑的根据是什么

**Comment by wsrf16** [comment]
![image](https://user-images.githubusercontent.com/11867768/100063709-910fa780-2e6c-11eb-8f2b-b15aa219dd60.png)
![image](https://user-images.githubusercontent.com/11867768/100063738-9b31a600-2e6c-11eb-9ca5-6fd81e3e1278.png)
切换了”SwaggerResource“之后，在knife4j中调用接口，返回404。原生swagger没有此问题。

**Comment by wsrf16** [comment]
看图1和图3，调用同一个接口返回的区别，不知道我说明白没有

**Comment by xiaoymin** [comment]
没看懂，404 ，你看network具体发送的请求对不对就是了，如果是404 那么必然接口地址有误，那正常的接口地址是什么？

**Comment by wsrf16** [comment]
是前面的host不对，swagger-ui取的是json中解析出来的host，knife4j取的可能是浏览器中url的host，导致404

**Comment by xiaoymin** [comment]
那就是你访问doc.html 不是localhost:58882?

**Comment by wsrf16** [comment]
这两个”SwaggerResource“用的不是同一个host，一个是"localhost:8880"，一个是"localhost:58882"

**Comment by xiaoymin** [comment]
knife4j 默认禁用openapi规范中的host

https://xiaoym.gitee.io/knife4j/documentation/host.html

**Comment by xiaoymin** [comment]
不同的host会导致跨域，很多人搞不清楚跨域，我也不想解释

**Comment by xiaoymin** [comment]
每个组如果host不同，可以在个性化配置中勾选启用 

，例如：http://knife4j.xiaomjnfo.com/doc.html#/documentManager/Settings

**Comment by wsrf16** [comment]
好的  谢谢

**Comment by xiaoymin** [comment]
可以使用Knife4jAggregation聚合组件，屏蔽HOST,和微服务聚合时一样简单

https://xiaoym.gitee.io/knife4j/documentation/knife4jAggregation.html

**Comment by wsrf16** [comment]
![image](https://user-images.githubusercontent.com/11867768/100066539-30826980-2e70-11eb-9f33-94f92fc952e1.png)
就是要一个这类的聚合功能，这里可不可以跨服务器上

**Comment by xiaoymin** [comment]
基于接口就是了 ，https://xiaoym.gitee.io/knife4j/action/aggregation-cloud.html
只要你的接口是通的 ，当然可以跨服务器

**Comment by wsrf16** [comment]
好的 正在找这类聚合的功能  微服务接口文档太离散  统一集中在一起便于管理
