### ISSUE TITLE
关于泛型数据接口返回list类型时的一个小bug

### ISSUE THREAD

**Issue by wulife** [xiaoymin/knife4j#29]
1.8.3的版本中的这个问题，正常情况下没问题，但是当泛型字段的注解加了example默认值时，list对象会解析不出来

![image](https://user-images.githubusercontent.com/26455549/45616030-d4a64400-baa0-11e8-983c-fad65bd80b07.png)

这是正常情况：
![image](https://user-images.githubusercontent.com/26455549/45616127-1c2cd000-baa1-11e8-8edf-2b569d46010a.png)
![image](https://user-images.githubusercontent.com/26455549/45616202-55fdd680-baa1-11e8-8293-31f53765b05b.png)
这是加了默认值的情况：

![image](https://user-images.githubusercontent.com/26455549/45616293-93fafa80-baa1-11e8-9bbb-381764e5a2e7.png)

![image](https://user-images.githubusercontent.com/26455549/45616285-8f364680-baa1-11e8-9bb2-8e415691a48f.png)

**Comment by xiaoymin** [comment]
感谢反馈~！

**Comment by wulife** [comment]
还有，1.8.3的版本post请求类型会出错，后端接收不到参数，看了一下好像是前端传参问题

![image](https://user-images.githubusercontent.com/26455549/45661526-70cb5c00-bb30-11e8-8119-0823e9f9baea.png)
@xiaoymin

**Comment by xiaoymin** [comment]
嗯 这个问题已经收到反馈，

**Comment by xiaoymin** [comment]
最新版本1.8.5，试试
