### ISSUE TITLE
nginx 反向代理后，请求地址不正确

### ISSUE THREAD

**Issue by Bleoo** [xiaoymin/knife4j#291]
版本 2.0.8

当我使用 nginx 时，nginx 配置如下，希望通过 https://domin/apitest/ 来访问我的服务
```
location /apitest/ {
    proxy_pass http://myLocalIp:port/;
}
```
![image](https://user-images.githubusercontent.com/11569795/100315663-f9d55c00-2ff3-11eb-8882-4a12a1806b54.png)

此时，文档正常能访问，但是debug接口时 host 似乎没有添加上 /apitest/ 的后缀

![image](https://user-images.githubusercontent.com/11569795/100315430-9c410f80-2ff3-11eb-9245-3552054c4fc7.png)

**Comment by Bleoo** [comment]
升级到 2.0.8 后已解决

**Comment by xiaoymin** [comment]
@Bleoo 

这个也算老版本文档了，试试Knife4j的聚合组件吧，Knife4jAggregation

https://xiaoym.gitee.io/knife4j/documentation/knife4jAggregation.html

市面上没有比这个更简单好用的聚合OpenAPI组件了

如果是别的语言，用Docker镜像

https://xiaoym.gitee.io/knife4j/action/aggregation-docker.html

**Comment by Bleoo** [comment]
谢谢你的回复，我是服务是个单体应用，要如何使用 文档聚合功能 呢？我看到 https://doc.xiaominfo.com/solution/ui-front-nginx.html 这里说是加一个json 文件，我不太确定怎么解决，

**Comment by Bleoo** [comment]
我通过这种方式可行了
```
knife4j.enableAggregation=true
knife4j.cloud.enable=true
knife4j.cloud.routes[0].name=MadTrace-1.0
knife4j.cloud.routes[0].uri=localhost:12345
knife4j.cloud.routes[0].location=/v2/api-docs?group=MadTrace-1.0
knife4j.cloud.routes[0].servicePath=/apitest
```
但是感觉怪怪的，通过应用自身聚合后，又转发给自身。

**Comment by xiaoymin** [comment]
你如果是springboot项目，为啥要搞nginx？

**Comment by Bleoo** [comment]
因为有一个前端的项目用的是同一台服务器，走的 nginx，我也就这样用了，就没用 spring boot 的网关... 有更好的解决方式么

**Comment by xiaoymin** [comment]
你不知道可以设置context-path的么？

**Comment by Bleoo** [comment]
知道的，但是我不想让这个应用绑死了 路径 前缀...

**Comment by Bleoo** [comment]
哈哈，我想了一下，我觉得也可以设置一下context-path，可以做成外部配置... 
非常谢谢你，你比 my*****plus 的作者热心多了。

**Comment by xiaoymin** [comment]
如果你不想设置context-path的话，Knife4jAggregation聚合组件应该是目前最合适的，因为文档中的servicPath是一个虚拟的路径地址，是满足你的要求的
