### ISSUE TITLE
spring boot 2.3.4 集成knife4j 2.0.7 后再linux下页面无法，但是在windows下是正常的

### ISSUE THREAD

**Issue by yangzhe09** [xiaoymin/knife4j#292]
![捕获](https://user-images.githubusercontent.com/74532673/101114460-7aabdd80-361c-11eb-9250-9281aac00f06.PNG)
页面network中显示js与请求状态都是200

**Comment by yangzhe09** [comment]
![image](https://user-images.githubusercontent.com/74532673/101114364-46382180-361c-11eb-88f8-0633c10f457b.png)

**Comment by xiaoymin** [comment]
页面JS没报错吗

**Comment by yangzhe09** [comment]
> 页面JS没报错吗
js没有报错

**Comment by yangzhe09** [comment]
![捕获](https://user-images.githubusercontent.com/74532673/101114595-c78fb400-361c-11eb-8c17-e043ce7f3001.PNG)

**Comment by xiaoymin** [comment]
对照这篇去分析

https://xiaoym.gitee.io/knife4j/faq/knife4j-exception.html

**Comment by yangzhe09** [comment]
![捕获](https://user-images.githubusercontent.com/74532673/101114902-5f8d9d80-361d-11eb-8f91-2c82a4bf40a6.PNG)
![捕获](https://user-images.githubusercontent.com/74532673/101114945-73390400-361d-11eb-9dad-369ce98bccdf.PNG)
![捕获](https://user-images.githubusercontent.com/74532673/101115003-8ba91e80-361d-11eb-97ae-3b92754cbb5c.PNG)
目前来看js等都是正常的

**Comment by yangzhe09** [comment]
![捕获](https://user-images.githubusercontent.com/74532673/101115122-cc089c80-361d-11eb-918e-b0db03c551a2.PNG)

**Comment by xiaoymin** [comment]
什么错误都没有的话，很难排查

**Comment by yangzhe09** [comment]
呜呜.... 我之前以为是浏览器兼容问题，可是换了好几个浏览器，依旧是这样，那Knide4j可以和原生swagger2 共同使用吗？

**Comment by xiaoymin** [comment]
两个对外提供的路径不一样，是可以兼容共同使用的
