### ISSUE TITLE
如何修改 knife4j接口文档首页的basePath地址

### ISSUE THREAD

**Issue by xupengjun** [xiaoymin/knife4j#293]
![1607391653(1)](https://user-images.githubusercontent.com/20333917/101427283-8f98b180-3939-11eb-863a-f465b834fd5c.png)

**Comment by xupengjun** [comment]
我使用的是springboot 2.3.5和knife4j-spring-boot-starter-3.0.2版本

**Comment by xiaoymin** [comment]
Spring Boot不是可以配置servlet.context-path么

**Comment by xupengjun** [comment]
我配置了这个server.servlet.context-path=/api/,但是在这里首页没有在basePath展示呢
![1607392621(1)](https://user-images.githubusercontent.com/20333917/101428481-c40d6d00-393b-11eb-8bea-896f2259b8ae.png)
![1607392608(1)](https://user-images.githubusercontent.com/20333917/101428485-c53e9a00-393b-11eb-8dd0-a9c95494704a.png)

**Comment by xiaoymin** [comment]
在OpenAPI3的规范定义中，根本没有basePath的概念了，这是OpenAPI2里面的概念，这个你可以去看你的接口/v3/api-docs返回的JSON内容里面，没有basePath属性

**Comment by xupengjun** [comment]
是的，我看到是没有属性了，但是首页页面还有这个属性展示，但是还没有修改的地方呢

**Comment by xiaoymin** [comment]
没改，目前以v2稳定版为主，因为springfox3 bug不少，这个v3版本是一个兼容的过程，很漫长

https://xiaoym.gitee.io/knife4j/documentation/changelog.html

**Comment by xupengjun** [comment]
那在文最后一个问题吧，我项目启动的时候，控制台打印了好多我的接口信息，我看都是springfox-shcma包中这个类打印的，我把这个类排除了，还不能启动了，就没有排除，打印信息如下，如何关闭这个打印信息
![image](https://user-images.githubusercontent.com/20333917/101429408-d7b9d300-393d-11eb-886f-2caf6e97c634.png)

**Comment by xiaoymin** [comment]
这个不是很简单么，日志框架里面过滤级别改一下就是了

**Comment by xupengjun** [comment]
不是的，我同一个日志配置文件，在两个不同的项目中，打印出来结果不一样

**Comment by xiaoymin** [comment]
那这个应该是你日志框架是否生效的问题
