### ISSUE TITLE
2.0.8版本，增强模式下，setting下的设置都不生效

### ISSUE THREAD

**Issue by ZhiQinIsZhen** [xiaoymin/knife4j#294]
knife4j.setting.enableSwaggerModels=true
knife4j.setting.enableDocumentManage=false
knife4j.setting.enableHomeCustom=true
knife4j.setting.enableFooterCustom=true
knife4j.setting.footerCustomContent=Apache License 2.0 | Copyright  2020-[xxxx科技有限公司](http://https://gitee.com/xiaoym/knife4j)

这几个配置配置了之后感觉都没有起到作用

**Comment by xiaoymin** [comment]
仔细看每篇文档，看全，不要只看开头而忘了结尾

https://xiaoym.gitee.io/knife4j/documentation/customFooter.html

**Comment by ZhiQinIsZhen** [comment]
soga，感谢老哥
