### ISSUE TITLE
返回结果为一个html地址时，会报错Network Error

### ISSUE THREAD

**Issue by taotaoing** [xiaoymin/knife4j#296]
**返回结果为一个html地址时，会报错Network Error**
![image](https://user-images.githubusercontent.com/53855530/102679761-1167c500-41ed-11eb-8925-51921135e665.png)
**但是postman这类工具是可以正常显示的**
![image](https://user-images.githubusercontent.com/53855530/102679771-27758580-41ed-11eb-9057-75ceba8384c4.png)

**代码返回逻辑：**
![image](https://user-images.githubusercontent.com/53855530/102679846-c69a7d00-41ed-11eb-9eb1-588d70ed4cc8.png)

**swagger版本：2.9.2
knife4j版本：2.0.4
springboot版本：2.0.5.RELEASE**

**Comment by xiaoymin** [comment]
针对后端重定向，因为浏览器有跨域的限制，而postman没有

**Comment by taotaoing** [comment]
你好, 信件已经收到, 我会尽快处理, 谢谢。
