### ISSUE TITLE
入参排序能够更改吗 

### ISSUE THREAD

**Issue by ct850230163** [xiaoymin/knife4j#297]
每个入参对象里面属性都必须@ApiModelProperty上面加上position来进行排序 不然默认是按照acsii码来排序的 能够默认按照属性的顺序来排序吗？

**Comment by xiaoymin** [comment]
从问题进行分析：
1、springfox解析类时，是根据反射获取当前类的属性成员的，既然是反射，你可以想象一下这个属性的顺序还能有保证吗？
2、OpenAPI的规范里面我目前好像并没有发现position这个字段规范
