### ISSUE TITLE
MacBook Pro15款，分辨率(2560 × 1600)，版本2.0.8，调试接口发送按钮适配问题

### ISSUE THREAD

**Issue by heliangtmac** [xiaoymin/knife4j#298]
MacBook Pro15款，分辨率(2560 × 1600)，版本2.0.8，调试接口发送按钮适配问题

<img width="925" alt="image" src="https://user-images.githubusercontent.com/26305901/103199120-17645100-4925-11eb-92b2-450fe70d15af.png">
<img width="832" alt="image" src="https://user-images.githubusercontent.com/26305901/103199134-1f23f580-4925-11eb-9b9f-739332cbe999.png">

**Comment by xiaoymin** [comment]
没法测试，在[v4.0快照版本](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)里面，我调整了地址输入框的长度(80% -> 70%)，可以试试看，这个issue我就先关了,有问题再新开一个，感谢
