### ISSUE TITLE
ApiOperationSupport注解排序无效

### ISSUE THREAD

**Issue by Kevintian77585** [xiaoymin/knife4j#299]
不管是用什么版本，都试过了，注解ApiOperationSupport中的order属性就是不生效，springboot使用的是2.2.10，
![image](https://user-images.githubusercontent.com/28503719/103528066-4dbe4500-4ebe-11eb-921f-1e44bf43b5fe.png)

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/master/knife4j-spring-boot-demo

demo你可以下载下来运行参考一下
