### ISSUE TITLE
对象参数展示解析问题

### ISSUE THREAD

**Issue by rbfw** [xiaoymin/knife4j#3]
swagger-ui.html是这样的
{
  "token": "string",
  "userInfo": {
    "email": "string",
    "emailBinding": "string",
    "encryMode": "string",
    "faviconFileId": "string",
    "id": 0,
    "identityFileId": "string",
    "identityNum": "string",
    "identityType": "string",
    "isDeleted": "string",
    "mobile": "string",
    "mobileBinding": "string",
    "nickname": "string",
    "oldId": 0,
    "oldusername": "string",
    "orgCode": "string",
    "orgCodes": "string",
    "orgId": 0,
    "orgIds": "string",
    "orgName": "string",
    "password": "string",
    "salt": "string",
    "sex": "string",
    "sysCode": "string",
    "tel": "string",
    "trueName": "string",
    "trueNameEn": "string",
    "username": "string",
    "verifyStatus": "string"
  }
}
Swagger-Bootstrap-UI是这样的：
{
    "token":"",
    "userInfo":""//这是一个对象，里面的属性就出不来了
}

**Comment by xiaoymin** [comment]
你好，使用最新版本1.7.7的 ，欢迎升级反馈，谢谢：）
