### ISSUE TITLE
控制层无法接收form表单格式的请求参数

### ISSUE THREAD

**Issue by lei911gang** [xiaoymin/knife4j#30]
查看swagger发送的请求发现，请求头的Content-Type一直为application/json，且设定全局参数后也无法对其进行修改，导致controller无法接收到参数

**Comment by xiaoymin** [comment]
能否贴一下controller层这个接口的代码

**Comment by xiaoymin** [comment]
还有接口参数等

**Comment by lei911gang** [comment]
@PostMapping("/query")
public HsResult query(AuthorityAllot authorityAllot, Integer page, Integer rows) {
    if (null == page || page < 0) {
        page = 1;
    }
    if (null == rows || rows < 0) {
        rows = 10;
    }
    Page<AuthorityAllot> authorityAllotPage = this.authorityAllotService.selectPage(new Page<>(page, rows), new EntityWrapper<>(authorityAllot));
    return HsResult.build(CommonConstants.SUCCESS_CODE, CommonConstants.SUCCESS_MESSAGE, authorityAllotPage);
}



lei911gang@vip.qq.com
 
发件人： xiaoymin
发送时间： 2018-09-18 16:23
收件人： xiaoymin/Swagger-Bootstrap-UI
抄送： lei911gang; Author
主题： Re: [xiaoymin/Swagger-Bootstrap-UI] 控制层无法接收form表单格式的请求参数 (#30)
能否贴一下controller层这个接口的代码

**Comment by xiaoymin** [comment]
1.8.4 版本已解决 试试吧
