### ISSUE TITLE
能不能新增复制完整接口(例如：http://localhost:8080/login)的功能，现在好像只能复制（/login）这样的局部接口

### ISSUE THREAD

**Issue by DY-YLS** [xiaoymin/knife4j#300]
能不能新增复制完整接口(例如：http://localhost:8080/login)的功能，现在好像只能复制（/login）这样的局部接口

**Comment by DY-YLS** [comment]
![捕获](https://user-images.githubusercontent.com/46810227/103554899-95f35c80-4eea-11eb-8abc-cba75d271e0f.JPG)

**Comment by xiaoymin** [comment]
这个我觉得没什么必要吧，一般host+端口 全局配置一下就好了，不知道要复制这个干嘛？
