### ISSUE TITLE
setting中的配置不生效

### ISSUE THREAD

**Issue by caidingnu** [xiaoymin/knife4j#304]
版本：2.0.8
springboot版本：2.2.0.RELEASE
配置如下：
knife4j:
  # 开启增强配置
  enable: true
  setting:
    enableDynamicParameter: true
    enableVersion: true
    enableReloadCacheParameter: true
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Apache License 2.0 | Copyright  XXXX

如上配置之后，footer还是默认的

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/knife4j/documentation/customFooter.html

文档读一半是不行的，仔细读三遍

实在不行，demo下载下来运行一下
https://doc.xiaominfo.com/knife4j/documentation/simple-demo.html
