### ISSUE TITLE
发送按钮不显示

### ISSUE THREAD

**Issue by acemma** [xiaoymin/knife4j#305]
![微信图片_20210114112502](https://user-images.githubusercontent.com/26995850/104540853-4f74cf00-565b-11eb-8be7-576aa14a52aa.png)
Spring Boot v2.1.18.RELEASE
swagger：2.8.0
swagger-bootstrap-ui：1.9.6
Chrome： 87.0.4280.141

**Comment by xiaoymin** [comment]
你设置了UiConfiguration吧， 配置了支持调试的类型，supportMethod

另外你这个版本有点老了，都发布到2.0.8了

**Comment by acemma** [comment]
修改了swagger版本，可以了
