### ISSUE TITLE
Swagger Models静态匿名内部类

### ISSUE THREAD

**Issue by wzhw0v0** [xiaoymin/knife4j#309]
版本： <version>3.0.2.version>或<version>2.0.8</version>
问题:实体对象使用匿名静态匿名内部类，无法在Swagger Models展示
代码：@Data
@ApiModel(description = " 数据分类标签对象")
public class DataClassTabRequestObject {

    private DataClassTabListObject DataClassTabListObject;

    @Data
    public static class DataClassTabListObject {
        private List<DataClassTab> DataClassTabObject;
    }

    @Data
    public static class DataClassTab {
        @ApiModelProperty(value = "标签标识 21-22 位取 05表示人脸库,06 人员库,07 机动车库,08 非机动车库,09 物品库,10 场景库")
        private String TabID;
        @ApiModelProperty(value = "标签名称")
        private String TabName;
        @ApiModelProperty(value = "标签说明")
        private String Description;
        @ApiModelProperty(value = "是否是已知身份标签 0：已知身份 1：未知身份")
        private Boolean IsAffirmed;
    }
}

**Comment by xiaoymin** [comment]
无法识别内部类的话，这个要去springfox里面提了，解析规则是引用的springfox项目
