### ISSUE TITLE
能否支持个性化的外部地址？

### ISSUE THREAD

**Issue by lephix** [xiaoymin/knife4j#31]
希望能够个性化host，port，/swagger-resources和/v2/api-docs的地址。 
这样可以根据外部传入的参数，让一套ui程序，适应多个后台的文档。

**Comment by ousui** [comment]
同意，也就是像官方 swagger-ui 一样，将前后端分离。

**Comment by xiaoymin** [comment]
> 同意，也就是像官方 swagger-ui 一样，将前后端分离。

分离的版本已经分离出来了，可以看看文档http://www.xiaominfo.com/swagger-bootstrap-ui/ui-front.html

**Comment by ousui** [comment]
> > 同意，也就是像官方 swagger-ui 一样，将前后端分离。
> 
> 分离的版本已经分离出来了，可以看看文档http://www.xiaominfo.com/swagger-bootstrap-ui/ui-front.html

棒棒哒

**Comment by xiaoymin** [comment]
front版本太难用了，可以使用Google的扩展程序，在应用商店就能搜索安装
![image](https://user-images.githubusercontent.com/7894406/58074764-9a191c00-7bd8-11e9-8895-19b2e5768c5d.png)

https://www.oschina.net/news/106825/swagger-boostrap-ui-1-0-0-released
