### ISSUE TITLE
swagger2 api中多个接口，文档中统计接口个数怎么去掉，看着怪难受的

### ISSUE THREAD

**Issue by liuwenya1234** [xiaoymin/knife4j#311]
![image](https://user-images.githubusercontent.com/14358709/111742342-fc213600-88c2-11eb-8266-6be2e5c9f839.png)
swagger2 api中多个接口，文档中统计接口个数怎么去掉，看着怪难受的
图片中标红的地方怎么设置隐藏

**Comment by xiaoymin** [comment]
无法满足每个人口味，你不喜欢的 ，可能别人正需要
