### ISSUE TITLE
非网关方式聚合后，发送请求路径不对

### ISSUE THREAD

**Issue by parkerisme** [xiaoymin/knife4j#312]
非网关聚合参考：https://github.com/varghgeorge/microservices-single-swagger
经测试：
1.<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.5</version>
        </dependency>
当聚合的项目springboot中设置了contextpath，比如contextpath为servicecap，doc.html中看到的接口路径为：/servicecap/servicecap/apiDetail/list会多出来一个contextpath，并且http://ip:port部分也不对，不是具体的服务路径

2.0.8中contextpath不存在问题。但是http://ip:port部分也不对

原生swagger无问题。

**Comment by xiaoymin** [comment]
贴图说明之

**Comment by xiaoymin** [comment]
可以升级下版本试试，或者用[4.0快照](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)版本试试，这个issue我就先关闭了，有问题再新开一个，感谢
