### ISSUE TITLE
access 127.0.0.1:port/doc.html return 404

### ISSUE THREAD

**Issue by littleCherryYo** [xiaoymin/knife4j#316]
why I add configurations “spring.mvc.static-path-pattern“ and “spring.resources.static-locations” in application.yml,  then access 127.0.0.1:port/doc.html return 404

**Comment by xiaoymin** [comment]
Spring MVC:  https://xiaoym.gitee.io/knife4j/faq/springmvc-404.html

Spring Boot:  https://xiaoym.gitee.io/knife4j/faq/springboot-404.html

**Comment by littleCherryYo** [comment]
> Spring MVC: https://xiaoym.gitee.io/knife4j/faq/springmvc-404.html
> 
> Spring Boot: https://xiaoym.gitee.io/knife4j/faq/springboot-404.html

well done.
thanks
