### ISSUE TITLE
有没有单独设置某个接口的版本的

### ISSUE THREAD

**Issue by lianbitangjin** [xiaoymin/knife4j#317]

**Comment by xiaoymin** [comment]
没明白你想表达什么

**Comment by lianbitangjin** [comment]
> 没明白你想表达什么

你好，我详细描述一下，就是能不能设置某一个接口controller 的版本，现在是设置全局的版本，如果之前设置的1.0，现在1.1我只修改了其中一个接口，我想让前端知道原来的老版本里哪个接口更新版本了，请问有没有这样的实现

**Comment by xiaoymin** [comment]
> > 没明白你想表达什么
> 
> 你好，我详细描述一下，就是能不能设置某一个接口controller 的版本，现在是设置全局的版本，如果之前设置的1.0，现在1.1我只修改了其中一个接口，我想让前端知道原来的老版本里哪个接口更新版本了，请问有没有这样的实现

没有
