### ISSUE TITLE
作者：您好！现在对于字符串类型的如果Swagger不传值的时候，默认的是“”，但是我想他默认的是null。这种怎么解决呀

### ISSUE THREAD

**Issue by beifeng15** [xiaoymin/knife4j#325]

**Comment by xiaoymin** [comment]
这个目前是没有设置的，有些人想默认“”

**Comment by beifeng15** [comment]
因为这种默认是“”,在使用MybatisPlus进行SQL语句解析的时候，就会默认成查询条件了。这种应该怎么处理呀

**Comment by xiaoymin** [comment]
你用的是什么版本，我看现在如果是空的参数没填值的，请求里面都不包含该参数

**Comment by xiaoymin** [comment]
http://knife4j.xiaominfo.com/doc.html#/2.X%E7%89%88%E6%9C%AC/2.0.6%E7%89%88%E6%9C%AC-20200919/reqJsonUsingPOST_1

**Comment by xiaoymin** [comment]
有些类型的是没有，有些类型确实存在“”

**Comment by xiaoymin** [comment]
> 因为这种默认是“”,在使用MybatisPlus进行SQL语句解析的时候，就会默认成查询条件了。这种应该怎么处理呀

这种业务判断在代码逻辑里面也要判断的吧
