### ISSUE TITLE
关于 Cloud 聚合模式下，是否目前没有支持动态更新路由

### ISSUE THREAD

**Issue by LeoAshin** [xiaoymin/knife4j#337]
由于眼拙，暂时没有找到knife4j-aggregation-spring-boot-starter包的source code。
就目前从 maven下看源代码， 貌似不支持路由的动态更新。
因为目前这边想满足在不基于注册中心的情况下实现路由动态刷新

**Comment by xiaoymin** [comment]
源码在[gitee的v2分支](https://gitee.com/xiaoym/knife4j/tree/v2/knife4j/knife4j-aggregation-spring-boot-starter)里面，动态路由刷新目前确实没有做，有兴趣的话可以提交一个PR

**Comment by xiaoymin** [comment]
用aggregation来做动态刷新的话有点麻烦，因为这是一个依附于Spring Boot的组件，服务发布后，一般不动，要做的话也只能基于配置中心来做了

[desktop](https://xiaoym.gitee.io/knife4j/resources/desktop-introduction.html)是基于本地文件配置的，如果本地文件配置更新后，会动态更新

**Comment by LeoAshin** [comment]
行，有源码就比较好办一点， 谢啦。 如果顺利 PR 再见
