### ISSUE TITLE
在线调试，如果请求参数很长，看不见返回结果

### ISSUE THREAD

**Issue by lwydyby** [xiaoymin/knife4j#34]
![default](https://user-images.githubusercontent.com/30611869/46722196-88b57c00-cca7-11e8-8db7-f19de42cb715.jpg)
如果我调小界面才能显示出来
![default](https://user-images.githubusercontent.com/30611869/46722258-aedb1c00-cca7-11e8-8921-8ca1b7f950b1.jpg)

**Comment by xiaoymin** [comment]
184版本 确实存在这个问题
参数过多，导致下面的无法显示，因为设置了定长。下个版本会优化改进这个问题的，感谢反馈

**Comment by xiaoymin** [comment]
1.8.5版本已经发布了，解决了该问题，欢迎升级

**Comment by lwydyby** [comment]
嗯可以了，不过排版还是有点问题，能优化下就更好了
![default](https://user-images.githubusercontent.com/30611869/47147571-242a9a80-d301-11e8-8e99-bb7ebe93d82d.png)

**Comment by xiaoymin** [comment]
> 嗯可以了，不过排版还是有点问题，能优化下就更好了
> ![default](https://user-images.githubusercontent.com/30611869/47147571-242a9a80-d301-11e8-8e99-bb7ebe93d82d.png)

使用的什么浏览器？建议用chrome，其他浏览器没测过
