### ISSUE TITLE
排版还是有点问题，如果能优化下就更好了

### ISSUE THREAD

**Issue by lwydyby** [xiaoymin/knife4j#35]
![default](https://user-images.githubusercontent.com/30611869/47147571-242a9a80-d301-11e8-8e99-bb7ebe93d82d.png)

_Originally posted by @lwydyby in https://github.com/xiaoymin/Swagger-Bootstrap-UI/issue_comments#issuecomment-430953326_

**Comment by xiaoymin** [comment]
是什么浏览器呢

**Comment by lwydyby** [comment]
chrome

**Comment by xiaoymin** [comment]
这就很奇怪了，http://swagger-bootstrap-ui.xiaominfo.com/doc.html

这个demo在chrome下是正常的额

**Comment by lwydyby** [comment]
会不会是我的返回结构中包含多个集合，并且有的集合中还含有集合，结构太复杂了导致的

**Comment by lwydyby** [comment]
![f sjaeq o8nv5tc4 pfbwx](https://user-images.githubusercontent.com/30611869/47210233-fe66c980-d3c4-11e8-9ee7-4241fcee40ab.png)
从第三个开始出错的

**Comment by xiaoymin** [comment]
> 会不会是我的返回结构中包含多个集合，并且有的集合中还含有集合，结构太复杂了导致的

在demo里面  API注释-请求参数多层

这个接口也是多层的

**Comment by lwydyby** [comment]
我这个参数太长了吗，我拖了下宽度就正常了，好像是集合这种也需要个长度过长隐藏

**Comment by xiaoymin** [comment]
> 我这个参数太长了吗，我看demo里会省略号隐藏，为什么我这个没隐藏

要么你这几个实体类发我一些，我测测看

邮箱：xiaoymin@foxmail.com

**Comment by xiaoymin** [comment]
> 我这个参数太长了吗，我拖了下宽度就正常了，好像是集合这种也需要个长度过长隐藏

应该是这个参数太长的原因，我在新版中对table表格使用的是不换行策略（因为layui的省略号会让这个浮层一直存在），我demo没更新上去。。

**Comment by xiaoymin** [comment]
导致新问题产生了

**Comment by xiaoymin** [comment]
1.8.6 已发布，已解决此问题
