### ISSUE TITLE
request mapping 中地址不支持path参数，只支持value，可否增加path参数的支持

### ISSUE THREAD

**Issue by yiminyangguang520** [xiaoymin/knife4j#36]
1、request mapping 中地址不支持path参数，只支持value，可否增加path参数的支持？
2、请求参数为实体类对象时，如果实体类中有验证注解，可否增加对JSR-303 annotations 注解的支持

**Comment by xiaoymin** [comment]
> 1、request mapping 中地址不支持path参数，只支持value，可否增加path参数的支持？
> 2、请求参数为实体类对象时，如果实体类中有验证注解，可否增加对JSR-303 annotations 注解的支持

可否详细贴一下相关代码？

**Comment by yiminyangguang520** [comment]
问题1：

**Comment by yiminyangguang520** [comment]
问题1：请求路径中为path时，会报数组越界，换成value后就可以了
![2018-10-19_091216](https://user-images.githubusercontent.com/7455230/47192359-5844a080-d37f-11e8-8b40-b2cd72951244.png)
问题2：
![2018-10-19_091517](https://user-images.githubusercontent.com/7455230/47192464-0fd9b280-d380-11e8-9d65-c21e1edd05cf.png)
上图对实体类校验
![2018-10-19_091817](https://user-images.githubusercontent.com/7455230/47192476-19631a80-d380-11e8-9a7c-a8960d8f7d58.png)
上图是实体类中一个属性的校验
![2018-10-19_091750](https://user-images.githubusercontent.com/7455230/47192483-25e77300-d380-11e8-8741-ed5ee1366310.png)
上图是原生的swagger中显示效果
Swagger-Bootstrap-UI能否支持这种显示效果呢？

**Comment by xiaoymin** [comment]
> 问题1：请求路径中为path时，会报数组越界，换成value后就可以了
> ![2018-10-19_091216](https://user-images.githubusercontent.com/7455230/47192359-5844a080-d37f-11e8-8b40-b2cd72951244.png)
> 问题2：
> ![2018-10-19_091517](https://user-images.githubusercontent.com/7455230/47192464-0fd9b280-d380-11e8-9d65-c21e1edd05cf.png)
> 上图对实体类校验
> ![2018-10-19_091817](https://user-images.githubusercontent.com/7455230/47192476-19631a80-d380-11e8-9a7c-a8960d8f7d58.png)
> 上图是实体类中一个属性的校验
> ![2018-10-19_091750](https://user-images.githubusercontent.com/7455230/47192483-25e77300-d380-11e8-8741-ed5ee1366310.png)
> 上图是原生的swagger中显示效果
> Swagger-Bootstrap-UI能否支持这种显示效果呢？

好的 ，非常感谢~

**Comment by xiaoymin** [comment]
@yiminyangguang520  这个path不支持是使用增强排序 才不支持的吧？

**Comment by yiminyangguang520** [comment]
@xiaoymin 说的是@EnableSwaggerBootstrapUI这个注解开启增强排序吗？这个注解我是加了的，其他的没有

**Comment by xiaoymin** [comment]
> @xiaoymin 说的是@EnableSwaggerBootstrapUI这个注解开启增强排序吗？这个注解我是加了的，其他的没有

前台个性化配置里面 保存了吧？如果保存后，path这个属性我刚刚调试了，确实没判断作支持，

**Comment by yiminyangguang520** [comment]
保存了

发自我的 iPhone

**Comment by yiminyangguang520** [comment]
@xiaoymin 前台个性化配置里面确实保存了，另外第二个问题能否考虑支持一下？

**Comment by xiaoymin** [comment]
> @xiaoymin 前台个性化配置里面确实保存了，另外第二个问题能否考虑支持一下？

好的，下个版本会集成进去，有更多的问题也非常欢迎反馈过来

**Comment by xiaoymin** [comment]
第一个path属性新版本1.8.6已经支持，第二个JSR-303 annotations 注解的支持还没有，1.8.7 版本将集成进去

**Comment by yiminyangguang520** [comment]
> 第一个path属性新版本1.8.6已经支持，第二个JSR-303 annotations 注解的支持还没有，1.8.7 版本将集成进去

好的，非常感谢！

**Comment by xiaoymin** [comment]
@yiminyangguang520 你好，1.8.7版本已经支持了JSR-303 annotations 的部分注解

但是目前的显示方式是鼠标悬停显示，如果有更好的展示方式的话 我们可以沟通一下

1.8.7新闻https://www.oschina.net/news/101720/swagger-bootstrap-ui-1-8-7-released

预览地址：http://swagger-bootstrap-ui.xiaominfo.com/doc.html

预览菜单：
 api-1871-controller -> @Valid注解

**Comment by yiminyangguang520** [comment]
> 
> 
> @yiminyangguang520 你好，1.8.7版本已经支持了JSR-303 annotations 的部分注解
> 
> 但是目前的显示方式是鼠标悬停显示，如果有更好的展示方式的话 我们可以沟通一下
> 
> 1.8.7新闻https://www.oschina.net/news/101720/swagger-bootstrap-ui-1-8-7-released
> 
> 预览地址：http://swagger-bootstrap-ui.xiaominfo.com/doc.html
> 
> 预览菜单：
> api-1871-controller -> @Valid注解

好的，谢谢支持!!!，另外感觉新增Swagger Models菜单项功能，点击model属性时，会有一点卡顿

**Comment by xiaoymin** [comment]
> > @yiminyangguang520 你好，1.8.7版本已经支持了JSR-303 annotations 的部分注解
> > 但是目前的显示方式是鼠标悬停显示，如果有更好的展示方式的话 我们可以沟通一下
> > 1.8.7新闻https://www.oschina.net/news/101720/swagger-bootstrap-ui-1-8-7-released
> > 预览地址：http://swagger-bootstrap-ui.xiaominfo.com/doc.html
> > 预览菜单：
> > api-1871-controller -> @Valid注解
> 
> 好的，谢谢支持!!!，另外感觉新增Swagger Models菜单项功能，点击model属性时，会有一点卡顿

这个已经使用async异步加载了。。。感觉效率已经到极限了

使用async异步创建table，但是table并没有赋值，而是在详细点开的时候初始化treetable

所以可能Models太多了。。不过应该还是可以忍受的吧。。
