### ISSUE TITLE
xml格式放回，示例是json的

### ISSUE THREAD

**Issue by spacestime** [xiaoymin/knife4j#360]
xml格式放回，示例是json的

**Comment by spacestime** [comment]
![image](https://user-images.githubusercontent.com/17666651/123632532-9f7ed100-d84a-11eb-8a51-4276edbcc8b1.png)

**Comment by spacestime** [comment]
![image](https://user-images.githubusercontent.com/17666651/123632838-fbe1f080-d84a-11eb-99db-5610fb67e252.png)

**Comment by xiaoymin** [comment]
![image](https://user-images.githubusercontent.com/7894406/123720537-e1ddf780-d8b6-11eb-9c88-a8f41538559f.png)

**Comment by xiaoymin** [comment]
代码里有指定响应类型吗？

**Comment by spacestime** [comment]
![image](https://user-images.githubusercontent.com/17666651/123722579-34211780-d8bb-11eb-88ba-b25b7bca0663.png)

**Comment by xiaoymin** [comment]
响应示例 用xml这个 还真不好搞，用xml的话，字段的说明都没法显示了
