### ISSUE TITLE
作者您好，请教关于调试页面outputstream图片流乱码问题。

### ISSUE THREAD

**Issue by YanisSong** [xiaoymin/knife4j#362]
<groupId>com.github.xiaoymin</groupId>
<artifactId>knife4j-spring-boot-starter</artifactId>
<version>3.0.2</version>
以上为依赖版本；
接口定义如下：
![图片](https://user-images.githubusercontent.com/12448134/124216361-b3675300-db28-11eb-916a-c26ecaf04d02.png)
工程中添加处理图片流转换器：converters.add(new BufferedImageHttpMessageConverter());
接口返回为 httpserverletresponse，outputsteam中为图片数据，调试页面显示为乱码，原swagger页面可以正常显示。
目前页面显示如下：
![图片](https://user-images.githubusercontent.com/12448134/124214381-b2ccbd80-db24-11eb-80b1-3bfc1b3722f8.png)

**Comment by xiaoymin** [comment]
服务端写一个header出来吧

response.addHeader("Content-Type","image/png")
