### ISSUE TITLE
AfterScript中使用全局变量ke，ke not define error

### ISSUE THREAD

**Issue by LelandACM** [xiaoymin/knife4j#364]
在XMLHttpRequest()中，调用成功后，设置token , 使用`ke.global.setAllHeader(XXX)` ,提示`ke not define` ,是还需要引入什么？
示例
![image](https://user-images.githubusercontent.com/19402747/124697589-9b714400-df19-11eb-9355-f3e7d10d8678.png)
错误提示
![image](https://user-images.githubusercontent.com/19402747/124697629-b3e15e80-df19-11eb-8458-82e205a37ee8.png)

**Comment by xiaoymin** [comment]
仅限在knife4j的界面中使用

**Comment by LelandACM** [comment]
@xiaoymin 那如果我想把登录后的token设置到全局如何做？ 请求还要复制一下token怪麻烦的

**Comment by xiaoymin** [comment]
我是没搞懂你的流程，如果是你自己写代码的，对接接口，用knife4j提供的这个干嘛，那完全是你自己的事情了

如果只是想在knife4j提供的界面中进行接口调试，afterScript里面的文档介绍也提供了使用文档了

**Comment by LelandACM** [comment]
@xiaoymin 我的的登录接口使用的是spring security内置的，这样的话，在使用的的knife4j调用接口之前还要用其他的方法先获取到token登录后，其他的接口才能调用， 因为controller里面没有login函数

**Comment by GitACDreamer** [comment]
@xiaoymin 我的的登录接口使用的是spring security内置的，这样的话，在使用的的knife4j调用接口之前还要用其他的方法先获取到token登录后，其他的接口才能调用， 因为controller里面没有login函数
