### ISSUE TITLE
动态 Json 参数问题

### ISSUE THREAD

**Issue by yihuishou** [xiaoymin/knife4j#365]
运行环境：

spring-boot 2.3.4 knife4j-spring-boot-starter 3.0.3

问题：

APIModel 有多个属性

接口正常使用@RequestBody 对象，但是每个接口只需要使用 APIModel 中不同的几个属性作为参数，但是文档上返回了全部属性，想要在接口上屏蔽掉不需要显示的属性。（并不是全局屏蔽）

解决想法：

1. 定义一堆DTO
2. 使用HashMap + 增强版 @DynamicParameter

3. **使用对象** + @ApiIgnore + @DynamicParameter 可以覆盖掉原有的对象

不知道如何能实现第三种方式，或者 @DynamicParameter 可以增加一个覆盖选项

Bug：屏蔽参数后格式不正确
![Snipaste_2021-07-16_11-39-45](https://user-images.githubusercontent.com/26241263/125888603-66e87db1-7299-4ef3-b664-ccbcc86b8d66.png)

![Snipaste_2021-07-16_11-40-25](https://user-images.githubusercontent.com/26241263/125888471-48db7d9a-dd92-44f8-935d-b731f3c923fc.png)

![Snipaste_2021-07-16_11-41-19](https://user-images.githubusercontent.com/26241263/125888617-c0acbae3-0039-4f8a-9536-3d8a64056900.png)

**Comment by xiaoymin** [comment]
写实体类吧，这个注解随着深入兼容成本越来越高了，后期版本不在提供支持了
