### ISSUE TITLE
能否支持调试spring webflux 的 rest api?

### ISSUE THREAD

**Issue by gy0801151351** [xiaoymin/knife4j#37]

**Comment by xiaoymin** [comment]
这个只支持springfox-swagger的。。

spring webflux不熟哦。。没使用过

**Comment by gy0801151351** [comment]
可能我没说清楚，我的情况是，你的这个项目，用spring boot mvc可以正常启动，用spring boot webflux 就启动报错。就是springboot 2.0，把容器由tomcat的servlet替换为tomcat的reactive。因为我现在的项目是用spring boot webflux, 所以希望能找到一个能支持这种框架的测试和文档工具.

**Comment by xiaoymin** [comment]
> 可能我没说清楚，我的情况是，你的这个项目，用spring boot mvc可以正常启动，用spring boot webflux 就启动报错。就是springboot 2.0，把容器由tomcat的servlet替换为tomcat的reactive。因为我现在的项目是用spring boot webflux, 所以希望能找到一个能支持这种框架的测试和文档工具.

那暂时是不支持的
