### ISSUE TITLE
uncaught SyntaxError: Unexpected string in JSON at position

### ISSUE THREAD

**Issue by DemoMeng** [xiaoymin/knife4j#377]
前台console控制台显示 ： uncaught SyntaxError: Unexpected string in JSON at position
接口的DTO均是正常的

**Comment by DemoMeng** [comment]
奇怪的是swagger-ui.html入口进去的文档不会有这个异常

**Comment by DemoMeng** [comment]
![image](https://user-images.githubusercontent.com/22184109/129682068-cd0392c6-5f8b-4abe-b944-6e26fd38898d.png)
swagger:2.9.2
swagger-bootstrap-ui: 1.8.5

**Comment by xiaoymin** [comment]
https://xiaoym.gitee.io/knife4j/faq/swaggerResourceInvalid.html#json%E6%A0%BC%E5%BC%8F%E9%9D%9E%E6%B3%95

**Comment by DemoMeng** [comment]
没有设置 example属性的情况呢？

**Comment by DemoMeng** [comment]
![image](https://user-images.githubusercontent.com/22184109/129695237-bb3b059d-5a04-4d15-9730-164f5dda3dc3.png)
是否跟返回数据结构层级也有关系 ？

**Comment by xiaoymin** [comment]
你可以把你的json拿出来 用一个json格式化工具格式化一下，报错是通过JSON.parse方法抛出的错误，说明这个JSON是非法的

**Comment by DemoMeng** [comment]
问题已经找到了是因为另外一个java同事使用 exmpale 属性不规范，现准备杀了他祭天！！
ps：要是能做个编译检查或前端给出提示就完美了

**Comment by xiaoymin** [comment]
> 问题已经找到了是因为另外一个java同事使用 exmpale 属性不规范，现准备杀了他祭天！！
> ps：要是能做个编译检查或前端给出提示就完美了

不太好提示，判断不出到底是JSON的格式问题，还是不符合OpenAPI(有些情况是后端做了一层统一的封装导致)不显示文档，所以我写了一篇FAQ的文章，文章中说明的情况基本能定位到问题吧

https://xiaoym.gitee.io/knife4j/faq/knife4j-exception.html
