### ISSUE TITLE
依赖检查发现依赖低版本Jquery漏洞

### ISSUE THREAD

**Issue by zerodayZHOUXUTIAN** [xiaoymin/knife4j#378]
knife4j-spring-ui-3.0.3.jar: jquery.min.js |   | pkg:javascript/jquery@3.2.1

**Comment by zerodayZHOUXUTIAN** [comment]
jQuery before 3.4.0, as used in Drupal, Backdrop CMS, and other products, mishandles jQuery.extend(true, {}, ...) because of Object.prototype pollution. If an unsanitized source object contained an enumerable __proto__ property, it could extend the native Object.prototype.
CWE-79 Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')

**Comment by zerodayZHOUXUTIAN** [comment]
不知道哪里依赖了Jquery3.2.1,相关文件hash: c9f5aeeca3ad37bf2aa006139b935f0a

**Comment by xiaoymin** [comment]
我印象中都没有引用jquery了，我找找看

**Comment by choudewh** [comment]
同样的问题，作者何时修复呀

**Comment by xiaoymin** [comment]
没发现jquery啊

**Comment by choudewh** [comment]
knife4j-spring-ui resources webjars里面 jQuery版本3.2.1

**Comment by xiaoymin** [comment]
好，下个版本干掉

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/I5RHDE
