### ISSUE TITLE
knife4j-spring-boot-starter 大于2.0.4版本时@ApiModelProperty(required=true)失效

### ISSUE THREAD

**Issue by einsitang** [xiaoymin/knife4j#379]
我们使用的springboot版本是 `2.1.18`,查看依赖支持应该使用knife4j-spring-boot-starter `2.0.5`(最高的稳定版)，后来发现ApiModel下定义的ApiModelProperty(required=true)注解中的required在文档中不生效，但降到`2.0.4` 则可以。

我们有计划在下个季度对我们的系统springboot包括其依赖做整体的更新，届时是否也会重现这个问题？

这个问题排查和解决我们具体参考了这篇文章：https://blog.csdn.net/shaoming314/article/details/119700000

**Comment by xiaoymin** [comment]
有几种办法

1、升级SpringBoot版本到2.2.x版本以上，使用Knife4j 2.0.9版本

2、不升级SpringBoot版本，依然可以使用Knife4j的2.0.5版本，但是将2.0.5版本中的knife4j-spring-ui的依赖排除掉，单独引用2.0.9版本的ui包

更新日志(2.x使用OpenAPI2的规范，稳定版本)：https://xiaoym.gitee.io/knife4j/changelog/

**Comment by einsitang** [comment]
@xiaoymin 感谢
