### ISSUE TITLE
请问swagger2中怎么选择性的影藏参数属性

### ISSUE THREAD

**Issue by lshz0088** [xiaoymin/knife4j#38]
问题一：
比如
POST的时候不需要id属性
PUT的时候必须有id属性

问题二：
我设置了consumes=multipart/form-data
为什么还是不能multipart/form-data方式提交

tips：另外中文文档中的maven包版本没有更新，太老了

**Comment by xiaoymin** [comment]
问题一貌似没有办法

问题二 可否贴一下代码，还有UI相关截图？

**Comment by lshz0088** [comment]
问题二我知道了，不用设置consumes，直接使用springMVC的接参注解就可以用来区分了
@RequestParam    普通的form-data提交
@PathVariable       路径上的参数提交
@RequestBody     json对象提交
