### ISSUE TITLE
是否可以呈現map請求參數

### ISSUE THREAD

**Issue by faithfay** [xiaoymin/knife4j#383]
遇到了一些問題疑慮想詢問以下請求參數是否可以完整呈現
{
    "project":"project01",
    "users":[
        {
            "user1":[
                "role1"
            ]
        }
    ]
}

我使用了
@ApiOperationSupport(includeParameters = {"json.project","json.users"})

目前呈現的結果
{
  "users": [
    {}   >>>> 這邊想要完整呈現
  ],
  "project": "project01"
}

我的請求物件
private List<Map<String,Object>> users;

看了文檔目前我還是無法呈現該有的請求參數格式

**Comment by xiaoymin** [comment]
走实体吧
