### ISSUE TITLE
不使用@RequestBody  @ApiModelProperty hidden 隐藏对象属性失效

### ISSUE THREAD

**Issue by foralllove** [xiaoymin/knife4j#385]
不使用@RequestBody 导致  @ApiModelProperty hidden 隐藏对象属性失效

    @ApiModelProperty(value = "用户信息", hidden = true)
    private SysUser sysUser;
![image](https://user-images.githubusercontent.com/34620975/132650926-7d957c6b-748e-45b4-af6a-8dfccabbd730.png)

**Comment by xiaoymin** [comment]
你好，可以试一下 [4.0.0快照版本](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)，我用该版本测试是好了

参考[demo地址](https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot27-demo/src/main/java/com/knife4j/demo/new2/Job1Controller.java)
