### ISSUE TITLE
 debug页有否别禁用滚动条

### ISSUE THREAD

**Issue by zwllxs** [xiaoymin/knife4j#39]
我有个两个建议，  
1:  你的文档界面右边的滚动条能正常使用，为什么debug界面，右边滚动条要禁用呢？如果我调试时返回的json较长，查看起来超级不方便，每次我都要把返回的json复制出来用记事本查看，麻烦死了。如果不禁用滚动条，且下面的结果区域能自己调大小，就方便多了  
2:有办法支持拓展mock功能吗？

**Comment by xiaoymin** [comment]
1.8.7已改
