### ISSUE TITLE
knife4j.enable=false时不希望注册bean

### ISSUE THREAD

**Issue by Aresxue** [xiaoymin/knife4j#394]
![image](https://user-images.githubusercontent.com/22526463/138632036-ffc2666e-59b0-4f6c-87d0-5f483e6bb8b5.png)
knife4j.enable=false时@ComponentScan依然会生效，注册一些我并不需要的bean，希望能优化成只有knife4j.enable=true时@ComponentScan才生效

**Comment by xiaoymin** [comment]
感谢建议，下个版本会修复：https://gitee.com/xiaoym/knife4j/commit/d4b6c98e571e3cf144a829979cd285791c255b50

关注[v4.0计划](https://doc.xiaominfo.com/docs/v4)
