### ISSUE TITLE
与springboot3兼容问题，请问是否会有后续版本？

### ISSUE THREAD

**Issue by 0556heqing** [xiaoymin/knife4j#4]
我引入的jar为："com.github.xiaoymin:knife4j-micro-spring-boot-starter:3.0.3"。
配合 springboot 2.7.5 使用正常，但切换到 springboot 3.0.0  会提示 “Knife4j文档请求异常”。
项目报错如下：
![image](https://user-images.githubusercontent.com/24474897/208230290-8efb757e-0499-49eb-9951-4435cee1487f.png)

**Comment by xiaoymin** [comment]
目前4.0快照版本兼容了spring boot3，但是必须使用OpenAPI3规范

参考issue：https://gitee.com/xiaoym/knife4j/issues/I5LIQZ

4.0版本会近期发布

**Comment by xiaoymin** [comment]
Spring Boot 3+ OpenAPI3规范：[knife4j-spring-boot3-demo](https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/master/knife4j-spring-boot3-demo)
