### ISSUE TITLE
multipart/form-data模式下formData类型字段没有出现文件域可选

### ISSUE THREAD

**Issue by gooking** [xiaoymin/knife4j#40]
<img width="1237" alt="1" src="https://user-images.githubusercontent.com/7286469/47976156-13916700-e0ec-11e8-87ab-9b16db30b253.png">

consumes ["multipart/form-data"]
请求类型：formData

点击调试的时候，这个字段还是 input type=text 的输入框

这种情况下，能否这个字段直接显示成 input type=file 这样子调试的时候可以直接点击选择文件方便测试？

**Comment by gooking** [comment]
<img width="1326" alt="2" src="https://user-images.githubusercontent.com/7286469/47976251-84388380-e0ec-11e8-846c-fbe47b4acaab.png">

**Comment by xiaoymin** [comment]
看看这个https://gitee.com/xiaoym/swagger-bootstrap-ui/issues/IMQY9

**Comment by gooking** [comment]
就是这么设置的，1.8.6 版本，就是一个输入框，而不是文件选择按钮

**Comment by xiaoymin** [comment]
allowMultiple = true

**Comment by gooking** [comment]
我接收的不是数组，就是一个文件的，也要添加 allowMultiple = true 吗？
如果我接收的是 MultipartFile[] files ，加上 allowMultiple 可以理解
但是我接收的是 MultipartFile files ，也要加上 allowMultiple = true 页面才能显示选择文件么？

**Comment by xiaoymin** [comment]
> 我接收的不是数组，就是一个文件的，也要添加 allowMultiple = true 吗？
> 如果我接收的是 MultipartFile[] files ，加上 allowMultiple 可以理解
> 但是我接收的是 MultipartFile files ，也要加上 allowMultiple = true 页面才能显示选择文件么？

你理解的并没有错，我原以为swagger也是如此解析的，后来测试的时候，因为springfox-swagger不同的版本，针对文件上传都会出现差异，解析出来的json会产生差异，后来就强制设置这个type类型和allow参数才显示，以应对springfox-swagger的变化

**Comment by gooking** [comment]
那应该要改一下的，只要数据类型是 MultipartFile 的就应该是文件选择域
allowMultiple = true的话，页面上可以有个“＋”号，点击后又出来一行文件选择域
期待下个版本可以把这个 fix 了，因为官方的 UI ，只要是 MultipartFile 类型的就是文件选择域而不是文本输入框的

**Comment by xiaoymin** [comment]
> 那应该要改一下的，只要数据类型是 MultipartFile 的就应该是文件选择域
> allowMultiple = true的话，页面上可以有个“＋”号，点击后又出来一行文件选择域
> 期待下个版本可以把这个 fix 了，因为官方的 UI ，只要是 MultipartFile 类型的就是文件选择域而不是文本输入框的

不同的springfox-swagger版本解析出来的json，有些是不存在这个MultipartFile 类，老版本貌似是有的，现在我用的springfox-swagger2.9.2 如果不加allow属性 官方的ui也是不出来文件选择域

**Comment by xiaoymin** [comment]
最新的springfox-swagger解析出来的dataType如果后台指定MultipartFile 类型，解析出来并不是这个，而是ref
这样造成前台就无法判断了

**Comment by kenmanoy** [comment]
public class Param1{
    @ApiModelProperty(value ="身份证背面", dataType =  "MultipartFile")
    private MultipartFile idcardBack;
...
1.8.9 这样是没有作用的，也没有 allowMultiple  属性可用

**Comment by iamyuzhe** [comment]
参考这个：
https://github.com/springfox/springfox/issues/3642#issue-746303542
