### ISSUE TITLE
文件上传时使用MultipartFile类型不显示文件上传按钮。

### ISSUE THREAD

**Issue by lingyangcj** [xiaoymin/knife4j#400]
系统版本：
swagger.fox.version = 3.0.0
swagger-bootstrap-ui = 1.9.6
springboot= 2.5.6

接口如下图：
![image](https://user-images.githubusercontent.com/38120299/145002955-82fa6a67-94cc-40c2-ae16-90843f7c10d8.png)

![image](https://user-images.githubusercontent.com/38120299/145002912-e3f7bfc1-21c8-4ab3-922d-af6606eb2208.png)

**Comment by KyrieY** [comment]
解决了吗

**Comment by xiaoymin** [comment]
1.9.6很老了，可以考虑用2.0.9 看看更新日志https://doc.xiaominfo.com/docs/changelog
