### ISSUE TITLE
@ApiImplicitParam 中的 example value 与调试UI介面有思考过要整合吗？

### ISSUE THREAD

**Issue by benjamin-kuo** [xiaoymin/knife4j#402]
![image](https://user-images.githubusercontent.com/6489005/147209389-f236f4e7-ef78-4788-8eae-024e6d1b41d8.png)

调试UI介面有思考过对于example 的 value 进行整合吗？
例如新增一个Button或栏位可以便捷代入 example 的 value 到参数值栏位裡。

**Comment by xiaoymin** [comment]
第一个example值未填入是ui的bug，

新增button这个没看懂，是指的动态参数调试吗？https://doc.xiaominfo.com/docs/features/dynamicRequestParameter

**Comment by xiaoymin** [comment]
长时间可能有些久了，我先close了，可以试试[4.0快照版本](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ),有问题再新开issue，感谢
