### ISSUE TITLE
很奇怪的问题,多层嵌套泛型,部分字段未展示

### ISSUE THREAD

**Issue by mjwyr** [xiaoymin/knife4j#404]
因为这个问题还跟前端吵了一下,我代码明明写了相关文档注释,但页面上却不展示,已清除页面缓存和maven缓存,甚至我改了泛型内实体类的注释后,文档都不会更新

![image](https://user-images.githubusercontent.com/55934340/148318144-3435ecbe-ba50-4fd0-be9c-de06ffe299e3.png)
![image](https://user-images.githubusercontent.com/55934340/148318321-ded2d4ee-bc48-4e75-87b9-bd690aef9896.png)
![image](https://user-images.githubusercontent.com/55934340/148318655-7180913b-5957-47d6-b4ca-5629ab2c0a9d.png)

**Comment by xiaoymin** [comment]
首先很抱歉发生这样的问题，字段不显示我估计有几方面的原因：

1、用@ApiModel注解标注实体类时，该值必须是全局唯一，可以确认一下

2、泛型类封装的问题，可以参考一下[这篇文章](https://doc.xiaominfo.com/docs/faq/swagger-des-not-found)

3、可以考虑升级一下knife4j的版本，2.x版本最后一个版本是2.0.9，目前v4.0正在计划中，已经发布快照版本，可以试试看，参考[v4.0.0 迭代计划](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)

**Comment by xiaoymin** [comment]
这个issue我先关了，有问题再新开issue反馈，感谢
