### ISSUE TITLE
新版Spring boot 2.6.1 和 Spring Cloud 2021.1 集成报错

### ISSUE THREAD

**Issue by Jzow** [xiaoymin/knife4j#405]
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-06 22:19:37.273 ERROR 47620 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.13.jar:5.3.13]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.13.jar:5.3.13]
```

pom 版本文件如下:
```
  <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <spring-boot.version>2.6.1</spring-boot.version>
        <spring-cloud.version>2021.0.0</spring-cloud.version>
        <nacos.version>2021.1</nacos.version>
        <druid-spring-boot-starter.version>1.2.8</druid-spring-boot-starter.version>
        <knife4j-spring-boot-starter.version>3.0.3</knife4j-spring-boot-starter.version>
    </properties>
```

**Comment by yunlonglei** [comment]
配置类或主启动类加@EnableWebMvc

**Comment by yunlonglei** [comment]
> ```
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2022-01-06 22:19:37.273 ERROR 47620 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.context.ApplicationContextException: Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
> 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.13.jar:5.3.13]
> 	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
> 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.13.jar:5.3.13]
> ```
> 
> pom 版本文件如下：
> 
> ```
>   <properties>
>         <maven.compiler.source>11</maven.compiler.source>
>         <maven.compiler.target>11</maven.compiler.target>
>         <spring-boot.version>2.6.1</spring-boot.version>
>         <spring-cloud.version>2021.0.0</spring-cloud.version>
>         <nacos.version>2021.1</nacos.version>
>         <druid-spring-boot-starter.version>1.2.8</druid-spring-boot-starter.version>
>         <knife4j-spring-boot-starter.version>3.0.3</knife4j-spring-boot-starter.version>
>     </properties>
> ```

配置类或主启动类加@EnableWebMvc

**Comment by yunlonglei** [comment]
但是我访问http://ip:port/doc.html 还是404，可以解决的话请回复！

**Comment by Jzow** [comment]
@yunlonglei 不行的，我已解决

**Comment by fwk1010** [comment]
你好，请问怎么解决的

**Comment by xieyan9-tal** [comment]
你好，请问怎么解决的？

**Comment by xiaoymin** [comment]
这是`spring-boot-starter-actuator`组件冲突引起的
```
<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-actuator</artifactId>
	</dependency>
```

解决方案：

1、底层换掉springfox，使用OpenAPI3的规范，可以考虑使用`knife4j-openapi3-spring-boot-starter`

2、继续用springfox和swagger2的规范，参考这两个issues：


- https://gitee.com/xiaoym/knife4j/issues/I5BW82
- https://gitee.com/xiaoym/knife4j/issues/I4JT89
