### ISSUE TITLE
上传下载功能希望再完善一下 页面会把MultipartFile类型的文件识别成为String类型~~~

### ISSUE THREAD

**Issue by flowclouds** [xiaoymin/knife4j#41]
就是上传的MultipartFile对象会被识别成表单String参数，能否修改一下

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/Swagger-Bootstrap-UI/issues/40

可以参考这个issue里面讨论的

**Comment by flowclouds** [comment]
好的，刚刚没看到。
