### ISSUE TITLE
`knife4j-springdoc-ui` 在网关访问的情况下发生异常

### ISSUE THREAD

**Issue by HaceraI** [xiaoymin/knife4j#423]
项目使用的是springdoc-openapi-ui，根据官方给出的Demo将`knife4j-spring-ui`更换为`knife4j-springdoc-ui`后，本机不走网关时可以正常显示doc.html内容; 但是走网关的时候就发生异常了;

走网关时：
![image](https://user-images.githubusercontent.com/48341368/155122584-fa463102-b4ff-43cd-8cff-befc50d7bfbe.png)

不走网关时：
![image](https://user-images.githubusercontent.com/48341368/155122763-da5f8d7d-9b04-4813-9cd0-681ffbb0a855.png)

---------
版本信息：
springdoc-openapi-ui:  1.6.6
knife4j-springdoc-ui: 3.0.3

**Comment by xiaoymin** [comment]
这个问题我测出来了，主要是context-path的关系，可以用[4.0快照版本](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)试试看，目前已经fixed了
