### ISSUE TITLE
swagger-resources报404

### ISSUE THREAD

**Issue by dajiao918** [xiaoymin/knife4j#429]
http://localhost:8081/swagger-resources，找不到

**Comment by weaponready** [comment]
+1

**Comment by JiFeiYe** [comment]
我在使用gateway文档聚合时也出现了这个问题，我使用springboot2.7.18，其他组件版本如图：

![Snipaste_2024-10-15_16-39-22](https://github.com/user-attachments/assets/7c8d7d2c-964a-4ba2-bd37-4b352bb2248f)

项目中的gateway服务中似乎因为我误导入了knife4j-openapi2-spring-boot-starter导致swagger-resources找不到。
于是我通过尝试从maven去除这个坐标，保留knife4j-gateway-spring-boot-starter，目前暂时已解决该问题。

![image](https://github.com/user-attachments/assets/8f77e7e0-5c56-4533-b127-dc34bfbe2d80)
![image](https://github.com/user-attachments/assets/46d01840-961b-475e-9f69-387b32aff1b0)
