### ISSUE TITLE
不能正确解析response内非$ref的schema内容。

### ISSUE THREAD

**Issue by lephix** [xiaoymin/knife4j#43]
使用版本1.8.7

案例：

	{
	  "get": {
	    "summary": "第一个list功能",
	    "deprecated": false,
	    "produces": [
	      "*/*"
	    ],
	    "operationId": "list3GET4997028859787988992",
	    "responses": {
	      "200": {
	        "schema": {
	          "type": "object",
	          "properties": {
	            "id": {
	              "name": "id",
	              "in": "formData",
	              "description": "标识的desc",
	              "required": true,
	              "type": "string"
	            },
	            "createTime": {
	              "name": "createTime",
	              "in": "formData",
	              "description": "时间的desc",
	              "required": false,
	              "type": "string"
	            }
	          }
	        },
	        "description": "返回profile列表"
	      }
	    },
	    "description": "list的description",
	    "parameters": [
	      {
	        "name": "id",
	        "in": "formData",
	        "description": "标识的desc",
	        "required": true,
	        "type": "string"
	      },
	      {
	        "name": "createTime",
	        "in": "formData",
	        "description": "时间的desc",
	        "required": false,
	        "type": "string"
	      }
	    ],
	    "tags": [
	      "profile"
	    ],
	    "consumes": [
	      "application/xml"
	    ]
	  }
	}

在responses里面的schema不能正确的展示。 该问题在springfox-swagger-ui等其他工具上可以正确展示。如果schema内容为$ref指到definitions内的元素，展示没有问题。

**Comment by xiaoymin** [comment]
这个后台的代码结构能否贴一下？

**Comment by lephix** [comment]
我们没有使用springfox的框架生成文档，因为他本身也有一些约束，我们是按照swagger2的文档规范来生成的json，所以我贴出来代码你也不能转换成JSON。
规范文档 https://swagger.io/specification/v2

**Comment by xiaoymin** [comment]
1.8.8版本已优化，可以试一下
