### ISSUE TITLE
使用'knife4j-springdoc-ui'的3.0.3版本。对于@GetMapping请求解析对象入参异常

### ISSUE THREAD

**Issue by kaxu** [xiaoymin/knife4j#430]
使用'knife4j-springdoc-ui'的3.0.3版本。对于@GetMapping请求解析对象入参异常

```
@Schema(description = "分页查询角色")
    @GetMapping("list")
    public JsonResult list(@ModelAttribute RolePageParam rolePageQueryParam,Pagination pagination) {
//        RolePageParam rolePageQueryParam = new RolePageParam();
        List<SysRoleVO> list = sysRoleService.pageList(rolePageQueryParam,pagination);
        return JsonResult.OK(list).bindPagination(pagination);
    }
```

![image](https://github.com/kaxu/img/blob/main/20220304215156.png?raw=true)

提交界面上
rolePageQueryParam  ：   {  "roleName": "",  "status": ""}
pagination   ：   {  "pageIndex": 0,  "pageSize": 2,  "totalCount": 0,  "orderBy": "",  "totalPage": 0}
点击发送以后提交的完整curl如下：
curl -X GET -H  "Accept:*/*" -H  "Content-Type:application/x-www-form-urlencoded" "http://localhost:8080/sys/role/list?rolePageQueryParam=%7B%0A%20%20%22roleName%22:%20%22%22,%0A%20%20%22status%22:%20%22%22%0A%7D&pagination=%7B%20%20%22pageIndex%22:%200,%20%20%22pageSize%22:%202,%20%20%22totalCount%22:%200,%20%20%22orderBy%22:%20%22%22,%20%20%22totalPage%22:%200%7D"

期望的效果是：
http://localhost:8080/sys/role/list?roleName=&status=&pageIndex=0&pageSize=2&totalCount=0&orderBy=&totalPage=0

**Comment by kaxu** [comment]
![image](https://github.com/kaxu/img/blob/main/20220304215156.png?raw=true)

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/I5TFDA
