### ISSUE TITLE
js 加载慢

### ISSUE THREAD

**Issue by 908028664** [xiaoymin/knife4j#434]

**Comment by 908028664** [comment]
一个最简单的springboot项目，集成了knife4j，打开接口文档前端，居然有个js要2M多，线上环境加载太慢了，我1M带宽要等很久，这个js能否优化一下，让他变小一些输入图片说明
![image](https://user-images.githubusercontent.com/18205566/160543660-525f900f-fc01-4efb-84c9-80baaa4ce174.png)

**Comment by xiaoymin** [comment]
这个没办法压缩了，如果是带宽太小，建议导出一个离线的html 放上去吧
