### ISSUE TITLE
js 加载慢，请作者优化

### ISSUE THREAD

**Issue by 908028664** [xiaoymin/knife4j#435]
![image](https://user-images.githubusercontent.com/18205566/160543730-265e21f6-7680-4539-ae3c-d345f310a87f.png)
一个最简单的springboot项目，集成了knife4j，打开接口文档前端，居然有个js要2M多，线上环境加载太慢了，我1M带宽要等很久，这个js能否优化一下，让他变小一些

**Comment by 908028664** [comment]
![image](https://user-images.githubusercontent.com/18205566/160543880-61ae5ae8-82dd-45fd-9fb1-f69b179bf160.png)

**Comment by 908028664** [comment]
![image](https://user-images.githubusercontent.com/18205566/160543973-df3095dd-6f68-4829-b3f3-7facc158626e.png)

**Comment by xiaoymin** [comment]
这个没法优化了呢
