### ISSUE TITLE
deprecated的API没有显示删除线。

### ISSUE THREAD

**Issue by lephix** [xiaoymin/knife4j#44]
可以参考spingfox-swagger-ui的效果。

**Comment by xiaoymin** [comment]
你好，Swagger的deprecated是通过在方法上标注`@Deprecated`注解还是通过本身Swagger的注解？这个功能我没使用过，不是太清楚

**Comment by lephix** [comment]
该功能也是在标准内包含的，swagger的annotation并没有包含这个选项。https://swagger.io/specification/v2

**Comment by xiaoymin** [comment]
> 该功能也是在标准内包含的，swagger的annotation并没有包含这个选项。https://swagger.io/specification/v2

好的，我刚试了一下，是通过在方法上加@Deprecated注解

swagger的效果如下：
![](http://www.xiaominfo.com/images/swaggerdelete.png)

你说的应该是这个效果吧?

**Comment by xiaoymin** [comment]
1.8.8版本已支持
