### ISSUE TITLE
能否支持按照请求参数必填字段排序

### ISSUE THREAD

**Issue by acloudyh** [xiaoymin/knife4j#45]
是否能支持true类型置顶
![image](https://user-images.githubusercontent.com/33645878/48817170-22307d00-ed80-11e8-8f41-cd444b2df9fa.png)

**Comment by acloudyh** [comment]
![image](https://user-images.githubusercontent.com/33645878/48817248-7d626f80-ed80-11e8-9ecd-4acd0d25772c.png)

**Comment by xiaoymin** [comment]
可以的，这个需求很实用

**Comment by xiaoymin** [comment]
1.8.8版本已支持

**Comment by xuzongmeng** [comment]
在此基础上能否支持返回的字段排序，在实体类上加个注解什么的，默认不排序也就是说默认按照原有实体类Dto或Entity的字段顺序输出。
![微信截图_20200417101926](https://user-images.githubusercontent.com/16155051/79525725-29071080-8096-11ea-9d40-10f161e93585.png)
比如这个列表，其实createDate和updateDate通常我做管理系统或者前端显示应该在最后几列，grade在我的singinCout之后，期初设计数据库以及生成实体类都是这个顺序，现在顺序是A-Z的顺序，这字段少还好，字段多，很难找，况且有时候有些字段可能不显示或者做一些其它转换. 小建议哈
