### ISSUE TITLE
功能建议：新接口高亮显示

### ISSUE THREAD

**Issue by xqdd** [xiaoymin/knife4j#46]
这个功能在开发中比较有用

我有一个不成熟的想法
在local storage中维护一个非高亮接口的列表
1.所有未在该列表的接口进行高亮显示
2.当点击了该接口后，从高亮列表中删除
3.在这后面加上新接口个数
![image](https://user-images.githubusercontent.com/20871761/48832035-2e81fd80-edb3-11e8-9203-33e45e2f2957.png)

**Comment by xiaoymin** [comment]
Good idea

**Comment by xiaoymin** [comment]
1.8.8版本已加该功能
