### ISSUE TITLE
枚举类型，@ApiModelProperty.allowableValues

### ISSUE THREAD

**Issue by isCmy** [xiaoymin/knife4j#467]
能不能通过allowableValues值，来控制枚举值在文档中显示可用值

**Comment by isCmy** [comment]
![image](https://user-images.githubusercontent.com/52767489/175912536-caceec74-691a-4715-b31a-60f7761bcb6f.png)

**Comment by xiaoymin** [comment]
可用值支持的吧
<img width="632" alt="image" src="https://user-images.githubusercontent.com/7894406/206090634-25162778-4c4c-425f-a0d0-d0de6fcba935.png">

<img width="724" alt="image" src="https://user-images.githubusercontent.com/7894406/206090660-6a1fa9d2-9ec9-431d-8c49-d8c21bec1554.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/7894406/206090713-3978a44d-22ae-442f-8408-d0b823b258da.png">
<img width="938" alt="image" src="https://user-images.githubusercontent.com/7894406/206090743-19ad3185-865b-49b7-b625-cd71ec2e53ff.png">

<img width="654" alt="image" src="https://user-images.githubusercontent.com/7894406/206090775-732b089c-2b28-4640-83aa-d8a0ee31cb5c.png">

**Comment by xiaoymin** [comment]
由于不知道你用的是那个版本，这个issue我先close了，你可以试试用[v4.0.0快照版先](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)试试看 是否可以，如果有问题再新开一个，感谢
