### ISSUE TITLE
响应信息不支持html标签，swaggerUI是支持的

### ISSUE THREAD

**Issue by xqdd** [xiaoymin/knife4j#47]
![image](https://user-images.githubusercontent.com/20871761/48839118-6003c480-edc5-11e8-8c5b-c6e027b0ecde.png)
![image](https://user-images.githubusercontent.com/20871761/48839129-66923c00-edc5-11e8-9d21-586e6a66b0a6.png)

**Comment by xiaoymin** [comment]
1.8.8已优化
