### ISSUE TITLE
版本有点老了，对最新版的springboot请求模式不支持，只能切换会ANT请求风格才行，什么时候可以支持下？

### ISSUE THREAD

**Issue by mingyang66** [xiaoymin/knife4j#473]
is:issue is:open 版本有点老了，对最新版的springboot请求模式不支持，只能切换会ANT请求风格才行，什么时候可以支持下？

**Comment by xiaoymin** [comment]
目前的想法分享一下，由于springfox长期不更新，所以后面的迭代计划是主要分几个方面

1、保留swagger2的版本，依然使用springfox项目作为解析生成swagger接口的方案，但是Knife4j会针对Spring Boot高版本提供适配，适配的思路也很简单，就是向spring的变量中注入一个ant风格的属性，参考[SpringFoxEnvironmentPostProcessor.java](https://gitee.com/xiaoym/knife4j/blob/dev/knife4j/knife4j-openapi2-spring-boot-starter/src/main/java/com/github/xiaoymin/knife4j/spring/common/bean/SpringFoxEnvironmentPostProcessor.java) 

2、knife4j拥抱springdoc-openapi3项目，针对OAS3规范做适配兼容

3、开发者做选择，即可以选择swagger2(底层使用springfox2)，也可以使用oas3（底层使用springdoc-openapi）

4、可以参考近期knife4j的[v4.0迭代计划](https://doc.xiaominfo.com/docs/v4)，欢迎参与贡献
