### ISSUE TITLE
能否同时根据position，@ApiSort进行排序

### ISSUE THREAD

**Issue by lshz0088** [xiaoymin/knife4j#48]
目前的情况，好像是设置了position，@ApiSort就无效了。
我的预期是，当position相同的情况下，再按@ApiSort进行排序。
在实际应用中，可能几个API属于同一大类的，该大类使用position进行排序。
然后大类中的API根据@ApiSort进行内部排序。

或者加一个API分组的功能也不错（组名，排序）

例如：
1.一个投票APP有系统管理，和投票管理两个大类
2.系统管理中，又分为用户对象、角色对象、权限对象等等
3.用户对象又分为增删改查的接口

在SpringMVC中对应的具体控制器名类似：
一、
1.UsersController

- 增加接口
- 删除接口
- 查询接口

2.RolesController

二、
1.VoteSubjectsController（投票主体管理）
2.VoteResultsController（投票结果管理）

**Comment by xiaoymin** [comment]
接口类的注解排序 是可以使用`@ApiOperation`注解里面的position来排序的，当时提供这个@ApiSort是用来排分组的，也是以为swagger没有这个position这种类似的参数，

既然swagger的注解有position值，就按照这个来了，也省去了我ui新增的注解

```java

@ApiOperation(value = "post请求参数Hidden属性是否生效",position = 3)
    @PostMapping("/postRequest")
    public Rest<Model187> postRequest(@RequestBody Model187 model187){
        Rest<Model187> r=new Rest<>();
        r.setData(model187);
        return r;
    }
```
