### ISSUE TITLE
Considerations for the support timeline for SpringDoc 2.x

### ISSUE THREAD

**Issue by linghengqian** [xiaoymin/knife4j#484]
## Question

- SpringDoc switched GAV information in a major version change in 2.x to support Jakarta EE namespaces.  Refer to https://github.com/springdoc/springdoc-openapi/issues/1284.  For Knife4j which is currently in SpringDoc 1.x, is this piece not considered, or will there be a predetermined module to distribute additionally?

- Should we consider releasing two different packages to support SpringDoc 1.x and SpringDoc 2.x respectively, or should we consider SpringDoc 2.x after SpringDoc 1.x support is dropped at some point in the future?  The roadmap for Knife4j V4 does not reflect this for Jakarta EE namespace support.🤔

**Comment by xiaoymin** [comment]
Thanks for your suggestion, I see that the springdoc2.x version has not yet released a stable version.

So for Knife4j, the main work:

1. Adapt the enhanced functions provided by Knife4j to the springdoc1.x version, including the Openapi3 specification in the ui part, and provide a Spring boot starter that is easy for developers to use

2. After the release of 4.0, enterprise developers can gradually use the OpenAPI3 specification, which requires an excessive process. At present, as far as I know, many developers are still using springfox2.x or springfox3.0 version, although springfox3.0 provides correct Openapi3 specification support, but in my opinion, the support is still not good enough

3. After the stable version of springdoc2.x is released later, knife4j will keep up with the adaptation and support Jarkarta EE.

**Comment by linghengqian** [comment]
Thank you for your answer.😃 Since this is unmanageable work at this stage, I will close this issue.
