### ISSUE TITLE
knife4j + springdoc-openapi, 在接口组tags中加入x-order信息，knife4j前端并没有根据x-order进行排序

### ISSUE THREAD

**Issue by tablesheep233** [xiaoymin/knife4j#487]
version: 
 knife4j: 3.0.3
 springdoc-openapi: 1.6.9

question:
使用knife4j + springdoc-openapi, 在接口组tags中加入x-order信息，knife4j前端并没有根据x-order进行排序
![1661244939965](https://user-images.githubusercontent.com/29518454/186116546-9f517c1d-3ea7-4fe3-806a-85d9111791f0.jpg)

repository: 
https://github.com/tablesheep233/knife4j-springdoc-order-test

**Comment by xiaoymin** [comment]
已复现，下个4.0版本修复
