### ISSUE TITLE
关于设置全局参数

### ISSUE THREAD

**Issue by Rupert333** [xiaoymin/knife4j#488]
接口路径中是带有版本号的，例如/{v}/order
在全局设置中设置参数如下：参数名：{v} 、参数值：v1.0、类型：query
如此设置会导致页面空白报错，无法重设参数

**Comment by xiaoymin** [comment]
版本。贴图？

**Comment by Rupert333** [comment]
辛苦啦
| |
杨月岗
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年08月24日 22:33 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xiaoymin/swagger-bootstrap-ui] 关于设置全局参数 (Issue #488) |

版本。贴图？

**Comment by xiaoymin** [comment]
？？？

**Comment by Rupert333** [comment]
您需要哪些信息？


| |
杨月岗
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年09月1日 09:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xiaoymin/swagger-bootstrap-ui] 关于设置全局参数 (Issue #488) |

？？？

**Comment by xiaoymin** [comment]
1、我不知道你使用的Knife4j的版本
2、针对你说的，是否贴图来描述你的场景，让我回归测试验证。

**Comment by Rupert333** [comment]
1、项目中引用的版本为3.0.3（见下图）


2、我们的接口路径上是包含版本信息的，例如：/{v}/role
为了设置版本号，在文档管理-全局参数设置处添加了参数如下图


添加后，接口文档无法访问
| |
杨月岗
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年09月1日 09:48 |
| 收件人 | ***@***.***> |
| 主题 | 回复： [xiaoymin/swagger-bootstrap-ui] 关于设置全局参数 (Issue #488) |




辛苦啦
| |
杨月岗
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年08月24日 22:33 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [xiaoymin/swagger-bootstrap-ui] 关于设置全局参数 (Issue #488) |

版本。贴图？

**Comment by linghengqian** [comment]
If you cannot provide images and reproducible examples, this issue should be closed and marked as invalid.
