### ISSUE TITLE
能否把spring.factories中的 Knife4jAutoConfiguration 拿掉

### ISSUE THREAD

**Issue by Jxin-Cai** [xiaoymin/knife4j#490]
1.spring.factories 加载配置类 Knife4jAutoConfiguration

2.@EnableKnife4j 也是加载配置类 Knife4jAutoConfiguration

两个并存，等于 @EnableKnife4j / 条件装配直接无效。 一旦引入 knife4j 就一定会加载配置。

**Comment by xiaoymin** [comment]
spring.factories不能拿掉啊，之前搞@EnableKnife4j注解是考虑到springmvc的情况，如果是boot环境 不使用这个注解也没啥影响吧

**Comment by linghengqian** [comment]
> spring.factories不能拿掉啊，之前搞@EnableKnife4j注解是考虑到springmvc的情况，如果是boot环境 不使用这个注解也没啥影响吧

- FYI, `spring.factories` should remove the `AutoConfiguration` class and keep the others.  The feature that `spring.factories` includes `AutoConfiguration` is deprecated in SpringBoot OSS 2.7 and removed in Springboot OSS 3.0.  Refer to https://github.com/spring-projects/spring-boot/issues/29699 .

**Comment by linghengqian** [comment]
- Do you think it is necessary to add a `volunteer wanted` tag to this issue?

**Comment by xiaoymin** [comment]
> > spring.factories不能拿掉啊，之前搞@EnableKnife4j注解是考虑到springmvc的情况，如果是boot环境 不使用这个注解也没啥影响吧
> 
> * FYI, `spring.factories` should remove the `AutoConfiguration` class and keep the others.  The feature that `spring.factories` includes `AutoConfiguration` is deprecated in SpringBoot OSS 2.7 and removed in Springboot OSS 3.0.  Refer to [Remove spring.factories auto-configuration support spring-projects/spring-boot#29699](https://github.com/spring-projects/spring-boot/issues/29699) .

get

**Comment by linghengqian** [comment]
- I forgot to add, or just add new files, according to https://github.com/remkop/picocli/pull/1778#issuecomment-1242654922 , only adding new files can allow compatibility with both SpringBoot OSS 2.x and SpringBoot OSS 3.x.

**Comment by linghengqian** [comment]
- I am working on this issue.
