### ISSUE TITLE
下标越界

### ISSUE THREAD

**Issue by CodeMan-cmd** [xiaoymin/knife4j#496]
![image](https://user-images.githubusercontent.com/52879329/189500061-eb632b4d-cdd5-4925-a372-6b3295e3833c.png)
![image](https://user-images.githubusercontent.com/52879329/189500069-cab14ac8-c115-441d-9bc4-c9bb6a745506.png)
问题是出现了下标越界，肯定是框架问题了，records参数出现了问题导致下标越界
![image](https://user-images.githubusercontent.com/52879329/189500097-1e644c0e-10ef-4721-ad51-89baacc4dd93.png)

**Comment by CodeMan-cmd** [comment]
帮帮忙看下用原生的swagger-ui没有问题。

**Comment by xiaoymin** [comment]
或者可以升级下ui版本

**Comment by CodeMan-cmd** [comment]
@xiaoymin 我切换过版本，还是有问题

**Comment by xiaoymin** [comment]
500 是服务端的问题，这种情况 你能贴出来knife4j发送的xhr和swagger-ui发送的xhr参数格式 对比图吗？

**Comment by CodeMan-cmd** [comment]
@xiaoymin 麻烦你了我刚刚看是我配置的问题。

**Comment by CodeMan-cmd** [comment]
开源响应真快，感谢感谢
