### ISSUE TITLE
页面卡死

### ISSUE THREAD

**Issue by HeHuan-666** [xiaoymin/knife4j#497]
工程接口挺多了，现在发现访问接口的页面，直接就卡住了，直接等到卡死，下载为离线文档，按钮点没没反应，一直等到页面崩溃。请求大佬帮帮忙

**Comment by xiaoymin** [comment]
要分组一下，这个确实目前存在性能问题

**Comment by pengqidehao** [comment]
怎么分组

**Comment by xiaoymin** [comment]
> 怎么分组

多建几个docket对象
