### ISSUE TITLE
docs.html界面上“接口地址”与“调试地址”不相等

### ISSUE THREAD

**Issue by lulouis** [xiaoymin/knife4j#499]
<img width="1398" alt="1" src="https://user-images.githubusercontent.com/8636491/194815616-46a51cb3-077c-410b-9678-c219c79e73d8.png">
<img width="1321" alt="2" src="https://user-images.githubusercontent.com/8636491/194815636-8b4ef331-891f-4c06-afdb-eab53a2049dc.png">

如图对比，劳烦帮助分析，参数为path类型时，为何调试时路径会忽略占位符
实现代码如下：
` 
    @ApiOperation(value = "根据用户名查询用户",notes = "根据用户名查询用户")
    @ApiResponses({@ApiResponse(code=400,message="请填写请求参数")})
    @GetMapping("/find/{loginName}/")
    @ApiImplicitParam(paramType = "path", name = "loginName", dataType = "String", required = true, value = "loginName")
    public Set<SysUser> findByUsername(@PathVariable  String loginName)
    {
        return sysUserService.selectUserByLoginName(loginName);
    }`

**Comment by lulouis** [comment]
少了占位符之后，导致人工输入的参数，后端无法接受的。F12浏览器分析可以看出请求地址中没有参数。人工补全调试地址/user/find/{loginName}后，一切正常

**Comment by xiaoymin** [comment]
这个版本有点历史了，可以用用新版本呢？ 比如2.0.9

**Comment by xiaoymin** [comment]
也可以试试4.0快照版本

https://gitee.com/xiaoym/knife4j/issues/I5LIQZ
