### ISSUE TITLE
@requestbody类型参数的问题

### ISSUE THREAD

**Issue by yuexiaown** [xiaoymin/knife4j#50]
@requestbody注解时，请求参数最外层的哪个类型(即@requestbody所标注的参数类型)没有必要要把，误导前端

**Comment by xiaoymin** [comment]
类型？你说的是body、header、query这种吗？

**Comment by yuexiaown** [comment]
比如说@RequestBody User，UI这样显示

| 参数名称         | 说明     |     参数类型 |  是否必须      |  类型   |  schema  |
| ------------ | -------------------------------- |-----------|--------|----|--- |
| - User          |      user|     body   |       true     |User      | 
|  &nbsp;&nbsp; &nbsp;&nbsp;  userId        |      userId   |     body        |       true|int| 
|  &nbsp;&nbsp; &nbsp;&nbsp;  userName|      userName|     body        |       true|String| 

我想把第一行的User去掉，因为这样会误导前端
前端只需要传
{
"userId":1,
"userName":"git"
}
他们没必要知道后端用什么类型的对象接收
_User_{
"userId":1,
"userName":"git"
}

**Comment by xiaoymin** [comment]
这个有请求示例展现出来的吧，requestbody类型的参数 

table里面只是需要这层tree结构来列举说明
