### ISSUE TITLE
Header不显示description，example无效

### ISSUE THREAD

**Issue by sizhuruoshui** [xiaoymin/knife4j#501]
knife4j-springdoc-ui 3.0.3
springdoc-openapi-ui 1.6.12

![image](https://user-images.githubusercontent.com/2943037/198838601-9c2e72fe-6d6a-42c5-89aa-e38f08d50513.png)
![image](https://user-images.githubusercontent.com/2943037/198838664-b1cf30ca-d4ae-4564-af2f-e813179b4dd4.png)

**Comment by yhl452493373** [comment]
同问题+1
