### ISSUE TITLE
Swagger版本兼容问题

### ISSUE THREAD

**Issue by victor-lsn** [xiaoymin/knife4j#505]
是不是不支持Swagger3，Models全都显示不出来

**Comment by xiaoymin** [comment]
是怎么使用的呢？

**Comment by victor-lsn** [comment]
> 是怎么使用的呢？

就是正常的集成的，swagger使用的springfox-boot-starter这个坐标3.0.0版本，
![image](https://user-images.githubusercontent.com/64344557/200450561-d9a59d32-1ccc-443b-b368-79924ed23529.png)
使用DocumentationType.OAS_30初始化的Docket，然后swagger官方页面可以显示所有Models，但是咱这个界面显示都是空的，目前我使用DocumentationType.SWAGGER_2初始化后都显示出来了

**Comment by xiaoymin** [comment]
1.9.6 很老的版本，不支持swagger3的
