### ISSUE TITLE
swagger.json请求超时

### ISSUE THREAD

**Issue by pengqidehao** [xiaoymin/knife4j#508]
框架接口默认20000ms的超时时间，单体接口数量过多会导致ui加载swagger.json超时报错，望开发者增加全局Ajax加载超时设置，让用户自定义，或者默认超时时间设置长一点。

**Comment by xiaoymin** [comment]
那只能改长一点了，60s吧

**Comment by xiaoymin** [comment]
先关注snapshot版本 https://gitee.com/xiaoym/knife4j/issues/I5LIQZ
