### ISSUE TITLE
对象作为参数时，选择性显示参数，能在3.0版本中把这个功能加回来吗？

### ISSUE THREAD

**Issue by Zomty** [xiaoymin/knife4j#513]
![Y8CTP5$SIK~CWNT7 6LFAVT](https://user-images.githubusercontent.com/42804378/205545144-344ef195-15ab-408f-9738-842352a54778.png)

**Comment by xiaoymin** [comment]
你用2的注解就一直用springfox2.x版本好了，没关系的

如果要彻底换掉，就放弃springfox，使用springdoc-openapi项目，采用openapi3的规范。

knife4j在后面的版本中，会把两个分开，2的规范继续停留在springfox2.x版本，如果说openapi3，则会使用springdoc项目，抛弃springfox，因为springfox3.0.0版本兼容性问题太多了

参考[v4.0.0](https://gitee.com/xiaoym/knife4j/issues/I5LIQZ)
