### ISSUE TITLE
参数 example 展示错误

### ISSUE THREAD

**Issue by jerryskyr** [xiaoymin/knife4j#518]
![image](https://user-images.githubusercontent.com/44660033/209321900-7e801b1a-2e15-40d1-b5e5-adf33443943c.png)

接口返回的 example 是数组形式的格式
但是示例参数和调试参数, 都展示为文本格式, 使得无法快速正确的提交参数

**Comment by xiaoymin** [comment]
版本？

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/swagger-bootstrap-ui/issues/220
