### ISSUE TITLE
添加官网依赖，打包报错

### ISSUE THREAD

**Issue by huaye-dsg** [xiaoymin/knife4j#519]
java.lang.IllegalArgumentException: Unable to instantiate factory class [com.github.xiaoymin.knife4j.spring.common.bean.SpringFoxEnvironmentPostProcessor] for factory type [org.springframework.boot.env.EnvironmentPostProcessor]
Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/DefaultPropertiesPropertySource

springboot版本：2.2.4
只按照官网页面添加了如下依赖，打包会爆上面的错
    <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>

swagger配置
@Configuration
@EnableSwagger2WebMvc
public class SwaggerConfig {

    private final OpenApiExtensionResolver openApiExtensionResolver;

    /**
     * 是否开启swagger
     */
    @Value("${swagger.enabled}")
    private boolean enabled;

    @Autowired
    public SwaggerConfig(OpenApiExtensionResolver openApiExtensionResolver) {
        this.openApiExtensionResolver = openApiExtensionResolver;
    }

    @Bean
    Docket docket() {
        return new Docket(DocumentationType.SWAGGER_2)
                .enable(enabled)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.withMethodAnnotation(ApiOperation.class))
                .paths(PathSelectors.any())
                .build()
                .extensions(openApiExtensionResolver.buildExtensions(""));
    }

    private ApiInfo apiInfo() {
        return new ApiInfoBuilder()
                .title("demo")
                .description("demo")
                .version("1.0")
                .contact(new Contact("demo",
                        "",
                        ""))
                .build();
    }
}

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/quick-start

<img width="915" alt="image" src="https://user-images.githubusercontent.com/7894406/209466069-6cb67651-7b80-48d4-b604-91a24115c00c.png">
