### ISSUE TITLE
可以生成多个文档吗？

### ISSUE THREAD

**Issue by hackeryutu** [xiaoymin/knife4j#526]
**Describe the bug**

**Expected behavior**
我一个spring boot应用里面需要多份文档， 因为我通过文件夹映射地址前缀来隔离接口。
比如 com.xxxx.biz.controller.admin 映射前缀 /admin-api/
比如 com.xxxx.biz.controller.app 映射前缀 /app-api/
比如 /admin-api/doc.html 看的是运营端的接口文档，  /app-api/doc.html 看的是app的接口文档。
**Screenshots**

**Knife4j Version (please complete the following information):**
version 3.0.3
**Additional context**

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/middleware-sources/desktop-introduction

你可以用这个
