### ISSUE TITLE
希望在接下来的版本中添加basePath的设置

### ISSUE THREAD

**Issue by magese** [xiaoymin/knife4j#529]
项目版本如下：
`spring-cloud 2022.0.0`
`spring-cloud-alibaba 2022.0.0.0-RC1`
`spring-boot 3.0.1`

使用的`spring-gateway`聚合，
目前使用的 `knife4j 4.0.0` 版本，现版本无法配置文档请求的 basePath ，导致在调试的时候每次都要手动加上路由前缀，希望在配置项中可以增加 basePath 的设置。

**Comment by xiaoymin** [comment]
你用那个？

**Comment by LinShengwzp** [comment]
网关路由中(knife4j:gateway:routes)只能配置 name url service-name order四个值，由于不同服务下前缀不一样，每次访问都需要自己加上服务前缀

**Comment by zzl14273119** [comment]
这个情况我同样遇到这，大佬有什么解决办法吗？

**Comment by LinShengwzp** [comment]
> context-path 用这个

**Comment by HarrisonQi** [comment]
大佬怎么解决的呢，这个对于前后端联调非常不友好，每次都要手动拼上服务前缀
