### ISSUE TITLE
Swagger Models不能正确显示

### ISSUE THREAD

**Issue by lephix** [xiaoymin/knife4j#53]
使用版本：1.8.8
问题描述：在左侧栏的swagger models，没有展示definitions里面定义的Model。
截取的definitions例子如下：

    {
      "definitions":{
        "MetaEntity":{
          "properties":{
            "id":{
              "type":"integer",
              "format":"int64"
            },
            "name":{
              "type":"string"
            },
            "description":{
              "type":"string"
            },
            "countType":{
              "type":"string"
            }
          }
        }
      }
    }

**Comment by xiaoymin** [comment]
UI能截个图么

**Comment by lephix** [comment]
<img width="609" alt="swagger1" src="https://user-images.githubusercontent.com/308410/50320292-a2283f00-0506-11e9-9675-4729fb9208bc.png">
上面是bootstrap-ui的展示

<img width="472" alt="swagger2" src="https://user-images.githubusercontent.com/308410/50320304-aeac9780-0506-11e9-93b6-dd76b35f3cfd.png">
上图是官方ui的展示
