### ISSUE TITLE
knife4j-openapi3-jakarta-spring-boot-starter依赖在yml文件中没有配置提示

### ISSUE THREAD

**Issue by IHEL** [xiaoymin/knife4j#531]
以下依赖引入没有配置描述生成文件
<dependency>
    <groupId>com.github.xiaoymin</groupId>
    <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
    <version>4.0.0</version>
</dependency>

没有以下文件，导致配置没有提示
![image](https://user-images.githubusercontent.com/17951700/215410185-bdb95b35-3c39-4acd-b56d-9a7b321631ac.png)

**Comment by xiaoymin** [comment]
忘记加自动生成的dependency了，下个版本带上

**Comment by IHEL** [comment]
这个问题下个版本大概什么时候可以发布到maven中央仓库中？

**Comment by xiaoymin** [comment]
预计是这个月
