### ISSUE TITLE
Bug: 在 swagger 设置了全局安全验证, 并且在knife4j的界面设置了全局鉴权头, 但是全局鉴权未生效

### ISSUE THREAD

**Issue by hsiong** [xiaoymin/knife4j#534]
**Describe the bug**
在 swagger 设置了全局安全验证, 并且在knife4j的界面设置了全局鉴权头, 但是全局鉴权未生效

**To Reproduce**
1. Swagger 配置如下

<img width="1279" alt="Screen Shot 2023-02-06 at 11 12 17" src="https://user-images.githubusercontent.com/37357447/216875463-4663af98-d88e-426a-b54a-d98f9583d7b4.png">

2. knife4j 界面全局鉴权头配置如下

<img width="1461" alt="Screen Shot 2023-02-06 at 09 48 21" src="https://user-images.githubusercontent.com/37357447/216863450-85a2767a-dee4-43d4-93ad-6015a2be44ae.png">

3. 请求界面如下

<img width="1372" alt="Screen Shot 2023-02-06 at 09 49 20" src="https://user-images.githubusercontent.com/37357447/216863593-1317115a-c634-4bd3-9f48-257e444723b0.png">

4. bug 结果如下, 如图未在 header 中配置全局参数

<img width="736" alt="Screen Shot 2023-02-06 at 09 49 59" src="https://user-images.githubusercontent.com/37357447/216863651-72b25c40-17c8-4bff-a70b-75d39cdc0bfb.png">

**Expected behavior**
在 swagger-ui 中, 是可以传递 auth header 的, 效果如下; 所以在此认为是 knife4j 升级到 4.0.0 后产生的 bug 

![image](https://user-images.githubusercontent.com/37357447/216873986-de3f690c-c9ac-4968-9468-5c97c9629b40.png)

**Knife4j Version:**

```xml
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>
```

**Additional context**
相关 issue:
+ [x] #524 
+ [ ] #523

期待您的回复, 感谢  ~
@xiaoymin

**Comment by xiaoymin** [comment]
参考下这个issues中回复的呢

[https://github.com/xiaoymin/knife4j/issues/523](https://github.com/xiaoymin/knife4j/issues/523)

或者升级一下4.1.0版本

**Comment by hsiong** [comment]
好的  非常感谢 !
