### ISSUE TITLE
请求保存，方便下次调用

### ISSUE THREAD

**Issue by lovecodeyou** [xiaoymin/knife4j#537]
发起一次请求的时候能不能保存一下当前请求比如表单参数、json请求体、请求头这些信息，在当前api页面某个地方添加一个历史记录，下次在发起某个曾经发过的请求直接一个按钮就完事了，而不是重新敲表单参数、json请求体，太麻烦了，

强烈建议作者加上这个功能

**Comment by xiaoymin** [comment]
现在有保存调试信息的功能啊，你版本太老了？

**Comment by lovecodeyou** [comment]
![image](https://user-images.githubusercontent.com/38997988/218300756-1051f22a-aa21-4f69-a89e-6be11d07bdfe.png)

用的是这个版本

**Comment by xiaoymin** [comment]
这个版本也有的，你是不是默认关掉了 

https://doc.xiaominfo.com/docs/features/requestCache
