### ISSUE TITLE
某些情况不能正确识别 MediaType (swagger-ui/index.html 是正常的) 

### ISSUE THREAD

**Issue by zhuzhongxing** [xiaoymin/knife4j#538]
<img width="583" alt="51495df7d354a0d2a59ab72937ee8bc" src="https://user-images.githubusercontent.com/18155296/220012517-affd5656-5d6c-4a10-ae74-13c57b14ef5a.png">

如上图所示，JavaBean (包含一个 MultipartFile[] file 属性)  作为参数时，不能正确识别 MediaType 为 multipart/form-data

**Comment by zhuzhongxing** [comment]
相关环境：
springboot 2.2.7.RELEASE
springdoc-openapi-ui  1.6.9
knife4j-openapi3-spring-boot-starter  4.0.0

knife4j 效果图 (正确识别需要放开注释部分)
<img width="320" alt="ad12a2e12bac8fe4ceb5a2933c8d764" src="https://user-images.githubusercontent.com/18155296/220013155-f05792cd-7b74-46c6-8e69-cc224a3d1899.png">

swagger 效果图
<img width="850" alt="1676869208260" src="https://user-images.githubusercontent.com/18155296/220013203-e85d9931-039c-447b-84de-ff8babfc7cfb.png">

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/I6HAW0
