### ISSUE TITLE
请求示例，在Chrome中，中英文高度不一致，可能是由于字体原因导致，Firefox正常

### ISSUE THREAD

**Issue by light-speak** [xiaoymin/knife4j#54]

**Comment by xiaoymin** [comment]
截图看看？

**Comment by light-speak** [comment]
![2018-12-26 23-54-33](https://user-images.githubusercontent.com/31815444/50467097-4a914400-09dc-11e9-9d87-249bc42066c5.png)

**Comment by light-speak** [comment]
![2018-12-27 13-37-37](https://user-images.githubusercontent.com/31815444/50467164-a1971900-09dc-11e9-9b8f-68867dda01b2.png)
上面那个是Chrome的，这个是Firefox的

**Comment by xiaoymin** [comment]
我这边测试的chrome又是正常的

chrome版本71.0.3578.98

**Comment by xiaoymin** [comment]
推荐升级chrome浏览器
