### ISSUE TITLE
termsOfServiceUrl 翻译问题

### ISSUE THREAD

**Issue by SouthMountains** [xiaoymin/knife4j#540]
**Describe the bug**
termsOfService 的中文翻译应该是“服务条款 ” 。  现在的翻译 “服务 URL” 让人搞不懂是什么意思。

**Expected behavior**
希望修改termsOfServiceUrl标签的翻译

**Screenshots**
![image](https://user-images.githubusercontent.com/8558204/221614489-fa970c4c-55f2-47c6-930d-d5e8d50e290f.png)

**Knife4j Version (please complete the following information):** 4.0.0

**Additional context**

**Comment by xiaoymin** [comment]
|Field Name | Type | Description|
-- | -- | --
title | string | Required. The title of the application.
description | string | A short description of the application. GFM syntax can be used for rich text representation.
termsOfService | string | The Terms of Service for the API.
contact | Contact Object | The contact information for the exposed API.
license | License Object | The license information for the exposed API.
version | string | Required Provides the version of the application API (not to be confused with the specification version).
 

用百度翻译：API的服务条款


后面改成这个吧

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/knife4j/commit/646cdb5efdce7f6043cbcf488173287ea48f099f
