### ISSUE TITLE
@Parameter 的required无效

### ISSUE THREAD

**Issue by q1055145251** [xiaoymin/knife4j#541]
**Describe the bug**
@Parameter 的required无效

**To Reproduce**
@Parameter 的required无效

**Expected behavior**
设置了required=false后应该变为选填但是还是必填

**Screenshots**
![image](https://user-images.githubusercontent.com/26460127/221783624-9c4405af-0e2e-4a43-82ec-d31812e62f69.png)
![image](https://user-images.githubusercontent.com/26460127/221783681-140ed411-3a52-4d27-81a7-a45180af7280.png)

**Knife4j Version (please complete the following information):**
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.0.0</version>
        </dependency>
springboot版本3.0.2

**Comment by xiaoymin** [comment]
我测试了一下，springdoc框架针对Spring做了处理，如果我们的代码是这样：

```java
@Operation(summary = "普通body请求+Param+Header")
    @Parameters({
            @Parameter(name = "token",description = "请求token",required = true,in = ParameterIn.HEADER),
            @Parameter(name = "name",description = "文件名称",required = false,in=ParameterIn.QUERY)
    })
    @PostMapping("/bodyParamHeader")
    public ResponseEntity<FileResp> bodyParamHeader(@RequestHeader("token") String token, @RequestParam(value = "name")String name,@RequestBody FileResp fileResp){
        fileResp.setName(fileResp.getName()+",receiveName:"+name+",token:"+token);
        return ResponseEntity.ok(fileResp);
    }

```

虽然给`name`参数设置了required=false的属性，但是我们的接口实际上还是需要传参的，也就是必出传，springdoc在解析得到的OpenAPI规范里面，就是true，和`@Parameter`注解有差别的，应该是springdoc默认以框架为主了

如果代码改成这样：
```java
@Operation(summary = "普通body请求+Param+Header")
    @Parameters({
            @Parameter(name = "token",description = "请求token",required = true,in = ParameterIn.HEADER),
            @Parameter(name = "name",description = "文件名称",required = false,in=ParameterIn.QUERY)
    })
    @PostMapping("/bodyParamHeader")
    public ResponseEntity<FileResp> bodyParamHeader(@RequestHeader("token") String token, @RequestParam(value = "name",required = false)String name,@RequestBody FileResp fileResp){
        fileResp.setName(fileResp.getName()+",receiveName:"+name+",token:"+token);
        return ResponseEntity.ok(fileResp);
    }

```

在`@RequestParam(value = "name",required = false)`注解中设置了false，那么springdoc解析得到的OpenAPI规范就是false

![image](https://user-images.githubusercontent.com/7894406/222871854-f2131604-1637-4acb-ba0b-0a133ea1c6c4.png)

在Knife4j的界面中也是false

![image](https://user-images.githubusercontent.com/7894406/222871874-d5b48b4b-03bf-4bb4-aa8c-be888460ecc9.png)

你可以确认一下
