### ISSUE TITLE
knife4j2.0.9 同时使用RequestBody和文件上传，不显示文件选择域

### ISSUE THREAD

**Issue by valllwj** [xiaoymin/knife4j#544]
**Describe the bug**
如果一个接口同时存在@RequestBody和@RequestParam文件上传，文件选择域不显示，去掉了@RequestBody就可以显示

**Expected behavior**
1、带@RequestBody
![QQ截图20230308170307](https://user-images.githubusercontent.com/9146230/223672839-0906d4cf-5b58-4cf3-918f-f3f8d320d462.png)
![QQ截图20230308170230](https://user-images.githubusercontent.com/9146230/223672897-e64a8dca-bcf5-4111-a343-b14b9d77a63f.png)

2、不带@RequestBody
![QQ截图20230308170334](https://user-images.githubusercontent.com/9146230/223672952-cf5631ba-17bf-4dc5-b329-1a5a3b020b18.png)
![QQ截图20230308170356](https://user-images.githubusercontent.com/9146230/223672971-205ab990-b8a0-438d-9cd6-7dd759186746.png)

**Knife4j Version (please complete the following information):**
```
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-spring-boot-starter</artifactId>
	<version>2.0.9</version>
</dependency>
```

**Comment by xiaoymin** [comment]
试试看4.0版本呢？

https://doc.xiaominfo.com/docs/upgrading/upgrading-to-v4

**Comment by valllwj** [comment]
> 试试看4.0版本呢？
> 
> https://doc.xiaominfo.com/docs/upgrading/upgrading-to-v4

这个奇葩需求应该是不合理的，最后把数据放到参数query里解决了，之前是因为请求数据类型被自动识别为application/json，所以无法显示文件选择域
