### ISSUE TITLE
knife4j-dependencies缺少swagger-annotations-jakarta依赖

### ISSUE THREAD

**Issue by leftnine** [xiaoymin/knife4j#546]
**Describe the bug**
依赖管理里添加 knife4j-dependencies 依赖后,子module依赖swagger的注解时只能依赖 swagger-annotations, 不能依赖 swagger-annotations-jakarta, 导致在实体类上的@Schema 注解缺少 requiredMod() 方法, 服务如果依赖了 knife4j-openapi3-jakarta-spring-boot-starter 启动后访问文档页面会报 NoSuchMethodError 错误

**Expected behavior**
在 knife4j-dependencies 中添加 swagger-annotations-jakarta 依赖

**Screenshots**

**Knife4j Version (please complete the following information):**
4.0.0

**Additional context**

**Comment by leftnine** [comment]
knife4j-gateway-spring-boot-starter 依赖是否也可以加入 knife4j-dependencies 管理里

**Comment by xiaoymin** [comment]
感谢反馈，会在[4.1版本](https://github.com/xiaoymin/knife4j/milestone/2)中加入进去
