### ISSUE TITLE
list套list的返回值会不显示

### ISSUE THREAD

**Issue by xyqasunyang** [xiaoymin/knife4j#55]
只能list套实体，实体里再写list，原生ui是正常的....

**Comment by xiaoymin** [comment]
贴个代码 结构？

**Comment by xyqasunyang** [comment]
![image](https://user-images.githubusercontent.com/17777767/50511107-3fffa900-0ac7-11e9-8a84-5b48ee4af9be.png)
![image](https://user-images.githubusercontent.com/17777767/50511120-5443a600-0ac7-11e9-8b52-ba3cc5dae4ce.png)
TemplateFormValues就不会显示

**Comment by xiaoymin** [comment]
试试1.8.9
