### ISSUE TITLE
分页对象，结构不显示

### ISSUE THREAD

**Issue by LeoLB-Wang** [xiaoymin/knife4j#551]
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.9</version>
        </dependency>

      <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.5.RELEASE</version>
knife4j：版本2.0.9  spring-boot:版本：2.3.5

接口controller代码：
![image](https://user-images.githubusercontent.com/43638251/225627182-b62cf949-e39b-4f63-93b6-194bcf0ef711.png)
Result代码：
![image](https://user-images.githubusercontent.com/43638251/225627335-ce091aac-3bbb-4e9e-8360-1badb6b78689.png)
PageResult代码：
![image](https://user-images.githubusercontent.com/43638251/225627002-b7d80d87-fad5-48ec-8867-ce69821a5522.png)
HtApplyAwardPageVo代码：
![image](https://user-images.githubusercontent.com/43638251/225627473-15be377b-a0e1-491a-9ec2-0dae7de22dae.png)
接口文档截图：
![image](https://user-images.githubusercontent.com/43638251/225628091-2ed9fee9-0031-41c0-8564-04ee56eb900a.png)

**Comment by xiaoymin** [comment]
可以考虑升级下用4.0.0的版本

**Comment by xiaoymin** [comment]
泛型类不用写ApiModel或者Schema注解，参考
https://doc.xiaominfo.com/docs/faq/swagger-des-not-found
