### ISSUE TITLE
微服务环境下gateway集成Knife4j时，无法对文档设置帐号密码

### ISSUE THREAD

**Issue by AAAzhen** [xiaoymin/knife4j#555]
如题

**Comment by xiaoymin** [comment]
其实这个功能在子服务Servlet体系下是通过Filter来实现。放网关是否有必要哦

**Comment by xander-os** [comment]
knife4j的autoConfigure没作用，没配置上BasicFilter。可能得自己做一套校验了

**Comment by xander-os** [comment]
> knife4j的autoConfigure没作用，没配置上BasicFilter。可能得自己做一套校验了

是说Gateway，是基于webflux的

**Comment by xiaoymin** [comment]
> knife4j的autoConfigure没作用，没配置上BasicFilter。可能得自己做一套校验了

是的，本来就没有做的

**Comment by bowenchang** [comment]
你就是懒，几行代码的事，非得自己写。

@Configuration
@EnableWebFluxSecurity
public class SwaggerSecurityConfigurer {

	@Bean
	public SecurityWebFilterChain securityFilterChain(ServerHttpSecurity httpSecurity) {
		return httpSecurity.authorizeExchange()
			.pathMatchers("/doc.html").authenticated().anyExchange().permitAll()
			.and().httpBasic().and().csrf().disable().cors().disable().build();

	}

}

**Comment by xander-os** [comment]
> knife4j的autoConfigure没作用，没配置上BasicFilter。可能得自己做一套校验了

我在knife4j-gateway-spring-boot-starter聚合模块增加了对文档路径的权限校验，思路和core模块的ServletSecurityBasicAuthFilter类实现基本一致。
