### ISSUE TITLE
Knife4jHttpBasic没有加@ConfigurationProperties注解，导致开启BasicHttp验证后的配置文件无法解析配置属性 'knife4j.basic.username' 

### ISSUE THREAD

**Issue by win301** [xiaoymin/knife4j#556]
![image](https://user-images.githubusercontent.com/8447708/227937589-4931984c-77c3-4195-be5f-8a197832db98.png)

**Comment by xiaoymin** [comment]
4.1版本吗

**Comment by win301** [comment]
是的
implementation("com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.1.0")

**Comment by xiaoymin** [comment]
4.2已加
