### ISSUE TITLE
在微服务中配置了请求头部，网关聚合后，调试中请求头部的缺失

### ISSUE THREAD

**Issue by shenstack** [xiaoymin/knife4j#560]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shenstack** [comment]
![image](https://user-images.githubusercontent.com/32202815/230240847-a694d65f-6d12-4ca2-b266-b630766b10ce.png)

**Comment by xiaoymin** [comment]
version？

**Comment by liujishui87** [comment]
knife4j-openapi3-jakarta-spring-boot-starter  使用这个请求头出不来，请求头配置方式如下：
@Bean
    public OpenAPI openAPI() {
        return new OpenAPI().info(apiInfo())
                .externalDocs(new ExternalDocumentation() // 外部文档
                        .description("SpringDoc Wiki Documentation")
                        .url("https://springdoc.org/v2")).addSecurityItem(new SecurityRequirement().addList(HttpHeaders.AUTHORIZATION))
                .components(new Components().addSecuritySchemes(HttpHeaders.AUTHORIZATION,new SecurityScheme()
                        .name(HttpHeaders.AUTHORIZATION).type(SecurityScheme.Type.HTTP).scheme("bearer")));
    }
