### ISSUE TITLE
@Parameter(required = false) required为false不起作用

### ISSUE THREAD

**Issue by TsukasaHwan** [xiaoymin/knife4j#562]
SpringDocOpenApi为啥@Parameter(required = false) required为false不起作用，还是得必传？
![1681265424576](https://user-images.githubusercontent.com/46735688/231329531-aa7fe630-c980-460d-87bc-036e95fc9faf.png)
![1681265448953](https://user-images.githubusercontent.com/46735688/231329578-15c5c849-4f2c-4242-86df-429bea070ee5.png)

**Comment by xiaoymin** [comment]
https://gitee.com/xiaoym/knife4j/issues/I7H44S
