### ISSUE TITLE
get 对象传参出错

### ISSUE THREAD

**Issue by zclcs** [xiaoymin/knife4j#564]
**Knife4j Version (please complete the following information):**
4.1.0
![image](https://user-images.githubusercontent.com/50291896/231644717-e243c3ae-e2d1-429a-b7cc-64a49718023b.png)
![image](https://user-images.githubusercontent.com/50291896/231644869-6608db4f-44d1-4b74-9403-7d7603d00fb0.png)

**Comment by xiaoymin** [comment]
传参应该是form，但是目前阶段 不太想改这个，可以看看这篇文章 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

**Comment by zclcs** [comment]
> 
谢谢解答
