### ISSUE TITLE
响应类设置了nullable=true 但是ts生成没有对应

### ISSUE THREAD

**Issue by q1055145251** [xiaoymin/knife4j#568]
**Describe the bug**
响应类设置了nullable=true 但是ts生成没有对应

**Screenshots**
![image](https://user-images.githubusercontent.com/26460127/234457100-84ee3ef6-77b7-4b76-85c9-5ec53ca79ca2.png)

**Knife4j Version (please complete the following information):**
<dependency>
                <groupId>com.github.xiaoymin</groupId>
                
                <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
                <version>4.0.0</version>
            </dependency>

**Comment by xiaoymin** [comment]
响应接口的interface 我觉得就不标了吧 ，目前只标请求body，用的require属性
