### ISSUE TITLE
knife4j-openapi3-spring-boot-starter 4.1.0 页面出错

### ISSUE THREAD

**Issue by ulwx** [xiaoymin/knife4j#572]
使用的是springboot 2.7.10，依赖如下：		
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
	<version>4.1.0</version>
</dependency>
  产生的错误如下：
![image](https://user-images.githubusercontent.com/78004279/237050942-1a831022-e28f-43f8-8fb3-209f2b524e11.png)

![image](https://user-images.githubusercontent.com/78004279/237051690-70829dbf-8fd2-4224-8166-8adaeb6e30f9.png)

**Comment by xiaoymin** [comment]
参考下：https://doc.xiaominfo.com/docs/faq/knife4j-exception
