### ISSUE TITLE
aggregation disk模式下，没有实时获取配置文件内容

### ISSUE THREAD

**Issue by Jamel-jun** [xiaoymin/knife4j#575]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
aggregation disk模式下，没有实时获取配置文件内容
应用启动时就将文件读取到内存中，进行了初始化，是否可以支持文件刷新机制。
取文件修改时间跟上次时间对比，一致就走缓存，如果不一致则刷新缓存？

**Comment by xiaoymin** [comment]
会有频率刷新的，不是实时

**Comment by Jamel-jun** [comment]
> 会有频率刷新的，不是实时

好的，谢谢作者回答。
请问下频率是多少呢，该机制的实现是在哪个模块里面呢，我好像没有找到，不好意思😬

**Comment by xiaoymin** [comment]
> > 会有频率刷新的，不是实时
> 
> 好的，谢谢作者回答。 请问下频率是多少呢，该机制的实现是在哪个模块里面呢，我好像没有找到，不好意思😬

sorry，我记混淆了，disk模式没有，在单组件中，只有nacos、cluod等模式中开了守护线程定时去同步的

在[knife4jInsight](https://doc.xiaominfo.com/docs/middleware-sources/desktop-introduction) 独立中间件里面是做了频率同步更新加载的
