### ISSUE TITLE
请问一下怎么去掉左侧菜单栏的蓝色小点点

### ISSUE THREAD

**Issue by SincerelyUnique** [xiaoymin/knife4j#576]
感谢作者提供这么好的工具！
有个问题请教下，请问一下怎么去掉左侧菜单栏的蓝色小点点 :)

![image](https://github.com/xiaoymin/knife4j/assets/16249717/ee4e597f-ea64-4214-bcd1-e899623ef44b)

**Comment by SincerelyUnique** [comment]
补充一下，用的是
```xml
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.3</version>
</dependency>
```

**Comment by xiaoymin** [comment]
版本有点老啊。可以考虑升级一下
新版本中在增强模式中，有这个开关的控制选项
https://doc.xiaominfo.com/docs/features/enhance

**Comment by SincerelyUnique** [comment]
> 版本有点老啊。可以考虑升级一下 新版本中在增强模式中，有这个开关的控制选项 https://doc.xiaominfo.com/docs/features/enhance

好滴，谢谢回复~
