### ISSUE TITLE
knife4j版本4.1.0整合最新springboot3和聚合网关get请求调试参数不正确

### ISSUE THREAD

**Issue by haioa** [xiaoymin/knife4j#579]
通过官网demo列子，发现get请求文档请求调试显示的参数不正确，点击按钮后后端无法接受
![image](https://github.com/xiaoymin/knife4j/assets/70361259/d003b6d0-fad9-4b61-8ff8-0f1da15d4c23)
页面展示
![image](https://github.com/xiaoymin/knife4j/assets/70361259/0288555c-a4d4-422a-bc97-2f99acd97907)
以前的版本是可以正常展示调试参数和发送正常请求参数
![image](https://github.com/xiaoymin/knife4j/assets/70361259/5d8dcff1-70f7-4732-a517-666b45ecacfe)

**Comment by xiaoymin** [comment]
在用springdoc-openapi作为解析后，实体是这样的，虽然在官方的swagger-ui中，会把一个json传解析成form进行debug调试发送，但如果实体类层级较升的话，我觉得这样反而是多此一举。所以前端ui就没解析。

导致这个原因：

1、springdoc-openapi解析form类型的实体，会弄成json的形式，如果想恢复之前的方式，参考：https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

2、前端ui成在官方的swagger-ui中会将json解析成form然后提交(调试的时候)，这个knife4j前端就不处理了，原因上面解释了
