### ISSUE TITLE
HttpRequestHandler  生成的接口有办法生成接口文档吗？

### ISSUE THREAD

**Issue by cqzaiercn** [xiaoymin/knife4j#580]
` class SimpleHttpRequestHandler implements HttpRequestHandler {

 public void handleRequest(HttpServletRequest request, HttpServletResponse response){
  // 处理请求
}

}`

我有办法添加HttpRequestHandler 接口地址吗?

**Comment by cqzaiercn** [comment]
// 注册处理器
    private void registerHandler(BeanDefinitionRegistry registry, String requestMappingPath) {
        BeanDefinitionBuilder builder = BeanDefinitionBuilder.genericBeanDefinition(SimpleHttpRequestHandler.class);
        builder.addPropertyValue("requestMappingPath", requestMappingPath);
        // 设置beanDefinition构造方法的参数
        String[] beanNamesForType = applicationContext.getBeanNamesForType(this.getClass());
        builder.addConstructorArgReference(beanNamesForType[0]);
        BeanDefinition beanDefinition = builder.getBeanDefinition();

        registry.registerBeanDefinition(requestMappingPath, beanDefinition);
    }

我是通过bean的名称生成的请求路径


![image](https://github.com/xiaoymin/knife4j/assets/37819946/aa3cf89f-d5b2-470d-ac5d-87c7c829711c)

**Comment by cqzaiercn** [comment]
是否有api 操作添加接口文档？

**Comment by xiaoymin** [comment]
核心就是添加api就可以了，后端如果用springfox，参考：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot27-demo/src/main/java/com/knife4j/demo/config/SwaggerManualApiConfiguration.java

如果是用springdoc，可以参考springdoc开放的customers接口，构建一个api对象实现注入，类似Knife4j提供增强的方法一样，参考代码：https://gitee.com/xiaoym/knife4j/blob/dev/knife4j/knife4j-openapi3-jakarta-spring-boot-starter/src/main/java/com/github/xiaoymin/knife4j/spring/extension/Knife4jJakartaOperationCustomizer.java

不过这个是Operation属性级别的，你要改为Operation接口级别

**Comment by cqzaiercn** [comment]
@xiaoymin 接口不是通过@RequestMapping的方式生成的？ 有手动加api接口方式吗

**Comment by xiaoymin** [comment]
> @xiaoymin 接口不是通过@RequestMapping的方式生成的？ 有手动加api接口方式吗

我上面回复的不就是手动加的么

**Comment by xiaoymin** [comment]
参考blog：https://doc.xiaominfo.com/docs/blog/customer-add-api
