### ISSUE TITLE
yarn install安装vue2版的前端代码无法启动

### ISSUE THREAD

**Issue by aa1050532409** [xiaoymin/knife4j#584]
为什么用yarn install安装那个vue2的前端代码会出现依赖冲突。。。是对node和npm版本有要求还是啥吗。。

**Comment by xiaoymin** [comment]
不知道你什么错误，我也无法判断，node就按提示的 用新的没啥问题，我本地是18.0

或者这个issue导致的也可以看看：https://gitee.com/xiaoym/knife4j/issues/I775XQ
