### ISSUE TITLE
Swagger Models 名称显示异常

### ISSUE THREAD

**Issue by Mr-LiuDC** [xiaoymin/knife4j#585]
knife4jVersion： 2.0.9
springCloudVersion： Hoxton.SR9
springBootVersion： 2.3.7.RELEASE

之前没发现有这个问题，不知什么情况产生的。Swagger Models中发现个别实体对象或者枚举对象会多出一个，具体情况可看截图。

<img width="299" alt="1685845618787" src="https://github.com/xiaoymin/knife4j/assets/18117854/07414500-4bc3-4c42-a658-3867bca6e781">
<img width="284" alt="1685845637570" src="https://github.com/xiaoymin/knife4j/assets/18117854/7ed06125-63b0-4e86-bd5c-d6150cdacde6">

**Comment by xiaoymin** [comment]
这个估计是和你用了一些热加载插件有关系

**Comment by Mr-LiuDC** [comment]
> 这个估计是和你用了一些热加载插件有关系

应该不是热加载导致的，首次启动后也会有这个问题

Swagger 官方UI也有这个问题。
