### ISSUE TITLE
nginx 反向代理 uri叠上叠

### ISSUE THREAD

**Issue by pastors-top** [xiaoymin/knife4j#586]
![图片](https://github.com/xiaoymin/knife4j/assets/71577061/13d36063-7fa5-48c2-865c-68c425726db1)

![图片](https://github.com/xiaoymin/knife4j/assets/71577061/1411c965-c27a-422a-9558-344c563e37b4)

**Comment by pastors-top** [comment]
knife4j-gateway-spring-boot-starter 4.1.0

**Comment by pastors-top** [comment]
com.github.xiaoymin.knife4j.spring.gateway.endpoint.OpenAPIEndpoint#swaggerConfig
看源码感觉是这里出了问题  每刷新一次都会把 Referer 重新拼接到缓存里
![图片](https://github.com/xiaoymin/knife4j/assets/71577061/42845644-ffcb-44fd-ac6d-a138bb8144f8)

**Comment by xiaoymin** [comment]
> com.github.xiaoymin.knife4j.spring.gateway.endpoint.OpenAPIEndpoint#swaggerConfig 看源码感觉是这里出了问题 每刷新一次都会把 Referer 重新拼接到缓存里 ![图片](https://user-images.githubusercontent.com/71577061/243708784-42845644-ffcb-44fd-ac6d-a138bb8144f8.png)

对，是这里的问题，老哥，来个PR吗

**Comment by pastors-top** [comment]
> > com.github.xiaoymin.knife4j.spring.gateway.endpoint.OpenAPIEndpoint#swaggerConfig 看源码感觉是这里出了问题 每刷新一次都会把 Referer 重新拼接到缓存里 ![图片](https://user-images.githubusercontent.com/71577061/243708784-42845644-ffcb-44fd-ac6d-a138bb8144f8.png)
> 
> 对，是这里的问题，老哥，来个PR吗

这段逻辑是为了解决什么样子的场景

**Comment by edwarddamon** [comment]
也遇到了这个问题，给我整麻了

**Comment by pastors-top** [comment]
> 也遇到了这个问题，给我整麻了

已经提了pr
