### ISSUE TITLE
lombok依赖问题

### ISSUE THREAD

**Issue by inism-cn** [xiaoymin/knife4j#591]
<dependency>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <scope>provided</scope>
    <optional>true</optional>
</dependency>

**Comment by xiaoymin** [comment]
那个模块？

**Comment by inism-cn** [comment]
core 模块的
https://github.com/xiaoymin/knife4j/blob/dev/knife4j/pom.xml  [line:112]
