### ISSUE TITLE
post请求，form-data类型，请求后带入莫名奇妙内容

### ISSUE THREAD

**Issue by gffguo** [xiaoymin/knife4j#595]
版本：
springboot == 2.6.14
org.springdoc == 1.7.0
knife4j-openapi3-spring-boot-starter == 4.1.0

如下图所示，导致我页面直接400
示意图
![image](https://github.com/xiaoymin/knife4j/assets/69896971/54d78e3e-597d-4d3f-96a6-fbd6893cdea9)

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

**Comment by gffguo** [comment]
喔~感谢大佬

**Comment by gffguo** [comment]
感谢大佬；

**Comment by gffguo** [comment]
感谢大佬；
我目前用的是我们得最新版本Knife4j 4.1.0（Knife4j-openapi3-spring-boot-starter）；
我尝试后发现，不管是springdoc添加注解@ParameterObject 或者配置default-flat-param-object=true好像都没有效果，我该如何去做，才能找到更多信息来一起去定位问题

pom文件中，只引入了Knife4j ，没有单独添加springdoc、Swagger、springfox等等其他包
![image](https://github.com/xiaoymin/knife4j/assets/69896971/6ee2d6eb-53fc-4da1-832a-1066d4adc744)

**Comment by xiaoymin** [comment]
org.springdoc == 1.7.0？

如果单独引入了springdoc，也许会有冲突。这个功能是springdoc提供的，knife4j只是按规范解析渲染

如果服务端的实体类被渲染到openapi规范是一个json，本身又不是json提交，那应该找找是不是springdoc在版本、boot框架适配上有了问题

每个人碰到的问题是一样的，但是每个人使用的版本，环境是不一样的。所以我也没法提供太多

**Comment by gffguo** [comment]
好的。感谢大佬
