### ISSUE TITLE
allowableValues 设置为 range时，页面无法正确展示“可用值”

### ISSUE THREAD

**Issue by shenhuaxx** [xiaoymin/knife4j#596]
**Describe the bug**
allowableValues 设置为 range时，页面无法正确展示“可用值”；当设置为按","分隔时能正常展示。
例如：
@ApiModelProperty(value = "xx", allowableValues = "range[0, 100]", example = "1")   不能展示"可用值"

@ApiModelProperty(value = "xx", allowableValues = ".25, .5, 1", example = "1")  能正常展示"可用值"

**版本**
knife4j-spring-boot-starter:2.0.9和knife4j-openapi2-spring-boot-starter:4.1.0均可见。
对应springfox-swagger2版本  2.9.2

**Comment by shenhuaxx** [comment]
springfox-swagger2版本  2.10.5也不能正常展示

**Comment by xiaoymin** [comment]
我测了一下，springfox响应的swagger2规范里面，针对range这种，会处理成类似JSR303的信息

![image](https://github.com/xiaoymin/knife4j/assets/7894406/370dc721-3bbe-4f47-b428-994fb71fe0ee)

在knife4j的界面中，只能和直接jsr303注解一样的处理方式：

![image](https://github.com/xiaoymin/knife4j/assets/7894406/de5ad41d-ca26-42e3-af30-fb2b667c82b2)

这种情况也没法在调试里面做成下拉框吧，第二种逗号分割的情况，处理成了enum，通过下拉框展示，枚举是穷举数量可控，如果开发者设置一个range，0-10000，那界面通过下拉框来展示很明显不合适
