### ISSUE TITLE
使用自定义Accept、Content-Type时，响应内容识别错误

### ISSUE THREAD

**Issue by holylcd** [xiaoymin/knife4j#597]
**Describe the bug**
使用Accept、Content-Type做API版本控制时，响应内容识别错误

**To Reproduce**
请求
<img width="795" alt="WechatIMG397" src="https://github.com/xiaoymin/knife4j/assets/34299400/a1507e66-1c32-4e57-835b-9bb4cd45d9e8">
响应
<img width="622" alt="WechatIMG395" src="https://github.com/xiaoymin/knife4j/assets/34299400/ae10ab70-1867-43a8-8138-961265d23642">
<img width="421" alt="WechatIMG396" src="https://github.com/xiaoymin/knife4j/assets/34299400/6d28c7da-9a89-48c7-9731-e9abf81a1c26">
请求响应正常，但无法识别 application/vnd.xx+json 格式，并显示按钮：下载文件

**Knife4j Version (please complete the following information):**
knife4j-openapi3-jakarta-spring-boot-starter 4.1.0
knife4j-spring-boot-starter 3.0.3

**Comment by xiaoymin** [comment]
可以贴一下后台代码吗？方便后面复现此问题

**Comment by holylcd** [comment]
感谢回复

以下为后台代码例子

spring mvc 定义一个 controller，指定 produces = `application/vnd.dim.s.v1+json`，此时 Accpet、响应头 Content-Type 为 `application/vnd.dim.s.v1+json`
<img width="847" alt="image" src="https://github.com/xiaoymin/knife4j/assets/34299400/cb7b5a8d-c1fa-40a1-8482-1ae2ea7f2f1f">

**Comment by xiaoymin** [comment]
`application/vnd.dim.s.v1+json`这个是自定义的吧？我看标准的MIME类型里面没这个东西？

产生这个原因是在OpenAPI3的规范中，Knife4j都加了stream的请求导致的，
```java
    if (res.data.type == "application/json" ||
                res.data.type == "application/xml" ||
                 res.data.type == "text/html" ||
                 res.data.type == "text/plain") {
```

限定了这些类型，在response处理的时候

后面4.3.0加上一个indexOf方法校验一下json算了
```javascript
assertProducesJson(produces) {
    if (!this.checkUndefined(produces)) {
      return false;
    }
    // 追加一个自定义json的MIME类型实现，issues：https://github.com/xiaoymin/knife4j/issues/597
    // MIME类型是：application/vnd.dim.s.v1+json
    //  "application/vnd.dim.s.v1+json" 是一种自定义的MIME类型，其中的 "vnd.dim.s.v1" 表示可能是某个特定厂商、组织或项目的标识符、版本，而 "application/json" 则是标准的JSON数据格式的MIME类型。
    // 针对OpenAPI3的规范,由于统一添加了blob类型，此处需要判断
    if (produces == "application/json" ||
      produces == "application/xml" ||
      produces == "text/html" ||
      produces == "text/plain") {
      return true;
    } else {
      //判断自定义扩展的MIME类型
      // application/vnd.dim.s.v1+json
      if (produces.toLowerCase().indexOf("json") > -1) {
        return true;
      }
    }
    return false;
  }

```

**Comment by holylcd** [comment]
感谢适配

有这个MIME类型的哈
可用于 API 版本控制
https://www.iana.org/assignments/media-types/application/vnd.api+json

期待 indexOf

**Comment by xiaoymin** [comment]
> 感谢适配
> 
> 有这个MIME类型的哈 可用于 API 版本控制 https://www.iana.org/assignments/media-types/application/vnd.api+json
> 
> 期待 indexOf

学习了，明天4.3.0会发掉
