### ISSUE TITLE
knife4j-openapi3-spring-boot-starter产生很多不存在类的schema

### ISSUE THREAD

**Issue by john1337** [xiaoymin/knife4j#598]
现在所有controller都会返回统一的数据结构，比如ApiResut<ClassA>、ApiResult<ClassB>，在knife4j-openapi3-spring-boot-starter生成的model中就会有很不存在的schema，比如ApiResutClassA、ApiResutClassB，这样所有的controller就会额外生成很多类似的schema，加载速度就会很慢，不知openapi3是否有对应的配置禁止生成ApiResutClassA这种复合schema的生成。

**Comment by xiaoymin** [comment]
可以去看看springdoc的文档

**Comment by john1337** [comment]
不是问题，顾不需要解决
