### ISSUE TITLE
knife4j-gateway-spring-boot-starter支持webflux吗

### ISSUE THREAD

**Issue by SileeLiu** [xiaoymin/knife4j#599]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Knife4j Version (please complete the following information):**

**Additional context**

**Comment by SileeLiu** [comment]
knife4j-gateway-spring-boot-starter支持webflux吗

**Comment by xiaoymin** [comment]
网关聚合，应该和webflux无关吧？这里你说的webflux我理解是两层意思：
1、子服务是webflux写的，那聚合应该只需要提供地址就可以了

2、网关层存在接口，webflux的。那目前是不支持的。会和springdoc框架冲突，knife4j-gateway提供得开放聚合分组接口与之冲突

**Comment by SileeLiu** [comment]
好的，了解啦
