### ISSUE TITLE
参数required = false无效

### ISSUE THREAD

**Issue by yidao620c** [xiaoymin/knife4j#6]
@ApiModelProperty注解里面不管设置required是true，还是false，生成出来doc页面，是否必须这一列总是true。

**Comment by xiaoymin** [comment]
你好，原始传参,如果使用的是

public RestMessage reqbody(@RequestBody ReqEntity reqEntity)  
这种接收实体类的，即使ReqEntity对象定义ApiModelProperty，因为swagger解析出来的json没有该字段，所以展现出来默认给处理成true了
如果用参数的形式 比如

public RestMessage deletetest(@RequestParam(value = "code") String code)  
这种，设置required是有效的
这里我是改成将实体类字段解析出来，针对写了ApiModelProperty注解的中文字段解析出来
swagger的默认ui处理就是一个json，字段没有列出

**Comment by AKcheng** [comment]
以上问题我已经修改过DApiUI.js来修复此问题，已实现@ApiModelProperty注解中required无效的问题，同时增加了example显示列，当然修改以上代码是不够的，还需要修改后台代码，后台代码可以参考我的文章
https://my.oschina.net/honesty/blog/1838007
@yidao620c @xiaoymin 
![swagger-bootstrap-ui](https://user-images.githubusercontent.com/16603416/42104310-a6004604-7bfe-11e8-86d8-4298265179d9.png)

**Comment by xiaoymin** [comment]
根据swagger的响应，目前已可以显示，使用版本1.7.7，欢迎升级反馈，谢谢：）
谢谢@AKcheng的建议

**Comment by einsitang** [comment]
@xiaoymin 

```xml
<dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-spring-boot-starter</artifactId>
      <version>2.0.5</version>
</dependency>
```

也存在上述问题。

如果我试用@PostMapping和@RequestBody的方式定义rest api接口，doc.html上的 Swagger Models 显示属性都是`false`,我看到接口上有单独的`required`字段，并且也和@ApiModelProperty定义的一致。

请问这个版本可以解决吗？我们正在使用`springboot 2.1.18`

**Comment by wanbolantian** [comment]
我用的2.0.5 版本，也是存在不能显示 required=true的情况

Spring boot 版本
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
    </parent>

knife4j版本
 <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>2.0.5</version>
   </dependency>

实体类定义
![image](https://user-images.githubusercontent.com/20452742/139218966-9ac491cd-4637-4dfc-8c1d-96f4fef7f81e.png)

**Comment by xiaoymin** [comment]
> 我用的2.0.5 版本，也是存在不能显示 required=true的情况
> 
> Spring boot 版本 org.springframework.boot spring-boot-starter-parent 2.1.7.RELEASE
> 
> knife4j版本 com.github.xiaoymin knife4j-spring-boot-starter 2.0.5
> 
> 实体类定义 ![image](https://user-images.githubusercontent.com/20452742/139218966-9ac491cd-4637-4dfc-8c1d-96f4fef7f81e.png)

2.0.5存在这个bug，后面的版本修复了，可以参考一下版本日志

https://xiaoym.gitee.io/knife4j/changelog/

另外如果Spring Boot的版本太低，可以考虑单纯用新版本的ui，排除掉老的，例如

```xml

<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-spring-boot-starter</artifactId>
	<exclusions>
              <!--排除老的->
		<exclusion>
			<groupId>com.github.xiaoymin</groupId>
			<artifactId>knife4j-spring-ui</artifactId>
		</exclusion>
	</exclusions>
</dependency>

 <!--使用新的->
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-spring-ui</artifactId>
       <version>2.0.9</version>
</dependency>


```
