### ISSUE TITLE
高版本Boot3 + Gradle运行Aggregation项目报错：Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter / Caused by: java.lang.ClassNotFoundException: jakarta.servlet.Registration$Dynamic

### ISSUE THREAD

**Issue by hikimy** [xiaoymin/knife4j#600]
1. 环境：
    a. Gradle
    b. Spring Boot3.0.2（从2.7.6升级到3.0.2）
    c. knife4JAggregationSpringBootStarter4.0.1

2. 问题详细描述
    使用上述环境运行搭建Aggregation项目并运行时，就会出现第一个错误：Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter，这是由于缺少了   低版本tomcat-embed-core依赖所导致的（我这边使用9.0.67版本可解决这个问题）。
   第二个报错：Caused by: java.lang.ClassNotFoundException: jakarta.servlet.Registration$Dynamic是由于缺少   高版本tomcat-embed-core依赖所导致的，而这两个又不可同时存在！
    请问这该如何解决？

3. 错误日志
[aLog.txt](https://github.com/xiaoymin/knife4j/files/11907828/aLog.txt)
[bLog.txt](https://github.com/xiaoymin/knife4j/files/11907830/bLog.txt)

**Comment by xiaoymin** [comment]
knife4JAggregation 目前不支持spring boot 3

**Comment by hikimy** [comment]
knife4JAggregation很赞，可惜现在没有支持Spring Boot 3版本，不知后续是否会支持

**Comment by xiaoymin** [comment]
> knife4JAggregation很赞，可惜现在没有支持Spring Boot 3版本，不知后续是否会支持

我以前写这个模块的时候，是因为很多人问spring cloud gateway网关集合的问题，而gateway又因为版本更新快，异步、微服务分布式等等问题，导致大家碰到的问题可以说是千奇百怪。

所以我就写了一个在Servlet体系下能任意聚合的组件,希望聚合简单一点，这就是knife4JAggregation的由来了。

不过在后面，我还是提供了spring cloud gateway网关下的聚合组件[knife4j-gateway](https://doc.xiaominfo.com/docs/middleware-sources/spring-cloud-gateway/spring-gateway-introduction)。目的都是希望能够简化聚合的流程，使用起来，学习成本没那么高。

这2个组件其实有点耦合的。如果都是gateway网关的话，我觉得[knife4j-gateway](https://doc.xiaominfo.com/docs/middleware-sources/spring-cloud-gateway/spring-gateway-introduction)可能会更受用一点

至于knife4JAggregation，在思想上我已经把他独立出来了。后面的重心应该会往[Knife4jInsight](https://doc.xiaominfo.com/docs/middleware-sources/desktop-introduction)这个独立的平台中去整合,Knife4jInsight的功能已经完全把knife4JAggregation的功能copy过来了。只是他是一个独立的服务平台

**Comment by hikimy** [comment]
好的，我这边也去了解[Knife4jInsight](https://doc.xiaominfo.com/docs/middleware-sources/desktop-introduction)，
感谢您耐心回答
