### ISSUE TITLE
4.0.0版本通过代理请求 /v3/api-docs/v1这个接口会把url的前缀去掉

### ISSUE THREAD

**Issue by rcf666** [xiaoymin/knife4j#603]
**Describe the bug**
4.0.0版本通过代理请求 /v3/api-docs/v1这个接口会把url的前缀去掉

**Comment by xiaoymin** [comment]
太简单了，一句话我不知道你得问题是什么。

**Comment by rcf666** [comment]
> 太简单了，一句话我不知道你得问题是什么。

和这个问题一样https://gitee.com/xiaoym/knife4j/issues/I6KYUJ
