### ISSUE TITLE
枚举类参数value和desc的注释

### ISSUE THREAD

**Issue by SherlockerSun** [xiaoymin/knife4j#605]
**问题：** 枚举类参数在文档中仅显示`value`，无法得知`value`对应的`desc`。
![image](https://github.com/xiaoymin/knife4j/assets/67036248/76ea1157-0ac1-4e8b-9a65-638f96636908)

**尝试：** 若重写枚举类的`toString`方法为 `return value + "-"+ desc;` 可以解决上述问题，但是会引发新的问题。

```java
    @Override
    public String toString() {
        return value + "-" + desc;
    }
```
![image](https://github.com/xiaoymin/knife4j/assets/67036248/7608fc82-947b-4c5d-85dd-2ba3d3e77d79)

**新的问题：** 在调试时，枚举类型参数选择下拉框，枚举类参数下拉框的值也会随之变成`value - desc`，导致传参异常。
![image](https://github.com/xiaoymin/knife4j/assets/67036248/52f5842f-a84d-4b9e-ad00-9fce9f466b3b)

**希望的结果：** 在文档中，枚举类型参数显示  `value-desc`  ，调试时，展示为 `value-desc` ，实际传参为  `value`  。

**版本：knife4j-spring-ui-2.0.4**

**Comment by xiaoymin** [comment]
This can be handled on the back end, not on the front end.

Considering that there may be multiple enumerations in the project, you can abstract a `fromValue` method, and each enumeration is converted according to the data content submitted by the form request. Of course, this format can be agreed by the team, such as you mentioned above How to display the `toString` method to the front end, then how to convert it back according to the format when the server is deserializing

Common interface:
```java
public interface CommonFormEnumParser<T extends Enum<T>> {

    /**
     * Realize the instantiation of the enumeration according to the input input
     * @param input input character
     * @return enumeration instance
     */
    T fromValue(String input);
}

```

Implement the interface in the enumeration class
```java
@Slf4j
@Getter
@AllArgsConstructor
public enum CourseType implements CommonFormEnumParser<CourseType> {
    /**
     * Graphic
     */
    PICTURE(102, "Picture Text"),
    /**
     * audio
     */
    AUDIO(103, "Audio"),
    /**
     * video
     */
    VIDEO(104, "Video"),
    /**
     * External link
     */
    URL(105, "external link");

    private final int type;
    private final String desc;



    @Override
    public String toString() {
        return this.type+":"+this.desc;
    }

    @Override
    public CourseType fromValue(String input) {
        log.info("input:{}",input);
        for (CourseType courseType : CourseType. values()) {
 // 根据规则自定义实现
            if (input. startsWith(Objects. toString(courseType. getType()))) {
                return courseType;
            }
        }
        throw new IllegalArgumentException("Invalid CourseType value: " + type);
    }
}
``` 

根据反射class创建一个默认的`PropertyEditorSupport`实现，代码如下：

```java
@AllArgsConstructor
public class GenericEnumPropertySupport<T extends Enum<T>> extends PropertyEditorSupport {

    final Class<T> enumClass;
    @Override
    public void setAsText(String text) throws IllegalArgumentException {
        if (enumClass.isEnum()){
            //必须是枚举
            if (CommonFormEnumParser.class.isAssignableFrom(enumClass)){
                T[] values=enumClass.getEnumConstants();
                if (values!=null&&values.length>0){
                    // 因为都实现了CommonFormEnumParser接口，随便取一个枚举元素都行
                    CommonFormEnumParser<T> one= (CommonFormEnumParser<T>) values[0];
                    setValue(one.fromValue(text));
                }
            }
        }
    }
}
```


最后通过Spring框架提供的`Advice`增强注入到框架中，实现`@InitBinder`绑定逻辑

```java
@RestControllerAdvice
public class GlobalRestAdvice {

    @InitBinder
    public void initBinder(WebDataBinder binder) {
        //这里可以做成scan扫描包的方式，扫描所有枚举类，然后分批注入，或者其他的方式也行，看自己项目的规则
        binder.registerCustomEditor(CourseType.class,new GenericEnumPropertySupport<>(CourseType.class));
    }

}
```

以上是针对form的实现

**Comment by xiaoymin** [comment]
如果请求是JSON的方式，那么这种方式不通用，因为JSON是考虑到框架的序列化和反序列化，以框架中用jackson为例，首先需要更改枚举类的toString方法，通过`@JsonValue`注解将枚举的属性值列出来，以便文档展示，其次，反序列化时，提供反序列化的规则。

枚举类：
```java
@Slf4j
@Getter
@AllArgsConstructor
@JsonDeserialize(using = CourseTypeDeserializer.class)
public enum CourseType implements CommonFormEnumParser<CourseType> {
    /**
     * 图文
     */
    PICTURE(102, "图文"),
    /**
     * 音频
     */
    AUDIO(103, "音频"),
    /**
     * 视频
     */
    VIDEO(104, "视频"),
    /**
     * 外链
     */
    URL(105, "外链");

    private final int type;
    private final String desc;



    @JsonValue
    @Override
    public String toString() {
        return this.type+":"+this.desc;
    }

    @Override
    public CourseType fromValue(String input) {
        log.info("input:{}",input);
        for (CourseType courseType : CourseType.values()) {
            if (input.startsWith(Objects.toString(courseType.getType()))) {
                return courseType;
            }
        }
        throw new IllegalArgumentException("Invalid CourseType value: " + type);
    }
}

```


反序列化类：
```java
@Slf4j
public class CourseTypeDeserializer  extends JsonDeserializer<CourseType> {
    @Override
    public CourseType deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException, JacksonException {
        log.info("des....");
        String type = jsonParser.getValueAsString();
        log.info("value:{}",type);
        for (CourseType courseType : CourseType.values()) {
            if (type.startsWith(Objects.toString(courseType.getType()))) {
                return courseType;
            }
        }
        throw new IllegalArgumentException("Invalid CourseType value: " + type);
    }
}


```

这种方式在json提交时，保证了文档的展示和调试功能

![image](https://github.com/xiaoymin/knife4j/assets/7894406/38e36bd0-e503-4da0-a88f-1a086f73004f)

![image](https://github.com/xiaoymin/knife4j/assets/7894406/18c04ccf-3f2f-496e-aa68-2930caf1206d)

参考代码：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot27-demo/src/main/java/com/knife4j/demo/new3/Job3Controller.java

**Comment by SherlockerSun** [comment]
非常感谢！

**Comment by PasseRR** [comment]
> 如果请求是JSON的方式，那么这种方式不通用，因为JSON是考虑到框架的序列化和反序列化，以框架中用jackson为例，首先需要更改枚举类的toString方法，通过`@JsonValue`注解将枚举的属性值列出来，以便文档展示，其次，反序列化时，提供反序列化的规则。
> 
> 枚举类：
> 
> @Slf4j
> @Getter
> @AllArgsConstructor
> @JsonDeserialize(using = CourseTypeDeserializer.class)
> public enum CourseType implements CommonFormEnumParser<CourseType> {
>     /**
>      * 图文
>      */
>     PICTURE(102, "图文"),
>     /**
>      * 音频
>      */
>     AUDIO(103, "音频"),
>     /**
>      * 视频
>      */
>     VIDEO(104, "视频"),
>     /**
>      * 外链
>      */
>     URL(105, "外链");
> 
>     private final int type;
>     private final String desc;
> 
> 
> 
>     @JsonValue
>     @Override
>     public String toString() {
>         return this.type+":"+this.desc;
>     }
> 
>     @Override
>     public CourseType fromValue(String input) {
>         log.info("input:{}",input);
>         for (CourseType courseType : CourseType.values()) {
>             if (input.startsWith(Objects.toString(courseType.getType()))) {
>                 return courseType;
>             }
>         }
>         throw new IllegalArgumentException("Invalid CourseType value: " + type);
>     }
> }
> 反序列化类：
> 
> @Slf4j
> public class CourseTypeDeserializer  extends JsonDeserializer<CourseType> {
>     @Override
>     public CourseType deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws IOException, JacksonException {
>         log.info("des....");
>         String type = jsonParser.getValueAsString();
>         log.info("value:{}",type);
>         for (CourseType courseType : CourseType.values()) {
>             if (type.startsWith(Objects.toString(courseType.getType()))) {
>                 return courseType;
>             }
>         }
>         throw new IllegalArgumentException("Invalid CourseType value: " + type);
>     }
> }
> 这种方式在json提交时，保证了文档的展示和调试功能
> 
> ![image](https://github.com/xiaoymin/knife4j/assets/7894406/38e36bd0-e503-4da0-a88f-1a086f73004f)
> 
> ![image](https://github.com/xiaoymin/knife4j/assets/7894406/18c04ccf-3f2f-496e-aa68-2930caf1206d)
> 
> 参考代码：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot27-demo/src/main/java/com/knife4j/demo/new3/Job3Controller.java

某种层面来说，这对mvc的参数解析带来了坏味道，value-desc拼接只是为了文档展示，为了文档展示而不得不改变或指定枚举参数解析的方式。有其他更纯粹一点的方案吗？
