### ISSUE TITLE
系统实现WebMvcConfigurer后打开Knife4j报异常

### ISSUE THREAD

**Issue by XSWClevo** [xiaoymin/knife4j#607]
系统没有实现WebMvcConfigurer之前可以正常访问Knife4j文档，实现后访问就报错。准确的来说是因为自己实现WebMvcConfigurer重写了全局日期返回导致。
配置如图：
![image](https://github.com/xiaoymin/knife4j/assets/39268560/5a545dcf-77b2-4d77-8a09-2fab8b94aef8)

当我把全局日期那串注释后就可以正常访问了。

访问文档的接口返回：
正常的返回值应该是个json传，重写了全局日期接口后返回的是一串密匙
![image](https://github.com/xiaoymin/knife4j/assets/39268560/7ac651c7-0097-43b2-8132-189af6e01b5f)

最后访问页面的结果就是提示Knife4j异常

我的spring boot版本是3.0.6，knife4j版本为4.1.0

目前Google和百度均未找到解决方案

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/v4/knife4j-base64-response
