### ISSUE TITLE
knife4j和Knife4jInsight如何展示自定义错误码。

### ISSUE THREAD

**Issue by Q-001** [xiaoymin/knife4j#611]
如题，目前没有好的办法展示业务上的错误码，错误码枚举值较多，此问题有什么好的结局方案吗？
项目中用到的版本：
knife4j版本：knife4j-spring-boot-starter.version=2.0.9。
openapi：2.0
Knife4jInsight：计划部署一个用作独立的接口文档管理工具。

**Comment by xiaoymin** [comment]
业务错误码其实是通用的，我的建议是单独写一个markdown文件，在文档上展示出来

https://doc.xiaominfo.com/docs/features/selfdocument
