### ISSUE TITLE
字段说明不支持多层泛型对象，泛型对象getter 方法返回是T

### ISSUE THREAD

**Issue by chelsen** [xiaoymin/knife4j#615]
knife4j-openapi2-spring-boot-starter=4.1.0
已参考：Swagger字段属性说明不显示 https://doc.xiaominfo.com/docs/faq/swagger-des-not-found
不属于文章提到的情况

data 里的一层泛型说明显示正常
<img width="978" alt="image" src="https://github.com/xiaoymin/knife4j/assets/19900651/2929c63c-a996-4c64-a007-abe8f68b366d">

data 里面的对象如果也有泛型，比如分页对象，就不能显示字段说明

<img width="1059" alt="image" src="https://github.com/xiaoymin/knife4j/assets/19900651/30a1e65f-5b95-4d00-9e20-c610e171081d">

swagger models 里面 可以看到对象的字段说明，但是Page分页对象的说明还是看不到
<img width="1038" alt="image" src="https://github.com/xiaoymin/knife4j/assets/19900651/49f749b5-345a-45af-8562-e461e3758b58">

谢谢各位解答！

**Comment by xiaoymin** [comment]
贴个类结构吧
