### ISSUE TITLE
如何在启动文档的时候插入全局参数

### ISSUE THREAD

**Issue by lyzklkl** [xiaoymin/knife4j#616]
我再使用 swagger2 中设置这样就可以

 @Bean
    public Docket createRestApi() {
        ParameterBuilder ticketPar = new ParameterBuilder();
        List<Parameter> pars = new ArrayList<>();
        ticketPar.name("token")
                .description("user token")
                .modelRef(new ModelRef("string"))
                .parameterType("header")
                .required(true)
                .defaultValue("eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhZG1pblVzZXJJZCI6Ijk4OTgyOWIwNWE1ZjE5NTVkMDVjYTU2ZTMyMmI3M2Q5IiwidXNlck51bSI6Im51bGwiLCJvcGVuaWQiOiJudWxsIiwiY29tcGFueU5hbWUiOiLmtYvor5Xlhazlj7giLCJjb21wYW55VG9wSWQiOiJudWxsIiwic3lzIjoi57uf56255om_5L-d57O757ufIiwiZW52IjoiZGV2IiwidXNlcklkIjoiOTg5ODI5YjA1YTVmMTk1NWQwNWNhNTZlMzIyYjczZDkiLCJjb21wYW55SWQiOiJhYjljOTg5NyIsIm5iZiI6MTY2MTk0MDkxMSwiZGVwdE5hbWVzIjoibnVsbCIsInBob25lIjoiMTg4ODg4ODg4ODgiLCJuYW1lIjoi566h55CG5ZGYIiwiZXhwIjoxNjYzNzU1MzExLCJpYXQiOjE2NjE5NDA5MTEsImVtYWlsIjoieXVhbm1vdUAxMjYuY29tIn0.DhiqpDWYWRJhUwgKmuEnCpet-XTMO26uXjmcbuwUHNk");
        pars.add(ticketPar.build());
        return new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                .select()
                .apis(RequestHandlerSelectors.basePackage(basePackage))
                .paths(PathSelectors.any())
                .build()
                .securitySchemes(securitySchemes())
                .securityContexts(securityContexts())
                .globalOperationParameters(pars);
    }

但是现在我不知道怎么配置了

**Comment by xiaoymin** [comment]
所以，要knife4j做什么？

**Comment by lyzklkl** [comment]
抱歉, 上面描述是错误的,  我现在引入的 jar 包是这样的
       <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.1.0</version>
        </dependency>

我在 openapi3 中, 如何配置默认的 全局请求头

**Comment by xiaoymin** [comment]
最简单的，可以自己实现一个springdoc提供的customer接口。参数添加进去

可以参考这篇文章中的思想，其实意思差不多：

https://doc.xiaominfo.com/docs/blog/customer-add-api
