### ISSUE TITLE
springboot集成fastjson添加过滤器接口文档就报异常

### ISSUE THREAD

**Issue by Jiesen-Chen** [xiaoymin/knife4j#617]
**Describe the bug**
![微信图片_20230724180217](https://github.com/xiaoymin/knife4j/assets/54491167/7ad10728-d743-485e-82b6-068fb5ecc998)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Knife4j Version (please complete the following information):**

**Additional context**

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/v4/knife4j-base64-response
