### ISSUE TITLE
Failed to start bean 'documentationPluginsBootstrapper';   because "this.condition" is null

### ISSUE THREAD

**Issue by xieyan9-tal** [xiaoymin/knife4j#619]
**Describe the bug**
Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

**To Reproduce**
1. springboot 2.7.14
2. spring cloud 2021.0.8

引入 
<dependency>
    <groupId>com.github.xiaoymin</groupId>
    <artifactId>knife4j-openapi2-spring-boot-starter</artifactId>
    <version>4.1.0</version>
</dependency>

error
Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null

无法启动项目

**Comment by xieyan9-tal** [comment]
删除掉

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
可以启动成功，这是什么原因呢？？？

**Comment by xieyan9-tal** [comment]
或者改为  
<dependency>
			<groupId>com.github.xiaoymin</groupId>
			<artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
			<version>4.1.0</version>
		</dependency>

也可以了

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/knife4j/issues/612
