### ISSUE TITLE
引用对象不展示的问题

### ISSUE THREAD

**Issue by tangxuefeng987** [xiaoymin/knife4j#62]
swagger自带的ui是可以展示对象的信息，说明数据是没问题的。
比如一下情况的数据，无法展示 “对账明细返回参数 ”:
通用返回对象«PageResult«对账明细返回参数»» {
code (string, optional): 结果码 ,
data (PageResult«对账明细返回参数», optional): 扩展数据 ,
msg (string, optional): 结果描述
}
PageResult«对账明细返回参数» {
pageCount (integer, optional): 总页数 ,
pageSize (integer, optional): 每页记录数 ,
recordCount (integer, optional): 总记录数 ,
resultList (Array[对账明细返回参数], optional): 列表 ,
targetPage (integer, optional): 当前页码，从1开始
}
对账明细返回参数 {
amount (integer, optional): 金额 
}

**Comment by xiaoymin** [comment]
1.9.0已改
