### ISSUE TITLE
knife4j-openapi3-spring-boot-starter 4.2.0有依赖冲突

### ISSUE THREAD

**Issue by lfz757077613** [xiaoymin/knife4j#620]
![image](https://github.com/xiaoymin/knife4j/assets/16242100/cdbd23b4-68e5-4f6c-a9b8-9e89d9109f34)

**Comment by xiaoymin** [comment]
备注说明一下，jackson和snak是springdoc-openapi本身jar里面就存在，估无法解决

swagger-*系列可以改一下。下个版本修复

感谢反馈
