### ISSUE TITLE
springboot3.0.7+springcloudalibaba2022.0.0.0-RC2 + nacos 异常  

### ISSUE THREAD

**Issue by zjypyj** [xiaoymin/knife4j#626]
<img width="1578" alt="image" src="https://github.com/xiaoymin/knife4j/assets/33253540/04dcb400-d55b-4c2a-980c-526e128e6c5f">

**Comment by xiaoymin** [comment]
和knife4j没啥关系，你把/v3/api-docs接口返回的内容单独拿出来通过JSON框架格式化一下试试就知道问题所在

服务端返回的内容JSON不标准，通过JSON.parse方法转换异常。
