### ISSUE TITLE
4.2.0版本中所有的post请求都变成表单形式

### ISSUE THREAD

**Issue by TsukasaHwan** [xiaoymin/knife4j#629]
4.2.0版本中使用post请求@RequestBody时参数是放在query上面的
![微信截图_20230809140132](https://github.com/xiaoymin/knife4j/assets/46735688/348b6b2d-55a9-4461-9146-928937358c5f)
![微信截图_20230809140145](https://github.com/xiaoymin/knife4j/assets/46735688/04bf8faa-9f6c-4fea-aca2-d79ff8c69f2b)

**Comment by TsukasaHwan** [comment]
spring boot版本为2.7.14

**Comment by TsukasaHwan** [comment]
使用spring boot版本2.7.11没有这个问题

**Comment by TsukasaHwan** [comment]
使用spring boot版本2.7.11和4.1.0没有这个问题

**Comment by TsukasaHwan** [comment]
使用spring boot版本2.7.14和4.1.0也没有这个问题

**Comment by TsukasaHwan** [comment]
而且所有的post请求都变成表单形式了，这个应该是个bug

**Comment by xiaoymin** [comment]
knife4j 4.2.0版本引用的1.7.0的springdoc有关系，可以在maven的pom.xml降低一下版本，用springdoc的1.6.x版本

springdoc这个问题，在Spring boot 3中的2.x版本中解决了,参考日志
https://github.com/springdoc/springdoc-openapi/releases

![image](https://github.com/xiaoymin/knife4j/assets/7894406/39a9219a-367f-43a1-bd41-3816507a15a1)

，但是在boot2中的1.x版本中还没有解决，后面如果解决了，knfie4j会把版本升上去，现阶段只能暂时，开发自己降低一下springdoc的版本，单独引用一个稍微低一些的版本

**Comment by TsukasaHwan** [comment]
好的，我把全局default-flat-param-object关了，手动使用注解的方式解决了
