### ISSUE TITLE
Authorize 不生效

### ISSUE THREAD

**Issue by vaulka** [xiaoymin/knife4j#630]
由于只想要简单 UI 版的 knife4j，故只引用 `com.github.xiaoymin:knife4j-openapi3-ui:4.3.0` 依赖，在使用过程中发现全局参数 Authorize 不生效，在 swagger 文档中是可以正常使用的，以下为复现场景：

![image](https://github.com/xiaoymin/knife4j/assets/53456132/c7256f87-85d2-46e7-b264-ef7313c3fb5a)

![image](https://github.com/xiaoymin/knife4j/assets/53456132/8b0c11d1-1ee1-4d47-a5e6-e70b592e34b9)

但是在 knife4j 中，并不能生效

![image](https://github.com/xiaoymin/knife4j/assets/53456132/5ebe215f-bb63-47b2-9931-553d648a2e0e)

![image](https://github.com/xiaoymin/knife4j/assets/53456132/213795ba-0d16-4f98-ace3-aa205221ab3b)

在浏览器控制台以及请求接口，并无看见报错，但是 swagger 本身又可以用，大概率是 knife4j-openapi3-ui 没适配好。

我的所有关于 springdoc 以及 knife4j 依赖引用如下：

<img width="604" alt="image" src="https://github.com/xiaoymin/knife4j/assets/53456132/2f95e68d-e62f-4e14-8f71-3408f039d0a4">

**Comment by zhoushuai1119** [comment]
我4.3.0版本也有这个问题，但是作者都没有回复这个问题的解决方案

**Comment by ZhiQinIsZhen** [comment]
+1

**Comment by ZhiQinIsZhen** [comment]
> 我4.3.0版本也有这个问题，但是作者都没有回复这个问题的解决方案



> +1

![image](https://github.com/xiaoymin/knife4j/assets/33510218/e1c4ee34-166b-4be0-a95b-848884e6df90)
配合这个，是生效的

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/blog/add-authorization-header

**Comment by careware134** [comment]
作者并没有解决issuer提出的问题，
添加SecuritySchema并不能和SecurityItem联动；

**Comment by careware134** [comment]
> 由于只想要简单 UI 版的 knife4j，故只引用 `com.github.xiaoymin:knife4j-openapi3-ui:4.3.0` 依赖，在使用过程中发现全局参数 Authorize 不生效，在 swagger 文档中是可以正常使用的，以下为复现场景：
> 
> ![image](https://private-user-images.githubusercontent.com/53456132/259592336-c7256f87-85d2-46e7-b264-ef7313c3fb5a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii81MzQ1NjEzMi8yNTk1OTIzMzYtYzcyNTZmODctODVkMi00NmU3LWIyNjQtZWY3MzEzYzNmYjVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxOTk1N2M1Y2JmMjI2MTY5NGQyYmZlYjIxNmM0MmI0OGIyZDFmOTI4ZTkzNTQxYmVkMDZjOTMxYzA2NjY2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hSW64w-M7G5AGu85djWtTs_G-yoAgG8xWQa56S3A5s)
> 
> ![image](https://private-user-images.githubusercontent.com/53456132/259592227-8b0c11d1-1ee1-4d47-a5e6-e70b592e34b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii81MzQ1NjEzMi8yNTk1OTIyMjctOGIwYzExZDEtMWVlMS00ZDQ3LWE1ZTYtZTcwYjU5MmUzNGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmM5YjUzNWRkYjg5YmNkZWJjNWFkYjI4YTVmNTdmNzcyOTkyOTg5ZjY2YjA5ODM1MzlkYzRlMWJhY2I3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Oe5or9c9itugPeVsptQ0DzxyJRotiJGyPv4qTaO-NLQ)
> 
> 但是在 knife4j 中，并不能生效
> 
> ![image](https://private-user-images.githubusercontent.com/53456132/259592550-5ebe215f-bb63-47b2-9931-553d648a2e0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii81MzQ1NjEzMi8yNTk1OTI1NTAtNWViZTIxNWYtYmI2My00N2IyLTk5MzEtNTUzZDY0OGEyZTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczNjlmY2UwYzhmYThmN2M1ZmQ3ZGFlMDBkODUyYzk3ZmNkZWY3M2RhNjI1MDNlZTM5ZjMyMmQ4NTExMzA1MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6xWO-8bQf979Rb3GQZczKzgzFjJgP_1dmr_1iv8pbM)
> 
> ![image](https://private-user-images.githubusercontent.com/53456132/259592677-213795ba-0d16-4f98-ace3-aa205221ab3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii81MzQ1NjEzMi8yNTk1OTI2NzctMjEzNzk1YmEtMGQxNi00Zjk4LWFjZTMtYWEyMDUyMjFhYjNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjNjI0OTcxYmIzNzliN2MzNjFhMDUyZGUxNzNlMDlmM2Y4NDU5MjgyZGZlNDRkOTVjNjI1MjM5NGUwOWVkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gQnDZTbaXuquYmLrqRbYNcQMgyf--c6Em5U-HwF1Es)
> 
> 在浏览器控制台以及请求接口，并无看见报错，但是 swagger 本身又可以用，大概率是 knife4j-openapi3-ui 没适配好。
> 
> 我的所有关于 springdoc 以及 knife4j 依赖引用如下：
> 
> <img alt="image" width="604" src="https://private-user-images.githubusercontent.com/53456132/259593305-2f95e68d-e62f-4e14-8f71-3408f039d0a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1OTY5MDMsIm5iZiI6MTcxNTU5NjYwMywicGF0aCI6Ii81MzQ1NjEzMi8yNTk1OTMzMDUtMmY5NWU2OGQtZTYyZi00ZTE0LThmNzEtMzQwOGYwMzlkMGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDEwMzY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MTQzYmY0OGU3OWRmYjdhNjJhNjM0MTljYThlZmMwYmE4MGUyNWExYTgwMmE5NzEwNDVhMzk0MGE1MjYwM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yt4xSIL5_ASDDlEUwwbNSfVZTz1c5ow00sdpRaCaW30">

试试这个：

https://github.com/xiaoymin/knife4j/issues/545

**Comment by careware134** [comment]
可以试试这个~ 亲测可以work
https://github.com/xiaoymin/knife4j/issues/545
@vaulka
