### ISSUE TITLE
关注一下这个issue 需要升级openapi相关依赖

### ISSUE THREAD

**Issue by johnluoyx** [xiaoymin/knife4j#635]
**Describe the bug**
[openapi #2170](https://github.com/springdoc/springdoc-openapi/issues/2170)
有一个controller 参数require不能识别的问题 需要[springdoc-openapi](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.7.0) 升级到 2.1.0 1.7.0 才可以解决

**To Reproduce**
issue里已经说的很清楚

**Expected behavior**
升级springdoc-openapi 相关依赖

**Comment by xiaoymin** [comment]
目前是2.0.4，其实springdoc 2.1.0也有bug，就是`@RequestBody`注解识别的问题，下个版本会升级到2.2.0

但是springdoc 目前1.7.0对于`@RequestBody`注解也有bug

**Comment by johnluoyx** [comment]
good 下一个版本计划什么时候发布？2.2.0的api有一些变化 和目前的代码有不适配

**Comment by xiaoymin** [comment]
> good 下一个版本计划什么时候发布？2.2.0的api有一些变化 和目前的代码有不适配

过一段时间吧，我主要关注1.x版本的发布，好一起升上去，如果后面knife4j的迭代等不了的话，那就会先发boot3对应的2.2.0版本
