### ISSUE TITLE
仅使用@Parameter(example = "3") 时，页面渲染会多个逗号

### ISSUE THREAD

**Issue by tntfyf** [xiaoymin/knife4j#639]
knife4j-openapi3-spring-boot-starter 4.2.0

![d8191c41ee653387e8c0f43abfe7c6d](https://github.com/xiaoymin/knife4j/assets/45613518/b867759c-79f5-4149-b8b2-4ddc414774c3)

**Comment by xiaoymin** [comment]
贴一个完整的类、接口 截图吧，不要吝啬空间

**Comment by tntfyf** [comment]
![图片](https://github.com/xiaoymin/knife4j/assets/45613518/330df6c6-c232-4387-901b-2d43c5eccaec)

**Comment by tntfyf** [comment]
![图片](https://github.com/xiaoymin/knife4j/assets/45613518/04cbd506-dc9a-4c62-a926-acf13c7369e8)
这两种只有类子参数的情况都会出现对多一个逗号
