### ISSUE TITLE
sun.misc.BASE64Decoder

### ISSUE THREAD

**Issue by sauzny** [xiaoymin/knife4j#64]
1.9.0版本
`filter/BasicFilter.java` 中使用了 `sun.misc.BASE64Decoder`
这个是不是换成 `java.util.Base64` 更好一些？

**Comment by xiaoymin** [comment]
这个就需要强制用户使用jdk 8了,过一段时间吧

```java
 * @author  Xueming Shen
 * @since   1.8
 */

public class Base64 {
//.....
}
```

**Comment by xiaoymin** [comment]
1.9.4版本已替换为JDK1.8中的方法

https://www.oschina.net/news/107336/swagger-bootstrap-ui-1-9-4-released
