### ISSUE TITLE
通过gateway访问doc.html时，找不到“v3/api-docs”这个路径

### ISSUE THREAD

**Issue by dengchufeng** [xiaoymin/knife4j#640]
【依赖版本】
你们好，maven依赖版本如下：
1、knife4j-openapi3-jakarta-spring-boot-starter：4.3.0
2、SpringCloud：2022.0.4
3、SpringBoot：3.0.9
4、SpringCloud Alibaba：2022.0.0.0
5、JDK：17

【问题描述】
1、gateway项目配置如下：
![image](https://github.com/xiaoymin/knife4j/assets/142789289/f2bc54c3-724d-4597-ac43-2b1fcfebb474)
2、通过gateway项目访问和zy-base项目时，v3/api-docs访问出错，zy-base项目没有添加swagger配置类，仅仅引用了maven依赖：http://188.188.3.220:20238/base/doc.html
![image](https://github.com/xiaoymin/knife4j/assets/142789289/50dfdf34-56c8-482e-83d2-416efbceb115)
3、看到issues里有类似的问题，意思是省略了前缀，但是没看懂解决方法，有好的解决方法或者建议吗

**Comment by xiaoymin** [comment]
20238端口不是网关项目吗？怎么访问doc.html的时候要带上/base？

走网关入口不是应该根目录吗

**Comment by dengchufeng** [comment]
20238端口是网关项目，base是zy-base项目的简称，在网关项目里配置的，如上面的gateway项目配置。带上这个前缀是为了区分不同的项目，网关里配置的filters，会在访问的时候去掉这个前缀，并且跳转到对应的项目地址。
1、访问zy-base项目示例：http://网关项目ip地址/base/xxx，会跳转到 http://zy-base项目ip地址/xxx
2、访问zy-produce项目示例：http://网关项目ip地址/produce/xxx，会跳转到 http://zy-produce项目ip地址/xxx
3、以此类推
4、现在遇到的问题是访问zy-base项目的doc.html时，http://网关项目ip地址/base/v3/api-docs，变成了 http://网关项目ip地址/v3/api-docs，base这个前缀不见了，导致没法跳转到 http://zy-base项目ip地址/xxx
5、以上就是我的理解了，感谢你抽空回复
@xiaoymin

**Comment by xiaoymin** [comment]
既然在网关配置了，就直接访问网关入口的doc.html吧，因为走网关在访问子服务的doc.html， 路由/v3/api-docs是根目录，实际根目录又是网关服务 ，所以必然是404

**Comment by dengchufeng** [comment]
> 既然在网关配置了，就直接访问网关入口的doc.html吧，因为走网关在访问子服务的doc.html， 路由/v3/api-docs是根目录，实际根目录又是网关服务 ，所以必然是404

没理解“直接访问网关入口的doc.html”的意思，能举个例子吗

**Comment by dengchufeng** [comment]
> 既然在网关配置了，就直接访问网关入口的doc.html吧，因为走网关在访问子服务的doc.html， 路由/v3/api-docs是根目录，实际根目录又是网关服务 ，所以必然是404

1、我就是通过网关访问子服务的doc.html的：http://188.188.3.220:20238/base/doc.html
（1）188.188.3.220:20238是网关地址
（2）base是zy-base项目的前缀
2、这样访问的时候， 路由/v3/api-docs前面没有base这个前缀

**Comment by xiaoymin** [comment]
从网关走，应该是根目录，我的意思是不要从网关+子服务前缀+doc.html

直接在网关聚合子服务的数据源，展示

路径 ：网关端口/doc.html

**Comment by dengchufeng** [comment]
> 从网关走，应该是根目录，我的意思是不要从网关+子服务前缀+doc.html
> 
> 直接在网关聚合子服务的数据源，展示
> 
> 路径 ：网关端口/doc.html

懂了，要是加前缀能访问就完美了。
