### ISSUE TITLE
enum Identify anomalies

### ISSUE THREAD

**Issue by FPEsocrter** [xiaoymin/knife4j#646]
public enum WebProxyEnum {
NO_PROXY,
HTTP,
HTTPS,
SOCKS,
SSH,
;

}

参数名称 | 参数说明 | 请求类型 | 是否必须 | 数据类型 | schema

type | 可用值:NO_PROXY,HTTP,HTTPS,SOCKS,SSH |   | true | string

应该是 type | 可用值:0（NO_PROXY）,1（HTTP）,2（HTTPS）,3（SOCKS）4,（SSH) |   | true | int

**Comment by xiaoymin** [comment]
解析出来是什么就是什么，你枚举如果存在属性，在让后端框架解析生成openapi规范的时候，应该要告诉他的，而不是只认为看见的是这个就以为是这个

可以参考blog：https://doc.xiaominfo.com/docs/blog/handler-enum

或者你自查最终生成的openapi规范的枚举值是什么
