### ISSUE TITLE
knife4j-gateway在4.3.0启用basic情况下，响应异常

### ISSUE THREAD

**Issue by slppls** [xiaoymin/knife4j#651]
**Describe the bug**
spring 6.0.11
spring-boot 3.1.2
knife4j-gateway 4.3.0

启用basic的情况下，访问doc响应异常
![image](https://github.com/xiaoymin/knife4j/assets/18140796/0261aa28-f4f5-4ec8-920b-359ce51531b4)

**To Reproduce**
![image](https://github.com/xiaoymin/knife4j/assets/18140796/3f77bb7e-aca9-4d23-89f9-de9b36ea8207)

**Expected behavior**
异常指向 boolean org.springframework.http.server.reactive.ServerHttpResponse.setStatusCode(org.springframework.http.HttpStatus) 方法不存在
![image](https://github.com/xiaoymin/knife4j/assets/18140796/37e8611e-5ca7-42b4-8f0d-78a3c38b7124)

**Screenshots**
![image](https://github.com/xiaoymin/knife4j/assets/18140796/0261aa28-f4f5-4ec8-920b-359ce51531b4)

**Knife4j Version (please complete the following information):**
4.3.0

**Additional context**
猜测是否spring6.x 的该方法修改导致，4.3.0的basic相关代码是否兼容

**Comment by xiaoymin** [comment]
感谢反馈
