### ISSUE TITLE
能否支持Get请求,url路径后面拼接参数

### ISSUE THREAD

**Issue by 91xinwei** [xiaoymin/knife4j#66]
在使用时发现Get请求情况下，请求参数只会存在于body体中，不能将参数拼接到url路径后面

**Comment by xiaoymin** [comment]
没太明白，是调试不可用还是你要把参数拼接到地址栏方便你复制？

**Comment by 695518147** [comment]
路径参数，调试不支持啊，特别是路径参数在中间的，调试直接没有后面的路径  还要手动补全
