### ISSUE TITLE
knife4j-insight 不支持处理content-type为br的响应

### ISSUE THREAD

**Issue by SicianLee** [xiaoymin/knife4j#670]
knife4j-insight  | 2023-10-26 17:11:57,930 ERROR (GatewayClient.java:76)- has Error:br
knife4j-insight  | 2023-10-26 17:11:57,930 ERROR (GatewayClient.java:77)- br
knife4j-insight  | java.nio.charset.UnsupportedCharsetException: br
knife4j-insight  |      at java.base/java.nio.charset.Charset.forName(Charset.java:537)
knife4j-insight  |      at net.knife4j.insight.gateway.response.ApacheClientResponse.getCharsetEncoding(ApacheClientResponse.java:110)
knife4j-insight  |      at net.knife4j.insight.gateway.utils.GatewayUtils.writeResponseHeader(GatewayUtils.java:138)
knife4j-insight  |      at net.knife4j.insight.gateway.GatewayClient.execute(GatewayClient.java:73)
knife4j-insight  |      at net.knife4j.insight.filter.GlobalRequestMapping.doFilter(GlobalRequestMapping.java:74)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
knife4j-insight  |      at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
knife4j-insight  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
knife4j-insight  |      at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
knife4j-insight  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
knife4j-insight  |      at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
knife4j-insight  |      at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)
knife4j-insight  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)
knife4j-insight  |      at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:166)
knife4j-insight  |      at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
knife4j-insight  |      at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482)
knife4j-insight  |      at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
knife4j-insight  |      at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
knife4j-insight  |      at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
knife4j-insight  |      at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
knife4j-insight  |      at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391)
knife4j-insight  |      at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
knife4j-insight  |      at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
knife4j-insight  |      at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740)
knife4j-insight  |      at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
knife4j-insight  |      at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
knife4j-insight  |      at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
knife4j-insight  |      at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
knife4j-insight  |      at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by xiaoymin** [comment]
能否贴一个服务端接口的例子，帮助我复现，谢谢

**Comment by SicianLee** [comment]
您好，已收到您的邮件，我会尽快给您答复！

**Comment by SicianLee** [comment]
> 能否贴一个服务端接口的例子，帮助我复现，谢谢

您好，这是一个百度图片搜索的接口，rsp压缩编码方式为br
`{
  "swagger": "2.0",
  "info": {
    "title": "个人项目",
    "description": "",
    "version": "1.0.0"
  },
  "host": "",
  "basePath": "/",
  "schemes": [],
  "consumes": [
    "*/*"
  ],
  "produces": [
    "*/*"
  ],
  "paths": {
    "/search/acjson": {
      "get": {
        "summary": "baidu_test",
        "x-apifox-folder": "",
        "x-apifox-status": "developing",
        "deprecated": false,
        "description": "",
        "tags": [
          "default"
        ],
        "parameters": [
          {
            "name": "tn",
            "in": "query",
            "description": "",
            "required": false,
            "example": "resultjson_com",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "logid",
            "in": "query",
            "description": "",
            "required": false,
            "example": "10839230793285218588",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ipn",
            "in": "query",
            "description": "",
            "required": false,
            "example": "rj",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ct",
            "in": "query",
            "description": "",
            "required": false,
            "example": "201326592",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "is",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "fp",
            "in": "query",
            "description": "",
            "required": false,
            "example": "result",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "fr",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "word",
            "in": "query",
            "description": "",
            "required": false,
            "example": "test",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "queryWord",
            "in": "query",
            "description": "",
            "required": false,
            "example": "test",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "cl",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "lm",
            "in": "query",
            "description": "",
            "required": false,
            "example": "-1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ie",
            "in": "query",
            "description": "",
            "required": false,
            "example": "utf-8",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "oe",
            "in": "query",
            "description": "",
            "required": false,
            "example": "utf-8",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "adpicid",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "st",
            "in": "query",
            "description": "",
            "required": false,
            "example": "-1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "z",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ic",
            "in": "query",
            "description": "",
            "required": false,
            "example": "0",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "hd",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "latest",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "copyright",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "s",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "se",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tab",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "width",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "height",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "face",
            "in": "query",
            "description": "",
            "required": false,
            "example": "0",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "istype",
            "in": "query",
            "description": "",
            "required": false,
            "example": "2",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "qc",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "nc",
            "in": "query",
            "description": "",
            "required": false,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "expermode",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "nojc",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "isAsync",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "pn",
            "in": "query",
            "description": "",
            "required": false,
            "example": "60",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "rn",
            "in": "query",
            "description": "",
            "required": false,
            "example": "30",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "gsm",
            "in": "query",
            "description": "",
            "required": false,
            "example": "3c",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "1698312936931",
            "in": "query",
            "description": "",
            "required": false,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "成功",
            "content": {
              "*/*": {
                "schema": {
                  "type": "object",
                  "properties": {},
                  "x-apifox-ignore-properties": [],
                  "x-apifox-orders": []
                }
              }
            }
          }
        },
        "x-run-in-apifox": "https://apifox.com/web/project/3381944/apis/api-119990656-run",
        "operationId": "3bb9605f6af8f7e0e22a52c46e87fdba"
      }
    }
  },
  "components": {}
}`

**Comment by SicianLee** [comment]
> 能否贴一个服务端接口的例子，帮助我复现，谢谢

您好，这是一个百度图片搜索的接口，回包的压缩编码方式为br
`curl --location --request GET 'https://image.baidu.com/search/acjson?tn=resultjson_com&logid=10839230793285218588&ipn=rj&ct=201326592&is=&fp=result&fr=&word=test&queryWord=test&cl=2&lm=-1&ie=utf-8&oe=utf-8&adpicid=&st=-1&z=&ic=0&hd=&latest=&copyright=&s=&se=&tab=&width=&height=&face=0&istype=2&qc=&nc=1&expermode=&nojc=&isAsync=&pn=60&rn=30&gsm=3c&1698312936931=' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: image.baidu.com' \
--header 'Connection: keep-alive' \`

**Comment by xiaoymin** [comment]
收到，我看看

**Comment by SicianLee** [comment]
> 收到，我看看

大佬，请问这个问题有后续吗？

**Comment by xiaoymin** [comment]
> > 收到，我看看
> 
> 大佬，请问这个问题有后续吗？

非常抱歉，我最近工作太忙了，下周我争取支持一下这个问题，发个版本

**Comment by SicianLee** [comment]
您好，已收到您的邮件，我会尽快给您答复！

**Comment by xiaoymin** [comment]
你好，v1.1.0版本以及发布，docker镜像推上去了，可以更新一下，有问题可以再反馈，感谢

**Comment by SicianLee** [comment]
您好，已收到您的邮件，我会尽快给您答复！
