### ISSUE TITLE
get请求参数为对象时，页面调试被解析成了json字符串

### ISSUE THREAD

**Issue by zhourenfei17** [xiaoymin/knife4j#674]
工程为微服务，spring boot版本为3.0.2，各服务使用文档使用openApi3，网关使用组件版本：
```
<dependency>
      <groupId>com.github.xiaoymin</groupId>
      <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
      <version>4.3.0</version>
  </dependency>
```
现有查询接口代码如下：
```
    @Operation(summary = "分页列表查询")
    @GetMapping(value = "/page")
    public Result<Page<SysOrg>> page(SysOrgQueryVO query, @Validated PageParam params) {
        Page<SysOrg> page = query.initPage(params);
        page.setRecords(service.list(query));
        return Result.ok(page);
    }
```
knife4j页面显示文档效果如下：
![image](https://github.com/xiaoymin/knife4j/assets/22901065/5ccedd27-688a-4bb5-9a58-0065a8381384)
knife4j页面显示调试效果如下：
![image](https://github.com/xiaoymin/knife4j/assets/22901065/e4e76d77-5f4f-41c9-85ba-aa2e8ddf7172)
相同api-docs导入到apifox，调试效果如下：
![image](https://github.com/xiaoymin/knife4j/assets/22901065/c1b5e0e0-051d-4afe-9a9c-6b31b5285171)
openapi3关键json如下：
```
"paths": {
    "/org/page": {
      "get": {
        "tags": [
          "组织机构信息"
        ],
        "summary": "分页列表查询",
        "operationId": "page",
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/SysOrgQueryVO"
            }
          },
          {
            "name": "params",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/PageParam"
            }
          }
        ],
      }
    }
  },
```
目前knif4j生成的调试页面不符合调试需求，实际应该像apifox页面的k-v模式，请问这个可以解决吗？

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

**Comment by zhourenfei17** [comment]
作者您好，我看了下该链接的解决方案是针对于knife4j-openapi3-spring-boot-starter包的，但是本人仅仅是在gateway下引用了knife4j，其他服务被没有单独引用，网关服务引入如下：
```
<dependency>
    <groupId>com.github.xiaoymin</groupId>
    <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
    <version>4.3.0</version>
</dependency>
```
但是该包下发现并未引用任何io.swagger和org.springdoc的依赖。
各微服务引用公共模块，核心依赖为：
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    <version>2.2.0</version>
</dependency>
```
请问该如何解决，感谢！

**Comment by xiaoymin** [comment]
网关只是聚合作用， 你子服务引用了springdoc，是你子服务提供的openapi结构

2.2.0版本的针对[parameterobject-flat-param](https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param)已经解决了吧

yml里面配上springdoc的该参数配置就可以了

**Comment by zhourenfei17** [comment]
感谢作者，已解决！
