### ISSUE TITLE
spring中属性命名策略为下划线时不生效

### ISSUE THREAD

**Issue by sangyuan6122** [xiaoymin/knife4j#676]
**Describe the bug**
1、项目json属性转换策略全局定义为下划线时，文档还是驼峰
```
spring:  
  jackson:
    property-naming-strategy: SNAKE_CASE
```
2、如果实体类中定义name为下划线(api-docs接口返回也是下划线)，则对应页面加载为空
```
@Schema(name="user_name",description="用户名")
private String userName;
```
![image](https://github.com/xiaoymin/knife4j/assets/37788109/01e12e98-3363-4f12-8cec-b80c2b33fe21)
![image](https://github.com/xiaoymin/knife4j/assets/37788109/f47c6a0f-7f0b-4159-aa29-7579ea6ae8fb)

**Knife4j Version (please complete the following information):**
spring.boot.version:3.1.4
spring-cloud.version:2022.0.4
spring-cloud-alibaba.version:2022.0.0.0
spring-cloud-gateway.version:4.0.7
knife4j-gateway-spring-boot-starter:4.4.0-SNAPSHOT

**Comment by xiaoymin** [comment]
我单体测 没测出来

demo：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/fdca69ab85ba1134362cdfd96bae9a3f9d2cf0f3/knife4j-springdoc-openapi-demo

代码：

<img width="540" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/a067ed59-1e04-47ff-966c-8b7176e93c01">


ui：

<img width="1307" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/4d3fd041-a26d-4dbc-ab9e-05281125a9f4">
