### ISSUE TITLE
无法识别 @RequestPart("files") MultipartFile[] files 参数

### ISSUE THREAD

**Issue by hopana** [xiaoymin/knife4j#679]
### 运行环境
jdk 17，springboot 3.1.5，knife4j 4.3.0

### 问题：无法识别以下接口参数
@PostMapping("/xxx/import/")
public RespEntity<XXX> importByFiles(final @RequestPart("files") MultipartFile[] files) {

}
### 截图
![image](https://github.com/xiaoymin/knife4j/assets/13976824/a5c0f633-993c-455d-8316-04e0041c9f5c)

**Comment by xiaoymin** [comment]
用`@RequestParam`来接

```java
@RequestParam("files") MultipartFile[] files

```
