### ISSUE TITLE
参数名为id example值不带入

### ISSUE THREAD

**Issue by chairal** [xiaoymin/knife4j#68]

**Comment by xiaoymin** [comment]
什么版本

**Comment by DanielLeens** [comment]
我也遇到这问题
            @ApiImplicitParam(name = "processDefinitionJson", value = "PROCESS_DEFINITION_JSON", required = true, type ="String", example="xxxxxx")

example内容不显示？

**Comment by xiaoymin** [comment]
信息太少了，版本号，页面什么效果 这些贴一下啊

**Comment by Coande** [comment]
@xiaoymin 请问 example 内容在页面上是没显示的吗？
