### ISSUE TITLE
knife4j高版本无法识别文件

### ISSUE THREAD

**Issue by zongyanglaobiao** [xiaoymin/knife4j#688]
**描述错误**
你好开发者，开发上传文件功能中发现knife4j不能正常显示文件上传按钮，版本4.2.0，接口中有一个实体类其中包含MultipartFile对象使用spring mvc注解@ModelAttribute无法识别其中有文件，而2.0.9版本同样的操作可以识别

**复制**
实现已经在描述中

**Comment by xiaoymin** [comment]
升级版本，或者贴代码
