### ISSUE TITLE
Hi! Is it possible to use json file instead of annotations to pass the doc? I've got the swagger.json file but not sure how to use it

### ISSUE THREAD

**Issue by jys-sun** [xiaoymin/knife4j#69]

**Comment by xiaoymin** [comment]
Now the front-end separation has not been done, you should want to use the UI to render the existing swagger.json file, right?

If you're a java software engineer, you can seamlessly introduce this UI package using springfox-swagger, which works like springfox-swagger-ui

**Comment by jys-sun** [comment]
yeah I've got my api documents previously done and archived in json and want to apply your project with those files. Guess now this is only available with springfox? Thank you for replying！

**Comment by xiaoymin** [comment]
Do you have many API documents?

need to manage these JSON files and render them through ui?

**Comment by jys-sun** [comment]
I've got my old api documents done in RAML and I transformed them to Swagger json file. Im trying to find a way to render these json files in Swagger ui without retouching my project codes. I wonder if it possible I could manage that with your project Bootstrap UI?

**Comment by xiaoymin** [comment]
Hi, I tried to separate a pure front-end version at https://github.com/xiaoymin/Swagger-Bootstrap-UI/tree/master/swagger-bootstrap-ui-front.

You can download and try to use IIS or nginx to deploy a static server to access and use.

Maintain a grouped URL address group. JSON on the doc. HTML page, which is stored under the JSON folder

```javascript
layui.config({
            base: 'ext/'
        }).use([ 'sbuadmin', 'element'], function () {
            var $ = layui.$;
            var admin=layui.sbuadmin;
            admin.run({
                ace:ace,
                url:"/json/group.json" //Configure your own swagger. JSON file in the group. JSON file
            });
        });

```

**Comment by jys-sun** [comment]
thank you a lot xiaoymin! I'll give it a try! 👍 😄
