### ISSUE TITLE
支持不同请求路径显示不同的Docket吗？ 一个路径对应一个Docket

### ISSUE THREAD

**Issue by Youth99** [xiaoymin/knife4j#697]
支持不同请求路径显示不同的Docket吗？ 一个路径对应一个Docket

**Comment by xiaoymin** [comment]
打开某个详细接口的url就是，比如：https://doc.xiaominfo.com/demo/doc.html#/Knife4j%E7%A4%BA%E4%BE%8B/body%E5%8F%82%E6%95%B0/bodyPut

或者可以考虑http://knife4j.net/

把文档单独维护起来
