### ISSUE TITLE
聚合平台问题

### ISSUE THREAD

**Issue by orange-juzipi** [xiaoymin/knife4j#699]
1. 目前聚合平台只能登录鉴权，是否可以通过输入密码鉴权？个人觉得这样方便些。
2. `自动注册`的`数据来源`是否可以使用`HTTP接口`获取 openapi。

**Comment by xiaoymin** [comment]
1.第一个鉴权这个可以做输入密码鉴权，比如给每一个namespace独立设置一个访问密码

2.第二个目前Knife4jInsight平台在渲染界面的时候，其实就是获取保存在DB里面的OpenAPI数据源，本来就是HTTP接口获取的

**Comment by orange-juzipi** [comment]
> 2.第二个目前Knife4jInsight平台在渲染界面的时候，其实就是获取保存在DB里面的OpenAPI数据源，本来就是HTTP接口获取的

了解，那 api 接口中使用 http 接口，参数是 path 这个吗？接口是由 `host`+`path`组成吗？
比如我配置的
`host`是 192.168.0.110
`path`是 /v1/api/openapi
`content `不设置
那么在聚合中就会自动获取`HTTP接口`数据，是这样吗？

**Comment by xiaoymin** [comment]
不是，是Knife4jInsight平台自定义的接口，用来获取已经上传到平台的OpenAPI数据源

我理解你的意思是否需要一个从Knife4jInsight平台开放出去的接口？用来获取平台中的OpenAPI数据源？

**Comment by orange-juzipi** [comment]
明白了，暂时不需要从平台中获取数据源，能在`content`设置数据源就行，是我没想明白。

那这个`path`是干啥的？暂时没发现这个的用处。

如果要设置`文档主页`简介、作者、版本等信息，参数是啥？

**Comment by xiaoymin** [comment]
> 明白了，暂时不需要从平台中获取数据源，能在`content`设置数据源就行，是我没想明白。
> 
> 那这个`path`是干啥的？暂时没发现这个的用处。
> 
> 如果要设置`文档主页`简介、作者、版本等信息，参数是啥？

要设置`文档主页`简介、作者、版本等信息，如果是openapi3的规范，在springdoc-openapi项目中直接注入Bean对象就可以了，代码如下：

[SwaggerConfig.java](https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/master/knife4j-spring-boot3-demo/src/main/java/com/github/xiaoymin/boot3/config/SwaggerConfig.java)
```java
@Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("XXX用户系统API")
                        .version("1.0")

                        .description( "Knife4j集成springdoc-openapi示例")
                        .termsOfService("http://doc.xiaominfo.com")
                        .license(new License().name("Apache 2.0")
                                .url("http://doc.xiaominfo.com")));
    }
```

你说的`path`我没理解是哪里的，贴图？

**Comment by orange-juzipi** [comment]
[上报接口](http://knife4j.net/api/home.html#%E4%B8%8A%E6%8A%A5%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)

这里面的 `path`
```json
{
    "cloudRoutes":[
        {
            "groupName":"用户服务", 
            "content":"", 
            "path":"/v3/api-docs"
        }
     ]
}
``` 

> 要设置文档主页简介、作者、版本等信息，如果是openapi3的规范，在springdoc-openapi项目中直接注入Bean对象就可以了，代码如下：

目前我不用 Java 写，是用别的语言接入。

**Comment by xiaoymin** [comment]
> [上报接口](http://knife4j.net/api/home.html#%E4%B8%8A%E6%8A%A5%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)
> 
> 这里面的 `path`
> 
> ```json
> {
>     "cloudRoutes":[
>         {
>             "groupName":"用户服务", 
>             "content":"", 
>             "path":"/v3/api-docs"
>         }
>      ]
> }
> ```
> 
> > 要设置文档主页简介、作者、版本等信息，如果是openapi3的规范，在springdoc-openapi项目中直接注入Bean对象就可以了，代码如下：
> 
> 目前我不用 Java 写，是用别的语言接入。

这个是java框架里面的，就是当前你上报的时候，这个分组下的服务接口，提供OpenAPI数据源的接口，java的springdoc-openapi框架提供的路径就是/v3/api-docs

完整的数据源获取OpenAPI的方式拼接起来，就是：http://host:port/v3/api-docs

这个路径是当前服务提供OpenAPI数据源的接口，一般不同的开源框架/语言 提供规范应该是不一样的

如果你是其它语言，能把当前服务启动后，拿到OpenAPI的数据源的JSON内容，放到content字段里面，就可以进行上报了，path参数可以忽略的

**Comment by orange-juzipi** [comment]
好的，明白了，目前[上报接口](http://knife4j.net/api/home.html#%E4%B8%8A%E6%8A%A5%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E)没啥问题了，感谢解答。
