### ISSUE TITLE
配置完成以后，报服务器错误？

### ISSUE THREAD

**Issue by wangrocky** [xiaoymin/knife4j#70]
![image](https://user-images.githubusercontent.com/6724040/54506276-c2855f80-4976-11e9-8088-c0fedbe3a83d.png)
![image](https://user-images.githubusercontent.com/6724040/54506297-d335d580-4976-11e9-989e-f026aeecad9f.png)

![image](https://user-images.githubusercontent.com/6724040/54506360-04160a80-4977-11e9-9558-7fbfa838e440.png)

**打成war包，放在本地tomcat运行，原生swagger可以运行成功，但是swaggerbootstrapui会报服务器错误；**

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54506426-56572b80-4977-11e9-974d-8aa21f0b2cf3.png)
添加sswaggerconfig的部分配置截图；

**Comment by wangrocky** [comment]
访问地址，应该是http://127.0.0.1:8099/***api/doc.html吧？
我访问http://127.0.0.1:8099/***api/swagger-ui.html是正常的。

**Comment by xiaoymin** [comment]
什么错误？

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54510413-22d0cd00-4988-11e9-8543-188f5f084dac.png)

以上这样的；

**Comment by xiaoymin** [comment]
这个是你自己后端把这个url拦截处理了吧，我并没有封装code、msg、result这些字段

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54510468-590e4c80-4988-11e9-89b4-3f92fcb2049d.png)
但是我用原生的swaggerui，是可以的，不知道原因是啥。。

**Comment by xiaoymin** [comment]
你可能需要在后端配置静态资源

doc.html这个

参考：http://www.xiaominfo.com/swagger-bootstrap-ui/springboot-404.html

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54510537-b1dde500-4988-11e9-99ab-01063d6871e7.png)
log是这样的；
我的是springmvc工程，需要怎么配置呢？

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54511266-6547d900-498b-11e9-9371-a387245ea5dd.png)
我下载了spring-mvc-demo，打war包放在tomcat运行，输入http://127.0.0.1/swagger-bootrap-ui**/doc.html，提示说要用户名密码？？

**Comment by xiaoymin** [comment]
SpringMVC需要配置静态资源，参考：http://www.xiaominfo.com/swagger-bootstrap-ui/springmvc-404.html

弹出的提升是UI提供的basic认证功能,保护Swagger的资源用的，用户名和密码在web.xml中可以查看

**Comment by wangrocky** [comment]
我按照说明配置了一下，现在报这个错误：
HTTP Status 500 - Servlet.init() for servlet dispatcherServlet threw exception

type Exception report

message Servlet.init() for servlet dispatcherServlet threw exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet.init() for servlet dispatcherServlet threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

root cause

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$164ae516]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$164ae516.<init>()
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1105)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:633)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:552)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

root cause

org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$164ae516]: No default constructor found; nested exception is java.lang.NoSuchMethodException: com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$164ae516.<init>()
	org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:85)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:633)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:552)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

root cause

java.lang.NoSuchMethodException: com.github.xiaoymin.swaggerbootstrapui.configuration.SecurityConfiguration$$EnhancerBySpringCGLIB$$164ae516.<init>()
	java.lang.Class.getConstructor0(Class.java:3082)
	java.lang.Class.getDeclaredConstructor(Class.java:2178)
	org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:80)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1098)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1050)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:838)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:537)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:633)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:681)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:552)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)

**Comment by xiaoymin** [comment]
这个错误需要下个版本了，如果你有兴趣 ，可以帮我测试一下，pull下gitee的代码，本地install一个版本

https://gitee.com/xiaoym/swagger-bootstrap-ui

应该是这个issue：https://gitee.com/xiaoym/swagger-bootstrap-ui/issues/ITI1C

gitee上SecurityConfiguration这个类我改成了`@Autowired`注入的方式,应该没问题，期待收到你的反馈~~

**Comment by wangrocky** [comment]
好的我看看~

**Comment by wangrocky** [comment]
![image](https://user-images.githubusercontent.com/6724040/54516130-04bf9880-4999-11e9-8a70-d5a881bf7e84.png)
我用之前的1.9.1 mvc-demo，是可以跑起来的；但是在自己的工程上修改，还是不行，即使把dependency改成你刚才提供的1.9.2也不行;
能否把那些安全设置给去掉呢？我只想跑起来，接口都是在内部传递的，不需要考虑什么页面安全啥的；该怎么配置？？

**Comment by wangrocky** [comment]
你有qq号吗？方便提供一下不？

**Comment by xiaoymin** [comment]
QQ群：608374991

不需要basic设置只需要把web.xml里面配置的filter去掉就可以了

完整文档可以参考：http://www.xiaominfo.com/swagger-bootstrap-ui/accessControl.html

**Comment by wangrocky** [comment]
已解决，初始化失败，主要是因为guava版本与swagger2不兼容，配置成最新版本后，就可以了~
谢谢
