### ISSUE TITLE
4.4.0 版本问题

### ISSUE THREAD

**Issue by refeccd** [xiaoymin/knife4j#700]
看到发布了 4.4 版本，但是中央仓库没看到版本

[knife4j-core](https://repo.maven.apache.org/maven2/com/github/xiaoymin/knife4j/)

[knife4j-openapi3-jakarta-spring-boot-starter](https://repo.maven.apache.org/maven2/com/github/xiaoymin/knife4j-openapi3-jakarta-spring-boot-starter/)

但是在 [https://central.sonatype.com](https://central.sonatype.com/) 可以看到 [4.4版本](https://central.sonatype.com/artifact/com.github.xiaoymin/knife4j-openapi3-jakarta-spring-boot-starter/versions)

然后由于用的阿里云 maven 镜像仓库，阿里云同步的好像是 maven-central，导致拉不到依赖

**Comment by xiaoymin** [comment]
阿里云都是私服，默认晚2-3天，我们推只负责官方的，其它私服不管

**Comment by refeccd** [comment]
官方仓库里也没看到？

**Comment by refeccd** [comment]
我不是提供了 2 个中央仓库的地址吗？没有 4.4 版本？

**Comment by xiaoymin** [comment]
![image](https://github.com/xiaoymin/knife4j/assets/7894406/9be0d953-3cd8-47dd-921e-ea765b390229)

这个才是官方啊

https://search.maven.org/search?q=g:com.github.xiaoymin

**Comment by refeccd** [comment]
<img width="636" alt="image" src="https://github.com/xiaoymin/knife4j/assets/26990889/91b39f2c-b313-430b-9b83-a7ecc7800f9c">

**Comment by refeccd** [comment]
repo.maven.apache.org 都不是官方了？

**Comment by refeccd** [comment]
<img width="894" alt="image" src="https://github.com/xiaoymin/knife4j/assets/26990889/dd56b276-a586-4cfe-b195-5215bb58ed50">

**Comment by xiaoymin** [comment]
那这个应该是官方的问题，我上面用search.maven.org不是搜索到了么

**Comment by xiaoymin** [comment]
https://repo1.maven.org/maven2/com/github/xiaoymin/knife4j-openapi3-spring-boot-starter/4.4.0/

**Comment by xiaoymin** [comment]
只是没显示出来

**Comment by xiaoymin** [comment]
https://repo.maven.apache.org/maven2/com/github/xiaoymin/knife4j-openapi3-jakarta-spring-boot-starter/4.4.0/

**Comment by refeccd** [comment]
所以我一开始也没报 bug 啊，我也说了中央仓库看不到，但是在 central.sonatype.com 可以找到 4.4.0 版本
估计阿里云镜像也是拉取的列表，发现列表没有所以没同步了吧。
归根到底还是中央仓库的问题

**Comment by huangrx6** [comment]
阿里云的镜像还是拉不到哎😭

mvn install：Failed to read artifact descriptor for com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:jar:4.4.0: Could not find artifact com.github.xiaoymin:knife4j:pom:4.4.0 in alimaven (https://maven.aliyun.com/repository/central)
