### ISSUE TITLE
knif4j 配置文件中如何设置文档标题

### ISSUE THREAD

**Issue by snipercy** [xiaoymin/knife4j#702]
版本 knife4j-openapi3-spring-boot-starter  4.4.0
有没有配置项可以设置标题
<img width="274" alt="image" src="https://github.com/xiaoymin/knife4j/assets/5162780/7088096d-88cd-4ca8-af51-4c302a9bfe91">

**Comment by xiaoymin** [comment]
```java
@Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("XXX用户系统API")
                        .version("1.0")

                        .description( "Knife4j集成springdoc-openapi示例")
                        .termsOfService("http://doc.xiaominfo.com")
                        .license(new License().name("Apache 2.0")
                                .url("http://doc.xiaominfo.com"))
                        ).addSecurityItem(new SecurityRequirement().addList(HttpHeaders.AUTHORIZATION))
                .components(new Components().addSecuritySchemes(HttpHeaders.AUTHORIZATION,new SecurityScheme()
                        .name(HttpHeaders.AUTHORIZATION).type(SecurityScheme.Type.HTTP).scheme("bearer")));
    }


```

`title`就是标题

**Comment by liuwenjie** [comment]
那knife4j.openapi.title/description/url/email...etc这个是配置什么数据的？ @xiaoymin

**Comment by liuwenjie** [comment]
knife4j-openapi2-spring-boot-starter 4.4.0 版本

**Comment by xiaoymin** [comment]
@liuwenjie 项目的概况信息，想配置就配，不想配置也无所谓

**Comment by OOMEcho** [comment]
@xiaoymin 我也遇到这个问题，其实会让人误解，在配置文件中的openapi.title/description/url/email和
`@Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("XXX用户系统API")
                        .version("1.0")

                        .description( "Knife4j集成springdoc-openapi示例")
                        .termsOfService("http://doc.xiaominfo.com")
                        .license(new License().name("Apache 2.0")
                                .url("http://doc.xiaominfo.com"))
                        ).addSecurityItem(new SecurityRequirement().addList(HttpHeaders.AUTHORIZATION))
                .components(new Components().addSecuritySchemes(HttpHeaders.AUTHORIZATION,new SecurityScheme()
                        .name(HttpHeaders.AUTHORIZATION).type(SecurityScheme.Type.HTTP).scheme("bearer")));
    }`
看着很相似，但是作用不一样
