### ISSUE TITLE
4.x 版本不可以设置每个接口的全局返回状态码吗

### ISSUE THREAD

**Issue by wandun** [xiaoymin/knife4j#704]
我希望每一个接口都会展示对应的返回相应状态码如下

![image](https://github.com/xiaoymin/knife4j/assets/29992863/d5ea645a-26b9-4af6-84ba-45f6fe30298f)

使用的版本是
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-spring-boot-starter</artifactId>
            <version>3.0.3</version>
        </dependency>

springBoot 版本是 2.3.1 

在升级到 4.x 后没有对应方法可以配置呢

**Comment by xiaoymin** [comment]
如果是springdoc，可以参考这篇文章说的customer接口：

https://doc.xiaominfo.com/docs/blog/customer-add-api
