### ISSUE TITLE
点击复制文档，复制的md文件中，没有接口名称

### ISSUE THREAD

**Issue by desertsurge** [xiaoymin/knife4j#71]
复制文档的内容是以“接口地址”开始的，缺少接口名称。

**Comment by xiaoymin** [comment]
你指的是单个接口页面的那个复制？

**Comment by desertsurge** [comment]
对的。

接口地址上面应该有接口名称， `@ApiOperation` 中的内容。

另外复制后，接口描述由于没有，显示两个引号‘’。

代码中Controller上写的是 `@ApiOperation("查询用户")`

**Comment by xiaoymin** [comment]
1.9.2已改进
