### ISSUE TITLE
4.x如何标识响应参数？

### ISSUE THREAD

**Issue by lengmianshi** [xiaoymin/knife4j#711]
swagger-bootstrap-ui中由@ApiOperation(response = xxx.class)来指定，4.x版本死活找不到response这个属性

**Comment by xiaoymin** [comment]
参考这篇文档：https://doc.xiaominfo.com/docs/quick-start/start-knife4j-version

`@ApiOperation`注解是Swagger2的规范，你要根据不同的规范选择不同的版本，看你自己用那个

**Comment by lengmianshi** [comment]
> 参考这篇文档：https://doc.xiaominfo.com/docs/quick-start/start-knife4j-version
> 
> `@ApiOperation`注解是Swagger2的规范，你要根据不同的规范选择不同的版本，看你自己用那个

我用这个版本，已经没有@ApiOperation注解了
`   <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.4.0</version>
        </dependency>`

**Comment by lengmianshi** [comment]
新版表示方式太繁琐了：
`@ApiResponse(description = "列表查询用户返回",content = {
    @Content(
        array= @ArraySchema(schema = @Schema(implementation = YaUser.class))
    )
})`

**Comment by xiaoymin** [comment]
规范就是这样，我也无能为力
