### ISSUE TITLE
用实体类接受参数，自动按json来接受

### ISSUE THREAD

**Issue by lengmianshi** [xiaoymin/knife4j#713]
我用实体类来接受请求参数，但是文档是以json形式来表示参数的。怎样像swagger-bootstrap-ui一样，将实体类的每个属性按普通参数来解析？
```java
@GetMapping(value = "list")
    @Operation(summary = "获取组列表")
    @ApiResponse(content = {
            @Content(array = @ArraySchema(schema = @Schema(implementation = ChannelGroupListDTO.class)))
    })
    public Object groupList(ChannelGroupParam param) {
        PageInfo<ChannelGroupListDTO> page = channelGroupService.selectPage(param);
        return AppResult.ok(page);
    }
```

文档：
![image](https://github.com/xiaoymin/knife4j/assets/18379086/463d9bc6-8e8c-4828-989f-21ee2b7ac845)

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

**Comment by lengmianshi** [comment]
> https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param

谢谢，已解决
