### ISSUE TITLE
SpringCloud Gateway网关聚合文档，关闭基于服务名的转发后，文档访问失败

### ISSUE THREAD

**Issue by bowenchang** [xiaoymin/knife4j#715]
使用SpringCloud Gateway网关聚合时，如果开启服务名转发则正常，如果关闭则出现404，具体配置如下：
# 是否开启基于服务名称的路由转发规则
spring.cloud.gateway.discovery.locator.enabled=false
# 将请求路径上的服务名配置为小写
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
如果将spring.cloud.gateway.discovery.locator.enabled=true时，文档正常，设置为false访问失败，是否有根据服务路由配置来转发呢？ 因为服务是动态接入的，需要自动发现，没办法手工去配置，有什么好的解决方案？

**Comment by xiaoymin** [comment]
如果你是服务发现的方式，但是转发策略不是gateway默认的基于服务名称转发，而是你们自定义的规则，那么你可以考虑自己写一个规则来适配你们自己的业务情况，`knife4j-gateway`组件默认4种实现，你可以根据你们自己的业务规则，扩展属于你们业务的第5种

- 文章参考：https://doc.xiaominfo.com/docs/blog/gateway/knife4j-gateway-introduce
- 源码参考：[DiscoverClientRouteServiceConvert.java](https://github.com/xiaoymin/knife4j/blob/dev/knife4j/knife4j-gateway-spring-boot-starter/src/main/java/com/github/xiaoymin/knife4j/spring/gateway/discover/router/DiscoverClientRouteServiceConvert.java),继承`AbstactServiceRouterConvert.java`，写自己业务规则
