### ISSUE TITLE
图片显示问题

### ISSUE THREAD

**Issue by xqdd** [xiaoymin/knife4j#72]
#### 如图所示，不能适应图片大小
两种解决方案：
1.显示大小用固定值，不过这个固定值要设置大一点
2.自动判断图片大小显示

![image](https://user-images.githubusercontent.com/20871761/54970410-eff88b80-4fbc-11e9-86ec-3e716b2e575b.png)
![image](https://user-images.githubusercontent.com/20871761/54970509-5aa9c700-4fbd-11e9-8c2f-68656e14921d.png)

**Comment by xqdd** [comment]
![image](https://user-images.githubusercontent.com/20871761/55391206-76880c80-556b-11e9-82e8-64abab4d52eb.png)

默认大小大一点吧，不要吝啬

**Comment by xiaoymin** [comment]
下个版本改进一下

**Comment by xiaoymin** [comment]
1.9.2已经发布 改进

**Comment by xqdd** [comment]
@xiaoymin  
### 不过在RAW，header，curl中还是一样

![image](https://user-images.githubusercontent.com/20871761/55719639-4c35c380-5a31-11e9-8495-98bf7154e724.png)
![image](https://user-images.githubusercontent.com/20871761/55719646-4fc94a80-5a31-11e9-9654-5908b214b78b.png)

**Comment by xiaoymin** [comment]
> @xiaoymin
> 
> ### 不过在RAW，header，curl中还是一样
> ![image](https://user-images.githubusercontent.com/20871761/55719639-4c35c380-5a31-11e9-8495-98bf7154e724.png)
> ![image](https://user-images.githubusercontent.com/20871761/55719646-4fc94a80-5a31-11e9-9654-5908b214b78b.png)

忘记了 下个版本再补上
