### ISSUE TITLE
knife4j-4.3.0版本doc.html访问404，怀疑是否是与satoken整合有关

### ISSUE THREAD

**Issue by Junlogz** [xiaoymin/knife4j#722]
springboot版本-3.1.7，sa-token-spring-boot3-starter版本-1.37.0，
<dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>4.3.0</version>
</dependency>
尝试了各种放行doc.*等方式还是无法访问 ip:port/doc.html
参考了相关文章:https://blog.csdn.net/qq_37681291/article/details/127208142
https://blog.csdn.net/dr3344521/article/details/122734311
仍然无法解决，奇怪的是swagger-ui.html是可以正常进行访问的
![image](https://github.com/xiaoymin/knife4j/assets/64343822/a6b59893-8beb-45e1-aafe-0d42d8a7de7f)

**Comment by xiaoymin** [comment]
不确定，这个得你自己排查一下

**Comment by Nelson-Wcg** [comment]
请问这个问题解决了吗，我最近也遇到了类似的问题，看看有没有可以借鉴的
