### ISSUE TITLE
springboot2.7.18 controller接口添加validation相关校验后query参数被判断为body参数 （knife4j-openapi2-spring-boot-starter 4.5.0）

### ISSUE THREAD

**Issue by tombingo** [xiaoymin/knife4j#724]
**Describe the bug**
controller接口添加validation相关校验后query参数被判断为body参数
![image](https://github.com/xiaoymin/knife4j/assets/13918652/eceaec61-7501-4928-844b-7f49d7ddadd8)
![image](https://github.com/xiaoymin/knife4j/assets/13918652/6ed531b3-f8a3-4a27-89d5-6978c48b0604)
![image](https://github.com/xiaoymin/knife4j/assets/13918652/b4df0a3f-92e6-430d-8918-b87a7c07b1d2)
![image](https://github.com/xiaoymin/knife4j/assets/13918652/62bbffe5-16f5-4dae-a826-a99f0afd8a34)
![image](https://github.com/xiaoymin/knife4j/assets/13918652/7cb938f7-87fe-46af-83a4-7198b8285936)
![image](https://github.com/xiaoymin/knife4j/assets/13918652/d5c38812-556b-4d61-8a03-3133bec306ce)

**Comment by xiaoymin** [comment]
写个`@RequestParam`即可
