### ISSUE TITLE
关于@ApiModelProperty中的dataType配置不生效问题

### ISSUE THREAD

**Issue by pengjianbo** [xiaoymin/knife4j#729]
字段名定义的是一个List<String>类型，自定dataType为string，在文档中还是显示array。效果如下：
![image](https://github.com/xiaoymin/knife4j/assets/3264712/3f344264-abb1-472d-bdc6-edefa380c84c)
![image](https://github.com/xiaoymin/knife4j/assets/3264712/23bbcd82-af02-4fee-9daf-ae6f53172884)

从结果上来看`@ApiModelProperty`配置没起作用，参数名应该显示`guids`，数据类型应该是`string`

**Comment by xiaoymin** [comment]
后面不是有schema吗？List<String>

另外这个不是ui解析的问题，springfox解析就认为你这个不对，按代码来才对

**Comment by pengjianbo** [comment]
使用openapi3是可以这样的写法，但knife4j使用openapi3又不支持国际化
