### ISSUE TITLE
openapi3有类似DocumentationPluginsBootstrapper.start()功能吗

### ISSUE THREAD

**Issue by Melodykuang** [xiaoymin/knife4j#730]
版本为knife4j-openapi3-jakarta-spring-boot-starter：4.3.0
想要实现类似springfox的功能怎么做呢
` try {
            DocumentationPluginsBootstrapper documentationPluginsBootstrapper = SpringBeanUtils.getExistBean(mainApplicationContext,
                    DocumentationPluginsBootstrapper.class);
            if (documentationPluginsBootstrapper != null) {
                documentationPluginsBootstrapper.stop();
                documentationPluginsBootstrapper.start();
            } else {
                log.warn("Not found DocumentationPluginsBootstrapper, so cannot refresh swagger");
            }
        } catch (Exception e) {
            // ignore
            log.warn("refresh swagger failure");
        }`

**Comment by xiaoymin** [comment]
要做什么，需求都不清楚

**Comment by Melodykuang** [comment]
> 要做什么，需求都不清楚

基于pf4j插件开发的接口，在install插件之后打开文档页面看不到插件里面的接口，想要在install的时候重新去加载
