### ISSUE TITLE
SpringBoot 3.X版本  Spring Cloud 2022.0.0.0 版本  加入knife4jknife4j-gateway-spring-boot-starter 404

### ISSUE THREAD

**Issue by Kiki513H** [xiaoymin/knife4j#735]
gateway  POM文件 加入 
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-gateway-spring-boot-starter</artifactId>
        </dependency>

版本是 4.4.0 

gateway启动没问题 访问 进去访问 开始 404
![企业微信截图_17070544598937](https://github.com/xiaoymin/knife4j/assets/130541435/755b6e89-eda0-4912-87a3-40bc2876a186)

xml配置文件是这一段:
knife4j:
  gateway:
    # 是否开启
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    # 子服务存在其他分组情况，聚合其他分组，只能手动配置
    routes:
      - name: 用户服务-1
        # 子服务存在其他分组情况，聚合其他分组
        url: /user-service/v2/api-docs?group=用户服务
        # 服务名称(Optional)
        service-name: user-service
        # 路由前缀
        context-path: /
        # 排序
        order: 2
      - name: 订单服务-2
        url: /order-service/v2/api-docs?group=订单服务
        service-name: order-service
        # 路由前缀
        context-path: /
        order: 3
    # 服务发现模式的配置
    discover:
      # 开启
      enabled: true
      # 指定版本号(swagger2|openapi3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway-service
      # 如果子服务是OpenAPI3，并且有个性化配置
      oas3:
        url: /v3/api-docs?group=default
        oauth2-redirect-url: ''
        validator-url: ''
      # 如何子服务是Swagger2，并且个性化配置
      swagger2:
        url: /v2/api-docs?group=default
      # 单个服务的个性化配置，key-服务名称，value-配置信息
      service-config:
        # 假设order服务(具体真实服务开发者根据自己的情况配置)
        order-service:
          # 该服务的排序
          order: 0
          # 分组显示名称
          group-name: 订单服务名称
          # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
          context-path: /
          # 该属性自4.2.0添加，支持子服务非`default`分组的其他分组聚合
          # 参考 https://gitee.com/xiaoym/knife4j/pulls/87
          group-names:
            - 分组1
            - 分组2

启动第二个微服务 POM是沿用基础包 :
  
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        </dependency>

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/org/**'
      packages-to-scan: com.hthium.user
  default-flat-param-object: false
![image](https://github.com/xiaoymin/knife4j/assets/130541435/020b8ee8-eaf3-411d-83a0-2368183106ea)

单独访问 子服务 是没有问题的
![image](https://github.com/xiaoymin/knife4j/assets/130541435/cff28767-83f4-426f-95c4-a012a49f438f)

诉求是: 我现在正在用 jdk17 + SpringCloud Alibaba 2022.0.0.0 SpringBoot 3.1.2版本 重构项目. 
需要用到聚合文档.
请各路大神 以及 作者 赐教帮助一下!
谢谢

**Comment by Kiki513H** [comment]
我下载了 源码 进行了 
改了
![1707056492699](https://github.com/xiaoymin/knife4j/assets/130541435/aaed0d54-fe32-4045-b343-140fe12275cb)
进行进行启动 启动完成之后  也是这个错误

**Comment by Kiki513H** [comment]
已解决！

**Comment by zoukaixin791** [comment]
@Kiki513H 请大神赐教一下，怎么解决的

**Comment by monchcc** [comment]
@zoukaixin791 最后是怎么解决的呢？

**Comment by HackerLZH** [comment]
因为gateway设置的filter拦截了/api/user/v3/api-docs，而/api/user/肯定是后端controller统一设置的请求前缀，我试验过，将/api/user/v3/api-docs开放也没用，还是得将这个请求前缀删掉，然后filter里面RewritePath去掉/api/user就可以正常显示了
