### ISSUE TITLE
响应内容无法如在线示例进行正常格式化

### ISSUE THREAD

**Issue by Maidamai** [xiaoymin/knife4j#74]
![GitHub](https://user-images.githubusercontent.com/35438086/55125478-c10d2180-5144-11e9-8c0c-969c626ce9e3.png)

**Comment by xiaoymin** [comment]
这个是你自己json序列化了两次吧，就不是一个正常的json，只是一个字符串

**Comment by Maidamai** [comment]
response里返回是正常的
![GitHub2](https://user-images.githubusercontent.com/35438086/55129338-b5742780-5151-11e9-81ea-2dca8a9c80f6.png)

**Comment by xiaoymin** [comment]
> response里返回是正常的
> ![GitHub2](https://user-images.githubusercontent.com/35438086/55129338-b5742780-5151-11e9-81ea-2dca8a9c80f6.png)

你这个响应出来的数据就是一个String字符串，后端并没有标注application/json

**Comment by Maidamai** [comment]
非常感谢你的回答，为我指明了方向。是后台内容协商的问题
