### ISSUE TITLE
SpringBoot3 报 javax.servlet.Filter  java.lang.ClassNotFoundException错误

### ISSUE THREAD

**Issue by marsxuefeng** [xiaoymin/knife4j#748]
**Describe the bug**
Spring Boot 3.0 已经从 Java EE 升级为 JakartaEE API，但knife4j引入的还是 javax.servlet相关的包，是否有计划支持SpringBoot3.0

**Screenshots**
![image](https://github.com/xiaoymin/knife4j/assets/41226448/be92e720-5929-469b-88ca-4e54cf695bdc)

**Knife4j Version (please complete the following information):**
 4.5.0

**Comment by xiaoymin** [comment]
我也不知道你用的那个组件

看blog：https://doc.xiaominfo.com/docs/quick-start/start-knife4j-version

**Comment by marsxuefeng** [comment]
好的，我看到了 https://github.com/xiaoymin/knife4j/issues/667 这个issue，已经解决了，谢谢~
