### ISSUE TITLE
Spring Boot3 版本，接口返回子字段含泛型展示错误

### ISSUE THREAD

**Issue by jiankian** [xiaoymin/knife4j#751]
**Bug描述**
接口返回泛型字段不能正确显示，所有接口只显示一个随机的Schema类型。

之前用Spring Boot 2.7老版本可以正确展示接口返回泛型字段
```xml
<dependency>
        <groupId>com.github.xiaoymin</groupId>
        <!--使用Swagger2-->
        <artifactId>knife4j-spring-boot-starter</artifactId>
        <version>3.0.3</version>
</dependency>
```
最新版本却不行，4.0以上版本每个版本都有问题。
```xml
<dependency>
       <groupId>com.github.xiaoymin</groupId>
       <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
       <version>4.5.0</version>
 </dependency>
```

IDEA标准项目，没有使用什么热更新插件啥的，主要是老版本是支持的，新版本就没了。

**Screenshots**

**Knife4j Version (please complete the following information):**
4.5.0
**Additional context**
Spring Boot3+knife4.5.0

**Comment by xiaoymin** [comment]
虽然你提了问题，但是我不知道提了什么问题。作者如何复现？

**Comment by jiankian** [comment]
假设我定义一个接口返回类型，字段 `data`是泛型
```java

public class ApiBaseDTO<T> implements Serializable {

    private int code;

    private String msg;

    private String extra;

    private boolean success;

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private LocalDateTime time = LocalDateTime.now();

    private T data;
}

```

然后，在控制器定义返回类型：

接口A：
```java
    @Operation(summary = "获取详情")
    @GetMapping("/getOneDetailById")
    ApiBaseDTO<Entity1> getOneDetailById(@RequestParam(required = false) Integer id) {
        return entity1Service.getOneDetailById(id);
    }
```
接口B：
```java
    @Operation(summary = "获取详情")
    @GetMapping("/getOneDetailById")
    ApiBaseDTO<Entity2> getOneDetailById(@RequestParam(required = false) Integer id) {
        return entity2Service.getOneDetailById(id);
    }
```

在渲染的文档中，所有接口的data字段的Schema都是同一个，且随机。
原来的Spring Boot 2.7 + knife4j-spring-boot-starter 3.0.3则是正常的。

**Comment by jiankian** [comment]
![微信图片_20240315110402](https://github.com/xiaoymin/knife4j/assets/9036838/6cb7dfd4-2cb5-4929-9a0e-075fcabf4aa7)

**Comment by xiaoymin** [comment]
demo无法复现

https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/ac55f7d3583596b22bcf8c2876acd03fd5e094f2/knife4j-springdoc-openapi-demo

**Comment by xiaoymin** [comment]
<img width="870" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/6e5bc2ef-4aee-46b8-a85c-95de2da85ab6">
<img width="877" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/2128b084-e8a8-47d3-a124-99a987c349bb">
<img width="1213" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/292c627d-d49f-40cc-a057-575aa926a40c">

**Comment by xiaoymin** [comment]
<img width="1816" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/811e39cb-2d62-4206-912b-a7dcad399a9e">
<img width="1491" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/2e0ee034-72f1-4ab3-a3d6-4120c44fd52d">

**Comment by jiankian** [comment]
我出现问题是 `Spring Boot3`版本，我的`Spring Boot 2.7.18`也是正常的。

**Comment by jiankian** [comment]
我把项目中多余内容删除，可以复现问题：

[https://gitee.com/jiankian/knife4j-v4-spring-boot-v3-demo/blob/master/src/main/java/com/binfei/yjs/server/controller/HelloController.java](https://gitee.com/jiankian/knife4j-v4-spring-boot-v3-demo/blob/master/src/main/java/com/binfei/yjs/server/controller/HelloController.java)

所有接口的data字段的schema都是同一个，本该是不同的schema

**Comment by jiankian** [comment]
降级到 Spring Boot 2.7.18也会有问题，带 `jakarta`的依赖的版本就有此问题

**Comment by xiaoymin** [comment]
> https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/tree/ac55f7d3583596b22bcf8c2876acd03fd5e094f2/knife4j-springdoc-openapi-demo

上面的例子就是2.7.18版本，正常的

**Comment by xiaoymin** [comment]
Spring Boot 3.2.3

Knife4j 4.5.0

基于你给的代码也没测出来

https://gitee.com/xiaoym/swagger-bootstrap-ui-demo/blob/bb3d4d39b4967876cf1a774b28a5cc156a25f981/knife4j-spring-boot3-demo/src/main/java/com/github/xiaoymin/boot3/web/Simple1Controller.java

**Comment by xiaoymin** [comment]
`@Schema`注解的作用是重命名，条件是**必须全局唯一**，这种场景下，在泛型类上面用这个注解是不合适的，需要去掉


```java
@Slf4j
@Data
public class ApiBaseDTO<T> implements Serializable {
  //....
}
```

**Comment by jiankian** [comment]
好的，已解决，谢谢
