### ISSUE TITLE
Kotlin DataClass 解析出重复字段

### ISSUE THREAD

**Issue by setruth** [xiaoymin/knife4j#752]
Kotlin DataClass的字段如果是uId 那么会解析出一个多的uid 这种全小写的 
knife4j 4.3.0
springboot 3.2.0

![BDD) 6FC@ `QO43%)YVI9OY](https://github.com/xiaoymin/knife4j/assets/108395774/061b5228-f7cf-4ad5-af59-1ef08ebce4a2)

**Comment by xiaoymin** [comment]
这个我印象中这种驼峰的写法就是不支持的。不是knife4j界面渲染的问题，不管是springdoc还是springfox，对于这种命名(第二个字母大写)都认为是不规范

**Comment by jiankian** [comment]
一般不推荐单字母的驼峰命名，很多地方容易出问题。

**Comment by setruth** [comment]
> 这个我印象中这种驼峰的写法就是不支持的。不是knife4j界面渲染的问题，不管是springdoc还是springfox，对于这种命名（第二个字母大写）都认为是不规范

好的感谢，主要是有一个ACTable所以用这种字段的命名比较方便，便于生成表中的字段
