### ISSUE TITLE
多层级泛型不显示字段注释  使用spring boot3和spring doc

### ISSUE THREAD

**Issue by DreamPWJ** [xiaoymin/knife4j#763]
![image](https://github.com/xiaoymin/knife4j/assets/16730031/7da15f26-0849-46f3-879b-c02581bcd4f9)
![image](https://github.com/xiaoymin/knife4j/assets/16730031/f65cbe20-f897-47ed-9d31-238d9b2a2a09)
![image](https://github.com/xiaoymin/knife4j/assets/16730031/c68975d0-9ce7-4a9a-a0ed-3cff89cd315c)
![image](https://github.com/xiaoymin/knife4j/assets/16730031/1b06fb64-7188-45ff-b7fd-4443679bded5)

**Comment by xiaoymin** [comment]
https://github.com/xiaoymin/knife4j/issues/751

**Comment by DreamPWJ** [comment]
这个ssues我已经试过了，不起作用  是去掉@ Data是吧？

**Comment by DreamPWJ** [comment]
這個issues和我的情况很像，但是没有生效， 如果不能用lombok那代码会很臃肿啊， 能给解释一下为什么吗？ 之前的spring boot2和spring fox方式是可以显示的  @xiaoymin

**Comment by xiaoymin** [comment]
泛型类不能用`@Schema`注解标注

**Comment by xiaoymin** [comment]
https://doc.xiaominfo.com/docs/faq/swagger-des-not-found

**Comment by DreamPWJ** [comment]
泛型类如果不能用@Schema注解那就没有意义了， 泛型类是实体类或者是主要的VO类，就是这个泛型类要展示到文档上去，有没有解决方案？   之前的spring boot2和spring fox方式是可以显示的，上面的文档我已经看过没有相关使用spring boot3和spring doc的解决方案 @xiaoymin

**Comment by xiaoymin** [comment]
`@Schema`标注了就是代表唯一，这个本身和泛型类冲突。

你要改自定义，不用Schema注解，自己写个扩展注解，用springdoc的[插件体系](https://doc.xiaominfo.com/docs/blog/customer-add-api#-springdoc)去重写更改解析规则即可

<img width="1044" alt="image" src="https://github.com/xiaoymin/knife4j/assets/7894406/210380b3-8787-423d-8959-08ef3ae40d33">

**Comment by DreamPWJ** [comment]
这个扩展有点成本，或者knife4j直接提供一个注解解决这个问题不就好了？而且这种泛型方式比较常用，我看issue里挺多的，knife4j最好能出个完整的解决方案,, 咱们提供的UI解决方案就比swagger官方强太多  @xiaoymin

**Comment by xiaoymin** [comment]
@DreamPWJ 欢迎PR

**Comment by DreamPWJ** [comment]
水平有限啊

**Comment by DreamPWJ** [comment]
去掉泛型属性 @Schema注解解决
