### ISSUE TITLE
求救，升级springboot3后多个对象识别为arg0、arg1

### ISSUE THREAD

**Issue by Hirsi-He** [xiaoymin/knife4j#769]
版本是4.5.0

![image](https://github.com/xiaoymin/knife4j/assets/48676315/5b5f4574-eb7a-4bfd-81b1-ba56d7e5d9d0)
![image](https://github.com/xiaoymin/knife4j/assets/48676315/287d3b8b-f014-4dfe-9457-d705da9c21de)
![image](https://github.com/xiaoymin/knife4j/assets/48676315/5fe08ad3-38cf-4808-88ff-e3495d0f4d63)
![image](https://github.com/xiaoymin/knife4j/assets/48676315/d6629c49-9107-4bb5-801b-e1de261bb2ad)
![image](https://github.com/xiaoymin/knife4j/assets/48676315/269f4901-35d4-40e4-8f3f-63c48be699a4)
一下是没有升级springboot 3的时候
![image](https://github.com/xiaoymin/knife4j/assets/48676315/a7157467-4fe9-4d7c-bbf2-c2608c7c2835)
![image](https://github.com/xiaoymin/knife4j/assets/48676315/4d151f31-a0d8-4f33-a93d-94141ccd8c7b)

**Comment by xiaoymin** [comment]
这个看看是否是springdoc的问题。或者是否用了热加载插件之类的，导致的

**Comment by hebrd** [comment]
请问这个问题是如何解决的？

**Comment by Hirsi-He** [comment]
这个问题已经解决，参数前加@ParameterObject注解

**Comment by Hirsi-He** [comment]
> 请问这个问题是如何解决的？
参数前加@ParameterObject注解
