### ISSUE TITLE
什么时候升级ClassGraph，io.github.classgraph版本低

### ISSUE THREAD

**Issue by DragonSuper** [xiaoymin/knife4j#770]
io.github.classgraph版本低，与新项目冲突，导致方法无法找到
![1-bug](https://github.com/xiaoymin/knife4j/assets/5461476/19bd3b81-006e-4dd8-a564-1b50e5a2e761)
![2-bug](https://github.com/xiaoymin/knife4j/assets/5461476/70f944f6-c542-4318-a949-ddda4b39e498)

**Comment by xiaoymin** [comment]
springfox的项目不会再升级，用openapi3，springdoc
