### ISSUE TITLE
favicon.ico  404 Not Found  

### ISSUE THREAD

**Issue by lexang** [xiaoymin/knife4j#772]
**Describe the bug**
favicon.ico  404 Not Found  

**Knife4j Version (please complete the following information):**
  4.3.0

**Additional context**
之前一直都可以 不知道为什么最近不行了
看网络是这个404  然后页面加载不出来

![微信截图_20240415100310](https://github.com/xiaoymin/knife4j/assets/10265864/04d6306f-832b-4851-b129-5a399f0edc2a)

**Comment by xiaoymin** [comment]
之前有人觉得放Knife4j自己的favicon.ico干扰了他们项目、公司之类的，后面我就把这个文件删了

你可以升级一下到4.5.0版本，最新版本的[doc.html](https://github.com/xiaoymin/knife4j/blob/dev/knife4j/knife4j-openapi2-ui/src/main/resources/doc.html) 都没有引入这个文件

**Comment by PVulcanCN** [comment]
> 之前有人觉得放Knife4j自己的favicon.ico干扰了他们项目、公司之类的，后面我就把这个文件删了
> 
> 你可以升级一下到4.5.0版本，最新版本的[doc.html](https://github.com/xiaoymin/knife4j/blob/dev/knife4j/knife4j-openapi2-ui/src/main/resources/doc.html) 都没有引入这个文件

4.5.0还是有这个问题

**Comment by xiaoymin** [comment]
也许是你们的浏览器缓存

openapi2-ui：https://github.com/xiaoymin/knife4j/blob/dev/knife4j/knife4j-openapi2-ui/src/main/resources/doc.html

openapi3-ui：https://github.com/xiaoymin/knife4j/blob/dev/knife4j/knife4j-openapi3-ui/src/main/resources/doc.html

都没有对favicon.ico的link引用

另外，这个ico文件后面也不会加了，免得说干扰之类的。

**Comment by jkhuangfu** [comment]
浏览器会自动查找 favicon.ico文件并引入，即使你html并未引入favicon.ico
解决方案就是把public下的favicon.ico文件删除

**Comment by freekevinCode** [comment]
也可以通过写个拦截器 拦截对favicon.ico的http请求 直接处理一下 就不会有这个报错了 
更省事的方法是 resource下static目录中直接放个favicon.ico 文件也行
