### ISSUE TITLE
@ApiModel value 长度限制？

### ISSUE THREAD

**Issue by wandun** [xiaoymin/knife4j#780]
**Describe the bug**

因为 @ApiModel 通过value 确认唯一性，所以，我直接给value赋值为 当前类的全类名如：
com.xxx.api.params.controller.resp.xxx.xxxxx.DetailDto

![image](https://github.com/xiaoymin/knife4j/assets/29992863/4edb52cd-69c8-496d-8734-dac8ce80e4b6)

但是页面不显示？一旦我减少内容 比如 xxxx 的 DetailDto 就会显示，所以value是有长度限制吗

springBoot：2.3.1.RELEASE
knife4j：  knife4j-spring-boot-starter  3.0.3

**Comment by xiaoymin** [comment]
这个knife4j这层是没有做这个限制的，你可以看看解析出来的openapi规范，是不是有这个问题呢？

唯一性不用这么长吧。。。。。
