### ISSUE TITLE
spring doc升级到2.4.0及以后的版本，group-configs异常

### ISSUE THREAD

**Issue by toby-huang-jp** [xiaoymin/knife4j#781]
**Describe the bug**
使用knife4j-openapi3-jakarta-spring-boot-starter的最新的4.5.0版本
将springdoc-openapi的相关依赖升级到2.4.0后，配置的API分组异常。
排查原因后，确定是org.springdoc.core.properties.SpringDocConfigProperties#getGroupConfigs的返回值类型，由List变为Set是方法查找失败导致。

查看源码后，不用做任何新的代码改动
需引入新的依赖后，再打一个对应的包即可

谢谢，你们的辛苦付出

**Comment by xiaoymin** [comment]
是什么意思？升级springdoc-openapi版本到2.4.0就好了吗？

**Comment by toby-huang-jp** [comment]
> 是什么意思？升级springdoc-openapi版本到2.4.0就好了吗？

就是springdoc-openapi版本到2.4.0及之后的版本，就会发生错误
无法找到org.springdoc.core.properties.SpringDocConfigProperties#getGroupConfigs方法。

其实方法本身是存在的，只是返回值类型变为了Set，原本是List类型。

我看了处理的源码，是使用collection类型来处理的，所以逻辑代码不用动。
需针对新的版本API再编译一遍就可以了

**Comment by xiaoymin** [comment]
需要knife4j这边做什么？发布新版本，springdoc的依赖升级为2.4.0吗

**Comment by toby-huang-jp** [comment]
> 需要knife4j这边做什么？发布新版本，springdoc的依赖升级为2.4.0吗

我认为是这样的

辛苦你了

**Comment by 805728578** [comment]
@xiaoymin 升级springdoc到2.5.0/1.8.0

**Comment by toby-huang-jp** [comment]
> @xiaoymin 升级springdoc到2.5.0/1.8.0

请问新版本什么时候发布？
