### ISSUE TITLE
knife4j文档请求异常

### ISSUE THREAD

**Issue by guaguaguaxia** [xiaoymin/knife4j#786]
**Describe the bug**

**To Reproduce**
多个模块只有其中一个模块有问题，看接口返回的数据是没问题的，复制到json格式化网站也可以格式化，但是看console报了一个错

**Expected behavior**

**Screenshots**
![image](https://github.com/xiaoymin/knife4j/assets/18466048/234022f2-7255-40d1-9f80-2ffcf61f4b93)

![image](https://github.com/xiaoymin/knife4j/assets/18466048/1bca6a02-424c-4524-adc1-0946f8774f13)

**Knife4j Version (please complete the following information):**
2.0.4

**Additional context**

**Comment by xiaoymin** [comment]
可以升级到4.5.0试试

https://doc.xiaominfo.com/docs/upgrading/upgrading-to-v4

https://doc.xiaominfo.com/docs/quick-start/start-knife4j-version

**Comment by guaguaguaxia** [comment]
好的，谢谢
