### ISSUE TITLE
请求字段修改，增加，文档给与提示

### ISSUE THREAD

**Issue by xuzongmeng** [xiaoymin/knife4j#79]
新增能否像新增接口一样，能够在新增或者修改的请求字段，上面标注修改或新增样式

**Comment by xiaoymin** [comment]
可以的，下个版本加进去

**Comment by xiaoymin** [comment]
文档内容修改会和新增一样，有标识

https://www.oschina.net/news/106165/swagger-bootstrap-ui-1-9-3-released
