### ISSUE TITLE
对于@Parameter @ModelAttribute @Valid共同注解所获取的数据，在请求时请求数据格式存在问题

### ISSUE THREAD

**Issue by Astrsea** [xiaoymin/knife4j#792]
使用依赖版本
````
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>3.2.4</version>
  <relativePath/> <!-- lookup parent from repository -->
</parent>

<java.version>21</java.version>
<knife4j.version>4.4.0</knife4j.version>
<springdoc-openapi.version>2.4.0</springdoc-openapi.version>

<!-- springdoc-openapi-ui界面 -->
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
	<version>${springdoc-openapi.version}</version>
</dependency>

<!-- springdoc-openapi-api接口 -->
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
	<version>${springdoc-openapi.version}</version>
</dependency>
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
	<version>${knife4j.version}</version>
</dependency>
````

请求查询参数实体类
````java
@Schema(title = "系统角色表查询对象")
@EqualsAndHashCode(callSuper = true)
@Data
public class SystemRoleQO extends BasePageQuery<SystemRole>{
    @Schema(title = "系统角色id")
    private String systemRoleId;

    @Schema(title = "系统角色名称")
    private String name;

    @Schema(title = "系统角色描述")
    private String description;
}

````
请求查询参数实体类父类
````java
@Data
public abstract class BasePageQuery<T> implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    @Min(1)
    @Schema(title = "当前页")
    private Integer pageIndex = 1;

    @Min(1)
    @Max(100)
    @Schema(title = "当前页大小")
    private Integer pageSize = 10;

    @Schema(title = "排序字段")
    @Xss
    private String orderBy;

    @Schema(title = "排序方式")
    private Boolean desc;
}
````

controller
````java
list(@Parameter(name = "列表查询对象", in = ParameterIn.QUERY) @ModelAttribute @Valid SystemRoleQO systemPermissionQO)
````

swagger中显示的内容及对应的请求内容
![image](https://github.com/xiaoymin/knife4j/assets/134401374/50e61a90-3eb8-4d1e-882d-98c51127e6bc)
![image](https://github.com/xiaoymin/knife4j/assets/134401374/d1187113-51cb-445b-86f1-9b6a39201c0c)
![image](https://github.com/xiaoymin/knife4j/assets/134401374/19ab3658-a7f7-44dd-8778-89420de85b80)

knife4j中显示的内容及对应的请求方式
![image](https://github.com/xiaoymin/knife4j/assets/134401374/a5e8c1f0-fa6f-4eb5-b266-e06c29dbdf8a)
![image](https://github.com/xiaoymin/knife4j/assets/134401374/95df84f2-cea9-44ee-914b-7822251f485b)
![image](https://github.com/xiaoymin/knife4j/assets/134401374/c9f3ee54-05a6-4a99-be9f-40cd8feb2f11)

问题：
会出现以单个对象的形式拼接到查询参数中，并非以单独参数的形式拼接到查询参数中

**Comment by Astrsea** [comment]
@xiaoymin 这个问题如何解决

**Comment by Xiamu-ssr** [comment]
嘿，请问这个解决了吗最后。我使用4.5.0也是如此.
<dependency>
	<groupId>com.github.xiaoymin</groupId>
	<artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
	<version>4.5.0</version>
</dependency>

**Comment by Astrsea** [comment]
> ```java
> te @Valid SystemRoleQO systemPe
> ```

@Operation(description = "列表")
    @OperationAnnotation
    @RateLimiter
    @PreAuthorize("@pu.hasRole('SuperAdminRole')")
    @GetMapping("list")
    public PageInfo<SystemConfigVO> list(@Parameter(name = "列表查询对象", in = ParameterIn.QUERY) @ParameterObject @ModelAttribute @Valid SystemConfigQO systemConfigQO) {
        return PageInfo.pageVoCovert(systemConfigService.selectAll(systemConfigQO), SystemConfigVO.class);
    }

**Comment by Astrsea** [comment]
> 嘿，请问这个解决了吗最后。我使用4.5.0也是如此. com.github.xiaoymin knife4j-openapi3-spring-boot-starter 4.5.0

```java
@Operation(description = "列表")
    @OperationAnnotation
    @RateLimiter
    @PreAuthorize("@pu.hasRole('SuperAdminRole')")
    @GetMapping("list")
    public PageInfo<SystemConfigVO> list(@Parameter(name = "列表查询对象", in = ParameterIn.QUERY) @ParameterObject @ModelAttribute @Valid SystemConfigQO systemConfigQO) {
        return PageInfo.pageVoCovert(systemConfigService.selectAll(systemConfigQO), SystemConfigVO.class);
    }
```
加 @ParameterObject

**Comment by Xiamu-ssr** [comment]
> > 嘿，请问这个解决了吗最后。我使用4.5.0也是如此. com.github.xiaoymin knife4j-openapi3-spring-boot-starter 4.5.0
> 
> ```java
> @Operation(description = "列表")
>     @OperationAnnotation
>     @RateLimiter
>     @PreAuthorize("@pu.hasRole('SuperAdminRole')")
>     @GetMapping("list")
>     public PageInfo<SystemConfigVO> list(@Parameter(name = "列表查询对象", in = ParameterIn.QUERY) @ParameterObject @ModelAttribute @Valid SystemConfigQO systemConfigQO) {
>         return PageInfo.pageVoCovert(systemConfigService.selectAll(systemConfigQO), SystemConfigVO.class);
>     }
> ```
> 
> 加 @ParameterObject

很好，在我这里起作用了。
```java
@Operation(summary = "查询新闻列表-基于各种条件")
    @PostMapping("/news/search")
    public ResponseInfo<TableDateInfo<NewsSingleVo>> getNewsListBySearch(
            @RequestBody @Validated NewsListBySearchAdjustDto dto,
            @ParameterObject @ModelAttribute @Validated PageQuery pagequery
    ) 
```
