### ISSUE TITLE
非200状态不能正确显示schema中的字段注视

### ISSUE THREAD

**Issue by brant-yan** [xiaoymin/knife4j#80]
仅有200状态可以在“响应示例”的右侧显示字段说明。其他状态均无显示。

**Comment by xiaoymin** [comment]
贴个图？

**Comment by brant-yan** [comment]
没找到怎么贴图，发个百度盘给你
链接: https://pan.baidu.com/s/1w26AiQgeXxxtswvO3inGsQ 提取码: ipu6

`<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>2.9.2</version>
        </dependency>
<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>swagger-bootstrap-ui</artifactId>
            <version>1.9.2</version>
        </dependency>`

**Comment by xiaoymin** [comment]
要么加群？QQ群：608374991


你图中的我看到有两处

第一种情况，code=201的情况，你指的schema字段注释不显示 响应示例里面没显示？ 是这里吗？

第二个就是403 401的message显示不对？
