### ISSUE TITLE
4.4.0版本不支持多个请求头吗，调试里不显示只显示一个

### ISSUE THREAD

**Issue by wangjiancheng180** [xiaoymin/knife4j#821]
看了swagger-config返回的security对象多个但是只有一个显示

```
 "security": [
                    {
                        "Authorization": [

                        ]
                    },
                    {
                        "platformKey": [

                        ]
                    }
                ]
```
<img width="894" alt="D5B9A2D8-AAC7-4b01-B98B-09854609EAAE" src="https://github.com/user-attachments/assets/32893fc0-5e7e-4387-9da0-42d9cdfadeda">

**Comment by wangjiancheng180** [comment]
@Bean
    public GlobalOpenApiCustomizer orderGlobalOpenApiCustomizer() {
        return openApi -> {
            // 全局添加鉴权参数
            if (openApi.getPaths() != null) {
                openApi.getPaths().forEach((s, pathItem) -> {
                    // 为所有接口添加鉴权
                    pathItem.readOperations().forEach(operation -> {
                        operation.addSecurityItem(new SecurityRequirement().addList(HttpHeaders.AUTHORIZATION));
                        operation.addSecurityItem(new SecurityRequirement().addList(BusinessCommonUtil.HEADER_PLATFORM_KEY));
                    });
                });
            }

        };

    }``

**Comment by yc8855** [comment]
这个解决了吗
