### ISSUE TITLE
能否支持mock数据功能

### ISSUE THREAD

**Issue by keji94** [xiaoymin/knife4j#83]
场景:前端请求url，返回mock的数据

**Comment by stxpons** [comment]
同求，项目直接集成在springboot项目里。
比如后端增加一个拦截器，指定某路径（方法）是否mock或者前端通过header指定需要mock标志。
需要mock时，后端根据swagger example生成或自动生成mock数据（或者本地文件夹或远程resource(如http url)可以手工指定mock的json数据）

**Comment by neilgamer** [comment]
同求，mock server

**Comment by xiaoymin** [comment]
响应结构里面展示了字段也差不多吧，mock？

**Comment by neilgamer** [comment]
> 响应结构里面展示了字段也差不多吧，mock？

mock，提供直接的虚拟api，在service代码逻辑还没写好的时候，controller层直接返回定义的虚拟返回参数，这样就能在后端没写好的时候就提供给前端接口文档了，前端直接调用会返回虚拟response比如：{
	"applicantName": "kkk",
	"channel": "减肥减肥减肥""
}

**Comment by Ysonglin** [comment]
有好的方式支持mock嘛 其实就是点击调试直接返回ｍｏｃｋ的数据，避免后端还没开发完成

**Comment by wll8** [comment]
正在尝试引入 [mockm](https://github.com/wll8/mockm) 来实现模拟接口数据自动生成。

**Comment by xiaoymin** [comment]
> 正在尝试引入 [mockm](https://github.com/wll8/mockm) 来实现模拟接口数据自动生成。

欢迎提交PR
