### ISSUE TITLE
能否增加swagger-codegen的支持

### ISSUE THREAD

**Issue by lwydyby** [xiaoymin/knife4j#84]
能否增加通过swagger-codegen生成相关语言sdk压缩包并导出的功能

**Comment by xiaoymin** [comment]
可以详细描述一下吗？

印象中swagger-codegen是自动生成代码的，但是我并没有使用过，所以需求可能不是太了解

**Comment by lwydyby** [comment]
就是这个swagger-codegen 是通过运行他的jar包生成对应语言的sdk
比如：java -jar swagger-codegen-cli-2.4.4.jar generate -i http://localhost:8888/v2/api-docs -l java -o sdk/
目前我遇到的问题是，每次更新都需要执行这个命令，生成sdk文件，然后压缩发给用户，如果能在页面上直接选择语言生成，相信会简化很多

**Comment by xiaoymin** [comment]
> 就是这个swagger-codegen 是通过运行他的jar包生成对应语言的sdk
> 比如：java -jar swagger-codegen-cli-2.4.4.jar generate -i http://localhost:8888/v2/api-docs -l java -o sdk/
> 目前我遇到的问题是，每次更新都需要执行这个命令，生成sdk文件，然后压缩发给用户，如果能在页面上直接选择语言生成，相信会简化很多

那其实就是我把swagger-codegen-cli的jar集成进去吧，然后提供一个界面的功能，可以导出下载使用swagger-codegen-cli生成的压缩文件？

**Comment by xiaoymin** [comment]
如果是通过java-jar 命令来调用的话，我觉得做成一个服务来调用比较合适，服务暴露出一个api接口，然后UI里面集成进去，最终提供一个界面来生成

本身swagger-codegen.jar包并不小，引入的话可能并不是很合理
