### ISSUE TITLE
Spring Boot 3.4.0 版本不兼容2.7.0版本以下的 springdoc-openapi 

### ISSUE THREAD

**Issue by yozurukt** [xiaoymin/knife4j#864]
**Describe the bug**
Spring Boot 3.4.0 版本不兼容2.7.0版本以下的 springdoc-openapi 
是否考虑修改一下springdoc-api的版本？

https://github.com/springdoc/springdoc-openapi/issues/2785

**Comment by Forevery1** [comment]
同样的问题

**Comment by silvericestorm** [comment]
参考我的回复
https://github.com/xiaoymin/knife4j/issues/867#issuecomment-2518861823

**Comment by xingfudeshi** [comment]
```
<dependency>
            <groupId>com.github.xingfudeshi</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.6.0</version>
 </dependency>
```
可以先用这个

**Comment by yozurukt** [comment]
项目中没有用到knife4j的高级特性
目前选择仅引入其UI相关的包，以防止出现更多的兼容性问题。
当前项目似乎已经不再活跃了。在新项目中会慢慢考虑废弃掉这个依赖。

**Comment by ZhiXiao-Lin** [comment]
SpringBoot3.4.0 只要添加异常过滤器就会导致Knife4j无法使用
