### ISSUE TITLE
引入springboot3.4后v3/api-docs接口报Handler dispatch failed: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by mingyang66** [xiaoymin/knife4j#867]
**描述**
knife4j-openapi3-jakarta-spring-boot-starter+springboot3.4后请求/v3/api-docs报如下异常:
`Handler dispatch failed: java.lang.NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean.<init>(java.lang.Object)`

分析错误后发现：
`org.springdoc.core.service.GenericResponseService.lambda$getGenericMapResponse$8(GenericResponseService.java:702)`

此处代码：
`new ControllerAdviceBean(controllerAdviceInfo.getControllerAdvice()).isApplicableToBeanType(beanType))`
用到了ControllerAdviceBean类的一个参数的构造函数，但是springboot3.4已经移除，只有一个三个构造函数的参数：
` public ControllerAdviceBean(String beanName, BeanFactory beanFactory, ControllerAdvice controllerAdvice) {`

能不能快速兼容一下发一个版本，谢谢

**Comment by silvericestorm** [comment]
你这个问题不是knife4j导致的，而是旧版本的springdoc的问题，升级到springdoc-2.7.0这个问题会消失，但会出现新问题。新问题出现在库knife4j-openapi3-jakarta-spring-boot-starter的Knife4jOpenApiCustomizer类第75行，由于springdoc的SpringDocConfigProperties.getGroupConfigs返回类型由List<GroupConfig>变为Set<GroupConfig>，导致抛出NoSuchMethod异常。解决方法也很简单，下载4.5.0的源码，升级pom中的版本到你希望的版本，重新编译即可。我编译了一个自己的4.5.1版本，目前为止文档都是正常的，当然，不排除其他地方还可能出现类似的兼容性错误，但那也只有发生了才会知道。
最后，感谢作者提供了一个这么好用的工具，我已经用了快5年了

**Comment by xingfudeshi** [comment]
```
<dependency>
            <groupId>com.github.xingfudeshi</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.6.0</version>
 </dependency>
```
可以先用这个

**Comment by mingyang66** [comment]
> ```
> <dependency>
>             <groupId>com.github.xingfudeshi</groupId>
>             <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
>             <version>4.6.0</version>
>  </dependency>
> ```
> 
> 可以先用这个

好的，谢谢。这个是正式版本还是临时版本，我在maven仓库里面没看到

**Comment by xingfudeshi** [comment]
> > ```
> > <dependency>
> >             <groupId>com.github.xingfudeshi</groupId>
> >             <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
> >             <version>4.6.0</version>
> >  </dependency>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以先用这个
> 
> 好的，谢谢。这个是正式版本还是临时版本，我在maven仓库里面没看到

这个是我在原版源码上改的,并发布在maven上,方便自己和大家使用.今天刚发布,同步可能需要最长48小时.目前,可以在central仓库看到[1]

[1]https://central.sonatype.com/artifact/com.github.xingfudeshi/knife4j-openapi3-jakarta-spring-boot-starter/overview

**Comment by rayliang123** [comment]
> ```
> <dependency>
>             <groupId>com.github.xingfudeshi</groupId>
>             <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
>             <version>4.6.0</version>
>  </dependency>
> ```
> 
> 可以先用这个

谁叫你改包名，搞到我项目全部都要改包名为“幸福的事【xingfudeshi】”

**Comment by xingfudeshi** [comment]
不改包名，无法发布到maven仓库，会和原项目冲突。


------------------ 原始邮件 ------------------
From: rayliang123 ***@***.***&gt;
发送时间: 12/06/2024, 21:41
To: xiaoymin/knife4j ***@***.***&gt;
抄送: xingfudeshi ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [xiaoymin/knife4j] 引入springboot3.4后v3/api-docs接口报Handler dispatch failed: java.lang.NoSuchMethodError (Issue #867)





  <dependency&gt;             <groupId&gt;com.github.xingfudeshi</groupId&gt;             <artifactId&gt;knife4j-openapi3-jakarta-spring-boot-starter</artifactId&gt;             <version&gt;4.6.0</version&gt;  </dependency&gt;  
可以先用这个
  
谁叫你改包名，搞到我项目全部都要改包名为“幸福的事【xingfudeshi】”

**Comment by java001** [comment]
> ```
> <dependency>
>             <groupId>com.github.xingfudeshi</groupId>
>             <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
>             <version>4.6.0</version>
>  </dependency>
> ```
> 
> 可以先用这个

1. 原先设置的鉴权失效了
2.文档路径有重复的，tag标签是正确的，api路径重复了
我遇到了这两个问题，退回到springboot3.3 用原版本就正常了。

**Comment by yeguoz** [comment]
> ```
> <dependency>
>             <groupId>com.github.xingfudeshi</groupId>
>             <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
>             <version>4.6.0</version>
>  </dependency>
> ```
> 
> 可以先用这个

可以了，感谢

**Comment by ilaotan** [comment]
老老实实自己打私服吧 别用这个  包名都换了 以后切回来麻烦

**Comment by xingfudeshi** [comment]
> 老老实实自己打私服吧 别用这个  包名都换了 以后切回来麻烦

包名更换是因为发布到maven中央仓库，需要用不同namespace，否则会冲突。不想用可以不用。

**Comment by imshenyz** [comment]
有个简单的临时解决办法

https://github.com/xiaoymin/knife4j/issues/884#issuecomment-2680382096

**Comment by liululu-code** [comment]
我修改knife4j引入的springdoc依赖版本解决了这个问题：
```xml
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>2.7.0</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
                <version>2.7.0</version>
            </dependency>

            <!-- knife4j依赖 -->
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>4.5.0</version>
            </dependency>
```

**Comment by lsx-xyg** [comment]
改为2.7版本依然无效，Knife4j文档请求异常，错误：No static resource v3/api-docs/swagger-config.

**Comment by Fizznoc** [comment]
话说Knife4j是弃坑了吗还是，已经很久没更新了
