### ISSUE TITLE
spring cloud 2023.0.3 聚合不生效

### ISSUE THREAD

**Issue by Lord1910** [xiaoymin/knife4j#871]
微服务环境下gateway聚合文档不生效
环境
JDK     21
spring-boot    3.3.5
spring-cloud   2023.0.3
springdoc-openapi   2.6.0
knife4j  4.5.0
Consul  v1.15.4

按照相关资料分别配置子模块和gateway

<img width="384" alt="微信图片_20241210111954" src="https://github.com/user-attachments/assets/cc5e40d1-d8dd-491a-9fbf-526147e814f7">
<img width="384" alt="微信图片_20241210112027" src="https://github.com/user-attachments/assets/3556d60d-c83f-4b03-813e-abb64906dc7d">

使用swagger-ui是可以正常聚合
![image](https://github.com/user-attachments/assets/70b5509b-9bcd-4abf-ad9c-1cdfd293acab)
直接访问子模块也可以使用knife4j文档
![image](https://github.com/user-attachments/assets/d94a4fe9-46a0-49e3-89bd-9930dc7c0cbf)
但gateway无法找到子模块
![image](https://github.com/user-attachments/assets/aa03ce84-8f21-4f0b-a1be-59222d0f504d)

**Comment by chenlong1728717074** [comment]
我现在也遇到了这个，但是如果关闭swagger就可以
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

**Comment by Lord1910** [comment]
> 我现在也遇到了这个，但是如果关闭swagger就可以 springdoc: api-docs: enabled: true swagger-ui: enabled: false

非常感谢已解决
