### ISSUE TITLE
希望UI再美化一些就好了，功能够用了，但是不够美观

### ISSUE THREAD

**Issue by 89333367** [xiaoymin/knife4j#89]
可以使用AdminLte或者ElementUI那种，好看一些的

**Comment by xiaoymin** [comment]
其实 ui看久了 都会有审美疲劳,现在还是会先把精力集中在实现功能上，提供一些好玩,易用的功能，整合一些Swagger更多的资源功能

**Comment by mrdong916** [comment]
自定义的markdown文档 显示出来的内容格式，看着有点费劲，建议参考https://doc.xiaominfo.com/这个UI而且还美观

**Comment by xiaoymin** [comment]
> 自定义的markdown文档 显示出来的内容格式，看着有点费劲，建议参考[https://doc.xiaominfo.com/这个UI而且还美观](https://doc.xiaominfo.com/%E8%BF%99%E4%B8%AAUI%E8%80%8C%E4%B8%94%E8%BF%98%E7%BE%8E%E8%A7%82)

1.9.4对自定义的markdown已优化

https://www.oschina.net/news/107336/swagger-bootstrap-ui-1-9-4-released


![https://oscimg.oschina.net/oscnet/c212fa45190d3169362810ad078fc37b810.jpg](https://oscimg.oschina.net/oscnet/c212fa45190d3169362810ad078fc37b810.jpg)
