### ISSUE TITLE
新功能 其他文档缺少样式

### ISSUE THREAD

**Issue by EagleFlyInSky** [xiaoymin/knife4j#90]
其他文档缺少样式
重api文档中复制的md内容，其他文档显示时缺少样式
![image](https://user-images.githubusercontent.com/23117927/57353993-d1c9a200-719c-11e9-8249-bc7089a9ea33.png)
![image](https://user-images.githubusercontent.com/23117927/57354039-eefe7080-719c-11e9-8562-16a970a467a4.png)

**Comment by xiaoymin** [comment]
其他文档这个功能建议附加文档的相关文字说明

比如签名说明、加密规则 等等

这个样式只是做了简单的处理,和接口文档是不一样的

**Comment by EagleFlyInSky** [comment]
嗯，谢谢回答。
我还以为是完整的markdown预览，
但还是希望可以支持
目前标题，表格都没有样式
