### ISSUE TITLE
BasicFilter优化建议

### ISSUE THREAD

**Issue by ywengineer** [xiaoymin/knife4j#91]
方法BasicFilter.match，每次调用String.matches的时候，使用了正则表达式，会创建并编译不同的Pattern。为了减少compile正则表达式频率。

优化建议：

1: 调整为使用Spring的RequestMatcher
2: 调整属性urlFilters类型为List&lt;Pattern&gt;

**Comment by xiaoymin** [comment]
感谢您的建议

**Comment by xiaoymin** [comment]
1.9.4版本已优化
