### ISSUE TITLE
使用QQ浏览器时报错

### ISSUE THREAD

**Issue by GuoXingyou** [xiaoymin/knife4j#93]
错误提示：请确保swagger资源接口正确

**Comment by xiaoymin** [comment]
不建议用其他浏览器，用chrome浏览器

一般报这个错误有多种情况

1、访问的swagger接口确实存在问题，这个可以在network里面查看一下，确认是否有问题
2、swagger返回的json格式不对，一般后端在给集合给example属性的时候会产生此问题，导致JSON.parse方法调用失败


可以下载demo对比看效果
demo地址：https://gitee.com/xiaoym/swagger-bootstrap-ui-demo
