### ISSUE TITLE
考虑接口请求的结果做一下本地缓存。

### ISSUE THREAD

**Issue by izenglong** [xiaoymin/knife4j#94]
场景：
调了一个接口拿到结果，然后请求另外一个接口，想看上一个接口的数据，尴尬。

**Comment by xiaoymin** [comment]
没太明白，现在多个tab直接 可以随意查看吧 前面一个接口调用了 可以切换tab查看的啊

**Comment by izenglong** [comment]
比如请求A接口，获得结果a；再去请求B接口，获得结果a；这时返回A接口，原来的请求结果a就看不到了。很多时候想直接复制结果，而不需要重新发起请求。

**Comment by xiaoymin** [comment]
![bug](https://user-images.githubusercontent.com/7894406/57840641-93b32a80-77fb-11e9-9867-b04025077019.gif)

是这种效果？这来回切换tab，原接口的响应结果存在 啊

**Comment by izenglong** [comment]
是这个功能。
我升级一下版本先 。。。

**Comment by izenglong** [comment]
哥们还有一个问题，这个位置有bug，类型转换出错，我的版本是 1.9.3


原始邮件
发件人:xiaoyminnotifications@github.com
收件人:xiaoymin/swagger-bootstrap-uiswagger-bootstrap-ui@noreply.github.com
抄送:南归的候鸟izenglong@163.com; Authorauthor@noreply.github.com
发送时间:2019年5月16日(周四) 16:57
主题:Re: [xiaoymin/swagger-bootstrap-ui] 考虑接口请求的结果做一下本地缓存。 (#94)


是这种效果？这来回切换tab，原接口的响应结果存在 啊

**Comment by xiaoymin** [comment]
什么bug？贴图？
