### ISSUE TITLE
每个API是否可以生成一个固定访问链接?

### ISSUE THREAD

**Issue by michael829** [xiaoymin/knife4j#95]
前端菜鸟过来提需求来了..公司的后端大佬用这个框架生成的静态页面都是用的tab方式预览, 导致无法将每个API的地址记录下来. 不小心刷新网页或关掉重新打开后就找不到之前正在看的API文档在哪一级菜单下面了.非常不方便..如果可以提供一个新的方式, 支持每个API页面独立访问就太棒了..不过因为这些数据不入库, 所以还得考虑下直接访问的唯一ID怎么保持在同一个项目中由不同的人生成文档时的一致性问题...是否可以考虑下呢? 目前我这边通过覆盖代码的逻辑解决了上一个问题, 但是唯一ID这个就得看后端大佬的了..

附上我的暴力解决方案, 在doc.html中的最下面的JS中, 粘帖以下代码即可:
  
     //也就是在 layui.config(....)代码的后面, 粘贴以下代码即可;

     SwaggerBootstrapUi.prototype.initializationMenuClickEvents=function () {
		var that=this;
        that.getMenu().find(".menuLi").bind("click",function (e) {
            e.preventDefault();
            var menu=$(this);
            var data=menu.data("data");

            $('.layui-layout-admin .layui-body .layui-tab .layui-tab-title li:gt(0)').find(".icon-sbu-tab-close").trigger("click");
            window.location.href = window.location.href.match(/[^\?#]+/g)[0]+'#'+data.id;

            that.log("Li标签click事件");
            that.removeLayerTips();
            that.log(data);
            //获取parent-Li的class属性值
            var parentLi=menu.parent().parent();
            that.log(parentLi);
            var className=parentLi.prop("class");
            that.log(className)
            that.getMenu().find("li").removeClass("active");
            //parentLi.addClass("active");
            menu.addClass("active");
            that.createApiInfoTable(data,menu);
            //DApiUI.createDebugTab(data);
        })
        setTimeout(function(){
        	$('.admin-tabs-control').remove();

        	var params = (window.location.href.match(/#[^\?#&]+/gi)||[])[0]||"";
	    	if(params){
	    		
	    		var tabId = "tab"+params.split('#')[1];
	    		var times = 30;

	    		$('.menuLi[lay-id$='+tabId+']').trigger('click');
	    		var interval = setInterval(function(){
	    			times--;
	    			that.layui.element.tabChange("admin-pagetabs", tabId);
	    			that.tabFinallyRight();
	    			if(times<=0){
	    				$('.menuLi.active').parentsUntil('li').slideDown(0)
	    				clearInterval(interval)
	    			}
	    		}, 10)
	    	}
        }, 0)
    }

**Comment by xiaoymin** [comment]
关于固定id的话，其实针对每一个接口的话有一个operateId，可以作为这个接口的地址来做

因为我们的接口都是按分组来列的，所以，最终该接口的可以给定一个hash，例如：`#/1.8.2版本/mulformAndBodyUsingPOST` ,规则就是`#/tag/operateId`，我看了swagger官方的ui是这个给的，不过貌似也没有实现，打不开固定的接口文档，不知道我用的官方的ui是不是假的，哈哈

获取hash这块可以用window.location对象中的hash属性，即window.location.hash,这比用正则更规范

你给定的代码方案考虑有所欠缺，没有考虑到后端针对api做分组的情况，当然用setTimeout函数也太暴力了，我画了个简单的流程图
![hash地址打开流程逻辑](https://user-images.githubusercontent.com/7894406/57967488-2b4a8180-7992-11e9-9c52-e50bd44171a0.png)

考虑到如果文档已经渲染doc.html的情况，后端可以给前端指定的hash值，前端在地址栏doc.html后键入这个hash值，此时，利用`window.onhashchange`函数来监听hash的变化，这样也就不用重新渲染doc.html，毕竟重新渲染还是有些耗时的

针对这个功能点有两处变化实现：

1、在每个文档中增加**复制地址 **功能，后端可以点击该功能，方便快捷发送给前端
2、实现此issue的功能


下个版本会实现掉

**Comment by michael829** [comment]
感谢您的回复, 实际上最开始用的是?id=xxxx和location.search来获取id值的.但是觉得效果不理想就干脆换成hash了..不用location.hash是因为感觉还是正则用得更顺手一些.呵呵...之所以直接重写initializationMenuClickEvents主要也是考虑到不想有太多的侵入性,尽可能不要改动过多的框架源文件..而项目开发时间太紧不打算在这个文档部分耗费太多时间,所以也没考虑分组和其它可能有的问题(性能方面和其它).....

目前我们前端开发会对每个调用的API特别录入对应的描述信息, 包括该接口的功能,参数,文档地址(写TS的习惯)等. 这样做对于测试(某个接口出错直接顺便将该接口调用时的入参和接口文档地址发送到Log服务器)和多人协作项目时帮助巨大,能够省去大量接口同步交流沟通的时间.所以还是相当实用的...

总之, 您已经明白我的意思了..方便的话希望有更规范的方案..期待下个版本. 另外您也看到了我在click事件里调用了$('.layui-layout-admin .layui-body .layui-tab .layui-tab-title li:gt(0)').find(".icon-sbu-tab-close").trigger("click");关闭除首页外所有的tab标签, 只保留要打开的这个tab标签.其实就是希望能有个模拟纯粹的独立HTML静态页体验..如果以上这功能实现并以配置参数方式加入应该非常赞...

期待, 加油!~

**Comment by xiaoymin** [comment]
1.9.4版本已实现

https://www.oschina.net/news/107336/swagger-bootstrap-ui-1-9-4-released
