### ISSUE TITLE
接口文档，请求参数和响应参数的问题，2个接口的请求参数 使用不同java包下bean来接收，但bean名是相同，在接口文档参数参数就是显示不正确

### ISSUE THREAD

**Issue by assupg** [xiaoymin/knife4j#97]
我理解的问题
@apimodel value 默认情况下，使用类名。不同包下面相同的bean，就会导致问题。

**Comment by xiaoymin** [comment]
这个是springfox的bug，因为在渲染出definition时候  并没有package名称，如果两个model一样 就会有问题

ui只负责显示

**Comment by assupg** [comment]
谢谢，明白了。

**Comment by zq99299** [comment]
> 我理解的问题 @apimodel value 默认情况下，使用类名。不同包下面相同的bean，就会导致问题。

我解决了，要用 Swagger 的插件去提供 model 的名称，防止重复。但是 Swagger 兼容的 model 名称 knife4j 不兼容，详细的看下面的笔记吧
https://www.yuque.com/mrcode.cn/note-combat/fec1g9?inner=c9wLo
